Repository activepieces/activepieces, pull requests merged in 2023-03, with the labels that each got.

#787 chore: added url encoding for code parameter
  packages/backend/src/main.ts
Labels: 💻 chore

#800 feat: square triggers
  packages/backend/src/app/app-event-routing/app-event-routing.service.ts
  packages/backend/src/app/helper/engine-helper.ts
  packages/backend/src/app/webhooks/webhook-service.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/pieces/apps/src/index.ts
  packages/pieces/framework/src/lib/framework/piece.ts
  packages/pieces/square/.eslintrc.json
  packages/pieces/square/README.md
  packages/pieces/square/package.json
  packages/pieces/square/project.json
  packages/pieces/square/src/index.ts
  packages/pieces/square/src/lib/common/props.ts
  packages/pieces/square/src/lib/triggers/index.ts
  packages/pieces/square/tsconfig.json
  packages/pieces/square/tsconfig.lib.json
  packages/shared/src/lib/engine/engine-operation.ts
  tsconfig.base.json
Labels: 🔌 pieces, trigger

#826 docs: Added SVG icon for Easypanel.
  docs/install/overview.mdx
Labels: documentation
