Repository activepieces/activepieces, pull requests merged in 2023-04, with the labels that each got.

#1017 chore: edit the message on the start
  packages/backend/src/main.ts
Labels: ⭐ enhancement

#949 feat: add nx cloud
  .github/workflows/build-cloud-nx.yml
  .github/workflows/build-everything.yml
  nx.json
  package-lock.json
  package.json
  packages/backend/src/app/store-entry/store-entry.service.ts
  packages/ui/feature-builder-form-controls/src/index.ts
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar/flow-right-sidebar.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-connections/src/lib/dialogs/cloud-oauth2-connection-dialog/cloud-oauth2-connection-dialog.component.ts
Labels: codeball:needs-careful-review

#1122 feat(blackbaud): add upsert contact
  packages/pieces/blackbaud/package.json
  packages/pieces/blackbaud/src/index.ts
  packages/pieces/blackbaud/src/lib/actions/create-contacts-batch.ts
  packages/pieces/blackbaud/src/lib/actions/update-contact.ts
  packages/pieces/blackbaud/src/lib/actions/upsert-contact.ts
Labels: codeball:approved

#1125 chore(freshsales): make first name optional
  packages/pieces/freshsales/package.json
  packages/pieces/freshsales/src/lib/actions/create-contact.ts
Labels: codeball:approved

#1119 chore: count executed tasks only
  packages/backend/src/app/database/database-connection.ts
  packages/backend/src/app/database/migration/1681019096716-StoreAllPeriods.ts
  packages/backend/src/app/flows/flow-run/flow-run-service.ts
  packages/backend/src/app/helper/system/system-prop.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/ee/billing/backend/billing.service.ts
  packages/ee/billing/backend/usage.entity.ts
  packages/ee/billing/backend/usage.service.ts
  packages/engine/src/lib/action/code-action-handler.ts
  packages/engine/src/lib/action/piece-action-handler.ts
  packages/engine/src/lib/executors/flow-executor.ts
  packages/engine/src/lib/globals.ts
  packages/engine/src/main.ts
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/execution-output.ts
Labels: codeball:needs-careful-review

#1147 fix: remove select button for autocomplete when stpe isn't tested
  packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.html
  packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
  packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/code-step-mention-item/code-step-mention-item.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/custom-path-mention-dialog/custom-path-mention-dialog.component.ts
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/mentions-list.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-step-mention-item/piece-step-mention-item.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/piece-trigger-mention-item/piece-trigger-mention-item.component.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar/input-forms/loop-step-input-form/loop-step-input-form.component.html
Labels: codeball:needs-careful-review

#1149 Fix/retrieving flow folder
  packages/ui/core/src/app/modules/flow-builder/flow-builder.routing.ts
  packages/ui/core/src/app/modules/flow-builder/page/flow-builder/collection-builder.component.ts
  packages/ui/core/src/app/modules/flow-builder/resolvers/flow.resolver.ts
  packages/ui/core/src/app/modules/flow-builder/resolvers/instance-run.resolver.ts
  packages/ui/core/src/app/modules/flow-builder/resolvers/list-flows.resolver.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.action.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/store/folders/folders.effects.ts
Labels: codeball:needs-careful-review

#1150 fix: added flow folder id in move action as param
  packages/ui/feature-dashboard/src/lib/pages/flows-table/move-flow-to-folder-dialog/move-flow-to-folder-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/store/folders/folders.actions.ts
  packages/ui/feature-dashboard/src/lib/store/folders/folders.reducer.ts
Labels: codeball:needs-careful-review

#1154 fix: frontend hot fixes
  packages/backend/src/app/flows/flow/flow.service.ts
  packages/ui/core/src/app/app.component.html
  packages/ui/core/src/app/app.component.ts
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-builder-header/src/lib/publish-button/publish-button.component.html
  packages/ui/feature-builder-header/src/lib/publish-button/publish-button.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
Labels: codeball:needs-careful-review

#1159 chore: added error response ui for test piece step
  packages/ui/common/src/lib/service/test-step.service.ts
  packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-step/test-piece-step.component.ts
Labels: codeball:needs-careful-review

#1155 fix: resolve first item for loops in step run
  packages/backend/src/app/flows/step-run/step-run-service.ts
Labels: codeball:needs-careful-review

#1156 chore: check limit before flow run
  packages/backend/src/app/flows/flow-run/flow-run-service.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/ee/billing/backend/usage.service.ts
Labels: codeball:needs-careful-review

#1160 fix: reset sizes for right sidebar sections on window resize
  packages/ui/common/src/lib/components/horizontal-sidebar-separator/horizontal-sidebar-separator.component.ts
  packages/ui/core/src/app/app.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
Labels: codeball:approved

#1162 Chore/add steps column
  packages/ui/common/src/lib/service/action-meta.service.ts
  packages/ui/core/src/assets/img/custom/piece/smtp_mention.png
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/builder/flow-item-details/flow-items-details.effects.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/folders-list/folders-list.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/folders-list/folders-list.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/steps-list-in-flows-table/steps-list-in-flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/steps-list-in-flows-table/steps-list-in-flows-table.component.ts
  packages/ui/feature-dashboard/src/lib/store/folders/folders.reducer.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
  tsconfig.base.json
Labels: codeball:needs-careful-review
