Repository activepieces/activepieces, pull requests merged in 2024-12, with the labels that each got.

#6196 fix: show missing step icon and stop converting custom code to mentions
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts
  packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx
  packages/react-ui/src/assets/img/custom/incomplete.png
  packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
Labels: 🐛 bug

#6179 feat(gistly): Get Transcript Action
  packages/pieces/community/gistly/.eslintrc.json
  packages/pieces/community/gistly/package.json
  packages/pieces/community/gistly/project.json
  packages/pieces/community/gistly/src/index.ts
  packages/pieces/community/gistly/src/lib/actions/get-transcript.ts
  packages/pieces/community/gistly/src/lib/config.ts
  packages/pieces/community/gistly/tsconfig.json
  packages/pieces/community/gistly/tsconfig.lib.json
Labels: 🔌 pieces

#6205 fix: show permission error for embed sdk when creating a connection + minor ui fixes for dialogs
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/routes/chat/chat-message/text-message.tsx
  packages/react-ui/src/components/custom/copy-to-clipboard.tsx
  packages/react-ui/src/components/delete-dialog.tsx
  packages/react-ui/src/components/ui/copy-button.tsx
  packages/react-ui/src/components/ui/download-button.tsx
  packages/react-ui/src/features/connections/components/edit-global-connection-dialog.tsx
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
Labels: skip-changelog

#6176 fix(dropbox): fix support of accented characters in path property
  packages/pieces/community/dropbox/package.json
  packages/pieces/community/dropbox/src/lib/actions/upload-file.ts
Labels: 🔌 pieces

#6209 feat(ftp): support ftp protocol
  package-lock.json
  package.json
  packages/pieces/community/sftp/package.json
  packages/pieces/community/sftp/src/index.ts
  packages/pieces/community/sftp/src/lib/actions/create-file.ts
  packages/pieces/community/sftp/src/lib/actions/create-folder.ts
  packages/pieces/community/sftp/src/lib/actions/delete-file.ts
  packages/pieces/community/sftp/src/lib/actions/delete-folder.ts
  packages/pieces/community/sftp/src/lib/actions/list-files.ts
  packages/pieces/community/sftp/src/lib/actions/list.ts
  packages/pieces/community/sftp/src/lib/actions/read-file.ts
  packages/pieces/community/sftp/src/lib/actions/rename-file-or-folder.ts
  packages/pieces/community/sftp/src/lib/actions/upload-file.ts
  packages/pieces/community/sftp/src/lib/triggers/new-modified-file.ts
Labels: 🔌 pieces

#6210 fix(common): use async validation in zod
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/validation/index.ts
Labels: 🐛 bug, 🛠️ piece-framework

#6212 feat(salesforce): add custom API call action
  packages/pieces/community/salesforce/package.json
  packages/pieces/community/salesforce/src/index.ts
Labels: 🔌 pieces

#6208 fix: change validation of piece names
  packages/cli/src/lib/commands/create-piece.ts
Labels: 🐛 bug, 🧹 clean up

#6061 feat: renovate code copilot
  package-lock.json
  package.json
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/copilot/chat-message.tsx
  packages/react-ui/src/app/builder/copilot/index.tsx
  packages/react-ui/src/app/builder/copilot/loading-message.tsx
  packages/react-ui/src/app/builder/copilot/welcome-message.tsx
  packages/react-ui/src/app/builder/flow-canvas/edges/add-button.tsx
  packages/react-ui/src/app/builder/flow-canvas/edges/ask-ai-indicator.tsx
  packages/react-ui/src/app/builder/flow-canvas/nodes/big-add-button-node.tsx
  packages/react-ui/src/app/builder/piece-properties/dictionary-property.tsx
  packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts
  packages/react-ui/src/app/builder/pieces-selector/ask-ai.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
  packages/react-ui/src/app/builder/step-settings/code-settings/code-editor.tsx
  packages/react-ui/src/app/builder/step-settings/code-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/features/pieces/lib/types.ts
  packages/react-ui/src/styles/globals.css
  packages/react-ui/tailwind.config.js
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/copilot/copilot.module.ts
  packages/server/api/src/app/copilot/copilot.service.ts
  packages/server/api/src/app/copilot/request-writer/request-writer.module.ts
  packages/server/api/src/app/copilot/request-writer/request-writer.service.ts
  packages/server/api/src/app/copilot/tools/code/code-agent.ts
  packages/server/api/src/app/copilot/tools/code/code-generate.ts
  packages/server/api/src/app/copilot/tools/http/http-agent.ts
  packages/server/api/src/app/copilot/tools/http/http-generate.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/shared/src/lib/copilot/index.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/websocket/index.ts
Labels: 🌟 feature

#6139 feat(twin-labs): Start Browsing Task Action
  packages/pieces/community/twin-labs/.eslintrc.json
  packages/pieces/community/twin-labs/README.md
  packages/pieces/community/twin-labs/package.json
  packages/pieces/community/twin-labs/project.json
  packages/pieces/community/twin-labs/src/index.ts
  packages/pieces/community/twin-labs/src/lib/actions/start-browsing-task.ts
  packages/pieces/community/twin-labs/tsconfig.json
  packages/pieces/community/twin-labs/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6177 feat(mysql): Allow MySQL Piece Authentication Without Specifying a Database for ‘Execute Query’ Action
  packages/pieces/community/mysql/package.json
  packages/pieces/community/mysql/src/index.ts
Labels: 🔌 pieces

#6218 fix(gmail): fix \n adding <br> in mail body issue
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
Labels: 🔌 pieces

#6200 feat(callable-flow): add simple/advanced modes to callable flow
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/actions/respond.ts
  packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
Labels: 🔌 pieces

#6219 feat(crypto): generate hmac signature
  packages/pieces/community/crypto/package.json
  packages/pieces/community/crypto/src/index.ts
  packages/pieces/community/crypto/src/lib/actions/hmac-signature.ts
Labels: 🔌 pieces

#6222 feat(bamboohr): add BambooHR piece with custom api call action
  packages/pieces/community/bamboohr/.eslintrc.json
  packages/pieces/community/bamboohr/README.md
  packages/pieces/community/bamboohr/package.json
  packages/pieces/community/bamboohr/project.json
  packages/pieces/community/bamboohr/src/index.ts
  packages/pieces/community/bamboohr/tsconfig.json
  packages/pieces/community/bamboohr/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6221 feat(scenario): add Scenario piece with custom api call action
  packages/pieces/community/scenario/.eslintrc.json
  packages/pieces/community/scenario/README.md
  packages/pieces/community/scenario/package.json
  packages/pieces/community/scenario/project.json
  packages/pieces/community/scenario/src/index.ts
  packages/pieces/community/scenario/tsconfig.json
  packages/pieces/community/scenario/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6223 feat(ashby): add basic Ashby piece
  packages/pieces/community/ashby/.eslintrc.json
  packages/pieces/community/ashby/README.md
  packages/pieces/community/ashby/package.json
  packages/pieces/community/ashby/project.json
  packages/pieces/community/ashby/src/index.ts
  packages/pieces/community/ashby/tsconfig.json
  packages/pieces/community/ashby/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6220 fix: local piece caching not clearing
  packages/server/shared/src/lib/pieces/file-pieces-utils.ts
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
Labels: 🐛 bug

#6227 feat: release 0.37.3
  docker-compose.yml
  package.json
Labels: release

#6232 fix: prevent crashing
  packages/engine/src/lib/helper/error-handling.ts
Labels: 🐛 bug

#6235 fix: include project role in user invitation
  docs/openapi.json
  package-lock.json
  packages/react-ui/src/features/team/component/invitation-card.tsx
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
Labels: 🐛 bug

#6229 docs: fix two minor typos in docs
  docs/embedding/overview.mdx
  docs/install/options/elestio.mdx
Labels: 📚 documentation

#6225 feat(instasent): add instant parameter to add/update contact action
  packages/pieces/community/instasent/package.json
  packages/pieces/community/instasent/src/index.ts
  packages/pieces/community/instasent/src/lib/actions/add-or-update-contact.ts
Labels: 🔌 pieces

#6237 docs(sso): add jump cloud instructions
  docs/resources/screenshots/jumpcloud/acl-url.png
  docs/resources/screenshots/jumpcloud/declare-login.png
  docs/resources/screenshots/jumpcloud/export-metadata.png
  docs/resources/screenshots/jumpcloud/user-attribute.png
  docs/resources/screenshots/jumpcloud/user-groups.png
  docs/security/sso.mdx
Labels: 📚 documentation

#6187 fix(appwebhooks): simulate when there is no test & sample data
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/trigger/trigger.ts
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/lib/triggers/conversation-assigned.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-closed.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-rated.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-snoozed.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-unsnoozed.ts
  packages/pieces/community/intercom/src/lib/triggers/new-conversation-from-user.ts
  packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
  packages/pieces/community/intercom/src/lib/triggers/reply-from-admin.ts
  packages/pieces/community/intercom/src/lib/triggers/reply-from-user.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/worker/src/lib/engine/threads/worker.ts
Labels: 🐛 bug

#6238 feat: release 0.37.4
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: release

#6248 chore: bump release
  docker-compose.yml
  package.json
Labels: release

#6240 refactor: google sheets
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-row-by-num.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/server/shared/src/lib/system/system.ts
Labels: 🔌 pieces

#6226 feat(pipedrive): add filters for updated deal trigger
  packages/pieces/community/pipedrive/package.json
  packages/pieces/community/pipedrive/src/index.ts
  packages/pieces/community/pipedrive/src/lib/common/types.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-activity.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-deal.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-person.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-deal.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-person.ts
Labels: 🔌 pieces

#6250 fix(google-sheets): insert & update
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
Labels: skip-changelog

#6255 fix(webhooks): return response redirect should work without protocl
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/lib/actions/return-response.ts
Labels: 🔌 pieces

#6260 fix(google-sheets): optimize metadata response
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts
Labels: skip-changelog

#6261 feat: avoid deep cloning in engine
  packages/engine/src/lib/variables/props-resolver.ts
  packages/shared/src/lib/common/utils/object-utils.ts
Labels: 🧹 clean up

#6285 fix(smtp): retry on connection refused
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🔌 pieces

#6287 feat(metabase): allow full question id
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/lib/actions/get-question.ts
Labels: 🔌 pieces

#6289 test: backend tests
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
  packages/pieces/community/smtp/src/lib/common/index.ts
  packages/server/api/src/app/helper/dayjs-helper.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/api/types/fastify.d.ts
Labels: 🔌 pieces

#6299 feat(gmail): new labeled email trigger
  package-lock.json
  packages/pieces/community/airtable/src/lib/trigger/new-record.trigger.ts
  packages/pieces/community/airtable/src/lib/trigger/update-record.trigger.ts
  packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts
  packages/pieces/community/apitable/src/lib/triggers/new-record.ts
  packages/pieces/community/clockodo/src/lib/triggers/new-absence-enquiry.ts
  packages/pieces/community/clockodo/src/lib/triggers/new-entry.ts
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/polling/index.ts
  packages/pieces/community/discord/src/lib/trigger/new-message.ts
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/index.ts
  packages/pieces/community/gmail/src/lib/common/data.ts
  packages/pieces/community/gmail/src/lib/triggers/new-email.ts
  packages/pieces/community/gmail/src/lib/triggers/new-labeled-email.ts
  packages/pieces/community/google-calendar/src/lib/triggers/calendar-event.ts
  packages/pieces/community/google-contacts/src/lib/trigger/new-contact.ts
  packages/pieces/community/google-drive/src/lib/triggers/new-file.ts
  packages/pieces/community/google-drive/src/lib/triggers/new-folder.ts
  packages/pieces/community/google-forms/src/lib/triggers/new-form-response.ts
  packages/pieces/community/google-my-business/src/lib/triggers/new-review.ts
  packages/pieces/community/google-tasks/src/lib/triggers/new-task.ts
  packages/pieces/community/hubspot/src/lib/triggers/deal-stage-updated.ts
  packages/pieces/community/hubspot/src/lib/triggers/new-company-added.ts
  packages/pieces/community/hubspot/src/lib/triggers/new-contact-added.ts
  packages/pieces/community/hubspot/src/lib/triggers/new-deal-added.ts
  packages/pieces/community/hubspot/src/lib/triggers/new-task-added.ts
  packages/pieces/community/hubspot/src/lib/triggers/new-ticket-added.ts
  packages/pieces/community/lead-connector/src/lib/triggers/contact-updated.ts
  packages/pieces/community/lead-connector/src/lib/triggers/new-contact.ts
  packages/pieces/community/lead-connector/src/lib/triggers/new-form-submission.ts
  packages/pieces/community/lead-connector/src/lib/triggers/new-opportunity.ts
  packages/pieces/community/microsoft-dynamics-365-business-central/src/lib/triggers/new-or-updated-record.trigger.ts
  packages/pieces/community/microsoft-excel-365/src/lib/trigger/new-row-added.ts
  packages/pieces/community/microsoft-onedrive/src/lib/triggers/new-file.ts
  packages/pieces/community/notion/src/lib/triggers/new-database-item.ts
  packages/pieces/community/notion/src/lib/triggers/updated-database-item.ts
  packages/pieces/community/postgres/src/lib/triggers/new-row.ts
  packages/pieces/community/rabbitmq/src/lib/triggers/message-received.ts
  packages/pieces/community/rss/src/lib/triggers/new-item-trigger.ts
  packages/pieces/community/salesforce/src/lib/trigger/new-record.ts
  packages/pieces/community/salesforce/src/lib/trigger/new-updated-record.ts
  packages/pieces/community/shopify/src/lib/triggers/new-abandoned-checkout.ts
  packages/pieces/community/tidycal/src/lib/trigger/cancelled-booking.ts
  packages/pieces/community/tidycal/src/lib/trigger/new-booking.ts
  packages/pieces/community/tidycal/src/lib/trigger/new-contacts.ts
  packages/pieces/community/totalcms/src/lib/triggers/new-blog-post.ts
  packages/pieces/community/webling/src/lib/triggers/calendar-event.ts
  packages/pieces/community/webling/src/lib/triggers/on-changed-data.ts
  packages/pieces/community/wordpress/src/lib/trigger/new-post.trigger.ts
  packages/pieces/community/zendesk/src/lib/trigger/new-ticket-in-view.ts
  packages/pieces/community/zoho-crm/src/lib/triggers/new-contact.ts
  packages/pieces/community/zoho-invoice/src/lib/triggers/new-invoice.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: 🔌 pieces

#6303 feat(piece-dialog): improve the error message
  docs/developers/misc/pieces-ci-cd.mdx
  packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
Labels: 📚 documentation

#6301 fix(apitable): fix two link field
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/lib/actions/update-record.ts
  packages/pieces/community/apitable/src/lib/common/constants.ts
  packages/pieces/community/apitable/src/lib/common/index.ts
Labels: 🔌 pieces

#6300 fix(utility-ai): fix empty text error
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
Labels: 🔌 pieces

#6308 chore: switch cloudflare to google dns in sandbox
  packages/server/api/src/assets/etc/resolv.conf
Labels: 🐛 bug

#6310 fix(truncation): allow max log size to be configurable
  packages/engine/src/lib/helper/logging-utils.ts
  packages/pieces/community/activepieces/src/index.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/shared/src/lib/flow-run/execution/execution-output.ts
Labels: 🐛 bug

#6311 feat: release 0.37.6
  docker-compose.yml
  docs/install/configuration/environment-variables.mdx
  docs/install/configuration/troubleshooting.mdx
  package.json
Labels: release

#6316 fix: pieces tables filtering
  package-lock.json
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/app/routes/settings/pieces/index.tsx
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: 🐛 bug

#6313 feat(google-sheets): insert the missing headers in JSON mode
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: 🔌 pieces

#6312 fix(slack): add text with with block kits
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/actions/send-direct-message-action.ts
  packages/pieces/community/slack/src/lib/actions/send-message-action.ts
  packages/pieces/community/slack/src/lib/actions/update-message.ts
Labels: 🔌 pieces

#6290 fix(google-sheets): "cannot read properties of null" error when using…
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
Labels: 🔌 pieces

#6307 feat(microsoft-outlook-calendar): create/delete/list events
  packages/pieces/community/microsoft-outlook-calendar/.eslintrc.json
  packages/pieces/community/microsoft-outlook-calendar/README.md
  packages/pieces/community/microsoft-outlook-calendar/package.json
  packages/pieces/community/microsoft-outlook-calendar/project.json
  packages/pieces/community/microsoft-outlook-calendar/src/index.ts
  packages/pieces/community/microsoft-outlook-calendar/src/lib/actions/create-event.ts
  packages/pieces/community/microsoft-outlook-calendar/src/lib/actions/delete-event.ts
  packages/pieces/community/microsoft-outlook-calendar/src/lib/actions/list-events.ts
  packages/pieces/community/microsoft-outlook-calendar/src/lib/common/common.ts
  packages/pieces/community/microsoft-outlook-calendar/tsconfig.json
  packages/pieces/community/microsoft-outlook-calendar/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6338 fix: search result should not tort alpha
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
Labels: 🐛 bug

#6339 feat(twin-lab): improved user experience
  packages/pieces/community/twin-labs/package.json
  packages/pieces/community/twin-labs/src/lib/actions/start-browsing-task.ts
Labels: 🔌 pieces

#6356 fix(linked-in): update api version
  packages/pieces/community/linkedin/package.json
  packages/pieces/community/linkedin/src/lib/common/index.ts
Labels: 🔌 pieces

#6365 fix(wedof-piece): fixing api link
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/lib/common/wedof.ts
Labels: 🐛 bug

#6321 feat(harvest): add basic Harvest piece
  packages/pieces/community/harvest/.eslintrc.json
  packages/pieces/community/harvest/README.md
  packages/pieces/community/harvest/package.json
  packages/pieces/community/harvest/project.json
  packages/pieces/community/harvest/src/index.ts
  packages/pieces/community/harvest/src/lib/actions/get-clients.ts
  packages/pieces/community/harvest/src/lib/actions/get-estimates.ts
  packages/pieces/community/harvest/src/lib/actions/get-expenses.ts
  packages/pieces/community/harvest/src/lib/actions/get-invoices.ts
  packages/pieces/community/harvest/src/lib/actions/get-projects.ts
  packages/pieces/community/harvest/src/lib/actions/get-roles.ts
  packages/pieces/community/harvest/src/lib/actions/get-tasks.ts
  packages/pieces/community/harvest/src/lib/actions/get-time_entries.ts
  packages/pieces/community/harvest/src/lib/actions/get-users.ts
  packages/pieces/community/harvest/src/lib/actions/reports-uninvoiced.ts
  packages/pieces/community/harvest/src/lib/common/index.ts
  packages/pieces/community/harvest/tsconfig.json
  packages/pieces/community/harvest/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6357 fix(google-search-console): fix date range format error
  packages/pieces/community/google-search-console/package.json
  packages/pieces/community/google-search-console/src/index.ts
  packages/pieces/community/google-search-console/src/lib/actions/search-analytics.ts
Labels: 🔌 pieces

#6369 fix: log sso sign ups events
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-module.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
Labels: 🐛 bug

#6373 fix: remove copilot flag and replace it with platform
  packages/react-ui/src/app/builder/pieces-selector/ask-ai.tsx
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
  packages/react-ui/src/app/builder/step-settings/code-settings/index.tsx
  packages/react-ui/src/app/components/platform-second-sidebar-layout.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/copilot/configure-provider-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/copilot/index.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/index.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/universal-pieces/ai-provider-card.tsx
  packages/react-ui/src/hooks/platform-hooks.ts
  packages/server/api/src/app/copilot/services/model.service.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-module.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: 🐛 bug

#6374 feat: release 0.38.0
  docker-compose.yml
  package.json
Labels: release

#6379 fix: history was recording incomplete urls inside the app
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/project-settings-layout.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/default-route.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/flows/id/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/lib/authentication-session.ts
Labels: 🐛 bug

#6380 feat: bump release
  docker-compose.yml
  package.json
Labels: release

#6378 fix(qdrant): fix content/payload field for add points action
  packages/pieces/community/qdrant/package.json
  packages/pieces/community/qdrant/src/index.ts
  packages/pieces/community/qdrant/src/lib/actions/add-points.ts
Labels: 🔌 pieces

#6391 fix(customerio): don't send customer identifier as event id
  packages/pieces/community/customer-io/package.json
  packages/pieces/community/customer-io/src/lib/actions/create_event.ts
Labels: 🔌 pieces

#6395 feat(s3-validation): add s3 conifguration validation
  packages/server/api/src/app/file/s3-helper.ts
  packages/server/api/src/app/helper/system-validator.ts
Labels: 🐛 bug

#6407 feat: 0.38.2
  docker-compose.yml
  package.json
Labels: release

#6408 fix(google-sheets): fix row number response
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
Labels: 🔌 pieces

#6410 fix: allow duplicate entries in dictionary inputs
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/app/builder/piece-properties/dictionary-property.tsx
Labels: 🐛 bug

#6375 feat: add check-file-type action for file-helper
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/index.ts
  packages/pieces/community/file-helper/src/lib/actions/check-file-type.ts
  packages/pieces/community/file-helper/src/lib/common/mimeTypes.ts
Labels: 🔌 pieces

#6412 chore: bump release version
  docker-compose.yml
  package.json
Labels: release

#6414 fix: ignore values whose types are not compatible with AP
  packages/pieces/community/notion/package.json
  packages/pieces/community/notion/src/lib/actions/create-database-item.ts
  packages/pieces/community/notion/src/lib/common/index.ts
Labels: skip-changelog

#6415 chore: remove sign in with github
  packages/react-ui/src/features/authentication/components/third-party-logins.tsx
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/authn-provider.ts
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/shared/src/lib/federated-authn/authn-provider-name.ts
Labels: 🧹 clean up, ⛓️‍💥 breaking-change

#6429 fix: improve skipped steps styling
  packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
  packages/react-ui/src/app/builder/flow-canvas/widgets/incomplete-settings-widget.tsx
Labels: 🐛 bug

#6423 feat: add alerts in flows/runs pages for task usage reaching limit + add widget to see tasks/ai credits consumption
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/header.tsx
  packages/react-ui/src/app/components/usage-limits-button.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/flows/task-limit-alert.tsx
  packages/react-ui/src/app/routes/platform/notifications/hooks/notifictions-hooks.ts
  packages/react-ui/src/app/routes/platform/notifications/platform-alert.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/components/ui/alert.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/server/api/src/app/project/usage/project-usage-service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/project/project.ts
Labels: review
