Repository activepieces/activepieces, pull requests merged in 2024-08, with the labels that each got.

#5230 feat: pre release 0.30.0-rc.4
  package.json
Labels: pre-release

#5232 fix(google-forms): handle empty response
  packages/pieces/community/google-forms/package.json
  packages/pieces/community/google-forms/src/lib/triggers/new-form-response.ts
Labels: 🔌 pieces

#5244 fix(log-truncation): treat array as leaf node
  packages/engine/src/lib/helper/logging-utils.ts
Labels: engine

#5248 fix: cache thread-safe and atomic
  package-lock.json
  package.json
  packages/server/worker/src/lib/utils/cache-handler.ts
Labels: 🐛 bug

#5255 fix: enforce store limit
  docs/flows/known-limits.mdx
  docs/mint.json
  packages/engine/src/lib/services/storage.service.ts
  packages/pieces/community/queue/package.json
  packages/server/api/src/app/store-entry/store-entry.controller.ts
  packages/shared/src/lib/store-entry/store-entry.ts
Labels: 🐛 bug

#5256 fix: count failed step
  packages/engine/src/lib/handler/piece-executor.ts
Labels: 🐛 bug

#5269 fix(gravity-forms): fix webhook test issue
  packages/pieces/community/gravityforms/package.json
  packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts
Labels: 🔌 pieces

#5287 fix: allow leaky rate limit
  packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
Labels: 🐛 bug

#5293 fix(google-contacts): fix new contact trigger
  packages/pieces/community/google-contacts/package.json
  packages/pieces/community/google-contacts/src/lib/trigger/new-contact.ts
Labels: 🔌 pieces

#5306 fix: number validation
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
Labels: 🐛 bug

#5311 fix(claude): fix ask claude response error
  packages/pieces/community/claude/package.json
  packages/pieces/community/claude/src/lib/actions/send-prompt.ts
Labels: 🔌 pieces

#5338 feat: 0.30.0-rc.5
  package.json
Labels: pre-release

#5342 feat: 0.30.0-rc.6 release
  package.json
Labels: pre-release

#5344 feat(rabbitmq): add support for vhosts
  packages/pieces/community/rabbitmq/package.json
  packages/pieces/community/rabbitmq/src/index.ts
  packages/pieces/community/rabbitmq/src/lib/common/index.ts
Labels: 🔌 pieces

#5340 feat(wedof): adding cfsurveys triggers / actions
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folder-survey/get-certification-folder-survey.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folder-survey/list-certification-folder-surveys.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-initial-experience-answered.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-initial-experience-available.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-long-experience-answered.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-long-experience-available.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-six-month-experience-answered.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-six-month-experience-available.ts
Labels: 🔌 pieces

#5358 fix: app event routing
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
Labels: 🐛 bug

#5369 fix(engine): use dest folder as installation path instead of src
  packages/server/worker/package.json
  packages/server/worker/src/lib/utils/cache-handler.ts
  packages/server/worker/src/lib/utils/engine-installer.ts
Labels: 🐛 bug

#5372 feat: 0.30.0-rc.8
  package.json
Labels: pre-release

#5374 feat: allow filter runs by more than one flow
  docs/openapi.json
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
Labels: ⭐ enhancement

#5379 feat(google-drive): delete file and send file to trash actions
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/index.ts
  packages/pieces/community/google-drive/src/lib/action/delete-file.ts
  packages/pieces/community/google-drive/src/lib/action/send-to-trash.ts
Labels: 🔌 pieces

#5393 docs: fix description for AP_PIECES_SYNC_MODE
  docs/install/configurations/environment-variables.mdx
Labels: 📚 documentation

#5398 fix(http): parse json body only if string
  packages/pieces/community/http/package.json
  packages/pieces/community/http/src/lib/actions/return-response.ts
  packages/server/worker/package.json
Labels: 🔌 pieces

#5405 feat: add powered by
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/components/show-powered-by.tsx
  packages/react-ui/src/features/forms/components/ap-form.tsx
Labels: ⭐ enhancement

#5409 feat: switch to react based on flag
  packages/ui/common/src/lib/service/telemetry.service.ts
Labels: skip-changelog

#5414 fix: handling unicode sequences in json-type columns of postgresql
  packages/server/api/src/app/ee/flow-template/flow-template.service.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
  packages/server/api/src/app/store-entry/store-entry.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/shared/src/lib/common/utils/object-utils.ts
Labels: 🐛 bug

#5416 docs(framework): deprecate processors
  docs/developers/piece-reference/properties-validation.mdx
  packages/pieces/community/linkedin/package.json
Labels: 📚 documentation

#5419 feat: support attaching jira tickets to parent epic/task
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/lib/actions/create-issue.ts
  packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts
  packages/pieces/community/jira-cloud/src/lib/common/index.ts
Labels: 🔌 pieces

#5437 feat(dust): make timeout customizable
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#5425 fix(airtable): fix empty attachment field update issue and upload file action
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/index.ts
  packages/pieces/community/airtable/src/lib/actions/upload-file-to-column.ts
  packages/pieces/community/airtable/src/lib/common/index.ts
Labels: 🔌 pieces

#5424 fix(apitable): fix member field options
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/lib/common/client.ts
  packages/pieces/community/apitable/src/lib/common/index.ts
Labels: 🔌 pieces

#5423 feat(hubspot): add amount property for deal action
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/lib/actions/create-deal.ts
Labels: 🔌 pieces

#5439 fix: trigger files should be stored in db
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/services/files.service.ts
  packages/server/api/src/app/flows/flow-run/log-serializer.ts
Labels: 🐛 bug, engine

#5446 docs: removed stacksnap from overview docs
  docs/install/overview.mdx
Labels: 📚 documentation

#5451 fix: permissions documentation typo
  docs/security/permissions.mdx
Labels: 📚 documentation, skip-changelog

#5460 feat: introduce analytics for ee
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/common/1725113652923-AddAnalyticsToPlatform.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/analytics/analytics-module.ts
  packages/server/api/src/app/ee/analytics/analytics.module.ts
  packages/server/api/src/app/ee/analytics/analytics.service.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/platform/platform.entity.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/src/app/user/user-service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/analytics/index.ts
  packages/shared/src/lib/license-keys/index.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: 🌟 feature
