Repository activepieces/activepieces, pull requests merged in 2024-05, with the labels that each got.

#4596 chore: add different colors for step output values depending on their types.
  packages/ui/common/src/lib/components/json-view/json-view.component.html
  packages/ui/common/src/lib/components/json-view/json-view.component.ts
  packages/ui/core/src/app/monaco-themes/ap-monaco-theme.ts
  packages/ui/core/src/assets/scss/json-editor-override.scss
  packages/ui/core/src/assets/scss/variables.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-action/test-action.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-polling-trigger/test-polling-trigger.component.html
Labels: frontend, auto-deploy

#4603 fix(apitable): Fix Boolean Field Not Updating Issue
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/lib/actions/create-record.ts
  packages/pieces/community/apitable/src/lib/actions/update-record.ts
Labels: 🔌 pieces

#4609 chore(apollo): bump package json
  packages/pieces/community/apollo/package.json
  packages/pieces/community/apollo/src/lib/actions/enrich-company.ts
  packages/pieces/community/apollo/src/lib/actions/match-person.ts
Labels: auto-deploy

#4606 feat(mailjet): send action
  packages/pieces/community/mailjet/.eslintrc.json
  packages/pieces/community/mailjet/README.md
  packages/pieces/community/mailjet/package.json
  packages/pieces/community/mailjet/project.json
  packages/pieces/community/mailjet/src/index.ts
  packages/pieces/community/mailjet/src/lib/actions/send-email.ts
  packages/pieces/community/mailjet/tsconfig.json
  packages/pieces/community/mailjet/tsconfig.lib.json
Labels: 🔌 pieces

#4597 fix(webflow): show collection fields in all items actions
  packages/pieces/community/webflow/package.json
  packages/pieces/community/webflow/src/index.ts
  packages/pieces/community/webflow/src/lib/actions/create-collection-item.ts
  packages/pieces/community/webflow/src/lib/actions/delete-collection-item.ts
  packages/pieces/community/webflow/src/lib/actions/find-collection-item.ts
  packages/pieces/community/webflow/src/lib/actions/find-order.ts
  packages/pieces/community/webflow/src/lib/actions/fulfill-order.ts
  packages/pieces/community/webflow/src/lib/actions/get-collection-item.ts
  packages/pieces/community/webflow/src/lib/actions/publish-collection-item.ts
  packages/pieces/community/webflow/src/lib/actions/refund-order.ts
  packages/pieces/community/webflow/src/lib/actions/unfulfill-order.ts
  packages/pieces/community/webflow/src/lib/actions/update-collection-item.ts
  packages/pieces/community/webflow/src/lib/common/client.ts
  packages/pieces/community/webflow/src/lib/common/common.ts
  packages/pieces/community/webflow/src/lib/common/props.ts
  packages/pieces/community/webflow/src/lib/triggers/new-form-submitted.ts
Labels: 🔌 pieces

#4615 feat: delete flow on git when deleted on user interface
  docs/operations/git-sync.mdx
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/server/api/src/app/ee/authentication/rbac/access-control-list.ts
  packages/server/api/src/app/ee/git-repos/git-repo.module.ts
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/src/app/flows/flow/flow-service-side-effects.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/shared/src/lib/common/security/permission.ts
  packages/ui/common/src/lib/components/dialogs/delete-enity-dialog/delete-entity-dialog.component.html
  packages/ui/common/src/lib/components/dialogs/delete-enity-dialog/delete-entity-dialog.component.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/push-to-git-dialog/push-to-git-dialog.component.ts
Labels: ⭐ enhancement, auto-deploy

#4616 feat: pre release 0.26.0-rc.3
  package.json
Labels: pre-release

#4617 feat(telegram): merge two prs into same one
  packages/pieces/community/telegram-bot/package.json
  packages/pieces/community/telegram-bot/src/lib/action/send-text-message.action.ts
  packages/pieces/community/telegram-bot/src/lib/trigger/new-message.ts
Labels: skip-changelog

#4604 feat(google-sheets): Updated Row Trigger Based on User Provided Column
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
Labels: 🔌 pieces

#4619 fix: delay step were failing after loop
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/server/worker/src/lib/queue/ap-memory-queue.ts
Labels: 🐛 bug, auto-deploy

#4618 feat(slack): add reaction to message action
  package-lock.json
  package.json
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/add-reaction-to-message.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
Labels: 🔌 pieces

#4620 feat(queue): pull items / push items into queue
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/pieces/community/queue/.eslintrc.json
  packages/pieces/community/queue/README.md
  packages/pieces/community/queue/package.json
  packages/pieces/community/queue/project.json
  packages/pieces/community/queue/src/index.ts
  packages/pieces/community/queue/src/lib/actions/pull-from-queue.ts
  packages/pieces/community/queue/src/lib/actions/push-to-queue.ts
  packages/pieces/community/queue/src/lib/common.ts
  packages/pieces/community/queue/tsconfig.json
  packages/pieces/community/queue/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4621 fix: queue fix
  packages/pieces/community/queue/package.json
  packages/pieces/community/queue/src/lib/actions/push-to-queue.ts
Labels: skip-changelog

#4622 feat(queue): clear queue action
  packages/pieces/community/queue/package.json
  packages/pieces/community/queue/src/index.ts
  packages/pieces/community/queue/src/lib/actions/clear-queue.ts
Labels: 🔌 pieces

#4626 feat(zerobounce): validate email action
  packages/pieces/community/apollo/package.json
  packages/pieces/community/apollo/src/lib/actions/enrich-company.ts
  packages/pieces/community/apollo/src/lib/actions/match-person.ts
  packages/pieces/community/zerobounce/.eslintrc.json
  packages/pieces/community/zerobounce/README.md
  packages/pieces/community/zerobounce/package.json
  packages/pieces/community/zerobounce/project.json
  packages/pieces/community/zerobounce/src/index.ts
  packages/pieces/community/zerobounce/src/lib/actions/validate-email.ts
  packages/pieces/community/zerobounce/tsconfig.json
  packages/pieces/community/zerobounce/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4627 fix: queue response
  packages/pieces/community/queue/package.json
  packages/pieces/community/queue/src/lib/actions/clear-queue.ts
  packages/pieces/community/queue/src/lib/actions/push-to-queue.ts
Labels: skip-changelog

#4632 fix: show dynamic input toggle for arrays
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/new-piece-properties-form/piece-properties-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.html
Labels: 🐛 bug, auto-deploy

#4634 feat: add first seen at
  packages/server/api/src/app/helper/telemetry.utils.ts
Labels: skip-changelog, auto-deploy

#4642 feat(poper): New Lead Trigger
  packages/pieces/community/poper/.eslintrc.json
  packages/pieces/community/poper/README.md
  packages/pieces/community/poper/package.json
  packages/pieces/community/poper/project.json
  packages/pieces/community/poper/src/index.ts
  packages/pieces/community/poper/src/lib/triggers/new-lead.ts
  packages/pieces/community/poper/tsconfig.json
  packages/pieces/community/poper/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4644 fix(github): load more than 100 repo
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/lib/common/index.ts
Labels: 🔌 pieces

#4648 fix(trello): fix boards dropdown error
  packages/pieces/community/trello/package.json
  packages/pieces/community/trello/src/lib/actions/get-card.ts
  packages/pieces/community/trello/src/lib/common/index.ts
Labels: 🔌 pieces

#4637 feat(wordpress): Add ACF field option for create/update post actions
  packages/pieces/community/wordpress/package.json
  packages/pieces/community/wordpress/src/lib/actions/create-post.action.ts
  packages/pieces/community/wordpress/src/lib/actions/update-post.action.ts
Labels: 🔌 pieces

#4636 feat(openai): Extract Data from Text Action
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/openai/src/lib/actions/extract-structure-data.action.ts
Labels: 🔌 pieces

#4635 feat(webhook): introduce production & testing url
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/index.ts
  packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts
  packages/server/api/src/app/core/security/authz/project-authz-handler.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
  packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-service.ts
  packages/ui/feature-builder-form-controls/src/lib/pipes/replace-markdown-consts.pipe.ts
Labels: ⭐ enhancement, 🔌 pieces

#4654 fix: change the step run duration to seconds
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
Labels: 🐛 bug, auto-deploy

#4651 fix: continue flow on pause
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/workers/flow-worker/engine-response-watcher.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
  packages/shared/src/lib/flow-run/flow-status.ts
  packages/shared/src/lib/websocket/index.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
Labels: 🐛 bug, auto-deploy

#4657 fix: infinite checking for run status
  package-lock.json
  package.json
  packages/pieces/community/pdf/package.json
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
  packages/server/api/src/app/workers/flow-worker/engine-response-watcher.ts
  packages/server/shared/package.json
  packages/server/shared/src/index.ts
  packages/server/shared/src/lib/typed-event-emitter.ts
Labels: skip-changelog

#4660 feat: extract structured data
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/lib/actions/extract-structure-data.action.ts
Labels: skip-changelog

#4662 fix(webhook): distinguish test webhooks to run when flow not published/enabled
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
Labels: 🐛 bug, auto-deploy

#4663 feat(clickup): Assignee Dropdown for Create Comment Action
  packages/pieces/community/clickup/package.json
  packages/pieces/community/clickup/src/lib/actions/comments/create-task-comment.ts
  packages/pieces/community/clickup/src/lib/common/index.ts
Labels: 🔌 pieces

#4676 feat(formbricks): support self hosted instance
  packages/pieces/community/formbricks/package.json
  packages/pieces/community/formbricks/src/index.ts
  packages/pieces/community/formbricks/src/lib/triggers/register.ts
Labels: 🔌 pieces

#4655 feat: release 0.26.0
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#4679 fix: webhook testing url
  docs/about/changelog.mdx
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
Labels: 🐛 bug, auto-deploy

#4680 feat: release 0.26.1
  package-lock.json
  package.json
Labels: release

#4664 feat(taskade): Create Task, Complete Task and Delete Task Actions
  packages/pieces/community/taskade/.eslintrc.json
  packages/pieces/community/taskade/README.md
  packages/pieces/community/taskade/package.json
  packages/pieces/community/taskade/project.json
  packages/pieces/community/taskade/src/index.ts
  packages/pieces/community/taskade/src/lib/actions/complete-task.action.ts
  packages/pieces/community/taskade/src/lib/actions/create-task.action.ts
  packages/pieces/community/taskade/src/lib/actions/delete-task.action.ts
  packages/pieces/community/taskade/src/lib/common/client.ts
  packages/pieces/community/taskade/src/lib/common/props.ts
  packages/pieces/community/taskade/src/lib/common/types.ts
  packages/pieces/community/taskade/tsconfig.json
  packages/pieces/community/taskade/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4595 feat: isolate worker form backend
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/flows/flow/flow-worker.controller.ts
  packages/server/api/src/app/helper/engine-helper.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/server/api/test/integration/ce/flows/flow-consume.test.ts
  packages/server/api/test/integration/ce/flows/flow-worker.test.ts
  packages/server/worker/package.json
  packages/server/worker/src/index.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/sandbox/files/cached-sandbox.ts
  packages/server/worker/src/lib/utils/ap-memory-queue.ts
  packages/server/worker/src/lib/utils/code-builder.ts
  packages/server/worker/src/lib/utils/engine-installer.ts
  packages/server/worker/src/lib/utils/log-serializer.ts
Labels: 🧹 clean up, auto-deploy

#4689 chore: remove client secret in client grant and user custom oauth2
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts
Labels: 🔒 security, 🧹 clean up, auto-deploy

#4688 fix: show loading indicator when searching dropdowns
  packages/ui/common/src/lib/components/dropdown-search-control/dropdown-search-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-property-core/refreshable-property-core-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/static-dropdown-control/static-dropdown-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/pipes/dropdown-selected-values.pipe.ts
Labels: 🐛 bug, frontend, auto-deploy

#4691 fix(slack): message should show before threadts
  packages/pieces/community/slack/src/lib/actions/send-message-action.ts
Labels: skip-changelog

#4694 fix: stop accessing label of connection dropdown option when none is selected
  packages/ui/feature-builder-form-controls/src/lib/components/connections-dropdown-control/connections-dropdown-control.component.ts
Labels: 🐛 bug, skip-changelog

#4695 fix: sdk-version in docs
  docs/embedding/embed-builder.mdx
Labels: 🐛 bug, skip-changelog

#4696 fix: typo in contribution note in docs
  docs/developers/building-pieces/start-building.mdx
Labels: 🐛 bug, skip-changelog

#4700 feat(metabase): switch to new API key auth mechanism
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/index.ts
  packages/pieces/community/metabase/src/lib/actions/get-question.ts
  packages/pieces/community/metabase/src/lib/common.ts
Labels: 🔌 pieces

#4706 feat: refresh dropdowns manually
  packages/ui/core/src/assets/img/custom/refresh.svg
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-property-core/refreshable-property-core-control.component.ts
Labels: ⭐ enhancement, frontend, auto-deploy

#4709 fix: add flowIssuesEnabled to the license
  packages/server/api/src/app/ee/helper/license-validator/license-validator.ts
  packages/server/api/src/app/ee/helper/license-validator/network-license-validator.ts
  packages/server/api/src/app/platform/platform.service.ts
Labels: 🐛 bug, auto-deploy

#4710 fix: issue feature lock
  packages/ui/common/src/lib/service/platform.service.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
Labels: skip-changelog, auto-deploy

#4712 fix: avoid flow lock when updated by api key
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Labels: 🐛 bug, auto-deploy

#4690 fix(notion): Fix Issue with Skipped Items within the Same Minute Interval
  packages/pieces/community/notion/package.json
  packages/pieces/community/notion/src/index.ts
  packages/pieces/community/notion/src/lib/triggers/new-database-item.ts
  packages/pieces/community/notion/src/lib/triggers/updated-database-item.ts
Labels: 🔌 pieces

#4699 feat(openai): support gpt-4o in assistant actions
  package-lock.json
  package.json
  packages/pieces/community/openai/package.json
Labels: 🔌 pieces

#4720 feat: add appsumo tier 6
  packages/ee/ui/billing/src/lib/plan-name.pipe.ts
  packages/server/api/src/app/ee/billing/appsumo/appsumo.service.ts
Labels: skip-changelog, auto-deploy

#4713 fix: change incorrect spelling of Multiplication in math helper
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/math-helper/src/lib/actions/multiplication.ts
Labels: 🔌 pieces

#4723 refactor: remove activity logs
  docs/customer-portal/activity.mdx
  docs/customer-portal/connections.mdx
  docs/customer-portal/inviting-customer.mdx
  docs/customer-portal/overview.mdx
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/activity/activity-model.ts
  packages/ee/shared/src/lib/activity/activity-requests.ts
  packages/ee/shared/src/lib/activity/index.ts
  packages/ee/ui/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.ts
  packages/pieces/community/activity/.eslintrc.json
  packages/pieces/community/activity/README.md
  packages/pieces/community/activity/package.json
  packages/pieces/community/activity/project.json
  packages/pieces/community/activity/src/index.ts
  packages/pieces/community/activity/src/lib/actions/create-activity.ts
  packages/pieces/community/activity/src/lib/actions/shared.ts
  packages/pieces/community/activity/src/lib/actions/update-activity.ts
  packages/pieces/community/activity/tsconfig.json
  packages/pieces/community/activity/tsconfig.lib.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/common/1716105958530-RemoveShowActivityLog.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/activity/activity-controller.ts
  packages/server/api/src/app/ee/activity/activity-entity.ts
  packages/server/api/src/app/ee/activity/activity-module.ts
  packages/server/api/src/app/ee/activity/activity-service.ts
  packages/server/api/src/app/ee/activity/activity-worker-controller.ts
  packages/server/api/src/app/ee/authentication/rbac/access-control-list.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/server/api/src/app/platform/platform.entity.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/activity/activity-worker.test.ts
  packages/server/api/test/integration/cloud/activity/activity.test.ts
  packages/shared/src/lib/common/security/permission.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/platform/platform.model.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/core/src/assets/img/custom/dashboard/activity.svg
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/services/activity.service.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
  tsconfig.base.json
Labels: auto-deploy

#4724 chore: lint server-api
  packages/server/api/src/app/database/migration/common/1716105958530-RemoveShowActivityLog.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/platform/platform.entity.ts
Labels: skip-changelog

#4674 feat: isolated-vm / unsandboxed mode should execute in worker threads
  packages/engine/src/lib/operations.ts
  packages/engine/src/main.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/engine-helper.ts
  packages/server/api/src/app/helper/telemetry.utils.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/server/shared/src/lib/file-system.ts
  packages/server/worker/src/lib/sandbox/abstract-sandbox.ts
  packages/server/worker/src/lib/sandbox/file-sandbox.ts
  packages/server/worker/src/lib/sandbox/isolate-sandbox.ts
  packages/server/worker/src/lib/sandbox/provisioner/sandbox-provisioner.ts
  packages/server/worker/src/lib/sandbox/sandbox-manager.ts
  packages/server/worker/src/lib/utils/ap-memory-queue.ts
  packages/server/worker/src/lib/utils/code-builder.ts
Labels: pre-release

#4734 fix: add missing hashtags for colors on monaco editor
  packages/ui/core/src/app/monaco-themes/ap-monaco-theme.ts
Labels: 🐛 bug, skip-changelog

#4735 chore: release candidate
  package.json
Labels: skip-changelog

#4736 chore: release rc
  package.json
Labels: pre-release, skip-changelog

#4738 fix: switch to default browser styling for scroll bars on small screens
  packages/ui/core/src/assets/scss/scroll.scss
  packages/ui/core/src/assets/scss/utlis.scss
  packages/ui/core/src/styles.scss
Labels: 🐛 bug, frontend, auto-deploy

#4744 fix: sanitize functions before post message
  packages/engine/src/main.ts
Labels: 🐛 bug

#4731 fix: stop saving while navigating between draft and published versions or previous runs
  package-lock.json
  package.json
  packages/ui/core/src/assets/scss/quill-override.scss
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/interpolating-text-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/interpolating-text-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/text-control/text-control.component.ts
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/branch-step-input-form/branch-step-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/branch-step-input-form/branch-step-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/loop-step-input-form/loop-step-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/loop-step-input-form/loop-step-input-form.component.ts
Labels: 🐛 bug, frontend

#4745 fix: add only csp for cloud
  packages/ui/core/nginx.standard.conf
Labels: skip-changelog, auto-deploy

#4749 fix: nginx if in location
  packages/ui/core/nginx.standard.conf
Labels: auto-deploy

#4752 Revert "fix: nginx if in location"
  packages/ui/core/nginx.standard.conf
Labels: auto-deploy

#4755 fix: allow CSP for all hosts & fix static assets fetching
  packages/ui/core/nginx.standard.conf
Labels: skip-changelog

#4758 fix: (data to insert menu) wasn't taking full height possible in fullscreen mode
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/mentions-list/mentions-list.component.html
Labels: 🐛 bug, auto-deploy

#4761 chore: remove nginx
  packages/ui/core/nginx.standard.conf
Labels: auto-deploy

#4765 fix: limit task on flow worker
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/flow-worker/cloud-flow-worker-hooks.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker-hooks.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
Labels: 🐛 bug, auto-deploy

#4766 fix: revert not found redirection
  packages/ui/core/nginx.standard.conf
  packages/ui/core/src/app/app-routing.module.ts
Labels: 🐛 bug, auto-deploy

#4767 fix: add x-frame-option back
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/core/nginx.standard.conf
Labels: skip-changelog, auto-deploy

#4754 feat: add run duration to runs table and add durations of steps while viewing run details
  packages/ui/common/src/lib/components/sidebar-header/sidebar-header.component.html
  packages/ui/common/src/lib/components/sidebar-header/sidebar-header.component.ts
  packages/ui/common/src/lib/pipe/duration-formatter.pipe.ts
  packages/ui/common/src/lib/pipe/duration.pipe.ts
  packages/ui/common/src/lib/pipe/index.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/core/src/assets/img/custom/status/error.svg
  packages/ui/core/src/assets/img/custom/status/success.svg
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.html
  packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.html
  packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.scss
  packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.ts
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Labels: frontend, 🌟 feature

#4726 feat: update run in real time
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/src/lib/operations.ts
  packages/engine/src/lib/services/progress.service.ts
  packages/engine/test/handler/test-helper.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/flows/flow/flow-worker.controller.ts
  packages/server/api/src/app/helper/engine-helper.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
  packages/server/api/src/app/workers/flow-worker/consumer/flow-queue-consumer.ts
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/server/api/src/app/workers/flow-worker/job-data.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-queue.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts
  packages/server/api/test/integration/ce/flows/flow-consume.test.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/flow-run/execution/execution-output.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
  packages/shared/src/lib/flow-run/flow-run.ts
  packages/shared/src/lib/flow-run/flow-status.ts
  packages/shared/src/lib/flows/step-run/dto/test-step-request.ts
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.html
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
Labels: 🌟 feature, auto-deploy

#4768 docs: update docker-compose.mdx / upgrading section wording and formatting
  docs/install/options/docker-compose.mdx
Labels: 📚 documentation

#4771 refactor: move job data to worker
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/workers/flow-worker/consumer/flow-queue-consumer.ts
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-queue.ts
  packages/server/api/src/app/workers/flow-worker/queues/queue.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-consumer.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts
  packages/server/worker/src/index.ts
  packages/server/worker/src/lib/job-data.ts
Labels: 🧹 clean up

#4774 feat(twitter): update auth note
  packages/pieces/community/twitter/package.json
  packages/pieces/community/twitter/src/index.ts
Labels: 🔌 pieces

#4776 fix: limit project to 100 in project switcher
  packages/ui/common/src/lib/service/project.service.ts
Labels: skip-changelog, auto-deploy

#4772 fix(trello): fix trigger test function to load recent sample data
  packages/pieces/community/trello/package.json
  packages/pieces/community/trello/src/lib/common/index.ts
  packages/pieces/community/trello/src/lib/triggers/cardMoved.ts
  packages/pieces/community/trello/src/lib/triggers/newCard.ts
Labels: 🔌 pieces

#4777 feat: real time run status update for production runs
  package-lock.json
  package.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/flows/flow/flow-worker.controller.ts
  packages/server/api/src/app/websockets/websockets.service.ts
  packages/server/api/src/app/workers/flow-worker/engine-response-watcher.ts
  packages/server/shared/package.json
  packages/server/shared/src/index.ts
  packages/server/shared/src/lib/typed-event-emitter.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.html
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
Labels: ⭐ enhancement, auto-deploy

#4778 chore: rename engine response watcher to webhook
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow/flow-worker.controller.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
  packages/server/api/src/app/workers/flow-worker/webhook-response-watcher.ts
  packages/server/api/test/integration/ce/flows/flow-consume.test.ts
Labels: 🧹 clean up

#4779 feat: show execution time of flow excluding queuing
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/migration/common/1716725027424-AddDurationForRuns.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow/flow-worker.controller.ts
  packages/shared/src/lib/flow-run/flow-run.ts
  packages/ui/common/src/lib/pipe/duration.pipe.ts
  packages/ui/common/src/lib/pipe/index.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.html
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.html
Labels: ⭐ enhancement, auto-deploy

#4780 fix: store time
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: auto-deploy

#4781 chore: remove reward note
  packages/ui/feature-dashboard/src/lib/components/rewards-note/rewards-note.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
Labels: 🧹 clean up, auto-deploy

#4667 feat(google-forms): add support for Google Team drives
  packages/pieces/community/google-forms/package.json
  packages/pieces/community/google-forms/src/index.ts
  packages/pieces/community/google-forms/src/lib/common/common.ts
  packages/pieces/community/google-forms/src/lib/triggers/new-form-response.ts
Labels: 🔌 pieces

#4784 fix: isolated vm in worker threads
  packages/server/worker/src/lib/sandbox/file-sandbox.ts
Labels: 🐛 bug

#4785 feat: release 0.27.0-rc.3
  .github/workflows/release-rc.yml
  package.json
Labels: pre-release

#4788 fix: improve displaying primitive data (text, numbers and booleans) in sample data view
  packages/ui/common/src/lib/components/json-view/json-view.component.html
  packages/ui/common/src/lib/components/json-view/json-view.component.ts
  packages/ui/core/src/assets/scss/json-editor-override.scss
Labels: frontend, auto-deploy

#4789 fix: ignore x-frame-origin in forms
  packages/ui/core/nginx.standard.conf
Labels: 🐛 bug, auto-deploy

#4783 feat(slack): add thread timestamp URL option
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/actions/send-message-action.ts
  packages/pieces/community/slack/src/lib/common/utils.ts
Labels: 🔌 pieces

#4782 feat(rbac): add operator role
  packages/ee/ui/project-members/src/lib/utils.ts
  packages/server/api/src/app/ee/authentication/rbac/access-control-list.ts
  packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/server/api/test/integration/cloud/flow/flow.test.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/common/security/permission.ts
  packages/shared/src/lib/project/project-member.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
Labels: ⭐ enhancement, ☁️ Paid Feature

#4790 feat: release 0.27.0-rc.4
  package.json
Labels: pre-release

#4760 feat: add email alerts on the issues
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/ee/helper/license-validator/index.ts
  packages/server/api/src/app/ee/issues/issues-service.ts
  packages/server/api/src/assets/emails/issue-created.html
  packages/ui/core/src/assets/img/custom/notification_important.svg
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-route-item/sidenav-route-item.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Labels: 🌟 feature, auto-deploy

#4792 fix: proper handling of showing notifications icon in issues section
  packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Labels: auto-deploy

#4794 fix: platform frontend url
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
Labels: 🐛 bug, auto-deploy

#4795 feat: 0.27.0-rc.5 release
  package.json
Labels: pre-release

#4797 fix(google-sheets): fix empty row issue for updated trigger
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
Labels: 🔌 pieces

#4800 chore: remove notification url
  .github/pre-release-drafter.yml
  docs/install/configurations/environment-variables.mdx
  docs/install/configurations/error-notifications.mdx
  docs/install/options/docker-compose.mdx
  docs/mint.json
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/helper/notifications.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: ⛓️‍💥 breaking-change

#4804 fix(rbac): api keys permission
  packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
Labels: 🐛 bug, auto-deploy

#4808 fix: crash on quota exceeded & fix timeout error
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/flows/flow-run/flow-run-hooks.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/worker/src/lib/sandbox/file-sandbox.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html
  packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.html
Labels: 🐛 bug

#4809 feat: release 0.27.0-rc.6
  package.json
Labels: pre-release

#4812 fix: resolve platform for saml 2.0
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-module.ts
  packages/server/api/src/app/platform/platform-utils.ts
Labels: 🐛 bug, auto-deploy

#4814 chore: remove external customer role from ui
  packages/ee/ui/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.ts
  packages/ee/ui/project-members/src/lib/utils.ts
Labels: 🧹 clean up, auto-deploy

#4805 feat(issues): add first seen column, count column / remove description
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
Labels: ⭐ enhancement, auto-deploy

#4816 fix(rbac): operator role shouldn't show 404 on the login
  packages/ui/common/src/lib/guards/show-based-on-edition.guard.ts
  packages/ui/common/src/lib/guards/show-based-on-role.guard.ts
  packages/ui/common/src/lib/guards/show-platform-settings.guard.ts
  packages/ui/core/src/app/modules/forms/forms.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
Labels: 🐛 bug, auto-deploy

#4817 feat: release 0.27.0-rc.7
  docs/security/permissions.mdx
  package.json
Labels: pre-release

#4818 fix(team): showing when existing session is expired
  packages/ui/core/src/app/app.module.ts
Labels: 🐛 bug

#4819 fix(saml): acs saml link in service provider
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts
  packages/server/api/src/app/ee/authentication/saml-authn/saml-client.ts
Labels: 🐛 bug, auto-deploy

#4824 fix: outputs inside loops not showing
  packages/ui/common/src/lib/pipe/duration-formatter.pipe.ts
  packages/ui/core/src/assets/scss/scroll.scss
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/iteration-details.service.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.ts
  packages/ui/feature-builder-store/src/lib/model/canvas-state.ts
  packages/ui/feature-builder-store/src/lib/service/run-details.service.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.action.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts
  packages/ui/feature-builder-store/src/lib/utils/flowStructureUtil.ts
Labels: skip-changelog, auto-deploy

#4826 fix: remove extra space for duration formatter
  packages/ui/common/src/lib/pipe/duration-formatter.pipe.ts
Labels: skip-changelog, auto-deploy

#4828 feat(linear): add action to perform a raw GraphQL query
  packages/pieces/community/linear/package.json
  packages/pieces/community/linear/src/index.ts
  packages/pieces/community/linear/src/lib/actions/raw-graphql-query.ts
  packages/pieces/community/linear/src/lib/common/client.ts
Labels: 🔌 pieces

#4830 fix: acs saml url
  packages/ee/ui/platform/src/lib/components/custom-domain-table/custom-domain-table.component.html
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts
  packages/server/api/src/app/ee/authentication/saml-authn/saml-client.ts
Labels: 🐛 bug, auto-deploy

#4832 fix(saml): add missing /v1 in single sign url
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
Labels: 🐛 bug, auto-deploy

#4837 fix(connections): fail if the connection is not found
  packages/pieces/community/connections/package.json
  packages/pieces/community/connections/src/lib/actions/read-connection.ts
  packages/pieces/community/connections/src/lib/connections.mdx
Labels: 🔌 pieces
