Repository activepieces/activepieces, pull requests merged in 2024-10, with the labels that each got.

#4611 feat(youtube): Custom API Call Action
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/youtube/package.json
  packages/pieces/community/youtube/src/index.ts
  packages/pieces/community/youtube/src/lib/common/auth.ts
  packages/pieces/community/youtube/src/lib/triggers/new-video.trigger.ts
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
Labels: 🔌 pieces

#5723 feat: release 0.33.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#5724 fix: import flows inside builders now overwrites current flow
  packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/index.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/loops-settings.tsx
  packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/components/ui/form.tsx
  packages/react-ui/src/components/ui/input.tsx
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
Labels: 🐛 bug

#5732 fix: tab order of the sign in field
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
Labels: 🐛 bug

#5725 fix(airtable): fix multiselect field causing overwriting of existing values
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/lib/common/index.ts
Labels: 🔌 pieces

#5726 fix: rate limit per project is not based on ids not counter to be error bullet proof
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
Labels: 🐛 bug

#5733 fix: hide npm if they are not allowed
  packages/react-ui/src/app/builder/step-settings/code-settings/code-editor.tsx
Labels: 🐛 bug

#5734 chore: remove references to deprecated AP_WEBHOOK_URL
  .devcontainer/codespaces.sh
  packages/tests-e2e/.env.e2e
Labels: 🧹 clean up

#5735 fix: generate source map for backend
  packages/server/api/project.json
Labels: 🐛 bug

#5728 fix: improve user journey in platform admin to embed builder
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/components/header.tsx
  packages/react-ui/src/app/components/request-trial.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/platform/settings/api-keys/new-api-key-dialog.tsx
  packages/react-ui/src/app/routes/platform/settings/signing-keys/index.tsx
  packages/react-ui/src/app/routes/platform/settings/signing-keys/new-signing-key-dialog.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/app/routes/settings/appearance/language-switcher.tsx
  packages/react-ui/src/components/custom/copy-to-clipboard.tsx
  packages/react-ui/src/components/embed-provider.tsx
  packages/react-ui/src/components/ui/data-table.tsx
  packages/react-ui/src/features/flows/components/share-template-dialog.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/features/plans/components/plans.tsx
  packages/shared/src/lib/common/utils/utils.ts
Labels: 🐛 bug

#5738 docs: add on-call schedule
  docs/handbook/engineering/customer-support.mdx
  docs/handbook/engineering/how-we-work.mdx
  docs/handbook/engineering/on-call.mdx
  docs/handbook/engineering/pre-releases.mdx
  docs/handbook/hiring/compensation.mdx
  docs/handbook/hiring/hiring.mdx
  docs/handbook/hiring/levels.mdx
  docs/handbook/hiring/team.mdx
  docs/mint.json
Labels: 📚 documentation

#5739 fix: host url in ee edition
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/flags/flag.service.ts
Labels: 🐛 bug

#5740 fix(date-helper): convert to use dayjs
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/date-helper/src/lib/actions/add-subtract-date.ts
  packages/pieces/community/date-helper/src/lib/actions/date-difference.ts
  packages/pieces/community/date-helper/src/lib/actions/extract-date-parts.ts
  packages/pieces/community/date-helper/src/lib/actions/format-date.ts
  packages/pieces/community/date-helper/src/lib/actions/get-current-date.ts
  packages/pieces/community/date-helper/src/lib/actions/next-day-of-week.ts
  packages/pieces/community/date-helper/src/lib/actions/next-day-of-year.ts
  packages/pieces/community/date-helper/src/lib/common/index.ts
Labels: 🔌 pieces

#5746 fix(date-helper): extend dayjs with advancedFormat to support X format
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/date-helper/src/lib/actions/add-subtract-date.ts
  packages/pieces/community/date-helper/src/lib/actions/date-difference.ts
  packages/pieces/community/date-helper/src/lib/actions/extract-date-parts.ts
  packages/pieces/community/date-helper/src/lib/actions/format-date.ts
  packages/pieces/community/date-helper/src/lib/actions/get-current-date.ts
  packages/pieces/community/date-helper/src/lib/actions/next-day-of-week.ts
  packages/pieces/community/date-helper/src/lib/actions/next-day-of-year.ts
Labels: 🔌 pieces

#5748 chore: Security upgrade @activepieces/pieces-common from 0.2.15 to 0.2.16
  packages/pieces/community/retune/package.json
Labels: 🧹 clean up

#5752 fix: steps being invalid when they are not
  packages/ee/shared/package.json
  packages/ee/shared/src/lib/billing/index.ts
  packages/react-ui/src/app/builder/step-settings/code-settings/code-editor.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/features/plans/components/plans.tsx
Labels: 🐛 bug

#5751 fix: openai 401 caused by duplicate auth headers
  packages/server/api/src/app/ai/ai-provider-proxy.ts
Labels: 🐛 bug

#5755 fix: force path style
  packages/server/api/src/app/file/s3-helper.ts
Labels: 🐛 bug

#5756 feat: 0.34.0-rc.1
  package.json
Labels: pre-release

#5758 feat(s3): make signed urls optional
  docs/install/configuration/environment-variables.mdx
  docs/install/configuration/overview.mdx
  packages/server/api/src/app/file/step-file/step-file.controller.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
Labels: ⭐ enhancement

#5760 fix: stop steps values from being wiped
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
Labels: skip-changelog

#5768 fix: Youtube & Google search console authentication instructions
  packages/pieces/community/google-search-console/package.json
  packages/pieces/community/google-search-console/src/index.ts
  packages/pieces/community/google-search-console/src/lib/actions/url-inspection.ts
  packages/pieces/community/youtube/package.json
  packages/pieces/community/youtube/src/lib/common/auth.ts
Labels: 🔌 pieces

#5771 chore: security upgrade @sentry/node from 7.64.0 to 7.75.0
  packages/server/shared/package.json
Labels: 🧹 clean up

#5775 fix: uncontrolled to controlled input warning in SignInForm component
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
Labels: 🧹 clean up

#5767 chore: remove non-llm models and use max_completion_tokens
  package-lock.json
  package.json
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
  packages/pieces/community/openai/src/lib/common/common.ts
Labels: 🔌 pieces

#5780 fix: add missing spacing in the signing key dialog
  packages/react-ui/src/app/routes/platform/settings/signing-keys/new-signing-key-dialog.tsx
Labels: ⭐ enhancement

#5757 feat(slack): update custom slack channel ID instruction and ignore bot message option for trigger
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
Labels: 🔌 pieces

#5783 feat(pdf): revamp extract text / add pdf to images
  package-lock.json
  package.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/index.ts
  packages/pieces/community/pdf/src/lib/actions/convert-pdf-to-images.ts
  packages/pieces/community/pdf/src/lib/actions/extract-text.ts
  packages/pieces/community/simplepdf/package.json
  packages/pieces/community/simplepdf/src/lib/triggers/new-submission.ts
Labels: 🔌 pieces

#5785 feat(pdf): remove convert pdf to image / revamp extract text
  package-lock.json
  package.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/lib/actions/convert-pdf-to-images.ts
Labels: 🧹 clean up

#5787 feat(slack): new mention trigger
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/triggers/new-mention.ts
Labels: 🔌 pieces

#5788 fix: update role when switching project
  packages/react-ui/src/lib/authentication-session.ts
Labels: 🐛 bug

#5790 feat: release 0.34.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#5792 fix(slack): fix new mention trigger test
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/triggers/new-mention.ts
Labels: 🔌 pieces

#5797 fix: anthropic auth header
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/text-ai/package.json
Labels: 🐛 bug

#5798 fix: provision pending user invitation on sign
  packages/server/api/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-module.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
Labels: 🐛 bug

#5800 feat: allow file property inside array
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/property/input/array-property.ts
Labels: 🛠️ piece-framework

#5801 refactor: minor clean up for list runs endpoint
  packages/server/api/src/app/authentication/authorization.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
Labels: 🧹 clean up

#5793 feat(image-ai): extract structured data from image
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/index.ts
  packages/pieces/community/image-ai/src/lib/actions/extract-data.ts
Labels: 🔌 pieces

#5802 fix(array-property): append on array of object makes data disappear
  packages/react-ui/src/app/builder/piece-properties/array-property.tsx
Labels: 🐛 bug

#5804 fix(image-ai): add prompt guide
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/lib/actions/extract-data.ts
Labels: 🔌 pieces

#5807 fix(engine): apply error handling & retries on files service
  package-lock.json
  package.json
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/files.service.ts
Labels: engine

#5808 feat: release 0.34.1
  docker-compose.yml
  package-lock.json
  package.json
  packages/engine/src/lib/services/files.service.ts
Labels: release

#5812 style(settings): remove general settings from inside card
  packages/react-ui/src/app/builder/run-list/index.tsx
  packages/react-ui/src/app/routes/settings/appearance/index.tsx
  packages/react-ui/src/app/routes/settings/general/index.tsx
Labels: ⭐ enhancement

#5816 fix(file-helper): read file
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/lib/actions/read-file.ts
Labels: 🔌 pieces

#5817 fix(chat): send correct structure to sync endpoint
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
  packages/react-ui/src/app/routes/chat/index.tsx
Labels: skip-changelog

#5819 fix: empty multiselect value is undefined now
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/piece-properties/multi-select-piece-property.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
Labels: skip-changelog

#5811 feat(pdf): convert pdf to image
  .devcontainer/Dockerfile
  Dockerfile
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/index.ts
  packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
Labels: 🔌 pieces

#5824 fix: force maximum paused duration & update subflow piece documentation
  docs/install/configuration/environment-variables.mdx
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/execution-errors.ts
  packages/pieces/community/delay/package.json
  packages/pieces/community/delay/src/index.ts
  packages/pieces/community/delay/src/lib/actions/delay-for-action.ts
  packages/pieces/community/delay/src/lib/actions/delay-until-action.ts
  packages/pieces/community/delay/src/lib/common.ts
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/index.ts
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/isolate-sandbox.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/shared/src/lib/flag/flag.ts
Labels: 🐛 bug, 📚 documentation, 🔌 pieces

#5825 fix(chat): add proper error handling
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
  packages/pieces/community/forms/src/lib/triggers/form-trigger.ts
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/components/ui/chat/chat-bubble.tsx
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 🐛 bug

#5828 feat: release 0.34.2
  docker-compose.yml
  package.json
Labels: release

#5829 feat(pdf): option to concat all images
  packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
Labels: 🔌 pieces

#5830 feat(file-helper): Add Encoding property to createFile action
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/lib/actions/create-file.ts
Labels: 🔌 pieces

#5831 feat: speed up release pieces ci/cd
  tools/scripts/pieces/update-pieces-metadata.ts
  tools/scripts/utils/piece-script-utils.ts
Labels: 🧹 clean up, 🛠️ CI

#5832 fix(framework): resolving array of objects
  packages/engine/src/lib/variables/variable-service.ts
  packages/engine/test/services/variable-service.test.ts
Labels: 🛠️ piece-framework

#5789 feat: add activation license key through ui
  docs/install/configuration/overview.mdx
  docs/resources/screenshots/activation-license-key-settings.png
  package-lock.json
  package.json
  packages/react-ui/src/app/components/platform-settings-layout.tsx
  packages/react-ui/src/app/components/request-trial.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/settings/license-key/activate-license-dialog.tsx
  packages/react-ui/src/app/routes/platform/settings/license-key/index.tsx
  packages/react-ui/src/assets/img/custom/celeberation.json
  packages/react-ui/src/lib/platforms-api.ts
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/migration/common/1728827704109-AddLicenseKeyIntoPlatform.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
  packages/server/api/src/app/ee/license-keys/license-keys-controller.ts
  packages/server/api/src/app/ee/license-keys/license-keys-module.ts
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/flags/flag.module.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/error-handler.ts
  packages/server/api/src/app/platform/platform.entity.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/license-keys/index.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: 🌟 feature

#5837 feat(human-input): allow chat ui to view images
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/index.ts
  packages/pieces/community/forms/src/lib/actions/return-file.ts
  packages/pieces/community/forms/src/lib/actions/return-markdown.ts
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/components/custom/copy-to-clipboard.tsx
  packages/react-ui/src/components/ui/copy-button.tsx
  packages/react-ui/src/features/human-input/components/ap-form.tsx
  packages/react-ui/src/features/human-input/lib/human-input-api.tsx
  packages/shared/src/lib/forms/index.ts
Labels: 🔌 pieces

#5838 feat: add redis sentinels
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/database/redis-connection.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/server/shared/src/lib/system/system-prop.ts
Labels: ⭐ enhancement

#5850 feat(subflow): remove timeout restriction
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/src/lib/helper/piece-loader.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/operations.ts
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts
  packages/pieces/community/common/src/lib/http/core/http-request.ts
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/framework/src/lib/trigger/trigger.ts
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/actions/respond.ts
  packages/pieces/community/subflows/src/lib/common.ts
  packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
Labels: 🌟 feature

#5851 fix: bump subflows
  packages/pieces/community/common/package.json
  packages/pieces/community/framework/package.json
  packages/pieces/community/subflows/package.json
Labels: skip-changelog

#5853 fix(date-helper): add custom formats
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/date-helper/src/lib/common/index.ts
Labels: 🔌 pieces

#5839 chore: admin-console typo
  packages/pieces/community/activepieces/src/index.ts
Labels: 🐛 bug

#5854 fix: set initial values for connection properties for custom auth and oauth2
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
Labels: skip-changelog

#5861 feat(slack): add action to convert markdown text to Slack custom format
  package-lock.json
  package.json
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/markdown-to-slack-format.ts
Labels: 🔌 pieces

#5866 fix: support redis sentinel
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/database/redis-connection.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
Labels: 🐛 bug

#5863 feat: release 0.34.3
  docker-compose.yml
  nx.json
  package-lock.json
  package.json
  packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts
Labels: release

#5869 fix(redis): set max retries to zero
  packages/server/api/src/app/database/redis-connection.ts
Labels: 🐛 bug

#5872 fix: accept undefined sample data
  packages/shared/src/lib/flows/sample-data/index.ts
Labels: 🐛 bug

#5873 fix(sample-data): skip saving undefined
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/shared/src/lib/flows/sample-data/index.ts
Labels: 🐛 bug

#5881 refactor: remove piece generation cli
  docs/developers/misc/scale-pieces.mdx
  docs/mint.json
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/scale-pieces.ts
  packages/cli/src/lib/utils/scale/action-utils.ts
  packages/cli/src/lib/utils/scale/auth-utils.ts
  packages/cli/src/lib/utils/scale/helpers.ts
  packages/cli/src/lib/utils/scale/index.ts
  packages/cli/src/lib/utils/scale/openai-config.ts
  packages/cli/src/lib/utils/scale/openai-utils.ts
  packages/cli/src/lib/utils/scale/types.ts
Labels: 🧹 clean up

#5889 fix: build pieces on initial load
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
Labels: 🐛 bug

#5890 chore: remove unused turbowatch
  package-lock.json
  package.json
Labels: 🧹 clean up

#5856 fix: project.externalId uniqueness apply to non-deleted projects only
  packages/server/api/src/app/database/migration/common/1729098769827-ChangeProjectUniqueConstraintToPartialIndex.ts
  packages/server/api/src/app/database/migration/sqlite/1729330108485-UpdatePlaformInSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/project/project-entity.ts
Labels: 🐛 bug

#5895 fix(google-sheets): cast sheet ID to number
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
Labels: 🔌 pieces

#5905 chore: upgrade to 20.16 bulleye
  Dockerfile
Labels: 🧹 clean up

#5907 fix: validate system props type
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/helper/system-validator.ts
Labels: 🧹 clean up

#5903 fix: handle concat texts might be undefined
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/text-helper/src/lib/actions/concat.ts
  packages/pieces/community/text-helper/src/lib/actions/find.ts
  packages/pieces/community/text-helper/src/lib/actions/replace.ts
  packages/pieces/community/text-helper/src/lib/actions/split.ts
Labels: 🔌 pieces

#5908 docs: add hardware requirements
  docs/install/configuration/hardware.mdx
  docs/mint.json
Labels: 📚 documentation

#5910 feat(google-sheets): create worksheet action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-worksheet.ts
Labels: 🔌 pieces

#5911 fix(smtp): validate mail server on platform admin before saving
  packages/react-ui/src/app/routes/platform/settings/branding/smtp-section.tsx
  packages/react-ui/src/components/ui/form.tsx
  packages/react-ui/src/components/ui/use-toast.tsx
  packages/server/api/src/app/database/migration/1729601402320-MigrateSMTPInPlatformSqlite.ts
  packages/server/api/src/app/database/migration/1729602169179-MigrateSMTPInPlatform.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/server/api/src/app/platform/platform.entity.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/platform/platform.model.ts
  packages/shared/src/lib/platform/platform.request.ts
Labels: 🐛 bug

#5913 feat: release 0.34.5
  docker-compose.yml
  package.json
Labels: release

#5893 feat(chat-ui): major improvements
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
  packages/react-ui/src/app/routes/chat/file-message.tsx
  packages/react-ui/src/app/routes/chat/image-dialog.tsx
  packages/react-ui/src/app/routes/chat/image-message.tsx
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/chat/messages-list.tsx
  packages/react-ui/src/app/routes/chat/text-message.tsx
  packages/react-ui/src/app/routes/forms/index.tsx
  packages/react-ui/src/components/ui/chat/chat-bubble.tsx
  packages/react-ui/src/components/ui/copy-button.tsx
  packages/react-ui/src/components/ui/dialog.tsx
  packages/react-ui/src/features/human-input/lib/human-input-api.tsx
  packages/react-ui/src/lib/api.ts
  packages/react-ui/tailwind.config.js
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flows/flow/form/form.controller.ts
  packages/server/api/src/app/flows/flow/form/form.module.ts
  packages/server/api/src/app/flows/flow/human-input/human-input.module.ts
  packages/server/api/src/app/flows/flow/human-input/human-input.service.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/form.ts
Labels: 🌟 feature

#5918 fix: custom connections validation wasn't working
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
Labels: 🐛 bug

#5919 fix: smtp port issue
  packages/react-ui/src/app/routes/platform/settings/branding/smtp-section.tsx
Labels: 🐛 bug

#5920 fix(slack): add groups/im/mpim as scope
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
Labels: 🔌 pieces

#5921 feat(google-sheets): create blank spreadsheet action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-spreadsheet.ts
Labels: 🔌 pieces

#5912 docs: add elestio as installation option
  docs/install/options/elestio.mdx
  docs/install/overview.mdx
  docs/mint.json
Labels: 📚 documentation

#5922 fix(webhook): resolve "too long to reply" issue and incorrect response message in /sync calls
  packages/server/api/src/app/workers/engine-controller.ts
Labels: 🐛 bug

#5925 feat: release 0.35.6
  docker-compose.yml
  package.json
Labels: release

#5928 feat: release 0.34.7
  docker-compose.yml
  package.json
Labels: release

#5867 feat(reachinbox): 12 actions and 7 triggers
  packages/pieces/community/reachinbox/.eslintrc.json
  packages/pieces/community/reachinbox/README.md
  packages/pieces/community/reachinbox/package.json
  packages/pieces/community/reachinbox/project.json
  packages/pieces/community/reachinbox/src/index.ts
  packages/pieces/community/reachinbox/src/lib/actions/add-blocklist.ts
  packages/pieces/community/reachinbox/src/lib/actions/add-email.ts
  packages/pieces/community/reachinbox/src/lib/actions/add-leads.ts
  packages/pieces/community/reachinbox/src/lib/actions/enable-warmup.ts
  packages/pieces/community/reachinbox/src/lib/actions/get-campaign-analytics.ts
  packages/pieces/community/reachinbox/src/lib/actions/get-summary.ts
  packages/pieces/community/reachinbox/src/lib/actions/pause-campaign.ts
  packages/pieces/community/reachinbox/src/lib/actions/pause-warmup.ts
  packages/pieces/community/reachinbox/src/lib/actions/remove-email.ts
  packages/pieces/community/reachinbox/src/lib/actions/set-schedule.ts
  packages/pieces/community/reachinbox/src/lib/actions/start-campaign.ts
  packages/pieces/community/reachinbox/src/lib/actions/update-lead.ts
  packages/pieces/community/reachinbox/src/lib/common/index.ts
  packages/pieces/community/reachinbox/src/lib/triggers/campaign-completed.ts
  packages/pieces/community/reachinbox/src/lib/triggers/email-bounced.ts
  packages/pieces/community/reachinbox/src/lib/triggers/email-opened.ts
  packages/pieces/community/reachinbox/src/lib/triggers/email-sent.ts
  packages/pieces/community/reachinbox/src/lib/triggers/lead-interested.ts
  packages/pieces/community/reachinbox/src/lib/triggers/lead-not-interested.ts
  packages/pieces/community/reachinbox/src/lib/triggers/reply-received.ts
  packages/pieces/community/reachinbox/tsconfig.json
  packages/pieces/community/reachinbox/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5923 fix: facebook pages markdown rendering
  packages/pieces/community/facebook-pages/package.json
  packages/pieces/community/facebook-pages/src/index.ts
Labels: 🔌 pieces

#5926 feat(slack): update slack custom channel id info
  package-lock.json
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/actions/add-reaction-to-message.ts
  packages/pieces/community/slack/src/lib/actions/get-channel-history.ts
  packages/pieces/community/slack/src/lib/actions/request-action-message.ts
  packages/pieces/community/slack/src/lib/actions/request-approval-message.ts
  packages/pieces/community/slack/src/lib/actions/send-message-action.ts
  packages/pieces/community/slack/src/lib/actions/update-message.ts
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/triggers/new-mention.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
Labels: 🔌 pieces

#5931 feat: the ability to export the flow template
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/activepieces/src/index.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/test/integration/ce/flows/flow.test.ts
Labels: ⭐ enhancement

#5932 feat: add flow control & universal ai
  packages/pieces/community/approval/package.json
  packages/pieces/community/approval/src/index.ts
  packages/pieces/community/delay/package.json
  packages/pieces/community/delay/src/index.ts
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/index.ts
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/index.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/index.ts
  packages/shared/package.json
  packages/shared/src/lib/pieces/piece.ts
Labels: 🧹 clean up

#5933 feat: fast replace for step / trigger
  packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
Labels: ⭐ enhancement

#5936 fix: importing a shared template wasn't working
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/features/flows/components/share-template-dialog.tsx
  packages/react-ui/src/features/flows/lib/sample-data-hooks.ts
Labels: 🐛 bug

#5937 docs: add ai sdk
  docs/developers/building-pieces/overview.mdx
  docs/developers/unified-ai/chat.mdx
  docs/developers/unified-ai/function-calling.mdx
  docs/developers/unified-ai/image.mdx
  docs/developers/unified-ai/overview.mdx
  docs/mint.json
  docs/resources/unified-ai.png
Labels: 📚 documentation

#5939 fix(git-sync): validate connection
  packages/react-ui/src/features/git-sync/components/connect-git-dialog.tsx
  packages/react-ui/src/features/git-sync/components/review-change-dialog.tsx
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/ee/git-sync/git-helper.ts
  packages/server/api/src/app/ee/git-sync/git-sync-helper.ts
  packages/server/api/src/app/ee/git-sync/git-sync.entity.ts
  packages/server/api/src/app/ee/git-sync/git-sync.module.ts
  packages/server/api/src/app/ee/git-sync/git-sync.service.ts
  packages/server/api/src/app/ee/git-sync/project-diff/project-diff.service.ts
  packages/server/api/src/app/ee/git-sync/project-diff/project-mapping-state.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/helper/error-handler.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/project-diff.test.ts
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 🐛 bug

#5938 fix: add validation for items in the "Loop on Items" piece
  packages/engine/src/lib/handler/loop-executor.ts
  packages/engine/src/lib/operations.ts
  packages/react-ui/src/app/builder/run-details/flow-step-input-output.tsx
Labels: 🐛 bug

#5841 feat: chat and form testing experience
  packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
  packages/pieces/community/forms/src/lib/triggers/form-trigger.ts
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/forms/index.tsx
  packages/react-ui/src/features/human-input/lib/human-input-api.tsx
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/shared/src/lib/job/index.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
  packages/server/worker/src/lib/utils/webhook-utils.ts
Labels: ⭐ enhancement

#5940 feat: support files in the chat
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
  packages/react-ui/src/app/routes/chat/file-input-preview.tsx
  packages/react-ui/src/app/routes/chat/file-message.tsx
  packages/react-ui/src/app/routes/chat/image-dialog.tsx
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/chat/messages-list.tsx
  packages/react-ui/src/app/routes/chat/text-message.tsx
  packages/react-ui/src/components/ui/chat/chat-input.tsx
  packages/react-ui/src/components/ui/chat/chat-message-list.tsx
  packages/react-ui/src/components/ui/scroll-area.tsx
  packages/react-ui/src/features/human-input/lib/human-input-api.tsx
  packages/react-ui/tailwind.config.js
Labels: 🌟 feature

#5944 feat: add owner for the connection
  packages/ee/shared/src/lib/product-embed/connection-keys/connection-requests.ts
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
  packages/react-ui/src/app/connections/connection-table.tsx
  packages/react-ui/src/components/ui/avatar-letter.tsx
  packages/react-ui/src/components/ui/user-fullname.tsx
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/app-connection/app-connection.entity.ts
  packages/server/api/src/app/database/migration/postgres/1725699690971-AddLogsFileIdIndex.ts
  packages/server/api/src/app/database/migration/postgres/1726445983043-AddAiProviderTable.ts
  packages/server/api/src/app/database/migration/postgres/1730123432651-AddConnectionOwner.ts
  packages/server/api/src/app/database/migration/sqlite/1730121414658-AddConnectionOwnerSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/connection-keys/connection-key.service.ts
  packages/server/api/src/app/helper/security-helper.ts
  packages/shared/src/lib/app-connection/app-connection.ts
  packages/shared/src/lib/flows/flow-version.ts
Labels: ⭐ enhancement

#5948 fix: callable flow stuck in running in testing mode
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
  packages/shared/src/lib/store-entry/dto/store-entry-request.ts
Labels: 🔌 pieces

#5950 feat: release 0.34.8
  docker-compose.yml
  package.json
Labels: release

#5934 feat(ai-utility): check moderation, extract structured data and classify text actions
  package-lock.json
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/common/src/lib/ai/providers/index.ts
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/utils.ts
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/index.ts
  packages/pieces/community/image-ai/src/lib/actions/extract-data.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/index.ts
  packages/pieces/community/text-ai/src/lib/actions/extract-structured-data.ts
  packages/pieces/community/utility-ai/.eslintrc.json
  packages/pieces/community/utility-ai/README.md
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/project.json
  packages/pieces/community/utility-ai/src/index.ts
  packages/pieces/community/utility-ai/src/lib/actions/check-moderation.ts
  packages/pieces/community/utility-ai/src/lib/actions/classify-text.ts
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
  packages/pieces/community/utility-ai/tsconfig.json
  packages/pieces/community/utility-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5766 chore: remove skipValueChangeDetection
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx
Labels: 🧹 clean up

#5956 fix: user migration
  packages/server/api/src/app/database/migration/postgres/1730123432651-AddConnectionOwner.ts
Labels: 🐛 bug

#5957 feat: 0.34.9
  package.json
Labels: release

#5960 feat: 0.35.0-rc.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: pre-release

#5962 fix(facebook-leads): disable pages dropdown if no pages are found
  packages/pieces/community/facebook-leads/package.json
  packages/pieces/community/facebook-leads/src/index.ts
  packages/pieces/community/facebook-leads/src/lib/common/index.ts
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
Labels: 🐛 bug, 🔌 pieces

#5958 docs: Update overview.mdx to remove additional `:`
  docs/admin-console/overview.mdx
Labels: 📚 documentation
