Repository activepieces/activepieces, pull requests merged in 2024-09, with the labels that each got.

#5463 feat: enrich analytics api
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1725113652923-AddAnalyticsToPlatform.ts
  packages/server/api/src/app/database/migration/sqlite/1725151368300-AddAnalyticsToPlatformSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/analytics/analytics.service.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
  packages/shared/src/lib/analytics/index.ts
Labels: ⭐ enhancement

#5475 docs: update commercial license reference
  docs/about/license.mdx
Labels: 📚 documentation

#5479 docs: update the description of the deploy.sh keys
  docs/endpoints/overview.mdx
  docs/install/configurations/environment-variables.mdx
Labels: 📚 documentation

#5481 feat(dust): add mime type after breaking API change
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
Labels: 🔌 pieces

#5444 feat(slack): set user's status, find user by slack handle actions and make channel optional for trigger
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/find-user-by-handle.ts
  packages/pieces/community/slack/src/lib/actions/set-user-status.ts
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
Labels: 🔌 pieces

#5448 fix(dropbox): add token_access_type param to avail refresh token
  packages/pieces/community/dropbox/package.json
  packages/pieces/community/dropbox/src/index.ts
Labels: 🔌 pieces

#5500 fix(ai-table): handle empty array
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/lib/actions/find-record.ts
  packages/pieces/community/apitable/src/lib/actions/update-record.ts
Labels: 🔌 pieces

#5496 fix(image-helper): add custom file name property
  packages/pieces/community/image-helper/package.json
  packages/pieces/community/image-helper/src/lib/actions/compress-image.actions.ts
  packages/pieces/community/image-helper/src/lib/actions/crop-image.action.ts
  packages/pieces/community/image-helper/src/lib/actions/resize-Image.action.ts
  packages/pieces/community/image-helper/src/lib/actions/rotate-image.action.ts
Labels: 🔌 pieces

#5506 feat(wedof): adding cfSuerveys dropdown
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/lib/actions/certification-folders/declare-certification-folder-totake.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts
Labels: 🔌 pieces

#5510 feat(dust): improve error management and add action to get existing conversation
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/get-conversation.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#5513 fix(google-sheets): fix update row action input
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
Labels: 🔌 pieces

#5517 fix: empty variable resolving when delay is used inside loop
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/variables/variable-service.ts
  packages/engine/test/handler/flow-with-pause.test.ts
  packages/engine/test/services/variable-service.test.ts
Labels: 🐛 bug, engine

#5519 fix: step file should not be unique
  packages/server/api/src/app/database/migration/common/1725570317713-RemoveUniqueConstraintOnStepFile.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/step-file/step-file.entity.ts
  packages/server/api/src/app/flows/step-file/step-file.service.ts
Labels: 🐛 bug

#5497 feat(perplexity-ai): create chat completion action
  packages/pieces/community/perplexity-ai/.eslintrc.json
  packages/pieces/community/perplexity-ai/README.md
  packages/pieces/community/perplexity-ai/package.json
  packages/pieces/community/perplexity-ai/project.json
  packages/pieces/community/perplexity-ai/src/index.ts
  packages/pieces/community/perplexity-ai/src/lib/actions/create-chat-completion.action.ts
  packages/pieces/community/perplexity-ai/tsconfig.json
  packages/pieces/community/perplexity-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5523 docs: Breaking Changes in Sandbox Variables & Onboarding Checklist
  docs/_snippets/execution-mode.mdx
  docs/about/breaking-changes.mdx
  docs/embedding/provision-users.mdx
  docs/install/architecture.mdx
  docs/install/architecture/overview.mdx
  docs/install/architecture/stack.mdx
  docs/install/architecture/workers.mdx
  docs/install/configuration/environment-variables.mdx
  docs/install/configuration/overview.mdx
  docs/install/configuration/setup-app-webhooks.mdx
  docs/install/configuration/setup-ssl.mdx
  docs/install/configuration/troubleshooting.mdx
  docs/install/enterprise.mdx
  docs/install/options/docker-compose.mdx
  docs/install/options/docker.mdx
  docs/install/overview.mdx
  docs/mint.json
  packages/engine/src/lib/core/code/code-sandbox.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/encryption.ts
  packages/server/api/src/app/pieces/piece-service/index.ts
  packages/server/shared/src/lib/job/index.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/src/lib/engine/index.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/isolate-sandbox.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/shared/src/lib/engine/code-sandbox-type.ts
  packages/shared/src/lib/engine/index.ts
Labels: 📚 documentation

#5527 fix(apitable): remove AI category
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/index.ts
Labels: 🔌 pieces

#5401 feat: implement periodic cleanup for flow run log files
  packages/react-ui/src/app/builder/run-details/index.tsx
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
  packages/server/shared/src/lib/system/system.ts
Labels: 🌟 feature

#5533 fix: add proper message run for unavailable flow run log
  packages/react-ui/src/app/builder/run-details/index.tsx
  packages/server/api/src/app/flags/flag.service.ts
  packages/shared/src/lib/flag/flag.ts
Labels: ⭐ enhancement

#5535 fix(imap): enhance speed by filtering emails first
  packages/pieces/community/imap/src/index.ts
  packages/pieces/community/imap/src/lib/common/index.ts
  packages/pieces/community/imap/src/lib/triggers/new-email.ts
Labels: 🔌 pieces

#5536 chore: bump imap version
  packages/pieces/community/imap/package.json
Labels: skip-changelog

#5538 fix: batch delete run logs
  .vscode/settings.json
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
Labels: 🐛 bug

#5539 fix: add piece analytics back
  packages/server/api/src/app/ee/analytics/analytics.module.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
Labels: 🐛 bug

#5542 fix: handle removed sample data + correctly delete webhook simulation
  packages/react-ui/src/app/builder/run-details/index.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/features/flows/lib/trigger-events-api.ts
Labels: skip-changelog, auto-deploy

#5544 fix: whitelist accept user invites from having Authorization header
  packages/react-ui/src/lib/api.ts
Labels: skip-changelog, auto-deploy

#5545 feat(chargekeep): create product, get contact details actions and update new subscription trigger
  packages/pieces/community/chargekeep/package.json
  packages/pieces/community/chargekeep/src/index.ts
  packages/pieces/community/chargekeep/src/lib/actions/create-product.ts
  packages/pieces/community/chargekeep/src/lib/actions/get-contact-details.ts
  packages/pieces/community/chargekeep/src/lib/triggers/new-subscription.ts
Labels: 🔌 pieces

#5537 fix(actualbudget): refactor year/month dropdown options
  packages/pieces/community/actualbudget/package.json
  packages/pieces/community/actualbudget/src/index.ts
  packages/pieces/community/actualbudget/src/lib/actions/get-accounts.ts
  packages/pieces/community/actualbudget/src/lib/actions/get-budget.ts
  packages/pieces/community/actualbudget/src/lib/actions/get-categories.ts
  packages/pieces/community/actualbudget/src/lib/actions/import-transaction.ts
  packages/pieces/community/actualbudget/src/lib/actions/import-transactions.ts
  packages/pieces/community/actualbudget/src/lib/common/common.ts
Labels: 🔌 pieces

#5546 fix: toggling dynamic input for child dynamic props was not setting their values correctly
  packages/react-ui/src/app/builder/piece-properties/array-property.tsx
  packages/react-ui/src/app/builder/piece-properties/auto-form-field-wrapper.tsx
  packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx
Labels: auto-deploy

#5477 feat(smaily): add/update subscriber, get subscriber actions
  packages/pieces/community/smaily/.eslintrc.json
  packages/pieces/community/smaily/README.md
  packages/pieces/community/smaily/package.json
  packages/pieces/community/smaily/project.json
  packages/pieces/community/smaily/src/index.ts
  packages/pieces/community/smaily/src/lib/actions/create-or-update-subscriber.action.ts
  packages/pieces/community/smaily/src/lib/actions/get-subscriber.action.ts
  packages/pieces/community/smaily/src/lib/actions/trigger-automation-workflow.action.ts
  packages/pieces/community/smaily/tsconfig.json
  packages/pieces/community/smaily/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5552 docs: flow templates endpoint
  docs/endpoints/flow-templates/create.mdx
  docs/endpoints/flow-templates/delete.mdx
  docs/endpoints/flow-templates/get.mdx
  docs/endpoints/flow-templates/list.mdx
  docs/endpoints/flow-templates/schema.mdx
  docs/mint.json
  docs/openapi.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
  packages/server/api/src/app/flags/flag.service.ts
Labels: 📚 documentation

#5558 feat: release 0.30.0
  .github/workflows/release.yml
  docker-compose.yml
  package-lock.json
  package.json
  packages/engine/src/lib/variables/variable-service.ts
  packages/react-ui/src/app/components/locked-feature-guard.tsx
  packages/react-ui/src/app/components/project-settings-layout.tsx
  packages/react-ui/src/app/components/request-trial.tsx
  packages/react-ui/src/app/routes/issues/index.tsx
  packages/react-ui/src/app/routes/settings/team/index.tsx
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
  packages/react-ui/src/features/authentication/components/sign-up-form.tsx
Labels: release

#5564 fix: platform oauth2 connection creation
  packages/react-ui/src/app/builder/piece-properties/auto-form-field-wrapper.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
Labels: skip-changelog

#5566 feat: 0.31.0-rc.1 release
  package.json
Labels: pre-release

#5567 fix: users were not able to have multiple rows where the keys had the same prefix
  packages/react-ui/src/app/builder/piece-properties/dictionary-property.tsx
Labels: skip-changelog

#5560 feat(assemblyai): add actions for transcripts and LeMUR resources
  package-lock.json
  package.json
  packages/pieces/community/assemblyai/.eslintrc.json
  packages/pieces/community/assemblyai/.gitignore
  packages/pieces/community/assemblyai/README.md
  packages/pieces/community/assemblyai/assemblyai.env.sample
  packages/pieces/community/assemblyai/package-lock.json
  packages/pieces/community/assemblyai/package.json
  packages/pieces/community/assemblyai/project.json
  packages/pieces/community/assemblyai/scripts/generateFromSpec.ts
  packages/pieces/community/assemblyai/scripts/openapi.overrides.yml
  packages/pieces/community/assemblyai/src/index.ts
  packages/pieces/community/assemblyai/src/lib/actions/custom-api-call.ts
  packages/pieces/community/assemblyai/src/lib/actions/files/index.ts
  packages/pieces/community/assemblyai/src/lib/actions/files/upload.ts
  packages/pieces/community/assemblyai/src/lib/actions/index.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/get-lemur-response.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/index.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/lemur-task.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/purge-lemur-request-data.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/shared-props.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/delete-transcript.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-paragraphs.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-redacted-audio.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-sentences.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-subtitles.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-transcript.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/index.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/list-transcripts.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/shared-props.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/transcribe.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/word-search.ts
  packages/pieces/community/assemblyai/src/lib/auth.ts
  packages/pieces/community/assemblyai/src/lib/client.ts
  packages/pieces/community/assemblyai/src/lib/generated/lemur-task/props.ts
  packages/pieces/community/assemblyai/src/lib/generated/list-transcript/props.ts
  packages/pieces/community/assemblyai/src/lib/generated/transcribe/props.ts
  packages/pieces/community/assemblyai/tsconfig.json
  packages/pieces/community/assemblyai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5574 fix: svg piece logo rendering at 0x0
  packages/react-ui/src/features/pieces/components/piece-icon.tsx
Labels: 🐛 bug

#5573 feat(call-flows): manual subflow trigger and call flow action
  package-lock.json
  package.json
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/services/files.service.ts
  packages/engine/src/lib/services/flows.service.ts
  packages/engine/tsconfig.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/framework/src/lib/property/input/dynamic-prop.ts
  packages/pieces/community/subflows/.eslintrc.json
  packages/pieces/community/subflows/README.md
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/project.json
  packages/pieces/community/subflows/src/index.ts
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/actions/respond.ts
  packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
  packages/pieces/community/subflows/tsconfig.json
  packages/pieces/community/subflows/tsconfig.lib.json
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
  packages/react-ui/src/app/routes/settings/alerts/add-alert-email-dialog.tsx
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
  packages/react-ui/src/features/authentication/components/sign-up-form.tsx
  packages/react-ui/src/features/authentication/lib/password-validation-utils.ts
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  tsconfig.base.json
Labels: 🔌 pieces

#5578 refactor: remove upsert project member api
  docs/endpoints/project-members/create.mdx
  docs/mint.json
  docs/openapi.json
  packages/ee/shared/src/lib/project-members/project-member-request.ts
  packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
  packages/server/api/src/app/server.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
Labels: 🧹 clean up, 🖥️ api

#5579 fix: accept other non hex characters in encryption key
  packages/server/api/src/app/app.ts
Labels: 🐛 bug

#5580 fix: analytics dashboard
  packages/server/api/src/app/ee/analytics/analytics.module.ts
  packages/server/api/src/app/ee/analytics/analytics.service.ts
Labels: 🐛 bug

#5581 fix: resolve options for private piece with absolute verison
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
Labels: 🐛 bug

#5583 fix: signed in users in last 30 days
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/authentication/authentication.controller.ts
  packages/server/api/src/app/ee/analytics/analytics.service.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
  packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-controller.ts
  packages/server/api/src/app/ee/signing-key/signing-key-controller.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/folder/folder.module.ts
  packages/server/api/src/app/helper/application-events/index.ts
Labels: 🐛 bug

#5584 feat: release 0.31.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#5525 feat: add qrcode piece
  package-lock.json
  package.json
  packages/pieces/community/qrcode/.eslintrc.json
  packages/pieces/community/qrcode/README.md
  packages/pieces/community/qrcode/package-lock.json
  packages/pieces/community/qrcode/package.json
  packages/pieces/community/qrcode/project.json
  packages/pieces/community/qrcode/src/index.ts
  packages/pieces/community/qrcode/src/lib/actions/output-qrcode-action.ts
  packages/pieces/community/qrcode/tsconfig.json
  packages/pieces/community/qrcode/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5591 fix: send user invitation validation & remove project member endpoint
  docs/endpoints/user-invitations/upsert.mdx
  docs/mint.json
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/index.ts
  packages/react-ui/src/app/routes/settings/team/index.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/react-ui/src/features/team/component/project-member-card.tsx
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/shared/src/lib/invitations/index.ts
Labels: 🐛 bug

#5592 feat: 0.32.0-rc.1 pre release
  package.json
Labels: pre-release

#5594 fix: empty variable on resolving with v8 isolate
  packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
  packages/engine/src/lib/variables/variable-service.ts
  packages/react-ui/src/features/projects/components/project-switcher.tsx
Labels: 🐛 bug

#5595 feat: release 0.32.0-rc.2
  package.json
Labels: pre-release

#5596 feat(pieces-assemblyai): add instructions / validate api keys
  packages/pieces/community/assemblyai/package.json
  packages/pieces/community/assemblyai/src/index.ts
  packages/pieces/community/assemblyai/src/lib/actions/files/upload.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/get-lemur-response.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/lemur-task.ts
  packages/pieces/community/assemblyai/src/lib/actions/lemur/purge-lemur-request-data.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/delete-transcript.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-paragraphs.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-redacted-audio.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-sentences.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-subtitles.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/get-transcript.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/list-transcripts.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/transcribe.ts
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/word-search.ts
  packages/pieces/community/assemblyai/src/lib/auth.ts
  packages/pieces/community/assemblyai/src/lib/client.ts
Labels: 🔌 pieces

#5588 fix(chargekeep): update gender input, and add helper function for default date
  packages/pieces/community/chargekeep/package.json
  packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact-extended.ts
  packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact.ts
  packages/pieces/community/chargekeep/src/lib/actions/create-invoice.ts
Labels: 🔌 pieces

#5599 fix: tweak dark theme
  docs/openapi.json
  packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
  packages/react-ui/src/app/routes/settings/pieces/index.tsx
  packages/react-ui/src/components/json-viewer.tsx
  packages/react-ui/src/features/authentication/components/sign-up-form.tsx
  packages/react-ui/src/styles.css
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/shared/src/lib/invitations/index.ts
Labels: 🐛 bug

#5601 feat: 0.32.0-rc.3 release
  package.json
  packages/react-ui/src/components/theme-provider.tsx
Labels: pre-release

#5605 fix: disable insert in loops
  packages/react-ui/src/app/builder/data-selector/data-selector-node-content.tsx
  packages/react-ui/src/app/builder/data-selector/data-selector-utils.ts
  packages/react-ui/src/app/builder/data-selector/index.tsx
  packages/react-ui/src/styles.css
  packages/react-ui/tailwind.config.js
Labels: 🐛 bug

#5603 feat(metabase): raise error when question fails
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/lib/actions/get-question.ts
Labels: 🔌 pieces

#5602 feat(linear): add updated and removed issue trigger
  packages/pieces/community/linear/package.json
  packages/pieces/community/linear/src/index.ts
  packages/pieces/community/linear/src/lib/triggers/removed-issue.ts
  packages/pieces/community/linear/src/lib/triggers/updated-issue.ts
Labels: 🔌 pieces

#5612 fix: send authorization method on (notion) oauth2 connection
  packages/react-ui/src/app/components/request-trial.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
Labels: 🐛 bug

#5608 fix: spelling (editior -> editor, intalled -> installed)
  packages/react-ui/src/app/builder/copilot/chat-message.tsx
  packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx
  packages/react-ui/src/app/builder/piece-properties/builder-json-wrapper.tsx
  packages/react-ui/src/app/builder/step-settings/code-settings/code-editor.tsx
  packages/react-ui/src/app/builder/step-settings/code-settings/index.tsx
  packages/react-ui/src/components/custom/json-editor.tsx
  packages/server/worker/src/lib/engine/execution-files.ts
Labels: 🐛 bug

#5613 feat: 0.32.0 release
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/api/src/app/ee/analytics/analytics.service.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
Labels: release

#5614 docs: improve hiring docs
  docs/handbook/engineering/hiring.mdx
  docs/handbook/hiring/compensation.mdx
  docs/handbook/hiring/hiring.mdx
  docs/handbook/hiring/levels.mdx
  docs/handbook/hiring/team.mdx
  docs/handbook/overview.mdx
  docs/handbook/values.mdx
  docs/mint.json
Labels: 📚 documentation

#5617 fix(supabase): authentication now works
  package-lock.json
  package.json
  packages/pieces/community/supabase/package.json
  packages/pieces/community/supabase/src/index.ts
Labels: 🔌 pieces

#5597 chore(assemblyai): update readme of pieces-assemblyai
  packages/pieces/community/assemblyai/README.md
  packages/pieces/community/assemblyai/package.json
  packages/pieces/community/assemblyai/scripts/generateFromSpec.ts
Labels: 🧹 clean up

#5620 chore(chargekeep): update piece description
  packages/pieces/community/chargekeep/package.json
  packages/pieces/community/chargekeep/src/index.ts
Labels: 🔌 pieces

#5587 feat(sperse): create invoice, get contact detail, create product, including more 3 actions and 3 triggers
  packages/pieces/community/sperse/.eslintrc.json
  packages/pieces/community/sperse/README.md
  packages/pieces/community/sperse/package.json
  packages/pieces/community/sperse/project.json
  packages/pieces/community/sperse/src/index.ts
  packages/pieces/community/sperse/src/lib/actions/add-or-update-contact-extended.ts
  packages/pieces/community/sperse/src/lib/actions/add-or-update-contact.ts
  packages/pieces/community/sperse/src/lib/actions/add-or-update-subscription.ts
  packages/pieces/community/sperse/src/lib/actions/create-invoice.ts
  packages/pieces/community/sperse/src/lib/actions/create-product.ts
  packages/pieces/community/sperse/src/lib/actions/get-contact-details.ts
  packages/pieces/community/sperse/src/lib/common/common.ts
  packages/pieces/community/sperse/src/lib/triggers/new-lead.ts
  packages/pieces/community/sperse/src/lib/triggers/new-payment.ts
  packages/pieces/community/sperse/src/lib/triggers/new-subscription.ts
  packages/pieces/community/sperse/tsconfig.json
  packages/pieces/community/sperse/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5621 feat: switch project automatically to the flow project
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/project-settings-layout.tsx
  packages/react-ui/src/app/components/sidebar-layout.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/components/custom/circular-progress.tsx
  packages/react-ui/src/components/ui/report-bugs-button.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/features/issues/hooks/issue-hooks.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/react-ui/src/hooks/project-hooks.ts
  packages/react-ui/src/lib/authentication-session.ts
Labels: 🌟 feature

#5625 fix(sperse): triggers now showing
  packages/pieces/community/sperse/package.json
  packages/pieces/community/sperse/src/index.ts
Labels: 🔌 pieces

#5627 feat: add ai tokens limit to embed jwt
  packages/ee/shared/src/lib/billing/index.ts
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
Labels: ⭐ enhancement

#5628 fix: upload piece through ui
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
  packages/react-ui/src/features/pieces/lib/pieces-api.ts
  packages/react-ui/src/lib/api.ts
Labels: 🐛 bug

#5629 fix: add memory files back
  packages/engine/src/lib/services/files.service.ts
Labels: 🐛 bug

#5630 fix: duplicate form run
  packages/react-ui/src/features/forms/components/ap-form.tsx
Labels: 🐛 bug

#5631 fix(linkedin): company dropdown
  packages/pieces/community/linkedin/package.json
  packages/pieces/community/linkedin/src/lib/actions/create-company-update.ts
  packages/pieces/community/linkedin/src/lib/actions/create-share-update.ts
  packages/pieces/community/linkedin/src/lib/common/index.ts
Labels: 🔌 pieces

#5632 fix: increase limit size in project switcher
  packages/react-ui/src/hooks/project-hooks.ts
Labels: 🐛 bug

#5626 feat: support customizing the props in createCustomApiCallAction
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/helpers/index.ts
Labels: 🛠️ piece-framework

#5616 feat: add optional validation check to OAuth2
  packages/engine/src/lib/helper/piece-helper.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
Labels: 🛠️ piece-framework

#5642 fix(airtable): add aiText field type
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/lib/common/index.ts
  packages/pieces/community/airtable/src/lib/common/models.ts
Labels: 🔌 pieces

#5638 chore(talkable): removed 'no error on failure' checkbox property
  packages/pieces/community/talkable/package.json
  packages/pieces/community/talkable/src/lib/actions/coupons/find-coupon.ts
  packages/pieces/community/talkable/src/lib/actions/loyalty/get-loyalty-redeem-actions.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-event.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-events-batch.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-purchase.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-purchases-batch.ts
  packages/pieces/community/talkable/src/lib/actions/origins/refund.ts
  packages/pieces/community/talkable/src/lib/actions/people/anonymize-person.ts
  packages/pieces/community/talkable/src/lib/actions/people/find-person.ts
  packages/pieces/community/talkable/src/lib/actions/people/unsubscribe-person.ts
  packages/pieces/community/talkable/src/lib/actions/people/update-person.ts
  packages/pieces/community/talkable/src/lib/actions/referrals/update_referral_status.ts
Labels: 🔌 pieces

#5648 feat: release 0.32.2
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/api/src/app/server.ts
  packages/server/api/test/helpers/mocks/index.ts
Labels: release

#5639 feat(linka): create invoice, get contact detail, create product, including more 3 actions and 3 triggers
  packages/pieces/community/linka/.eslintrc.json
  packages/pieces/community/linka/README.md
  packages/pieces/community/linka/package.json
  packages/pieces/community/linka/project.json
  packages/pieces/community/linka/src/index.ts
  packages/pieces/community/linka/src/lib/actions/add-or-update-contact-extended.ts
  packages/pieces/community/linka/src/lib/actions/add-or-update-contact.ts
  packages/pieces/community/linka/src/lib/actions/add-or-update-subscription.ts
  packages/pieces/community/linka/src/lib/actions/create-invoice.ts
  packages/pieces/community/linka/src/lib/actions/create-product.ts
  packages/pieces/community/linka/src/lib/actions/get-contact-details.ts
  packages/pieces/community/linka/src/lib/common/common.ts
  packages/pieces/community/linka/src/lib/triggers/new-lead.ts
  packages/pieces/community/linka/src/lib/triggers/new-payment.ts
  packages/pieces/community/linka/src/lib/triggers/new-subscription.ts
  packages/pieces/community/linka/tsconfig.json
  packages/pieces/community/linka/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5640 feat(upgrade.chat): create invoice, get contact detail, create product, including more 3 actions and 3 triggers
  packages/pieces/community/upgradechat/.eslintrc.json
  packages/pieces/community/upgradechat/README.md
  packages/pieces/community/upgradechat/package.json
  packages/pieces/community/upgradechat/project.json
  packages/pieces/community/upgradechat/src/index.ts
  packages/pieces/community/upgradechat/src/lib/actions/add-or-update-contact-extended.ts
  packages/pieces/community/upgradechat/src/lib/actions/add-or-update-contact.ts
  packages/pieces/community/upgradechat/src/lib/actions/add-or-update-subscription.ts
  packages/pieces/community/upgradechat/src/lib/actions/create-invoice.ts
  packages/pieces/community/upgradechat/src/lib/actions/create-product.ts
  packages/pieces/community/upgradechat/src/lib/actions/get-contact-details.ts
  packages/pieces/community/upgradechat/src/lib/common/common.ts
  packages/pieces/community/upgradechat/src/lib/triggers/new-lead.ts
  packages/pieces/community/upgradechat/src/lib/triggers/new-payment.ts
  packages/pieces/community/upgradechat/src/lib/triggers/new-subscription.ts
  packages/pieces/community/upgradechat/tsconfig.json
  packages/pieces/community/upgradechat/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5656 fix: project switcher search wasn't working
  packages/react-ui/src/features/forms/components/ap-form.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
Labels: 🐛 bug

#5655 fix(form-piece): forms were considering unrequired inputs required
  packages/react-ui/src/features/forms/components/ap-form.tsx
Labels: 🐛 bug

#5657 fix: lint
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/features/forms/components/ap-form.tsx
Labels: skip-changelog

#5659 fix: steps logos looked squished
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/builder-publish-button.tsx
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
  packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts
  packages/react-ui/src/app/builder/run-details/flow-step-details-card-item.tsx
  packages/react-ui/src/app/routes/platform/settings/sso/oauth2-dialog.tsx
  packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx
  packages/react-ui/src/features/flows/components/flow-version-state-dot.tsx
  packages/server/api/src/app/authentication/authentication-service/index.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-service.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts
Labels: 🐛 bug

#5660 feat: release 0.32.3
  docker-compose.yml
  package.json
Labels: release

#5663 fix: sso page
  package-lock.json
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/authenticate/index.tsx
  packages/react-ui/src/app/routes/platform/settings/branding/custom-domain-section.tsx
  packages/react-ui/src/app/routes/platform/settings/sso/saml-dialog.tsx
  packages/react-ui/src/app/routes/switch-to-beta.tsx
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
Labels: 🐛 bug

#5665 fix: /api/ui loading static assets
  nginx.react.conf
Labels: 🐛 bug

#5675 feat(github): add octokit sdk and raw graphql action
  package-lock.json
  package.json
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/index.ts
  packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts
Labels: 🔌 pieces

#5677 feat(intercom): add conversation.rated trigger
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-rated.ts
Labels: 🔌 pieces

#5672 feat(nifty): add description field for create task action
  packages/pieces/community/nifty/package.json
  packages/pieces/community/nifty/src/lib/actions/create-task.ts
Labels: 🔌 pieces

#5688 feat(dust): improve error management
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#5618 feat(aianswer): schedule call, get call details ,transcript call data and other 3 actions
  packages/pieces/community/aianswer/.eslintrc.json
  packages/pieces/community/aianswer/README.md
  packages/pieces/community/aianswer/package.json
  packages/pieces/community/aianswer/project.json
  packages/pieces/community/aianswer/src/index.ts
  packages/pieces/community/aianswer/src/lib/actions/create-phone-call.ts
  packages/pieces/community/aianswer/src/lib/actions/get-call-details.ts
  packages/pieces/community/aianswer/src/lib/actions/get-call-transcript.ts
  packages/pieces/community/aianswer/src/lib/actions/gmail-get-list-of-agents.ts
  packages/pieces/community/aianswer/src/lib/actions/schedule-call-agent.ts
  packages/pieces/community/aianswer/src/lib/common/models.ts
  packages/pieces/community/aianswer/tsconfig.json
  packages/pieces/community/aianswer/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5681 feat(github): use octokit sdk for actions and triggers
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts
  packages/pieces/community/github/src/lib/actions/create-issue.ts
  packages/pieces/community/github/src/lib/actions/get-issue-information.ts
  packages/pieces/community/github/src/lib/actions/lock-issue.ts
  packages/pieces/community/github/src/lib/actions/unlock-issue.ts
  packages/pieces/community/github/src/lib/common/index.ts
  packages/pieces/community/github/src/lib/trigger/new-star.ts
  packages/pieces/community/github/src/lib/trigger/register-trigger.ts
Labels: 🔌 pieces

#5690 feat(dust): allow creation of empty conversations
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#5692 feat: release 0.32.4
  docker-compose.yml
  package.json
Labels: release

#5671 feat(google-contacts): search contacts and update contact actions
  packages/pieces/community/google-contacts/package.json
  packages/pieces/community/google-contacts/src/index.ts
  packages/pieces/community/google-contacts/src/lib/action/search-contact.ts
  packages/pieces/community/google-contacts/src/lib/action/update-contact.ts
Labels: 🔌 pieces

#5661 fix: project settings not visible on mobile
  packages/react-ui/src/app/components/sidebar-layout.tsx
Labels: 🐛 bug

#5676 docs: Rename AP_RESIS_DB to AP_REDIS_DB
  docs/install/configuration/environment-variables.mdx
Labels: 📚 documentation

#5693 fix: iterations should not show up
  packages/engine/src/lib/operations.ts
  packages/react-ui/src/lib/utils.ts
Labels: 🐛 bug

#5694 fix: match isolated-vm version
  Dockerfile
  packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
Labels: 🐛 bug

#5695 feat: release 0.33.0-rc.1
  package.json
Labels: pre-release

#5696 fix: unneeded frontend remove loops sample data iterations code
  packages/react-ui/src/app/builder/data-selector/data-selector-utils.ts
  packages/react-ui/src/app/builder/run-details/flow-step-input-output.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/flows/step-run/step-run-service.ts
Labels: skip-changelog

#5698 fix: validate storage keys
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/storage.service.ts
  packages/pieces/community/framework/src/lib/validators/errors.ts
  packages/react-ui/src/app/connections/secret-text-connection-settings.tsx
  packages/server/api/src/app/server.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
Labels: 🐛 bug

#5699 fix: remove gap in piece search
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx
Labels: 🐛 bug

#5701 fix: increase timeout to 15 minutes
  docs/install/configuration/environment-variables.mdx
  nginx.react.conf
Labels: 🐛 bug

#5646 feat(text-ai): add prompt field
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/lib/actions/summarize-text.ts
Labels: 🔌 pieces

#5703 fix: ui crash on clickup multi dropdown
  packages/react-ui/src/app/builder/piece-properties/multi-select-piece-property.tsx
Labels: 🐛 bug

#5704 feat(github): add trigger on new push
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/lib/trigger/index.ts
Labels: 🔌 pieces

#5705 fix: tests in the engine
  packages/engine/test/services/variable-service.test.ts
Labels: 🧹 clean up

#5708 fix: logging utils
  packages/engine/src/lib/helper/logging-utils.ts
Labels: 🐛 bug, engine

#5709 feat(text-helper): add slugify action
  package-lock.json
  package.json
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/text-helper/src/index.ts
  packages/pieces/community/text-helper/src/lib/actions/slugify.ts
Labels: 🔌 pieces

#5712 feat(Activepieces): add base url and api key secret
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/activepieces/src/index.ts
  packages/pieces/community/activepieces/src/lib/actions/create-project-member.ts
  packages/pieces/community/activepieces/src/lib/actions/create-project.ts
  packages/pieces/community/activepieces/src/lib/actions/delete-project-member.ts
  packages/pieces/community/activepieces/src/lib/actions/list-project-member.ts
  packages/pieces/community/activepieces/src/lib/actions/list-project.ts
  packages/pieces/community/activepieces/src/lib/actions/update-project.ts
Labels: 🔌 pieces

#5682 fix: validate dynamic properties in step settings
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx
  packages/react-ui/src/components/ui/skeleton.tsx
Labels: 🐛 bug

#5717 fix: move invalid code template to local variable
  packages/server/api/src/assets/invalid-code.js
  packages/server/worker/src/lib/utils/code-builder.ts
Labels: 🐛 bug

#5716 fix: validate dynamic properties in step settings
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/step-settings-context.tsx
  packages/react-ui/src/components/ui/skeleton.tsx
Labels: skip-changelog

#5662 feat: support large file upload for onedrive
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/index.ts
  packages/pieces/community/microsoft-onedrive/src/lib/actions/upload-file.ts
Labels: 🔌 pieces

#5719 feat(customer-io): add support for EU workspaces
  packages/pieces/community/customer-io/package.json
  packages/pieces/community/customer-io/src/index.ts
  packages/pieces/community/customer-io/src/lib/actions/create_event.ts
  packages/pieces/community/customer-io/src/lib/common/index.ts
Labels: 🔌 pieces
