Repository activepieces/activepieces, pull requests merged in 2024-11, with the labels that each got.

#5966 fix(connections): set owner id to null when deleted
  packages/server/api/src/app/app-connection/app-connection.entity.ts
  packages/server/api/src/app/database/migration/postgres/1730627612799-AppConnectionsSetNull.ts
  packages/server/api/src/app/database/migration/sqlite/1730627777709-AppConnectionsSetNullSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
Labels: 🐛 bug

#5969 fix: pdf failed to delete folder
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
Labels: 🔌 pieces

#5976 fix: applying tags to pieces in platform admin
  package-lock.json
  packages/react-ui/src/app/builder/piece-properties/text-input-with-mentions/text-input-utils.ts
  packages/react-ui/src/app/routes/platform/pieces/apply-tags.tsx
  packages/react-ui/src/app/routes/platform/pieces/create-tag-dialog.tsx
  packages/react-ui/src/app/routes/platform/pieces/index.tsx
Labels: 🐛 bug

#5977 feat: release 0.34.10
  docker-compose.yml
  package.json
Labels: release

#5979 fix: convert pdf to image too many files error
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/lib/actions/convert-to-image.ts
Labels: 🔌 pieces

#5970 docs: Add pikapods.com hosting option
  docs/install/overview.mdx
Labels: 📚 documentation

#5980 feat: add schema version for the flow version
  packages/server/api/src/app/database/migration/postgres/1730760434336-AddFlowSchemaVersion.ts
  packages/server/api/src/app/database/migration/sqlite/1730760312426-AddFlowSchemaVersionSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-version/flow-version-entity.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/shared/src/lib/flows/dto/flow-template-request.ts
  packages/shared/src/lib/flows/flow-version.ts
Labels: ⭐ enhancement

#5984 fix: import flow should specify schema
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
  packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx
  packages/react-ui/src/features/templates/components/share-template.tsx
  packages/server/api/src/app/ee/git-sync/git-sync-helper.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/shared/src/lib/flows/operations/index.ts
Labels: 🐛 bug

#5985 fix: execute fallback when none of branches executes
  packages/engine/src/lib/handler/router-executor.ts
  packages/engine/test/handler/conditions-evaluate.test.ts
  packages/engine/test/handler/router-branching.test.ts
  packages/engine/test/handler/test-helper.ts
  packages/react-ui/src/app/builder/step-settings/router-settings/index.tsx
Labels: 🐛 bug

#5996 docs(properties): added markdown variant options
  docs/developers/piece-reference/properties.mdx
Labels: 📚 documentation

#5994 chore(Google Drive): list all files in the folder even if they are > 100
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/list-files.action.ts
  packages/react-ui/src/app/builder/step-settings/code-settings/index.tsx
Labels: 🔌 pieces

#6003 feat(utility-ai): advanced structured data
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/property/input/dynamic-prop.ts
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: 🔌 pieces

#6005 refactor: delete branch and switch to router
  docs/about/breaking-changes.mdx
  packages/engine/src/lib/handler/branch-executor.ts
  packages/engine/src/lib/handler/context/test-execution-context.ts
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/test/handler/flow-branching-routing.test.ts
  packages/engine/test/handler/flow-branching.test.ts
  packages/engine/test/handler/flow-with-pause.test.ts
  packages/engine/test/handler/test-helper.ts
  packages/react-ui/src/app/builder/flow-canvas/flow-canvas-utils.ts
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
  packages/react-ui/src/app/builder/step-settings/branch-settings/branch-condition-group.tsx
  packages/react-ui/src/app/builder/step-settings/branch-settings/branch-single-condition.tsx
  packages/react-ui/src/app/builder/step-settings/branch-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/step-settings/router-settings/index.tsx
  packages/react-ui/src/features/pieces/lib/pieces-api.ts
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
  packages/react-ui/src/features/pieces/lib/types.ts
  packages/server/api/src/app/database/migration/common/1731019013340-switch-to-router.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-version/flow-version-validator-util.ts
  packages/server/worker/src/lib/engine/isolate/isolate-engine-runner.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/shared/src/lib/flow-run/execution/step-output.ts
  packages/shared/src/lib/flows/actions/action.ts
  packages/shared/src/lib/flows/operations/add-action.ts
  packages/shared/src/lib/flows/operations/delete-action.ts
  packages/shared/src/lib/flows/operations/import-flow.ts
  packages/shared/src/lib/flows/operations/index.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-branch-to-router.ts
  packages/shared/src/lib/flows/util/flow-structure-util.ts
Labels: 🧹 clean up, ⛓️‍💥 breaking-change

#5952 feat(human-input): unify respond actions and enhance chat file handling
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/index.ts
  packages/pieces/community/forms/src/lib/actions/return-file.ts
  packages/pieces/community/forms/src/lib/actions/return-markdown.ts
  packages/pieces/community/forms/src/lib/actions/return-response.ts
  packages/pieces/community/forms/src/lib/triggers/chat-trigger.ts
  packages/pieces/community/forms/src/lib/triggers/form-trigger.ts
  packages/react-ui/src/app/routes/404-page.tsx
  packages/react-ui/src/app/routes/chat/chat-message/file-message.tsx
  packages/react-ui/src/app/routes/chat/chat-message/image-dialog.tsx
  packages/react-ui/src/app/routes/chat/chat-message/image-message.tsx
  packages/react-ui/src/app/routes/chat/chat-message/index.tsx
  packages/react-ui/src/app/routes/chat/chat-message/text-message.tsx
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/chat/messages-list.tsx
  packages/react-ui/src/app/routes/forms/index.tsx
  packages/react-ui/src/components/custom/markdown.tsx
  packages/react-ui/src/features/human-input/components/ap-form.tsx
  packages/react-ui/src/features/human-input/lib/human-input-api.tsx
  packages/react-ui/src/styles.css
  packages/react-ui/tailwind.config.js
  packages/shared/package.json
  packages/shared/src/lib/forms/index.ts
Labels: 🔌 pieces

#5954 chore(http): move response return action to webhook piece
  packages/pieces/community/http/package.json
  packages/pieces/community/http/src/index.ts
  packages/pieces/community/webhook/src/index.ts
  packages/pieces/community/webhook/src/lib/actions/return-response.ts
  packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts
  packages/react-ui/src/components/custom/markdown.tsx
  packages/shared/test/flow/flow-helper.test.ts
Labels: ⭐ enhancement

#5964 feat: google-calendar add `Expand Recurring Event` option
  packages/pieces/community/google-calendar/package.json
  packages/pieces/community/google-calendar/src/index.ts
  packages/pieces/community/google-calendar/src/lib/actions/get-events.ts
Labels: 🔌 pieces

#6015 fix: save sample data when flow is not published
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
Labels: 🐛 bug

#6014 chore: delete all trigger data and move new one to s3
  packages/react-ui/src/features/flows/lib/trigger-events-api.ts
  packages/server/api/src/app/database/migration/postgres/1729602169179-MigrateSMTPInPlatform.ts
  packages/server/api/src/app/database/migration/postgres/1729776414647-AddPinnedPieces.ts
  packages/server/api/src/app/database/migration/postgres/1731247581852-StoreTriggerEventsInFile.ts
  packages/server/api/src/app/database/migration/sqlite/1729601402320-MigrateSMTPInPlatformSqlite.ts
  packages/server/api/src/app/database/migration/sqlite/1729774033945-AddPinnedPiecesSqlite.ts
  packages/server/api/src/app/database/migration/sqlite/1731247180217-StoreTriggerEventsInFileSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.entity.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
  packages/shared/src/lib/file/index.ts
  packages/shared/src/lib/flows/trigger-events/trigger-event.ts
Labels: 🐛 bug

#6018 fix: speed up deletion
  packages/server/api/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#5997 feat(webling): 2 triggers and get events by ID action
  packages/pieces/community/webling/.eslintrc.json
  packages/pieces/community/webling/README.md
  packages/pieces/community/webling/package.json
  packages/pieces/community/webling/project.json
  packages/pieces/community/webling/src/index.ts
  packages/pieces/community/webling/src/lib/actions/get-events-by-id.ts
  packages/pieces/community/webling/src/lib/common/helpers.ts
  packages/pieces/community/webling/src/lib/common/index.ts
  packages/pieces/community/webling/src/lib/common/types.ts
  packages/pieces/community/webling/src/lib/triggers/calendar-event.ts
  packages/pieces/community/webling/src/lib/triggers/on-changed-data.ts
  packages/pieces/community/webling/tsconfig.json
  packages/pieces/community/webling/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6021 fix: make piece selector and flow templates dialog adjust their height according to available height
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-tag-group.tsx
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
  packages/react-ui/src/app/builder/pieces-selector/steps-card-list.tsx
  packages/react-ui/src/components/ui/image-with-fallback.tsx
  packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx
  packages/react-ui/src/features/pieces/components/piece-icon.tsx
Labels: 🐛 bug

#6029 fix: e2e test
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
Labels: skip-changelog

#6030 feat: release 0.35.0
  docker-compose.yml
  package.json
Labels: release

#6027 feat(claude): add claude 3.5 haiku model
  packages/pieces/community/claude/package.json
  packages/pieces/community/claude/src/lib/actions/send-prompt.ts
Labels: 🔌 pieces

#6034 fix: graceful error handling
  packages/server/api/src/app/copilot/copilot.service.ts
Labels: 🐛 bug

#6039 fix: overwrite flow when importing from context menu
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
  packages/server/api/src/app/copilot/copilot.module.ts
  packages/server/api/src/app/copilot/copilot.service.ts
Labels: 🐛 bug

#6033 feat(connections): the ability to rename connections
  docs/about/breaking-changes.mdx
  docs/openapi.json
  package-lock.json
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/engine/.test.env
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/services/connections.service.ts
  packages/engine/src/lib/services/progress.service.ts
  packages/engine/test/handler/test-helper.ts
  packages/pieces/community/connections/package.json
  packages/pieces/community/connections/src/lib/actions/read-connection.ts
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
  packages/react-ui/src/app/connections/connection-table.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/connections/new-connection-dialog.tsx
  packages/react-ui/src/app/connections/new-connection-utils.ts
  packages/react-ui/src/app/connections/rename-connection-dialog.tsx
  packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/components/ui/table-title.tsx
  packages/react-ui/src/features/connections/lib/app-connections-api.ts
  packages/react-ui/src/features/connections/lib/app-connections-utils.ts
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/server/api/src/app/ai/ai-provider-proxy.ts
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection-worker-controller.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/app-connection/app-connection.entity.ts
  packages/server/api/src/app/app-connection/app-connection.module.ts
  packages/server/api/src/app/authentication/authentication-service/index.ts
  packages/server/api/src/app/copilot/copilot.module.ts
  packages/server/api/src/app/copilot/copilot.service.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1731428722977-MigrateConnectionNames.ts
  packages/server/api/src/app/database/migration/sqlite/1731443310900-MigrateConnectionNamesSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/connection-keys/connection-key.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/platform/platform-utils.ts
  packages/server/api/test/integration/cloud/app-connection/app-connection.test.ts
  packages/shared/src/lib/app-connection/app-connection.ts
  packages/shared/src/lib/app-connection/dto/read-app-connection-request.ts
  packages/shared/src/lib/app-connection/dto/upsert-app-connection-request.ts
  packages/shared/src/lib/user/user.ts
Labels: 🌟 feature, ⛓️‍💥 breaking-change

#6041 fix: inside builder is undefined
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/builder/flow-canvas/widgets/incomplete-settings-widget.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
  packages/shared/package.json
  packages/shared/src/lib/common/telemetry.ts
Labels: skip-changelog

#6040 fix(flows): import flow redirection
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
Labels: 🐛 bug

#6046 feat: release 0.35.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#6049 fix: pieces should be unique in the template
  packages/server/api/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#6042 chore: update webhook triggers desc
  packages/pieces/community/gravityforms/package.json
  packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts
  packages/pieces/community/moxie-crm/package.json
  packages/pieces/community/moxie-crm/src/lib/triggers/register-trigger.ts
  packages/pieces/community/poper/package.json
  packages/pieces/community/poper/src/lib/triggers/new-lead.ts
  packages/pieces/community/reachinbox/package.json
  packages/pieces/community/reachinbox/src/lib/triggers/campaign-completed.ts
  packages/pieces/community/reachinbox/src/lib/triggers/email-bounced.ts
  packages/pieces/community/reachinbox/src/lib/triggers/email-opened.ts
  packages/pieces/community/reachinbox/src/lib/triggers/email-sent.ts
  packages/pieces/community/reachinbox/src/lib/triggers/lead-interested.ts
  packages/pieces/community/reachinbox/src/lib/triggers/lead-not-interested.ts
  packages/pieces/community/reachinbox/src/lib/triggers/reply-received.ts
  packages/pieces/community/tally/package.json
  packages/pieces/community/tally/src/lib/triggers/new-submission.ts
Labels: 🔌 pieces

#6050 feat: bulk delete on projects / templates table
  package-lock.json
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/platform/templates/index.tsx
  packages/react-ui/src/features/connections/lib/app-connections-api.ts
Labels: ⭐ enhancement

#6056 feat: release 0.36.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#6057 fix(subflows): testing flow experience
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/actions/respond.ts
  packages/pieces/community/subflows/src/lib/common.ts
  packages/pieces/community/subflows/src/lib/triggers/callable-flow.ts
Labels: 🔌 pieces

#6058 feat(audit-logs): filter by user / project / action
  package-lock.json
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/react-ui/src/app/routes/platform/audit-logs/index.tsx
  packages/react-ui/src/app/routes/platform/users/index.tsx
  packages/react-ui/src/app/routes/platform/users/update-user-dialog.tsx
  packages/react-ui/src/features/connections/components/edit-global-connection-dialog.tsx
  packages/react-ui/src/hooks/platform-user-hooks.ts
  packages/react-ui/src/lib/platform-user-api.ts
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/database/migration/postgres/1731711188507-AddAuditLogIndicies.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-entity.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-module.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
Labels: 🌟 feature

#6025 feat(smtp): add support for multiple attachments in SMTP Piece
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🔌 pieces

#6060 fix: dragging step while the left side bar was open + stop deleting step when dragged under itself
  packages/react-ui/src/app/builder/flow-canvas/flow-drag-layer.tsx
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/app/builder/flow-canvas/step-drag-overlay.tsx
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/routes/platform/connections/index.tsx
Labels: 🐛 bug

#6062 chore(Human-Input): make it possible to drop/paste images in input + make text input resizable on new lines.
  package-lock.json
  package.json
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/components/ui/chat/chat-input.tsx
  packages/react-ui/src/components/ui/textarea.tsx
  packages/react-ui/src/lib/utils.ts
Labels: ⭐ enhancement

#6073 feat: release 0.36.1
  docker-compose.yml
  package.json
Labels: release

#6068 feat(sftp): add generic sftp actions
  packages/pieces/community/sftp/package.json
  packages/pieces/community/sftp/src/index.ts
  packages/pieces/community/sftp/src/lib/actions/create-folder.ts
  packages/pieces/community/sftp/src/lib/actions/delete-file.ts
  packages/pieces/community/sftp/src/lib/actions/delete-folder.ts
  packages/pieces/community/sftp/src/lib/actions/list.ts
  packages/pieces/community/sftp/src/lib/actions/read-file.ts
  packages/pieces/community/sftp/src/lib/actions/rename-file-or-folder.ts
  packages/pieces/community/sftp/src/lib/actions/upload-file.ts
Labels: 🔌 pieces

#6072 feat(apify): start actor action
  packages/pieces/community/apify/package.json
  packages/pieces/community/apify/src/index.ts
  packages/pieces/community/apify/src/lib/actions/get-actors.ts
  packages/pieces/community/apify/src/lib/actions/get-dataset-items.ts
  packages/pieces/community/apify/src/lib/actions/get-last-run.ts
  packages/pieces/community/apify/src/lib/actions/start-actor.ts
Labels: 🔌 pieces

#6077 fix: stop refreshing step settings editing a published version
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
  packages/react-ui/src/app/routes/platform/settings/license-key/activate-license-dialog.tsx
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
Labels: 🐛 bug

#6075 refactor: props resolver
  package-lock.json
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/test-execution-context.ts
  packages/engine/src/lib/handler/loop-executor.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/handler/router-executor.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/variables/props-processor.ts
  packages/engine/src/lib/variables/props-resolver.ts
  packages/engine/src/lib/variables/variable-service.ts
  packages/engine/test/handler/test-helper.ts
  packages/engine/test/services/props-resolver.test.ts
  packages/shared/src/lib/common/utils/object-utils.ts
  packages/shared/src/lib/flows/operations/index.ts
Labels: 🧹 clean up

#6078 fix(qdrant): fix embedding ids field parsing error
  packages/pieces/community/qdrant/package.json
  packages/pieces/community/qdrant/src/lib/actions/add-points.ts
Labels: 🔌 pieces

#6064 feat(instasent): add or update contact, delete contact and create event action
  packages/pieces/community/instasent/.eslintrc.json
  packages/pieces/community/instasent/README.md
  packages/pieces/community/instasent/package.json
  packages/pieces/community/instasent/project.json
  packages/pieces/community/instasent/src/index.ts
  packages/pieces/community/instasent/src/lib/actions/add-or-update-contact.ts
  packages/pieces/community/instasent/src/lib/actions/create-event.ts
  packages/pieces/community/instasent/src/lib/actions/delete-contact.ts
  packages/pieces/community/instasent/src/lib/common/constants.ts
  packages/pieces/community/instasent/src/lib/common/types.ts
  packages/pieces/community/instasent/tsconfig.json
  packages/pieces/community/instasent/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6084 feat(azure-communication-services): send email
  package-lock.json
  package.json
  packages/pieces/community/azure-communication-services/.eslintrc.json
  packages/pieces/community/azure-communication-services/README.md
  packages/pieces/community/azure-communication-services/package.json
  packages/pieces/community/azure-communication-services/project.json
  packages/pieces/community/azure-communication-services/src/index.ts
  packages/pieces/community/azure-communication-services/src/lib/actions/send-email.ts
  packages/pieces/community/azure-communication-services/tsconfig.json
  packages/pieces/community/azure-communication-services/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6088 fix(embed): stop task override when it is undefined in jwt
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
Labels: 🐛 bug

#6092 fix(pieces): revert validation in the piece
  packages/pieces/community/azure-openai/package.json
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/validation/index.ts
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/delay/package.json
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/openai/package.json
  packages/pieces/community/perplexity-ai/package.json
  packages/pieces/community/sendy/package.json
  packages/pieces/community/store/package.json
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/twitter/package.json
Labels: 🐛 bug

#6099 fix: remove public schema reference from migration files
  packages/server/api/src/app/database/migration/postgres/1730123432651-AddConnectionOwner.ts
  packages/server/api/src/app/database/migration/postgres/1731711188507-AddAuditLogIndicies.ts
Labels: 🧹 clean up

#6102 chore: upgrade bullmq
  package-lock.json
  package.json
  packages/server/api/src/app/workers/redis/redis-queue.ts
Labels: 🧹 clean up

#6104 feat: release 0.36.2
  docker-compose.yml
  package.json
Labels: release

#6105 fix: allow empty response in pause
  package-lock.json
  packages/engine/src/lib/handler/piece-executor.ts
Labels: 🐛 bug

#6106 fix(engine): handle empty value in store
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/storage.service.ts
Labels: 🐛 bug

#6107 feat(gmail): allow custom from address
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
Labels: 🔌 pieces

#6111 fix: remove invalid key error in the engine and handle null key
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/storage.service.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
Labels: 🐛 bug

#6109 fix(utility-ai): add raw message for data extraction error
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
Labels: 🔌 pieces

#6108 fix(google-sheets): fix duplicates option error
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
Labels: 🔌 pieces

#6112 fix: smtp port
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
Labels: 🐛 bug

#6113 feat: release 0.36.3
  package.json
Labels: release

#6115 fix: simplify delete stale data logic
  packages/server/api/src/app/file/file.module.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
Labels: 🐛 bug

#6116 fix: index trigger events & runs to speed up delete
  package-lock.json
  packages/server/api/src/app/database/migration/postgres/1732324567513-AddIndiciesToRunAndTriggerData.ts
  packages/server/api/src/app/database/migration/sqlite/1732324359348-AddIndiciesToTriggerEventSqlite.ts
  packages/server/api/src/app/database/migration/sqlite/1732324481815-AddIndiciesToRunSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.entity.ts
Labels: 🐛 bug

#6117 fix: delete s3 object when file is deleted
  packages/server/api/src/app/file/file.module.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/file/s3-helper.ts
Labels: 🐛 bug

#6118 feat: release 0.36.4
  docker-compose.yml
  package.json
Labels: release

#6114 feat: Flow Execution & Workers observability
  package-lock.json
  packages/react-ui/src/app/components/platform-settings-layout.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/settings/workers/index.tsx
  packages/react-ui/src/app/routes/platform/settings/workers/worker-configs-dialog.tsx
  packages/react-ui/src/components/custom/circular-icon.tsx
  packages/react-ui/src/features/platform-admin-panel/lib/workers-api.ts
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/workers/machine/machine-controller.ts
  packages/server/api/src/app/workers/machine/machine-service.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/utils/heartbeat.ts
  packages/shared/src/lib/workers/index.ts
Labels: 🌟 feature

#6119 refactor: minr ui change
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/ee/shared/src/lib/project-members/project-member.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/ee/authentication/authentication-service/hooks/authentication-helper.ts
  packages/server/api/src/app/ee/authentication/project-role/rbac-middleware.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-controller.ts
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
  packages/server/api/src/app/ee/pieces/platform-piece-module.ts
  packages/server/api/src/app/ee/project-members/project-member.entity.ts
  packages/server/api/src/app/ee/project-members/project-member.service.ts
  packages/server/api/src/app/ee/project-role/project-role.controller.ts
  packages/server/api/src/app/ee/project-role/project-role.service.ts
  packages/server/api/src/app/ee/signing-key/signing-key-controller.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/helper/application-events/index.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
  packages/shared/src/lib/invitations/index.ts
  packages/shared/src/lib/project-role/project-role.request.ts
  packages/shared/src/lib/project/project.ts
Labels: skip-changelog

#6121 feat: reorder sidebar items in platform
  packages/react-ui/src/app/components/platform-admin-container.tsx
  packages/react-ui/src/app/components/platform-second-sidebar-layout.tsx
  packages/react-ui/src/app/components/platform-settings-layout.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/settings/workers/index.tsx
Labels: ⭐ enhancement

#6122 refactor: sidebar folders
  packages/react-ui/src/app/components/platform-admin-container.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/infra/workers/index.tsx
  packages/react-ui/src/app/routes/platform/infra/workers/worker-configs-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/api-keys/index.tsx
  packages/react-ui/src/app/routes/platform/security/api-keys/new-api-key-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/audit-logs/index.tsx
  packages/react-ui/src/app/routes/platform/security/signing-keys/index.tsx
  packages/react-ui/src/app/routes/platform/security/signing-keys/new-signing-key-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/sso/allowed-domain.tsx
  packages/react-ui/src/app/routes/platform/security/sso/index.tsx
  packages/react-ui/src/app/routes/platform/security/sso/oauth2-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/sso/saml-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/ai-providers/ai-provider-card.tsx
  packages/react-ui/src/app/routes/platform/setup/ai-providers/index.tsx
  packages/react-ui/src/app/routes/platform/setup/ai-providers/upsert-provider-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/add-custom-domain.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/appearance-section.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/custom-domain-section.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/index.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/smtp-section.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/apply-tags.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/create-tag-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/piece-actions.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/sync-pieces.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/templates/index.tsx
  packages/react-ui/src/app/routes/platform/setup/templates/upsert-template-dialog.tsx
  packages/server/api/src/app/workers/machine/machine-controller.ts
  packages/server/api/src/app/workers/machine/machine-service.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/src/lib/utils/heartbeat.ts
  packages/shared/src/lib/workers/index.ts
Labels: 🧹 clean up

#6126 Revert "Revert "feat: add active flows and activated users columns to projects table in admin platform""
  packages/react-ui/src/app/routes/platform/notifications/ai-notification.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/piece-actions.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx
  packages/react-ui/src/app/routes/platform/users/index.tsx
  packages/react-ui/src/features/team/component/project-role-select.tsx
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/shared/package.json
  packages/shared/src/lib/project/project.ts
Labels: skip-changelog

#6129 feat: optimize step files uploading by relying on signed urls
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/services/files.service.ts
  packages/engine/src/lib/services/step-files.service.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/file/s3-helper.ts
  packages/server/api/src/app/file/step-file/step-file-migration.ts
  packages/server/api/src/app/file/step-file/step-file.controller.ts
  packages/server/api/src/app/file/step-file/step-file.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/step-run/sample-data.service.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
  packages/server/api/src/app/pieces/piece-service/index.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/isolate-sandbox.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/shared/src/lib/flows/step-file/step-file.ts
Labels: ⭐ enhancement

#6128 feat(google-drive): add option to support all drives when moving a file
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/move-file.ts
Labels: 🔌 pieces

#6131 fix(file-helper): fix change encoding
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/lib/actions/change-file-encoding.ts
Labels: 🔌 pieces

#6136 fix: speed up local piece development
  packages/server/shared/src/lib/pieces/file-pieces-utils.ts
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
Labels: 🌟 feature

#6145 feat(rbac): allow to update project role in teams page
  packages/ee/shared/src/lib/project-members/project-member-request.ts
  packages/react-ui/src/app/routes/settings/team/index.tsx
  packages/react-ui/src/features/platform-admin-panel/lib/project-role-api.ts
  packages/react-ui/src/features/team/component/edit-role-dialog.tsx
  packages/react-ui/src/features/team/component/project-member-card.tsx
  packages/react-ui/src/features/team/lib/project-members-api.ts
  packages/react-ui/src/hooks/authorization-hooks.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
  packages/server/api/src/app/ee/project-members/project-member.service.ts
  packages/server/api/src/app/ee/project-role/project-role.controller.ts
  packages/server/api/src/app/ee/project-role/project-role.service.ts
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
  packages/shared/src/lib/project-role/project-role.request.ts
Labels: ⭐ enhancement

#6140 fix(google-drive): files could not be moved
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/move-file.ts
Labels: 🔌 pieces

#6154 feat(form): fill the form with data from query params
  packages/react-ui/src/features/human-input/components/ap-form.tsx
Labels: ⭐ enhancement

#6159 fix: add object validation processor
  packages/engine/src/lib/variables/processors/index.ts
  packages/engine/src/lib/variables/processors/object.ts
  packages/engine/test/services/props-validator.test.ts
Labels: 🐛 bug, 🛠️ piece-framework, engine

#6146 fix: allowing json as query params on http piece
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts
  packages/pieces/community/http/package.json
Labels: 🐛 bug

#6132 fix(google-sheets): duplicate & overwrite
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-spreadsheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-worksheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts
Labels: 🔌 pieces

#6165 feat: release 0.37.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#6168 fix: rbac migration for ce edition
  packages/server/api/src/app/database/migration/postgres/1731424289830-CreateProjectRoleTable.ts
Labels: 🐛 bug

#6169 feat: release 0.37.1
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/worker/package.json
Labels: release

#6170 fix(imap): fix attachments response
  packages/pieces/community/imap/package.json
  packages/pieces/community/imap/src/lib/triggers/new-email.ts
Labels: 🔌 pieces

#6171 fix: memory usage in pod
  packages/server/worker/src/lib/utils/heartbeat.ts
Labels: 🐛 bug

#6173 fix: add project relation to user invitation
  package-lock.json
  packages/server/api/src/app/database/migration/postgres/1731424289830-CreateProjectRoleTable.ts
  packages/server/api/src/app/database/migration/postgres/1732790673766-AddProjectRelationInUserInvitation.ts
  packages/server/api/src/app/database/migration/sqlite/1732791068873-AddProjectRelationInUserInvitationSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/project-members/project-member.entity.ts
  packages/server/api/src/app/user-invitations/user-invitation.entity.ts
Labels: 🐛 bug

#6162 fix: force ui the respect the READ_RUN and other permissions
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/builder-publish-button.tsx
  packages/react-ui/src/app/builder/builder-state-provider.tsx
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
  packages/react-ui/src/app/components/allow-logged-in-user-only-guard.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/components/platform-admin-container.tsx
  packages/react-ui/src/app/components/project-settings-layout.tsx
  packages/react-ui/src/app/components/sidebar-layout.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/default-route.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/permission-guard.tsx
  packages/react-ui/src/app/routes/404-page.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/app/routes/settings/alerts/add-alert-email-dialog.tsx
  packages/react-ui/src/app/routes/settings/alerts/alerts-email-list-card.tsx
  packages/react-ui/src/app/routes/settings/alerts/alerts-frequency-card.tsx
  packages/react-ui/src/app/routes/settings/general/index.tsx
  packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx
  packages/react-ui/src/features/flows/components/flow-status-toggle.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/features/team/component/invitation-card.tsx
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/react-ui/src/features/team/component/project-member-card.tsx
  packages/react-ui/src/hooks/authorization-hooks.ts
  packages/react-ui/src/hooks/project-hooks.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
Labels: 🐛 bug

#6175 fix(engine): parsing objects
  packages/engine/src/lib/variables/processors/object.ts
  packages/engine/test/services/props-resolver.test.ts
  packages/engine/test/services/props-validator.test.ts
Labels: engine

#6174 feat(health): add health page and update routing
  packages/react-ui/src/app/components/platform-second-sidebar-layout.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/infra/health/index.tsx
Labels: 🌟 feature

#6182 fix: auto detect piece name & version in dialog
  package-lock.json
  package.json
  packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx
  packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
Labels: 🐛 bug

#6183 feat: release 0.37.2
  docker-compose.yml
  package.json
Labels: release

#6186 fix: template endpoint scope
  package-lock.json
  packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
Labels: 🐛 bug

#6191 feat(onedrive): add subfolders in dropdown
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/lib/common/common.ts
Labels: 🔌 pieces
