Repository activepieces/activepieces, pull requests merged in 2024-07, with the labels that each got.

#5021 feat(intercom): add optional keyword to filter incoming note hooks
  package-lock.json
  package.json
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
Labels: 🔌 pieces

#5026 feat: pre release 0.29.0-rc.1
  package.json
Labels: pre-release

#5027 fix: lock sandbox prepation
  package-lock.json
  package.json
  packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
Labels: 🧹 clean up

#5028 feat: 0.29.0-rc.2
  package.json
Labels: pre-release

#5035 test: add scenario for create user
  packages/server/api/src/app/core/security/authz/project-authz-handler.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/shared/src/lib/invitations/index.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.ts
Labels: skip-changelog

#5036 fix: test step infinity loading by enforcing minimum workers
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
Labels: 🐛 bug

#5038 feat: 0.29.0-rc.3
  package.json
  packages/server/api/src/app/flow-worker/redis/redis-consumer.ts
Labels: pre-release

#5039 fix: is timeout lock
  packages/server/api/src/app/flow-worker/worker-controller.ts
  packages/server/shared/src/lib/memory-lock.ts
Labels: pre-release, auto-deploy

#5040 chore: enforce disabling (Resolve Issue) button when user doesn't have the needed permission
  packages/ee/shared/src/lib/authn/access-control-list.ts
  packages/server/api/src/app/ee/issues/issues-controller.ts
  packages/shared/package.json
  packages/shared/src/lib/common/security/permission.ts
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.ts
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.html
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
Labels: auto-deploy

#4980 feat(captain-data): schedule workflow and get job results actions
  packages/pieces/community/captain-data/.eslintrc.json
  packages/pieces/community/captain-data/README.md
  packages/pieces/community/captain-data/package.json
  packages/pieces/community/captain-data/project.json
  packages/pieces/community/captain-data/src/index.ts
  packages/pieces/community/captain-data/src/lib/actions/get-job-results.ts
  packages/pieces/community/captain-data/src/lib/actions/launch-workflow.ts
  packages/pieces/community/captain-data/src/lib/common.ts
  packages/pieces/community/captain-data/tsconfig.json
  packages/pieces/community/captain-data/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5030 feat(slack): limit dropdown to 2000 channels to avoid timeout
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/common/props.ts
Labels: 🔌 pieces

#5043 chore: show 0 when run duration is 0
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.html
Labels: skip-changelog, auto-deploy

#5046 fix: stop operators from resolving issues
  docs/security/permissions.mdx
  packages/ee/shared/src/lib/authn/access-control-list.ts
  packages/ee/ui/platform/src/lib/components/dialogs/edit-user-role-dialog/edit-user-role-dialog.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
Labels: skip-changelog, auto-deploy

#5033 fix: make handlers static and refactor system jobs
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/ee/license-keys/license-keys-module.ts
  packages/server/api/src/app/ee/projects/platform-project-module.ts
  packages/server/api/src/app/ee/projects/platform-project-side-effects.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
  packages/server/api/src/app/helper/system-jobs/job-handlers.ts
  packages/server/api/src/app/helper/system-jobs/memory-system-jobs.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
  packages/server/api/src/app/pieces/piece-sync-service.ts
Labels: 🐛 bug

#5042 feat(data-summarizer): calculate average / calculate sum / count unique / get mind and max
  git-diagnostics-2024-07-02-1809.zip
  packages/pieces/community/data-summarizer/.eslintrc.json
  packages/pieces/community/data-summarizer/README.md
  packages/pieces/community/data-summarizer/package.json
  packages/pieces/community/data-summarizer/project.json
  packages/pieces/community/data-summarizer/src/index.ts
  packages/pieces/community/data-summarizer/src/lib/actions/calculate-average.ts
  packages/pieces/community/data-summarizer/src/lib/actions/calculate-sum.ts
  packages/pieces/community/data-summarizer/src/lib/actions/count-uniques.ts
  packages/pieces/community/data-summarizer/src/lib/actions/get-min-max.ts
  packages/pieces/community/data-summarizer/src/lib/common.ts
  packages/pieces/community/data-summarizer/tsconfig.json
  packages/pieces/community/data-summarizer/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5045 feat(worker): list active workers in platform admin
  packages/ee/ui/platform/src/lib/components/audit-event-table/audit-event-table.component.ts
  packages/ee/ui/platform/src/lib/components/audit-event-table/audit-event-table.datasource.ts
  packages/ee/ui/platform/src/lib/components/workers-table/workers-table.component.ts
  packages/ee/ui/platform/src/lib/components/workers-table/workers-table.datasource.ts
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ee/ui/platform/src/lib/service/audit-event.service.ts
  packages/ee/ui/platform/src/lib/service/workers.service.ts
  packages/ee/ui/platform/src/lib/ui-ee-platform.module.ts
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/retune/package.json
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/authentication/lib/access-token-manager.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1720101280025-AddWorkerMachine.ts
  packages/server/api/src/app/database/migration/sqlite/1720100928449-AddWorkerMachineSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/workers/consumer/consumer-manager.ts
  packages/server/api/src/app/workers/consumer/index.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/api/src/app/workers/helper/webhook-response-watcher.ts
  packages/server/api/src/app/workers/machine/machine-controller.ts
  packages/server/api/src/app/workers/machine/machine-entity.ts
  packages/server/api/src/app/workers/machine/machine-service.ts
  packages/server/api/src/app/workers/memory/ap-memory-queue.ts
  packages/server/api/src/app/workers/memory/memory-consumer.ts
  packages/server/api/src/app/workers/memory/memory-queue.ts
  packages/server/api/src/app/workers/queue/index.ts
  packages/server/api/src/app/workers/queue/queue-manager.ts
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
  packages/server/api/src/app/workers/redis/redis-consumer.ts
  packages/server/api/src/app/workers/redis/redis-migration.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/api/src/app/workers/worker-module.ts
  packages/server/shared/src/lib/network-utils.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/flow-worker.ts
  packages/server/worker/src/lib/utils/heartbeat.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/authentication/model/principal.ts
  packages/shared/src/lib/workers/index.ts
  packages/ui/feature-flow-builder/package.json
  packages/ui/feature-tags/package.json
Labels: ⭐ enhancement

#5047 chore: updated version for data summarizer and change caterogry
  packages/pieces/community/data-summarizer/package.json
  packages/pieces/community/data-summarizer/src/index.ts
Labels: skip-changelog

#4996 feat: send email reminders on flow run issues
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/alerts/alerts-handler.ts
  packages/server/api/src/app/ee/alerts/alerts-service.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/ee/license-keys/license-keys-module.ts
  packages/server/api/src/app/ee/projects/platform-project-module.ts
  packages/server/api/src/app/ee/projects/platform-project-side-effects.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
  packages/server/api/src/app/helper/system-jobs/job-handlers.ts
  packages/server/api/src/app/helper/system-jobs/memory-system-jobs.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
  packages/server/api/src/app/pieces/piece-sync-service.ts
  packages/server/api/src/assets/emails/issues-reminder.html
Labels: 🌟 feature

#5049 fix: remove add pragma no cache
  packages/ui/core/nginx.standard.conf
Labels: 🐛 bug

#5050 docs: update openai & fix user invitation api
  docs/openapi.json
  packages/server/api/src/app/app.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/shared/src/lib/invitations/index.ts
Labels: 📚 documentation

#5051 feat(audit-logs): reformat and stream to standard output
  docs/install/configurations/environment-variables.mdx
  docs/mint.json
  docs/openapi.json
  docs/operations/audit-logs/connection-deleted.mdx
  docs/operations/audit-logs/connection-upserted.mdx
  docs/operations/audit-logs/flow-created.mdx
  docs/operations/audit-logs/flow-deleted.mdx
  docs/operations/audit-logs/flow-run-finished.mdx
  docs/operations/audit-logs/flow-run-started.mdx
  docs/operations/audit-logs/flow-updated.mdx
  docs/operations/audit-logs/folder-created.mdx
  docs/operations/audit-logs/folder-deleted.mdx
  docs/operations/audit-logs/folder-updated.mdx
  docs/operations/audit-logs/overview.mdx
  docs/operations/audit-logs/signing-key-created.mdx
  docs/operations/audit-logs/user-email-verified.mdx
  docs/operations/audit-logs/user-password-reset.mdx
  docs/operations/audit-logs/user-signed-in.mdx
  docs/operations/audit-logs/user-signed-up.mdx
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/ee/ui/platform/src/lib/components/audit-event-table/audit-event-table.component.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/authentication/authentication.controller.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-entity.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
  packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-controller.ts
  packages/server/api/src/app/ee/signing-key/signing-key-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/folder/folder.controller.ts
  packages/server/api/src/app/helper/application-events/index.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/src/app/workers/helper/webhook-response-watcher.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/isolate-sandbox.ts
  packages/shared/src/lib/common/base-model.ts
  packages/shared/src/lib/invitations/index.ts
Labels: 🌟 feature

#5052 feat: release 0.29.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/pieces/piece-sync-service.ts
Labels: release

#5056 fix: remove value from store
  packages/engine/src/lib/services/storage.service.ts
Labels: 🐛 bug, auto-deploy

#5057 refactor: remove queues grouping
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/authentication/lib/access-token-manager.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/flows/step-run/step-run-service.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
  packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/server/api/src/app/helper/engine-helper.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/workers/consumer/consumer-manager.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/api/src/app/workers/memory/memory-consumer.ts
  packages/server/api/src/app/workers/memory/memory-queue.ts
  packages/server/api/src/app/workers/queue/queue-manager.ts
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
  packages/server/api/src/app/workers/redis/redis-consumer.ts
  packages/server/api/src/app/workers/redis/redis-migration.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/authentication/model/principal.ts
Labels: 🧹 clean up

#5058 fix: increase drain delay to 15 seconds
  packages/server/api/src/app/workers/redis/redis-consumer.ts
  packages/server/worker/src/lib/flow-worker.ts
Labels: 🐛 bug

#5053 feat(rabbitmq): new message trigger / publish message on queue / publish message on exchange
  package-lock.json
  package.json
  packages/pieces/community/rabbitmq/.eslintrc.json
  packages/pieces/community/rabbitmq/README.md
  packages/pieces/community/rabbitmq/package-lock.json
  packages/pieces/community/rabbitmq/package.json
  packages/pieces/community/rabbitmq/project.json
  packages/pieces/community/rabbitmq/src/index.ts
  packages/pieces/community/rabbitmq/src/lib/actions/send-message-to-exchange.ts
  packages/pieces/community/rabbitmq/src/lib/actions/send-message-to-queue.ts
  packages/pieces/community/rabbitmq/src/lib/common/index.ts
  packages/pieces/community/rabbitmq/src/lib/triggers/message-received.ts
  packages/pieces/community/rabbitmq/tsconfig.json
  packages/pieces/community/rabbitmq/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5059 fix: retry requests on 502
  package-lock.json
  package.json
  packages/server/worker/package.json
  packages/server/worker/src/lib/api/server-api.service.ts
Labels: 🐛 bug

#5060 fix: allow install pieces on cloud platform
  packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
  packages/server/api/src/app/ee/pieces/platform-piece-module.ts
Labels: 🐛 bug, auto-deploy

#5062 fix: ensure file exists when testing code
  packages/server/worker/src/lib/utils/code-builder.ts
Labels: 🐛 bug

#5063 feat: release 0.29.1
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/worker/src/lib/utils/code-builder.ts
Labels: release

#5064 fix: publish piece to npm & hot reload developer experience
  docs/developers/sharing-pieces/community.mdx
  docs/developers/sharing-pieces/private.mdx
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  tools/scripts/pieces/publish-piece.ts
  tools/scripts/pieces/turbowatch.ts
  tools/scripts/utils/piece-script-utils.ts
Labels: ⭐ enhancement, 💻 dx

#5065 fix: get the day of month for issue instead of day of week
  packages/server/api/src/app/ee/helper/email/email-service.ts
Labels: 🐛 bug

#5071 feat(text-helper): remove html tags from text action
  packages/pieces/community/text-helper/.eslintrc.json
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/text-helper/src/index.ts
  packages/pieces/community/text-helper/src/lib/actions/find.ts
  packages/pieces/community/text-helper/src/lib/actions/replace.ts
  packages/pieces/community/text-helper/src/lib/actions/split.ts
  packages/pieces/community/text-helper/src/lib/actions/strip-html.ts
Labels: 🔌 pieces

#5074 chore: revamp full screen code editor
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/assets/invalid-code.js
  packages/server/worker/src/lib/utils/code-builder.ts
  packages/shared/package.json
  packages/shared/src/lib/flag/flag.ts
  packages/ui/core/src/assets/img/custom/files/js.svg
  packages/ui/core/src/assets/img/custom/files/package.svg
  packages/ui/core/src/assets/img/custom/files/ts.svg
  packages/ui/core/src/assets/scss/code-editors-override.scss
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.scss
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/directives/flex-resize.directive.ts
  packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html
Labels: auto-deploy

#5076 fix: update user project role on switching
  packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
  packages/ui/common/src/lib/service/authentication.service.ts
Labels: auto-deploy

#5072 feat(workers): speed up caching in isolated mode by using global common cache
  packages/server/shared/src/lib/file-system.ts
  packages/server/shared/src/lib/package-manager.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/engine/execution-files.ts
  packages/server/worker/src/lib/engine/isolate/isolate-engine-runner.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/files/cached-sandbox-state.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/files/cached-sandbox.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/files/sandbox-cache-pool.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/isolate-sandbox.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/provisioner/sandbox-cache-key.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/provisioner/sandbox-provisioner.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/server/worker/src/lib/piece-manager/piece-manager.ts
  packages/server/worker/src/lib/piece-manager/registry-piece-manager.ts
  packages/server/worker/src/lib/trigger/hooks/extract-trigger-payload-hooks.ts
  packages/server/worker/src/lib/utils/code-builder.ts
  packages/server/worker/src/lib/utils/engine-installer.ts
Labels: 🌟 feature

#5073 fix(formbricks): survey dropdown error
  packages/pieces/community/formbricks/package.json
  packages/pieces/community/formbricks/src/index.ts
  packages/pieces/community/formbricks/src/lib/triggers/register.ts
Labels: 🔌 pieces

#5079 fix: limit to open polling connections to 10
  packages/server/worker/src/lib/flow-worker.ts
Labels: 🐛 bug

#5080 feat(embedding): add tasks limit to the jwt token
  docs/embedding/provision-users.mdx
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
Labels: ⭐ enhancement, Embed

#5082 fix: improve speed when switching between platform settings pages
  packages/ee/ui/platform/src/lib/components/sso-settings/sso-settings.component.ts
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ui/common/src/lib/resolvers/platform.resolver.ts
  packages/ui/common/src/lib/service/platform.service.ts
  packages/ui/common/src/lib/service/sync-project.service.ts
  packages/ui/core/src/app/app.component.ts
  packages/ui/feature-dashboard/src/lib/components/invite-user-button/invite-user-button.component.ts
Labels: auto-deploy

#5084 feat: show unset buttons for optional dropdowns inside automation builder
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/static-dropdown-control/static-dropdown-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/static-dropdown-control/static-dropdown-control.component.ts
Labels: auto-deploy

#5094 fix: infinite loading when switching alert type
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
Labels: auto-deploy

#5095 fix: increase fuse distance limit so it looks up deeper into text
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
Labels: skip-changelog, auto-deploy

#5077 feat(intercom): add support for EU and AU regions, add new actions
  package-lock.json
  package.json
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/actions/add-note-to-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/create-contact.action.ts
  packages/pieces/community/intercom/src/lib/actions/create-or-get-contact.action.ts
  packages/pieces/community/intercom/src/lib/actions/reply-to-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/send-message.action.ts
  packages/pieces/community/intercom/src/lib/common/index.ts
  packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
Labels: 🔌 pieces

#5098 fix: global lock pnpm add
  packages/server/worker/src/lib/piece-manager/registry-piece-manager.ts
Labels: 🐛 bug

#5099 feat(todoist): add support for natural language due dates
  packages/pieces/community/todoist/package.json
  packages/pieces/community/todoist/src/lib/actions/create-task-action.ts
  packages/pieces/community/todoist/src/lib/actions/update-task.action.ts
  packages/pieces/community/todoist/src/lib/common/client/rest-client.ts
  packages/pieces/community/todoist/src/lib/common/models.ts
Labels: 🔌 pieces

#5106 fix: ignore disabled flows
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
Labels: 🐛 bug

#5107 fix: support query by multiple status
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/shared/src/lib/app-connection/dto/read-app-connection-request.ts
  packages/ui/common/src/lib/service/app-connections.service.ts
Labels: 🐛 bug

#5108 fix: disable alerts type dropdown for non-admin users
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/delete-flow-item-action/delete-flow-item-action.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/delete-flow-item-action/delete-step-dialog/delete-step-dialog.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/delete-flow-item-action/delete-step-dialog/delete-step-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.html
Labels: skip-changelog, auto-deploy

#5111 chore: upgrade typebox
  package-lock.json
  package.json
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/ee/git-repos/git-repo.module.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/flows/dto/list-flows-request.ts
  packages/shared/src/lib/flows/flow-operations.ts
  packages/ui/common/src/lib/service/flow.service.ts
Labels: 🧹 clean up

#5113 feat(react): mark as resolved
  packages/react-ui/src/app/app.tsx
  packages/react-ui/src/components/layout/sidebar.tsx
  packages/react-ui/src/components/ui/data-table.tsx
  packages/react-ui/src/features/issues/api/issues-api.ts
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/features/issues/hooks/issue-hooks.tsx
Labels: skip-changelog

#5121 feat: persist the cache across restarts
  packages/server/shared/package.json
  packages/server/worker/src/lib/piece-manager/piece-manager.ts
  packages/server/worker/src/lib/piece-manager/registry-piece-manager.ts
  packages/server/worker/src/lib/utils/cache-handler.ts
  packages/server/worker/src/lib/utils/code-builder.ts
Labels: ⭐ enhancement

#5120 fix: activate delete dialogs
  packages/react-ui/src/app/components/invite-user-dialog.tsx
  packages/react-ui/src/app/routes/settings/team/index.tsx
  packages/react-ui/src/components/delete-dialog.tsx
  packages/react-ui/src/features/connections/components/connection-table.tsx
  packages/react-ui/src/features/connections/lib/app-connections-api.ts
  packages/react-ui/src/features/team/component/invitation-card.tsx
  packages/react-ui/src/features/team/component/platform-role-select.tsx
  packages/react-ui/src/features/team/component/project-member-card.tsx
  packages/react-ui/src/features/team/component/project-members-list.tsx
  packages/react-ui/src/features/team/component/team-list-card.tsx
  packages/react-ui/src/features/team/lib/project-members-api.ts
  packages/react-ui/src/features/team/lib/user-invitiation-api.ts
  packages/react-ui/src/hooks/project-hooks.ts
  packages/react-ui/src/hooks/project-members-hooks.ts
  packages/react-ui/src/hooks/user-invitations-hooks.ts
  packages/react-ui/src/lib/user-invitation.ts
Labels: skip-changelog

#5114 fix(airtable): use datetime formula to fetch updated records
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/lib/trigger/update-record.trigger.ts
Labels: 🔌 pieces

#5115 feat: graph rendering for loops & branches
  packages/react-ui/src/features/flow-canvas/components/big-button.tsx
  packages/react-ui/src/features/flow-canvas/components/canvas.tsx
  packages/react-ui/src/features/flow-canvas/lib/flow-canvas-utils.ts
Labels: skip-changelog

#5101 fix: Update to env docs. closes #5089
  docs/install/configurations/environment-variables.mdx
Labels: 📚 documentation

#5123 feat: add forget password component & 3P login
  packages/react-ui/src/app/router.tsx
  packages/react-ui/src/app/routes/change-password/index.tsx
  packages/react-ui/src/app/routes/forget-password/index.tsx
  packages/react-ui/src/app/routes/reset-password/index.tsx
  packages/react-ui/src/app/routes/sign-in/index.tsx
  packages/react-ui/src/app/routes/sign-up/index.tsx
  packages/react-ui/src/features/authentication/components/change-password.tsx
  packages/react-ui/src/features/authentication/components/reset-password-form.tsx
  packages/react-ui/src/lib/api.ts
  packages/react-ui/src/lib/authentication-api.ts
Labels: skip-changelog

#5127 feat: 0.30.0-rc1 release
  package.json
Labels: pre-release

#5130 chore: fix /api/ui loading static issue
  packages/ui/core/nginx.standard.conf
Labels: 🐛 bug

#5109 feat(aminos): create user action
  packages/pieces/community/aminos/.eslintrc.json
  packages/pieces/community/aminos/README.md
  packages/pieces/community/aminos/package.json
  packages/pieces/community/aminos/project.json
  packages/pieces/community/aminos/src/index.ts
  packages/pieces/community/aminos/src/lib/actions/createUser.ts
  packages/pieces/community/aminos/tsconfig.json
  packages/pieces/community/aminos/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5105 feat(razorpay): create payment link action
  packages/pieces/community/razorpay/.eslintrc.json
  packages/pieces/community/razorpay/README.md
  packages/pieces/community/razorpay/package.json
  packages/pieces/community/razorpay/project.json
  packages/pieces/community/razorpay/src/index.ts
  packages/pieces/community/razorpay/src/lib/actions/create-payment-link.ts
  packages/pieces/community/razorpay/src/lib/common/utils.ts
  packages/pieces/community/razorpay/tsconfig.json
  packages/pieces/community/razorpay/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5093 feat(actualbudget): get account / get budget / get categories / import transaction / import transactions actions
  package-lock.json
  package.json
  packages/pieces/community/actualbudget/.eslintrc.json
  packages/pieces/community/actualbudget/README.md
  packages/pieces/community/actualbudget/package-lock.json
  packages/pieces/community/actualbudget/package.json
  packages/pieces/community/actualbudget/project.json
  packages/pieces/community/actualbudget/src/index.ts
  packages/pieces/community/actualbudget/src/lib/actions/get-accounts.ts
  packages/pieces/community/actualbudget/src/lib/actions/get-budget.ts
  packages/pieces/community/actualbudget/src/lib/actions/get-categories.ts
  packages/pieces/community/actualbudget/src/lib/actions/import-transaction.ts
  packages/pieces/community/actualbudget/src/lib/actions/import-transactions.ts
  packages/pieces/community/actualbudget/src/lib/common/common.ts
  packages/pieces/community/actualbudget/src/lib/common/models.ts
  packages/pieces/community/actualbudget/tsconfig.json
  packages/pieces/community/actualbudget/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5162 fix: project switching wasn't fetching correct project role for user
  package.json
  packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
Labels: pre-release, auto-deploy

#5167 docs: add flow verisoning
  docs/flows/versioning.mdx
  docs/mint.json
  docs/resources/flow-history.png
Labels: 📚 documentation

#5178 fix: make progress update optional for old delayed runs
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/shared/src/lib/job/job-data.ts
Labels: 🐛 bug

#5139 feat(intercom): add various conversation triggers
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-assigned.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-closed.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-snoozed.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-unsnoozed.ts
  packages/pieces/community/intercom/src/lib/triggers/new-conversation-from-user.ts
  packages/pieces/community/intercom/src/lib/triggers/reply-from-admin.ts
  packages/pieces/community/intercom/src/lib/triggers/reply-from-user.ts
Labels: 🔌 pieces

#5194 fix: make cloud create trial key when requested
  packages/ui/common/src/lib/components/contact-sales/contact-sales.component.ts
Labels: auto-deploy

#5195 fix(git-sync): prevent overriding secrets after being modified on production branch
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/src/app/ee/git-repos/git-sync-helper.ts
  packages/shared/src/lib/flows/flow-helper.ts
Labels: 🐛 bug

#5208 fix: update build cloud nx with the updated template
  .github/workflows/build-cloud-nx.yml
Labels: 🧹 clean up, 🛠️ CI

#5207 feat: document pre-releases
  docs/handbook/engineering/pre-releases.mdx
  docs/mint.json
  package.json
Labels: 📚 documentation, pre-release

#5210 docs: update the pre release steps
  docs/handbook/engineering/pre-releases.mdx
Labels: 📚 documentation

#5213 fix: allow relative versions in dropdown options api
  packages/ee/ui/embed-sdk/.eslintrc.json
  packages/ee/ui/embed-sdk/package.json
  packages/engine/src/lib/helper/piece-loader.ts
  packages/pieces/community/activepieces/.eslintrc.json
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/brilliant-directories/.eslintrc.json
  packages/pieces/community/brilliant-directories/package.json
  packages/pieces/community/claude/.eslintrc.json
  packages/pieces/community/claude/package.json
  packages/pieces/community/convertkit/.eslintrc.json
  packages/pieces/community/convertkit/package.json
  packages/pieces/community/convertkit/project.json
  packages/pieces/community/file-helper/.eslintrc.json
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/math-helper/.eslintrc.json
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/pdf/.eslintrc.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/retune/.eslintrc.json
  packages/pieces/community/retune/package.json
  packages/pieces/community/saastic/.eslintrc.json
  packages/pieces/community/saastic/package.json
  packages/pieces/community/sendy/.eslintrc.json
  packages/pieces/community/vtiger/.eslintrc.json
  packages/pieces/community/vtiger/package.json
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
  packages/server/shared/package.json
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-property-core/refreshable-property-core-control.component.ts
  packages/ui/feature-flow-builder/package.json
  packages/ui/feature-tags/package.json
Labels: 🐛 bug

#5223 fix: remove stale scheduled jobs
  packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
Labels: 🐛 bug

#5180 feat(chargekeep): create invoice, create contact , create subscription actions and 3 triggers
  packages/pieces/community/chargekeep/.eslintrc.json
  packages/pieces/community/chargekeep/README.md
  packages/pieces/community/chargekeep/package.json
  packages/pieces/community/chargekeep/project.json
  packages/pieces/community/chargekeep/src/index.ts
  packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact-extended.ts
  packages/pieces/community/chargekeep/src/lib/actions/add-or-update-contact.ts
  packages/pieces/community/chargekeep/src/lib/actions/add-or-update-subscription.ts
  packages/pieces/community/chargekeep/src/lib/actions/create-invoice.ts
  packages/pieces/community/chargekeep/src/lib/common/common.ts
  packages/pieces/community/chargekeep/src/lib/triggers/new-lead.ts
  packages/pieces/community/chargekeep/src/lib/triggers/new-payment.ts
  packages/pieces/community/chargekeep/src/lib/triggers/new-subscription.ts
  packages/pieces/community/chargekeep/tsconfig.json
  packages/pieces/community/chargekeep/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#5200 feat(google-calendar): add search term to find events
  packages/pieces/community/google-calendar/package.json
  packages/pieces/community/google-calendar/src/lib/actions/get-events.ts
Labels: 🔌 pieces

#5224 chore: animate closing/opening sidebars
  packages/react-ui/src/app/builder/builder-page.tsx
  packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
  packages/shared/src/lib/flows/flow-helper.ts
Labels: blocked: waiting-response

#5228 fix: resolve dropdown options by relative version
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
  packages/server/shared/src/lib/system/system.ts
Labels: 🐛 bug
