Repository activepieces/activepieces, pull requests merged in 2024-02, with the labels that each got.

#3790 chore: fix typo
  packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/add-npm-package-modal/add-npm-package-modal.component.html
Labels: skip-changelog

#3772 feat(ninja-invoice): create invoice / create client action
  packages/pieces/community/invoiceninja/package.json
  packages/pieces/community/invoiceninja/src/index.ts
  packages/pieces/community/invoiceninja/src/lib/actions/create-client.ts
  packages/pieces/community/invoiceninja/src/lib/actions/create-invoice.ts
Labels: 🔌 pieces

#3796 fix: force logout for old tokens on cloud and newsletter
  packages/backend/src/app/authentication/authentication-service/index.ts
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/core/src/app/app.component.html
  packages/ui/core/src/app/app.component.ts
Labels: skip-changelog

#3797 fix: use test method in actions
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/engine/test/handler/flow-piece.test.ts
Labels: 🐛 bug, engine

#3799 feat: add search & sorting for pieces in the api
  package-lock.json
  package.json
  packages/backend/src/app/ee/pieces/enterprise-piece-metadata-service-hooks.ts
  packages/backend/src/app/pieces/piece-metadata-service/aggregated-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/hooks.ts
  packages/backend/src/app/pieces/piece-metadata-service/hooks/index.ts
  packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts
  packages/backend/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
Labels: ⭐ enhancement

#3792 feat(flowlu): add pipeline field for create opportunity action
  packages/pieces/community/flowlu/src/lib/common/client.ts
  packages/pieces/community/flowlu/src/lib/common/index.ts
  packages/pieces/community/flowlu/src/lib/common/props.ts
  packages/pieces/community/flowlu/src/lib/common/types.ts
Labels: 🔌 pieces

#3805 docs: create action / trigger tutorial based on gelato api
  docs/developers/building-pieces/create-action.mdx
  docs/developers/building-pieces/create-trigger.mdx
  docs/developers/piece-reference/triggers/overview.mdx
  docs/developers/piece-reference/triggers/polling-trigger.mdx
  docs/developers/piece-reference/triggers/webhook-trigger.mdx
  docs/embedding/embed-builder/embed-iframe.mdx
  docs/mint.json
  docs/resources/screenshots/gelato-action.png
  docs/resources/screenshots/gelato-trigger.png
Labels: 📚 documentation

#3807 chore: bump pre release version to 4
  package.json
Labels: pre-release

#3809 fix: install git in docker
  Dockerfile
  packages/backend/src/app/copilot/copilot.service.ts
  packages/backend/src/app/ee/helper/email/email-service.ts
  packages/backend/src/app/helper/system/system-prop.ts
Labels: 🐛 bug

#3817 feat: code writer now adds packages
  packages/backend/src/app/copilot/copilot.service.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
Labels: 🌟 feature

#3808 fix: remove stale runs
  packages/backend/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
Labels: 🐛 bug

#3803 fix: multiple delays should work
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/loop-executor.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/main.ts
  packages/engine/test/handler/flow-rerun.test.ts
  packages/engine/test/handler/flow-with-pause.test.ts
  packages/engine/test/handler/test-helper.ts
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/step-output.ts
Labels: 🐛 bug, engine

#3822 chore: bump release to 0.19.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/backend/src/app/ee/platform/lib/platform-utils.ts
Labels: release

#3818 feat(openai): allow custom base url + azure openai support
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/openai/src/lib/actions/ask-assistant.ts
  packages/pieces/community/openai/src/lib/actions/generate-image.ts
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
  packages/pieces/community/openai/src/lib/actions/text-to-speech.ts
  packages/pieces/community/openai/src/lib/actions/transcriptions.ts
  packages/pieces/community/openai/src/lib/actions/translation.ts
  packages/pieces/community/openai/src/lib/actions/vision-prompt.ts
Labels: 🔌 pieces, high priority

#3802 feat(odoo): get contacts / create contact / create comapany action
  package-lock.json
  package.json
  packages/pieces/community/odoo/.eslintrc.json
  packages/pieces/community/odoo/README.md
  packages/pieces/community/odoo/package-lock.json
  packages/pieces/community/odoo/package.json
  packages/pieces/community/odoo/project.json
  packages/pieces/community/odoo/src/commom/index.ts
  packages/pieces/community/odoo/src/commom/type.ts
  packages/pieces/community/odoo/src/index.ts
  packages/pieces/community/odoo/src/lib/actions/create-company.ts
  packages/pieces/community/odoo/src/lib/actions/create-contact.ts
  packages/pieces/community/odoo/src/lib/actions/get-contacts.ts
  packages/pieces/community/odoo/src/lib/actions/index.ts
  packages/pieces/community/odoo/tsconfig.json
  packages/pieces/community/odoo/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3813 feat(image-helper): crop image / get metadata / resize image / rotate image actions
  package-lock.json
  package.json
  packages/pieces/community/image-helper/src/index.ts
  packages/pieces/community/image-helper/src/lib/actions/crop-image.action.ts
  packages/pieces/community/image-helper/src/lib/actions/get-metadata.action.ts
  packages/pieces/community/image-helper/src/lib/actions/resize-Image.action.ts
  packages/pieces/community/image-helper/src/lib/actions/rotate-image.action.ts
Labels: 🔌 pieces

#3791 refactor: allow implementation of test function in webhook trigger
  packages/backend/src/app/database/migration/common/1707087022764-add-trigger-test-strategy.ts
  packages/backend/src/app/database/postgres-connection.ts
  packages/backend/src/app/database/sqlite-connection.ts
  packages/backend/src/app/flows/flow.module.ts
  packages/backend/src/app/flows/test-trigger/test-trigger-controller.ts
  packages/backend/src/app/flows/test-trigger/test-trigger-service.ts
  packages/backend/src/app/webhooks/webhook-simulation/webhook-simulation-service.ts
  packages/backend/src/app/webhooks/webhook-simulation/webhook-simulation-side-effects.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/trigger/trigger.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/index.ts
  packages/shared/src/lib/flows/test-trigger.ts
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
Labels: backend, frontend, 🛠️ piece-framework, high priority

#3831 chore: bump image helper
  packages/pieces/community/image-helper/package.json
Labels: skip-changelog

#3832 fix: cloud oauth2 toggle in admin console
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
Labels: 🐛 bug

#3833 fix: image helper
  package-lock.json
  package.json
Labels: skip-changelog

#3835 chore: turn off stats json to reduce docker image size
  packages/ui/core/project.json
Labels: 🧹 clean up

#3834 chore: bump package-lock
  package-lock.json
  package.json
Labels: 🧹 clean up

#3836 fix: install ssh client for git
  Dockerfile
Labels: 🐛 bug

#3837 chore: bump 0.20.0-rc.1
  package.json
Labels: pre-release

#3838 fix: rotate image degree description
  packages/pieces/community/image-helper/package.json
  packages/pieces/community/image-helper/src/lib/actions/rotate-image.action.ts
Labels: skip-changelog

#3749 feat(google-sheets): new row added instant trigger (BETA)
  package-lock.json
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: 🔌 pieces

#3828 feat(branch): add new condition "(number) is equal to"
  docs/openapi.json
  packages/engine/src/lib/handler/branch-executor.ts
  packages/engine/test/handler/flow-branching.test.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/actions/action.ts
Labels: 🔌 pieces

#3842 fix(api): bypass project authz for webhook endpoints
  packages/backend/src/app/core/security/authz/project-authz-handler.ts
Labels: 🐛 bug, backend, 🔒 security

#3843 fix: add categories db migration
  packages/backend/src/app/database/migration/postgres/1707231704973-AddCategoriesToPieceMetadataPostgres.ts
  packages/backend/src/app/database/migration/sqlite/1707229986819-AddCategoriesToPieceMetadata.ts
  packages/backend/src/app/database/postgres-connection.ts
  packages/backend/src/app/database/sqlite-connection.ts
  packages/backend/src/app/ee/pieces/admin-piece-requests.ee.ts
  packages/backend/src/app/pieces/piece-metadata-entity.ts
Labels: 🐛 bug

#3844 fix: only check email auth if provider is email
  packages/backend/src/app/authentication/authentication-service/hooks/authentication-service-hooks.ts
  packages/backend/src/app/authentication/authentication-service/index.ts
  packages/backend/src/app/authentication/authentication.controller.ts
  packages/backend/src/app/database/seeds/dev-seeds.ts
  packages/backend/src/app/ee/authentication/authentication-service/hooks/authentication-helper.ts
  packages/backend/src/app/ee/authentication/authentication-service/hooks/cloud-authentication-service-hooks.ts
  packages/backend/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
Labels: 🐛 bug

#3850 fix(sso): show correct url for platform on cloud edition
  package.json
  packages/backend/src/app/ee/authentication/federated-authn/authn-provider/authn-provider.ts
  packages/backend/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
  packages/backend/src/app/ee/authentication/federated-authn/authn-provider/google-authn-provider.ts
  packages/backend/src/app/ee/authentication/federated-authn/federated-authn-controller.ts
  packages/backend/src/app/ee/authentication/federated-authn/federated-authn-service.ts
  packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/backend/src/app/flags/flag.service.ts
Labels: 🐛 bug

#3851 fix: hide admin console for platform members
  packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/backend/src/app/flags/flag.service.ts
  packages/ee/ui-platform/src/lib/is-platform-demo.resolver.ts
  packages/shared/src/lib/flag/flag.ts
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
  packages/ui/common/src/lib/guards/show-platform-settings.guard.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
Labels: ⭐ enhancement

#3853 fix: sort & filtration on pieces
  package-lock.json
  package.json
  packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/backend/src/app/flags/flag.service.ts
  packages/backend/src/app/pieces/base-piece-module.ts
  packages/backend/src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/ee/ui-platform/src/lib/is-platform-demo.resolver.ts
  packages/shared/src/lib/flag/flag.ts
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
  packages/ui/common/src/lib/guards/show-platform-settings.guard.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
Labels: skip-changelog

#3854 fix: add categories endpoint
  packages/backend/src/app/pieces/base-piece-module.ts
Labels: skip-changelog

#3856 fix: ee filteration
  packages/backend/src/app/ee/pieces/enterprise-piece-metadata-service-hooks.ts
Labels: skip-changelog

#3857 fix(ui): allow empty arrays for non required array props
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts
Labels: frontend

#3858 fix(image-helper): changed the image library
  package-lock.json
  package.json
  packages/pieces/community/image-helper/package.json
  packages/pieces/community/image-helper/src/lib/actions/crop-image.action.ts
  packages/pieces/community/image-helper/src/lib/actions/get-metadata.action.ts
  packages/pieces/community/image-helper/src/lib/actions/resize-Image.action.ts
  packages/pieces/community/image-helper/src/lib/actions/rotate-image.action.ts
Labels: skip-changelog

#3860 feat: date range filter in runs page
  package-lock.json
  packages/backend/src/app/flows/flow-run/flow-run-controller.ts
  packages/backend/src/app/flows/flow-run/flow-run-service.ts
  packages/shared/package.json
  packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
  packages/ui/common/src/lib/service/instance-run.service.ts
  packages/ui/common/src/lib/utils/tables.utils.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🌟 feature

#3863 fix: add minimum support for interfaces
  packages/pieces/community/interfaces/src/index.ts
Labels: skip-changelog

#3861 fix: disappearing test data for piece triggers
  package-lock.json
  package.json
  packages/backend/src/app/flows/trigger-events/trigger-event.service.ts
  packages/shared/package.json
  packages/shared/src/lib/pieces/utils.ts
  packages/ui/core/src/app/modules/interfaces/interfaces.component.ts
  packages/ui/feature-pieces/package.json
Labels: 🐛 bug, backend

#3864 fix: snackbar after interface submission received
  packages/ui/core/src/app/modules/interfaces/interfaces.component.ts
Labels: skip-changelog

#3868 fix: salesforce authentication popup
  packages/backend/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts
  packages/pieces/community/salesforce/package.json
  packages/pieces/community/salesforce/src/index.ts
Labels: 🔌 pieces

#3867 fix: improve sorting of locales in locales list
  packages/ui/common/src/lib/utils/locales.ts
Labels: ⭐ enhancement

#3869 fix: wrrong payload retry latest version
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
Labels: 🐛 bug

#3830 feat(mailerlite): subscriber created,subscriber unsubscribed and subscriber added to group triggers
  packages/pieces/community/mailer-lite/package.json
  packages/pieces/community/mailer-lite/src/index.ts
  packages/pieces/community/mailer-lite/src/lib/actions/create-or-update-subscription.ts
  packages/pieces/community/mailer-lite/src/triggers/triggers.ts
Labels: 🔌 pieces

#3872 feat: add support for app webhooks in self hosted
  docs/install/configurations/setup-app-webhooks.mdx
  docs/mint.json
  packages/backend/src/app/flags/flag.service.ts
  packages/backend/src/app/helper/secret-helper.ts
  packages/backend/src/app/helper/system/system-prop.ts
  packages/shared/src/lib/flag/flag.ts
  packages/ui/common/src/lib/service/flag.service.ts
  packages/ui/feature-pieces/src/lib/services/piece-meta.service.ts
Labels: ⭐ enhancement

#3873 chore: bump to rc 0.19.0-rc.3
  package.json
Labels: pre-release

#3874 fix: rebuild rc3
  packages/backend/src/app/flags/flag.service.ts
  packages/backend/src/app/helper/secret-helper.ts
Labels: pre-release

#3875 fix: release rc.4
  package.json
Labels: pre-release

#3878 feat(snowflake): add run query action
  package-lock.json
  package.json
  packages/pieces/community/snowflake/.eslintrc.json
  packages/pieces/community/snowflake/README.md
  packages/pieces/community/snowflake/package.json
  packages/pieces/community/snowflake/project.json
  packages/pieces/community/snowflake/src/index.ts
  packages/pieces/community/snowflake/src/lib/actions/run-query.ts
  packages/pieces/community/snowflake/tsconfig.json
  packages/pieces/community/snowflake/tsconfig.lib.json
Labels: 🔌 pieces

#3882 feat: decrease spacing between inputs in the builder and their sizes in all of the app.
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.html
Labels: ⭐ enhancement

#3883 fix(openai): revert azure openai implementation
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/openai/src/lib/actions/ask-assistant.ts
  packages/pieces/community/openai/src/lib/actions/generate-image.ts
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
  packages/pieces/community/openai/src/lib/actions/text-to-speech.ts
  packages/pieces/community/openai/src/lib/actions/transcriptions.ts
  packages/pieces/community/openai/src/lib/actions/translation.ts
  packages/pieces/community/openai/src/lib/actions/vision-prompt.ts
  packages/pieces/community/openai/src/lib/common/common.ts
Labels: 🔌 pieces

#3884 fix: decrease steps visual space in builder
  packages/ui/feature-builder-canvas/src/lib/components/canvas-utils/drawing/draw-common.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.scss
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.ts
Labels: ⭐ enhancement

#3886 feat: add telemetry to interfaces and show error message for inputs when they required and not filled
  packages/pieces/community/interfaces/package.json
  packages/pieces/community/interfaces/src/lib/triggers/interface-trigger.ts
  packages/shared/package.json
  packages/shared/src/lib/common/telemetry.ts
  packages/ui/core/src/app/modules/interfaces/interfaces.component.html
  packages/ui/core/src/app/modules/interfaces/interfaces.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html
Labels: ⭐ enhancement

#3885 refactor(backend): clean code builder
  packages/backend/src/app/workers/code-worker/code-builder.ts
Labels: backend, 💻 tech debt, 🧹 clean up

#3895 fix: stop infinite loading when session expires
  .devcontainer/devcontainer.json
  packages/ui/core/src/app/app.module.ts
Labels: skip-changelog

#3894 fix: show step icons in import flow page
  packages/ui/core/src/app/app.module.ts
Labels: 🐛 bug, skip-changelog

#3896 feat: allow panning in builder canvas on left click holding and moving
  packages/ui/feature-builder-canvas/src/lib/components/canvas-utils/panning/panner.directive.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.html
Labels: ⭐ enhancement, frontend

#3900 fix: align icon inside step center with the rest of its content
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.scss
Labels: skip-changelog, auto-deploy

#3906 feat(whatsable): send message action
  packages/pieces/community/whatsable/.eslintrc.json
  packages/pieces/community/whatsable/README.md
  packages/pieces/community/whatsable/package.json
  packages/pieces/community/whatsable/project.json
  packages/pieces/community/whatsable/src/index.ts
  packages/pieces/community/whatsable/src/lib/actions/send-message.ts
  packages/pieces/community/whatsable/tsconfig.json
  packages/pieces/community/whatsable/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3899 feat: hide error handling options from helper pieces
  packages/pieces/community/approval/package.json
  packages/pieces/community/approval/src/lib/actions/create-approval-link.ts
  packages/pieces/community/approval/src/lib/actions/wait-for-approval.ts
  packages/pieces/community/csv/package.json
  packages/pieces/community/csv/src/lib/actions/convert-csv-to-json.ts
  packages/pieces/community/csv/src/lib/actions/convert-json-to-csv.ts
  packages/pieces/community/data-mapper/package.json
  packages/pieces/community/data-mapper/src/lib/actions/advanced-mapping.ts
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/date-helper/src/lib/actions/add-subtract-date.ts
  packages/pieces/community/date-helper/src/lib/actions/date-difference.ts
  packages/pieces/community/date-helper/src/lib/actions/extract-date-parts.ts
  packages/pieces/community/date-helper/src/lib/actions/format-date.ts
  packages/pieces/community/date-helper/src/lib/actions/get-current-date.ts
  packages/pieces/community/date-helper/src/lib/actions/next-day-of-week.ts
  packages/pieces/community/date-helper/src/lib/actions/next-day-of-year.ts
  packages/pieces/community/delay/package.json
  packages/pieces/community/delay/src/lib/actions/delay-for-action.ts
  packages/pieces/community/delay/src/lib/actions/delay-untill-action.ts
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/lib/actions/read-file.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/action/action.ts
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/math-helper/src/lib/actions/addition.ts
  packages/pieces/community/math-helper/src/lib/actions/division.ts
  packages/pieces/community/math-helper/src/lib/actions/generateRandom.ts
  packages/pieces/community/math-helper/src/lib/actions/modulo.ts
  packages/pieces/community/math-helper/src/lib/actions/multiplication.ts
  packages/pieces/community/math-helper/src/lib/actions/subtraction.ts
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
  packages/pieces/community/store/src/lib/actions/store-append-action.ts
  packages/pieces/community/store/src/lib/actions/store-get-action.ts
  packages/pieces/community/store/src/lib/actions/store-put-action.ts
  packages/pieces/community/store/src/lib/actions/store-remove-from-list.ts
  packages/pieces/community/store/src/lib/actions/store-remove-value.ts
  packages/pieces/community/tags/package.json
  packages/pieces/community/tags/src/lib/add-tag.ts
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/text-helper/src/lib/actions/concat.ts
  packages/pieces/community/text-helper/src/lib/actions/find.ts
  packages/pieces/community/text-helper/src/lib/actions/html-to-markdown.ts
  packages/pieces/community/text-helper/src/lib/actions/markdown-to-html.ts
  packages/pieces/community/text-helper/src/lib/actions/replace.ts
  packages/pieces/community/text-helper/src/lib/actions/split.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.ts
Labels: ⭐ enhancement

#3907 fix: minor ui fixes for inputs and canvas
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/core/src/assets/scss/quill-override.scss
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/dictionary-form-control/dictionary-form-control.component.scss
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/interpolating-text-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
Labels: skip-changelog, auto-deploy

#3910 fix: notify on failed runs toggle wasn't working
  packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts
  packages/ee/components/src/lib/third-party-auth/third-party-auth.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/create-project-dialog/create-project-dialog.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/create-project-dialog/create-project-dialog.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/update-project-dialog/update-project-dialog.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/update-project-dialog/update-project-dialog.component.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/authentication/dto/authentication-response.ts
  packages/ui/common/src/lib/guards/user-logged-in.guard.ts
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/common/src/lib/service/platform-project.service.ts
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/common/src/lib/store/common-state.model.ts
  packages/ui/common/src/lib/store/common.action.ts
  packages/ui/common/src/lib/store/project/project.action.ts
  packages/ui/common/src/lib/store/project/project.effects.ts
  packages/ui/common/src/lib/store/project/project.reducer.ts
  packages/ui/core/src/app/app.component.ts
  packages/ui/feature-authentication/src/lib/pages/sign-in/sign-in.component.ts
  packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
Labels: 🐛 bug, frontend

#3880 feat: add audit logs
  packages/backend/src/app/app-connection/app-connection.controller.ts
  packages/backend/src/app/app.ts
  packages/backend/src/app/core/security/rate-limit.ts
  packages/backend/src/app/database/database-connection.ts
  packages/backend/src/app/database/migration/postgres/1707614902283-AddAuditEvents.ts
  packages/backend/src/app/database/postgres-connection.ts
  packages/backend/src/app/ee/audit-logs/audit-event-entity.ts
  packages/backend/src/app/ee/audit-logs/audit-event-module.ts
  packages/backend/src/app/ee/audit-logs/audit-event-service.ts
  packages/backend/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts
  packages/backend/src/app/ee/helper/license-validator/index.ts
  packages/backend/src/app/ee/helper/license-validator/license-validator.ts
  packages/backend/src/app/ee/helper/license-validator/network-license-validator.ts
  packages/backend/src/app/ee/platform/platform.entity.ts
  packages/backend/src/app/ee/platform/platform.service.ts
  packages/backend/src/app/flows/flow/flow.controller.ts
  packages/backend/src/app/flows/flow/flow.service.ts
  packages/backend/src/app/flows/folder/folder.controller.ts
  packages/backend/src/app/flows/folder/folder.service.ts
  packages/backend/src/app/helper/audit-events/index.ts
  packages/backend/src/app/helper/domain-helper.ts
  packages/backend/src/app/helper/engine-helper.ts
  packages/backend/src/app/helper/error-handler.ts
  packages/backend/src/app/helper/exception-handler.ts
  packages/backend/src/app/helper/logger.ts
  packages/backend/src/app/helper/network-utils.ts
  packages/backend/src/app/helper/promise-handler.ts
  packages/backend/src/app/project/project-service.ts
  packages/backend/src/app/user/user-service.ts
  packages/backend/src/app/webhooks/webhook-service.ts
  packages/backend/test/helpers/mocks/index.ts
  packages/backend/test/integration/cloud/audit-event/audit-event.test.ts
  packages/backend/test/integration/cloud/platform/admin-platform.test.ts
  packages/backend/test/integration/cloud/platform/platform.test.ts
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/ee/shared/src/lib/platform/platform.model.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.html
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.datasource.ts
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ee/ui-platform/src/lib/service/audit-event-service.ts
  packages/ee/ui-platform/src/lib/ui-ee-platform.module.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/common/telemetry.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.datasource.ts
Labels: Enterprise, 🌟 feature, auto-deploy

#3912 docs: update execution_mode's default value to match the code
  docker-compose.dev.yml
  docs/install/configurations/environment-variables.mdx
Labels: 📚 documentation

#3914 fix: audit log migration
  packages/backend/src/app/database/migration/postgres/1707614902283-AddAuditEvents.ts
Labels: skip-changelog, auto-deploy

#3913 fix: show full step name in tooltip when truncated in the builder
  packages/ui/feature-builder-canvas/src/lib/components/canvas-utils/drawing/draw-common.ts
  packages/ui/feature-builder-canvas/src/lib/components/canvas-utils/panning/panner.directive.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.scss
  packages/ui/feature-connections/src/lib/dialogs/managed-oauth2-connection-dialog/managed-oauth2-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/oauth2-connection-dialog/oauth2-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/form-controls/o-auth2-connect-control/o-auth2-connect-control.component.ts
Labels: 🐛 bug, frontend

#3918 fix: build webhookUrl with flowId instead of versionId
  packages/ui/core/src/app/modules/interfaces/interfaces.component.ts
Labels: 🐛 bug, auto-deploy

#3920 fix: add props to connection card
  packages/backend/src/app/ee/connection-keys/connection-key.service.ts
Labels: skip-changelog, auto-deploy

#3893 feat(metabase): Get Question Action
  packages/pieces/community/metabase/.eslintrc.json
  packages/pieces/community/metabase/README.md
  packages/pieces/community/metabase/package-lock.json
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/project.json
  packages/pieces/community/metabase/src/index.ts
  packages/pieces/community/metabase/src/lib/actions/get-question.ts
  packages/pieces/community/metabase/src/lib/common.ts
  packages/pieces/community/metabase/tsconfig.json
  packages/pieces/community/metabase/tsconfig.lib.json
Labels: 🔌 pieces

#3919 chore: disable spellcheck on email invite field
  packages/ee/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.html
Labels: ⭐ enhancement

#3924 feat: add pagination to project members table in the admin console
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
  packages/ee/project-members/src/lib/project-members-table/project-members.datasource.ts
  packages/ee/project-members/src/lib/service/project-members.service.ts
  packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
Labels: ⭐ enhancement, frontend, auto-deploy

#3922 fix(smtp): connection timeout
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/index.ts
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🐛 bug

#3925 fix(pieces-search): weighted search, sorting by name
  packages/backend/src/app/flags/flag.service.ts
  packages/backend/src/app/pieces/base-piece-module.ts
  packages/backend/src/app/pieces/piece-metadata-entity.ts
  packages/backend/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts
Labels: 🐛 bug, auto-deploy

#3887 fix: allow multiple approvals in same flow
  packages/backend/src/app/flows/flow-run/flow-response-watcher.ts
  packages/backend/src/app/flows/flow-run/flow-run-controller.ts
  packages/backend/src/app/flows/flow-run/flow-run-service.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/test/handler/flow-with-pause.test.ts
  packages/pieces/community/approval/src/index.ts
  packages/pieces/community/approval/src/lib/actions/create-approval-link.ts
  packages/pieces/community/approval/src/lib/actions/wait-for-approval.ts
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/index.ts
  packages/pieces/community/discord/src/lib/actions/send-approval-message.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/request-approval-direct-message.ts
  packages/pieces/community/slack/src/lib/actions/request-approval-message.ts
  packages/shared/package.json
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/flow-run/execution/execution-output.ts
  packages/shared/src/lib/flow-run/flow-run.ts
Labels: 🐛 bug, auto-deploy

#3926 fix: only search in pieces name & description
  packages/backend/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
Labels: skip-changelog

#3928 feat(linkedin): add custom api call
  packages/pieces/community/linkedin/package.json
  packages/pieces/community/linkedin/src/index.ts
Labels: 🔌 pieces

#3935 chore(api): fix test strategy migration for sqlite
  packages/server/api/src/app/database/migration/common/1707087022764-add-trigger-test-strategy.ts
Labels: backend, 💻 tech debt

#3938 chore: release 0.20.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#3939 fix(GenerateBanners): remove deprecated fields
  packages/pieces/community/generatebanners/package.json
  packages/pieces/community/generatebanners/src/lib/actions/renderTemplate.action.ts
Labels: 🔌 pieces

#3941 fix: panning when zoom in/out
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/step-output.ts
  packages/ui/canvas-utils/src/lib/panning/panner.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
Labels: 🐛 bug, auto-deploy

#3942 fix: hide error handling for core pieces
  packages/pieces/community/approval/package.json
  packages/pieces/community/csv/package.json
  packages/pieces/community/data-mapper/package.json
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/delay/package.json
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/store/package.json
  packages/pieces/community/tags/package.json
  packages/pieces/community/text-helper/package.json
Labels: skip-changelog

#3943 fix: panning animation
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
Labels: ⭐ enhancement, auto-deploy

#3944 feat: release 0.20.2
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#3945 fix: remove duplicate sample data in webhook trigger
  package-lock.json
  packages/server/api/src/app/webhooks/webhook-service.ts
Labels: 🐛 bug, auto-deploy

#3946 fix: force logout old tokens
  packages/server/api/src/app/helper/jwt-utils.ts
Labels: 🐛 bug, auto-deploy

#3948 fix: panner zoom
  packages/ui/canvas-utils/src/lib/panning/panner.service.ts
Labels: skip-changelog, auto-deploy

#3950 fix: reset zoom and fit to screen on all screen sizes
  packages/ui/canvas-utils/src/lib/panning/panner.service.ts
  packages/ui/canvas-utils/src/lib/zooming/zooming.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
Labels: skip-changelog, auto-deploy

#3952 chore: validate special token
  packages/server/api/src/app/helper/jwt-utils.ts
Labels: skip-changelog, auto-deploy

#3940 feat(dust): create conversation action
  packages/pieces/community/dust/.eslintrc.json
  packages/pieces/community/dust/README.md
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/project.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/tsconfig.json
  packages/pieces/community/dust/tsconfig.lib.json
Labels: 🔌 pieces

#3956 fix: add animation back to panning
  packages/ui/canvas-utils/src/lib/drawing/draw-common.ts
  packages/ui/canvas-utils/src/lib/panning/panner.service.ts
  packages/ui/canvas-utils/src/lib/zooming/zooming.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
Labels: ⭐ enhancement, auto-deploy

#3959 fix(engine): set flow run status to `FAILED` if resolving inputs fails
  packages/engine/src/lib/handler/piece-executor.ts
Labels: 🐛 bug, engine

#3953 refactor(engine): clean connection service
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/connections.service.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection-worker-controller.ts
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 💻 tech debt, engine

#3958 fix: show blog suggestion after imporitng templates in ee
  packages/ee/components/src/lib/share-flow-template-dialog/share-flow-template-dialog.component.ts
  packages/ee/ui-platform/src/lib/components/dialogs/create-or-update-template-dialogue/create-or-update-template-dialogue.component.html
  packages/ee/ui-platform/src/lib/components/dialogs/create-or-update-template-dialogue/create-or-update-template-dialogue.component.ts
  packages/ui/common/src/lib/components/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
  packages/ui/feature-templates/src/lib/template-blog-notification/template-blog-notification.component.ts
Labels: 🐛 bug, auto-deploy

#3961 feat: allow users to share their flows on enterprise edition
  packages/ee/components/src/lib/share-flow-template-dialog/share-flow-template-dialog.component.ts
  packages/ui/core/src/app/app-routing.module.ts
  packages/ui/core/src/app/modules/import-flow/import-flow.component.ts
Labels: ⭐ enhancement

#3962 feat(airtable): add table view option for triggers
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/lib/common/index.ts
  packages/pieces/community/airtable/src/lib/trigger/new-record.trigger.ts
  packages/pieces/community/airtable/src/lib/trigger/update-record.trigger.ts
Labels: 🔌 pieces

#3960 feat(quickzu): order created/updated trigger and 15 actions
  packages/pieces/community/quickzu/.eslintrc.json
  packages/pieces/community/quickzu/README.md
  packages/pieces/community/quickzu/package.json
  packages/pieces/community/quickzu/project.json
  packages/pieces/community/quickzu/src/index.ts
  packages/pieces/community/quickzu/src/lib/actions/business-settings/update-business-time.ts
  packages/pieces/community/quickzu/src/lib/actions/categories/create-category.ts
  packages/pieces/community/quickzu/src/lib/actions/categories/delete-category.ts
  packages/pieces/community/quickzu/src/lib/actions/categories/list-categories.ts
  packages/pieces/community/quickzu/src/lib/actions/categories/update-category.ts
  packages/pieces/community/quickzu/src/lib/actions/discounts/create-product-discount.ts
  packages/pieces/community/quickzu/src/lib/actions/discounts/create-promo-code.ts
  packages/pieces/community/quickzu/src/lib/actions/orders/get-order-details.ts
  packages/pieces/community/quickzu/src/lib/actions/orders/list-live-orders.ts
  packages/pieces/community/quickzu/src/lib/actions/orders/list-orders.ts
  packages/pieces/community/quickzu/src/lib/actions/orders/update-order-status.ts
  packages/pieces/community/quickzu/src/lib/actions/products/create-product.ts
  packages/pieces/community/quickzu/src/lib/actions/products/delete-product.ts
  packages/pieces/community/quickzu/src/lib/actions/products/list-products.ts
  packages/pieces/community/quickzu/src/lib/actions/products/update-product.ts
  packages/pieces/community/quickzu/src/lib/common/client.ts
  packages/pieces/community/quickzu/src/lib/common/constants.ts
  packages/pieces/community/quickzu/src/lib/common/index.ts
  packages/pieces/community/quickzu/src/lib/common/types.ts
  packages/pieces/community/quickzu/src/lib/triggers/order-created.ts
  packages/pieces/community/quickzu/tsconfig.json
  packages/pieces/community/quickzu/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3955 feat: show suggested triggers/actions while searching
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.datasource.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-metadata-entity.ts
  packages/server/api/src/app/pieces/piece-metadata-service/aggregated-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-stats-service.ts
  packages/server/api/test/integration/cloud/piece-metadata/piece-metadata.test.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/shared/package.json
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  packages/ui/common/src/lib/models/flow-item-details.ts
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/mentions-list.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/common.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/ui-feature-builder-right-sidebar.module.ts
  packages/ui/feature-pieces/src/lib/services/piece-meta.service.ts
Labels: frontend, 🌟 feature, auto-deploy

#3775 feat(wootric): create survey
  .gitignore
  packages/pieces/community/wootric/.eslintrc.json
  packages/pieces/community/wootric/README.md
  packages/pieces/community/wootric/package.json
  packages/pieces/community/wootric/project.json
  packages/pieces/community/wootric/src/index.ts
  packages/pieces/community/wootric/src/lib/actions/create-survey.ts
  packages/pieces/community/wootric/tsconfig.json
  packages/pieces/community/wootric/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3965 fix: resize duplicate/delete step buttons
  packages/ui/core/src/assets/img/custom/duplicate-step.svg
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/actions-container/actions-container.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/actions-container/actions-container.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/common.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/delete-flow-item-action/delete-flow-item-action.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/delete-flow-item-action/delete-flow-item-action.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/duplicate-step-action/duplicate-step-action.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/duplicate-step-action/duplicate-step-action.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/replace-trigger-action/replace-trigger-action.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-connection/drop-zone/drop-zone.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.ts
Labels: ⭐ enhancement

#3966 fix: search sorting
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
Labels: skip-changelog

#3954 feat(audit-log): fix pagination and add update flow events
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.datasource.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/helper/application-events/index.ts
  packages/server/api/src/app/helper/error-handler.ts
  packages/server/api/test/integration/cloud/signing-key/signing-key.test.ts
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
  packages/ui/common/src/lib/components/pagination/ap-paginator.component.ts
Labels: 🐛 bug, auto-deploy

#3969 chore: make error handling param optional
  packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
Labels: skip-changelog, auto-deploy

#3870 feat: store service operations are now atomic
  .gitignore
  packages/engine/src/lib/services/storage.service.ts
  packages/server/api/src/app/database/migration/postgres/1708455034835-AddUniqueStoreConstrain.ts
  packages/server/api/src/app/database/migration/sqlite/1708454855876-AddUniqueStoreConstrain.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/store-entry/store-entry-entity.ts
  packages/server/api/src/app/store-entry/store-entry.controller.ts
  packages/server/api/src/app/store-entry/store-entry.service.ts
  packages/server/api/test/integration/cloud/store-entry/store-entry-controller.test.ts
Labels: 🛠️ piece-framework

#3971 chore: add letter icon instead of email
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/shared/src/lib/flows/flow-version.ts
  packages/ui/common/src/lib/components/index.ts
  packages/ui/common/src/lib/components/letter-icon/letter-icon.component.html
  packages/ui/common/src/lib/components/letter-icon/letter-icon.component.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.ts
Labels: skip-changelog

#3973 docs: add handbook
  docs/handbook/engineering/hiring.mdx
  docs/handbook/engineering/how-we-work.mdx
  docs/handbook/engineering/stack.mdx
  docs/handbook/engineering/team.mdx
  docs/handbook/overview.mdx
  docs/handbook/people/time.mdx
  docs/handbook/values.mdx
  docs/mint.json
Labels: 📚 documentation

#3974 docs: fix format in hiring
  docs/handbook/engineering/hiring.mdx
Labels: 📚 documentation, skip-changelog

#3976 fix: add none as body to http
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/engine/test/handler/flow-piece.test.ts
  packages/engine/test/handler/flow-rerun.test.ts
  packages/pieces/community/http/package.json
  packages/pieces/community/http/src/lib/actions/send-http-request-action.ts
Labels: skip-changelog

#3975 fix(typo): change "succuss" to "success"
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/lib/actions/store-remove-value.ts
Labels: skip-changelog

#3967 feat(forms): rename interfaces to forms
  packages/pieces/community/forms/.eslintrc.json
  packages/pieces/community/forms/README.md
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/project.json
  packages/pieces/community/forms/src/index.ts
  packages/pieces/community/forms/src/lib/actions/return-file.ts
  packages/pieces/community/forms/src/lib/actions/return-markdown.ts
  packages/pieces/community/forms/src/lib/triggers/file-trigger.ts
  packages/pieces/community/forms/src/lib/triggers/form-trigger.ts
  packages/pieces/community/forms/tsconfig.json
  packages/pieces/community/forms/tsconfig.lib.json
  packages/pieces/community/interfaces/README.md
  packages/pieces/community/interfaces/package.json
  packages/pieces/community/interfaces/src/index.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/common/telemetry.ts
  packages/shared/src/lib/forms/index.ts
  packages/ui/common/src/lib/service/flag.service.ts
  packages/ui/core/src/app/app-routing.module.ts
  packages/ui/core/src/app/app.module.ts
  packages/ui/core/src/app/modules/forms/forms.component.html
  packages/ui/core/src/app/modules/forms/forms.component.ts
  packages/ui/core/src/app/modules/forms/forms.service.ts
  packages/ui/core/src/app/modules/interfaces/interfaces.component.html
  packages/ui/core/src/app/modules/interfaces/interfaces.service.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
  tsconfig.base.json
Labels: 🔌 pieces

#3972 feat: Activity APIs
  docker-compose.dev.yml
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/activity/activity-model.ts
  packages/ee/shared/src/lib/activity/activity-requests.ts
  packages/ee/shared/src/lib/activity/index.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1708515756040-create-activity-table.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/activity/activity-controller.ts
  packages/server/api/src/app/ee/activity/activity-entity.ts
  packages/server/api/src/app/ee/activity/activity-module.ts
  packages/server/api/src/app/ee/activity/activity-service.ts
  packages/server/api/src/app/ee/activity/activity-worker-controller.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/activity/activity-worker.test.ts
  packages/server/api/test/integration/cloud/activity/activity.test.ts
Labels: ☁️ Paid Feature, 🖥️ api

#3980 fix(azure-openai): use chat completions instead of completions
  packages/pieces/community/azure-openai/package.json
  packages/pieces/community/azure-openai/src/lib/actions/ask-gpt.ts
Labels: 🔌 pieces

#3979 chore: enforce limit on storage key to be maximum 128
  packages/engine/src/lib/services/storage.service.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/validators/validators.ts
  packages/pieces/community/google-gemini/package.json
  packages/pieces/community/google-gemini/src/lib/actions/chat-gemini.action.ts
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/lib/actions/ask-assistant.ts
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
  packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
  packages/pieces/community/store/src/lib/actions/store-append-action.ts
  packages/pieces/community/store/src/lib/actions/store-get-action.ts
  packages/pieces/community/store/src/lib/actions/store-put-action.ts
  packages/pieces/community/store/src/lib/actions/store-remove-from-list.ts
  packages/pieces/community/store/src/lib/actions/store-remove-value.ts
  packages/server/api/src/app/database/migration/postgres/1708455034835-AddUniqueStoreConstrain.ts
  packages/server/api/src/app/database/migration/postgres/1708521505204-AddUniqueStoreConstraint.ts
  packages/server/api/src/app/database/migration/sqlite/1708527446535-AddUniqueStoreConstraint.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/store-entry/store-entry-entity.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/store-entry/dto/store-entry-request.ts
  packages/shared/src/lib/store-entry/store-entry.ts
Labels: auto-deploy

#3981 refactor: activity limits
  docker-compose.dev.yml
  packages/ee/shared/src/lib/activity/activity-model.ts
  packages/ee/shared/src/lib/activity/activity-requests.ts
  packages/server/api/src/app/database/migration/postgres/1708529586342-add-length-limits-to-activity.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/seeds/dev-seeds.ts
  packages/server/api/src/app/ee/activity/activity-entity.ts
  packages/server/api/test/integration/cloud/activity/activity-worker.test.ts
  packages/shared/package.json
Labels: 🧹 clean up, auto-deploy

#3982 chore: show piece name in dialog title when creating a new connection
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/input-forms-schema.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-trigger-input-form/piece-trigger-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-trigger-input-form/piece-trigger-input-form.component.ts
  packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
  packages/ui/feature-connections/src/lib/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/managed-oauth2-connection-dialog/managed-oauth2-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/managed-oauth2-connection-dialog/managed-oauth2-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/oauth2-connection-dialog/oauth2-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/oauth2-connection-dialog/oauth2-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.ts
Labels: ⭐ enhancement, frontend

#3984 fix(imap): deleted emails issue after publish and revamped new email trigger using new library
  package-lock.json
  package.json
  packages/pieces/community/imap/package.json
  packages/pieces/community/imap/src/index.ts
  packages/pieces/community/imap/src/lib/common/index.ts
  packages/pieces/community/imap/src/lib/triggers/new-email.ts
Labels: 🔌 pieces

#3987 fix: revert old token
  packages/server/api/src/app/helper/jwt-utils.ts
Labels: 🐛 bug, skip-changelog, auto-deploy

#3988 fix: remove initial route from embedding sdk
  docs/embedding/embed-builder/embed-iframe.mdx
  packages/ee/embed-sdk/src/index.ts
Labels: 🐛 bug

#3989 feat: release 0.20.3
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#3992 fix(gmail): resolve issue with BCC emails not being sent
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
Labels: 🔌 pieces

#3991 feat: add new connections from the connection table in dashboard
  packages/ui/common/src/lib/guards/user-logged-in.guard.ts
  packages/ui/common/src/lib/service/app-connections.service.ts
  packages/ui/core/src/assets/scss/utlis.scss
  packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-connection-dialog/new-connection-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-connection-dialog/new-connection-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
  packages/ui/feature-templates/src/lib/templates-dialog/templates-dialog.component.html
Labels: frontend, 🌟 feature, auto-deploy

#3996 fix(postgres): recommend parametrized queries
  packages/pieces/community/mysql/package.json
  packages/pieces/community/mysql/src/lib/actions/execute-query.ts
  packages/pieces/community/postgres/package.json
  packages/pieces/community/postgres/src/lib/actions/run-query.ts
Labels: 🔌 pieces, skip-changelog

#3995 fix: stop array label from overflowing in readonly mode
  packages/ui/common/src/lib/components/letter-icon/letter-icon.component.html
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html
Labels: ⭐ enhancement

#3993 fix: stop flows filter in runs table from flickering
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
Labels: ⭐ enhancement, frontend

#3994 fix: make step title sticky in edit step form
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.css
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
Labels: ⭐ enhancement, frontend

#3997 chore: keep pieces sorted alphabetically
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
Labels: skip-changelog, auto-deploy

#4000 feat(audit-log): track sign up events
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.ts
  packages/server/api/src/app/authentication/authentication.controller.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
  packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-controller.ts
  packages/server/api/src/app/helper/application-events/index.ts
Labels: ⭐ enhancement

#4001 fix: retry internal server
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
Labels: 🐛 bug, auto-deploy

#4003 feat: sort flows by enabled first
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/helper/pagination/paginator.ts
  packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.html
Labels: ⭐ enhancement, auto-deploy

#4004 chore: use query to limit instead of stored record
  packages/server/api/src/app/ee/billing/limits/tasks-limit.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: skip-changelog, auto-deploy

#4005 feat(microsoft-dynamics): create / update / get / delete record (only at enterprise edition)
  packages/ee/pieces/microsoft-dynamics-crm/.eslintrc.json
  packages/ee/pieces/microsoft-dynamics-crm/README.md
  packages/ee/pieces/microsoft-dynamics-crm/package.json
  packages/ee/pieces/microsoft-dynamics-crm/project.json
  packages/ee/pieces/microsoft-dynamics-crm/src/index.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/create-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/delete-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/get-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/update-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/client.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/constants.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/index.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/types.ts
  packages/ee/pieces/microsoft-dynamics-crm/tsconfig.json
  packages/ee/pieces/microsoft-dynamics-crm/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, ☁️ Paid Feature, Enterprise

#4006 fix: track platform usage on cloud
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
Labels: skip-changelog, auto-deploy

#4008 chore: improve spacing between inputs in forms
  packages/ee/project-members/src/lib/dialogs/invite-project-member-dialog/invite-project-member.component.html
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
Labels: ⭐ enhancement, frontend, auto-deploy

#4009 fix: limit step execution duration to 1 decimal number
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
Labels: ⭐ enhancement, frontend

#4010 chore: select first invalid step on viewing flow, and select trigger on viewing run
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
Labels: ⭐ enhancement, frontend

#4017 fix(http): add failsafe option back
  packages/pieces/community/http/package.json
  packages/pieces/community/http/src/lib/actions/send-http-request-action.ts
Labels: 🔌 pieces

#4018 fix: update project billing with limits
  packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.service.ts
Labels: 🐛 bug, auto-deploy

#4019 docs: update opanapi spec
  docs/openapi.json
Labels: skip-changelog

#4020 fix: appsumo billing
  packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts
Labels: skip-changelog, auto-deploy

#4021 fix: opening new connection
  packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
Labels: 🐛 bug, auto-deploy

#4022 chore: upgrade bullmq from 5.1.2 to 5.3.3
  package.json
Labels: 🧹 clean up

#4024 fix: use redis for task limit
  package-lock.json
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/ee/project-plan/tasks-limit.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-hooks.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/project/usage/project-usage-service.ts
Labels: 🐛 bug

#4025 fix: persist plan on registration
  packages/server/api/src/app/ee/authentication/authentication-service/hooks/cloud-authentication-service-hooks.ts
  packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts
  packages/server/api/src/app/ee/billing/appsumo/appsumo.service.ts
Labels: 🐛 bug, auto-deploy

#4029 fix: center logo in builder header and align dynamic inputs icon correctly
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
Labels: 🐛 bug, frontend, auto-deploy

#4028 fix(quikzu): fix trigger payload
  packages/pieces/community/quickzu/package.json
  packages/pieces/community/quickzu/src/lib/triggers/order-created.ts
Labels: 🔌 pieces

#4027 feat(acumbamail): create/delete list, add/update/delete/search subscriber and duplicate template actions
  packages/pieces/community/acumbamail/.eslintrc.json
  packages/pieces/community/acumbamail/README.md
  packages/pieces/community/acumbamail/package.json
  packages/pieces/community/acumbamail/project.json
  packages/pieces/community/acumbamail/src/index.ts
  packages/pieces/community/acumbamail/src/lib/actions/add-subscriber.ts
  packages/pieces/community/acumbamail/src/lib/actions/create-subscriber-list.ts
  packages/pieces/community/acumbamail/src/lib/actions/delete-subscriber-list.ts
  packages/pieces/community/acumbamail/src/lib/actions/delete-subscriber.ts
  packages/pieces/community/acumbamail/src/lib/actions/duplicate-template.ts
  packages/pieces/community/acumbamail/src/lib/actions/search-subscriber.ts
  packages/pieces/community/acumbamail/src/lib/common/constants.ts
  packages/pieces/community/acumbamail/src/lib/common/index.ts
  packages/pieces/community/acumbamail/src/lib/common/types.ts
  packages/pieces/community/acumbamail/tsconfig.json
  packages/pieces/community/acumbamail/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4015 feat: add Activity page
  packages/ee/shared/src/lib/activity/activity-requests.ts
  packages/server/api/src/app/ee/activity/activity-controller.ts
  packages/server/api/src/app/ee/activity/activity-service.ts
  packages/ui/core/src/assets/img/custom/dashboard/activity.svg
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.html
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/services/activity.service.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: ☁️ Paid Feature

#4035 fix(api): wrong resource name for app-connections
  packages/server/api/src/app/ee/authentication/rbac-auth-middleware.ts
Labels: 🐛 bug, 🖥️ api

#4038 fix(smtp): preset ports as dropdown
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/index.ts
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
  packages/pieces/community/smtp/src/lib/common/index.ts
Labels: 🔌 pieces

#4036 feat(afforai): ask chatbot action
  packages/pieces/community/afforai/.eslintrc.json
  packages/pieces/community/afforai/README.md
  packages/pieces/community/afforai/package.json
  packages/pieces/community/afforai/project.json
  packages/pieces/community/afforai/src/index.ts
  packages/pieces/community/afforai/src/lib/actions/ask-chatbot.ts
  packages/pieces/community/afforai/tsconfig.json
  packages/pieces/community/afforai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces
