Repository activepieces/activepieces, pull requests merged in 2024-04, with the labels that each got.

#4309 feat: add request trial form
  packages/ee/ui-platform/src/lib/components/api-keys-table/api-keys-table.component.html
  packages/ee/ui-platform/src/lib/components/api-keys-table/api-keys-table.component.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.html
  packages/ee/ui-platform/src/lib/components/sso-settings/sso-settings.component.html
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.html
  packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/templates-table/templates-table.component.html
  packages/ui/common/src/index.ts
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.html
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.ts
  packages/ui/common/src/lib/service/contact-sales.service.ts
  packages/ui/feature-dashboard/src/lib/components/contact-sales/contact-sales.component.html
  packages/ui/feature-dashboard/src/lib/components/contact-sales/contact-sales.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🐛 bug, ⭐ enhancement, auto-deploy

#4329 fix: browser running out of memory when viewing a large step output
  packages/ui/common/src/lib/components/horizontal-sidebar-separator/horizontal-sidebar-separator.component.ts
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.html
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.ts
  packages/ui/core/src/assets/scss/horizontal-sidebar-separator.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.ts
Labels: 🐛 bug, frontend

#4331 fix: resize YAML viewer on content change
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.html
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.ts
Labels: frontend, skip-changelog, auto-deploy

#4334 fix(cli): fix create piece lint option error
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/utils/files.ts
Labels: 💻 dx

#4337 fix: show all items in fulls creen mode in data to insert popover
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/mentions-list/mentions-list.component.html
Labels: 🐛 bug, frontend

#4336 fix: include old git state after pulling
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/src/app/ee/git-repos/project-diff/project-mapping-state.ts
Labels: 🐛 bug

#4338 fix: stop escaping html in steps outputs
  packages/ui/common/src/lib/pipe/output-log.pipe.ts
Labels: 🐛 bug, auto-deploy

#4327 chore: release 0.22.0
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#4347 fix(telegram): sample data for trigger works
  packages/pieces/community/telegram-bot/package.json
  packages/pieces/community/telegram-bot/src/lib/trigger/new-message.ts
Labels: 🔌 pieces

#4348 fix: publish failed for new slack connections
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
  packages/pieces/community/slack/src/lib/triggers/new-reaction-added.ts
Labels: 🔌 pieces

#4349 feat: add attachment to smtp piece
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/index.ts
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🔌 pieces

#4355 fix: increase minimum height of step output
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item.component.html
Labels: auto-deploy

#4344 fix(google-calendar): fix update event action
  packages/pieces/community/google-calendar/package.json
  packages/pieces/community/google-calendar/src/lib/actions/update-event.ation.ts
Labels: 🔌 pieces

#4361 fix: json form control should send value as object not string
  packages/ui/common/src/lib/utils/utils.ts
  packages/ui/feature-builder-form-controls/src/lib/components/json-control/json-control.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
Labels: 🐛 bug, auto-deploy

#4362 chore: bump release 0.23.0-rc.1
  package.json
Labels: pre-release

#4363 fix: json values method
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
Labels: 🐛 bug, pre-release

#4368 fix: saving when a dynamic property is being loaded caused wiping its value.
  packages/server/api/.env
  packages/ui/feature-builder-form-controls/src/lib/components/new-piece-properties-form/properties-controls-helper.ts
Labels: 🐛 bug, auto-deploy

#4340 feat(lever): add Lever integration
  packages/pieces/community/lever/.eslintrc.json
  packages/pieces/community/lever/README.md
  packages/pieces/community/lever/package.json
  packages/pieces/community/lever/project.json
  packages/pieces/community/lever/src/index.ts
  packages/pieces/community/lever/src/lib/actions/get-opportunity.ts
  packages/pieces/community/lever/src/lib/actions/list-opportunity-forms.ts
  packages/pieces/community/lever/src/lib/actions/update-opportunity-stage.ts
  packages/pieces/community/lever/tsconfig.json
  packages/pieces/community/lever/tsconfig.lib.json
Labels: 🔌 pieces

#4370 fix: remove commented code in lever
  packages/pieces/community/lever/src/index.ts
  packages/pieces/community/lever/src/lib/actions/get-opportunity.ts
  packages/pieces/community/lever/src/lib/actions/list-opportunity-forms.ts
  packages/pieces/community/lever/src/lib/actions/update-opportunity-stage.ts
Labels: skip-changelog

#4372 fix: include properties for oauth2 in the body in client grant
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
Labels: 🐛 bug

#4360 fix(microsoft-excel-365): fix workbook dropdown and add/update row action
  packages/pieces/community/microsoft-excel-365/package.json
  packages/pieces/community/microsoft-excel-365/src/lib/actions/append-row.ts
  packages/pieces/community/microsoft-excel-365/src/lib/actions/update-row.ts
  packages/pieces/community/microsoft-excel-365/src/lib/common/common.ts
Labels: 🔌 pieces

#4365 feat(elevenlabs): Text to Speech Action
  package-lock.json
  package.json
  packages/pieces/community/elevenlabs/.eslintrc.json
  packages/pieces/community/elevenlabs/README.md
  packages/pieces/community/elevenlabs/package.json
  packages/pieces/community/elevenlabs/project.json
  packages/pieces/community/elevenlabs/src/index.ts
  packages/pieces/community/elevenlabs/src/lib/actions/text-to-speech-action.ts
  packages/pieces/community/elevenlabs/tsconfig.json
  packages/pieces/community/elevenlabs/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4359 fix(google-sheets): Add row count condition in case of manual row deletion.
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: 🔌 pieces

#4373 feat: merge different google drive changes
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/search-folder-or-file.action.ts
  packages/pieces/community/google-drive/src/lib/action/upload-file.ts
  packages/pieces/community/google-drive/src/lib/common/index.ts
  packages/pieces/community/google-drive/src/lib/triggers/new-file.ts
Labels: skip-changelog

#4377 fix(turbowtach): show compilation error for pieces
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/index.ts
  tools/scripts/pieces/turbowatch.ts
Labels: 🐛 bug, 💻 dx

#4380 revert: filter pieces
  packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
Labels: skip-changelog

#4381 fix: show upgrade note for git sync page
  packages/ee/ui-platform/src/lib/lib.routes.ts
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
  packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ui/common/src/lib/resolvers/index.ts
  packages/ui/common/src/lib/resolvers/platform.resolver.ts
  packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
  packages/ui/feature-dashboard/src/lib/pages/settings-page/settings-page.component.html
  packages/ui/feature-dashboard/src/lib/pages/settings-page/settings-page.component.ts
  packages/ui/feature-git-sync/package.json
  packages/ui/feature-git-sync/src/lib/components/sync-project/sync-project.component.html
  packages/ui/feature-git-sync/src/lib/components/sync-project/sync-project.component.ts
  packages/ui/feature-pieces/src/lib/project-pieces-table/project-pieces-table.component.html
Labels: auto-deploy

#4383 fix: init worker after piece sync setup
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
Labels: auto-deploy

#4384 chore: bump version to 0.23.0-rc.2
  package.json
Labels: pre-release

#4386 fix(google-sheets): renew notification webhooks
  packages/engine/src/lib/helper/piece-loader.ts
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/flows/trigger/hooks/trigger-utils.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/pieces/utils.ts
Labels: 🔌 pieces

#4388 chore: remove console log
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: skip-changelog

#4382 feat: add community rewards information in dashboard
  docs/developers/building-pieces/create-action.mdx
  docs/developers/building-pieces/create-trigger.mdx
  docs/developers/building-pieces/piece-authentication.mdx
  docs/developers/building-pieces/piece-definition.mdx
  docs/developers/building-pieces/start-building.mdx
  docs/developers/piece-reference/triggers/polling-trigger.mdx
  docs/developers/piece-reference/triggers/webhook-trigger.mdx
  docs/mint.json
  packages/ee/billing/ui/src/index.ts
  packages/ee/billing/ui/src/lib/billing-sidenav-item/billing-sidenav-item.component.html
  packages/ee/billing/ui/src/lib/billing-sidenav-item/billing-sidenav-item.component.ts
  packages/ee/billing/ui/src/lib/ee-billing-ui.module.ts
  packages/ee/billing/ui/src/lib/plans-page/plans-page.component.html
  packages/ee/billing/ui/src/lib/plans-page/plans-page.component.ts
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/retune/package.json
  packages/server/api/.env
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
  packages/shared/package.json
  packages/shared/src/lib/common/telemetry.ts
  packages/shared/src/lib/flag/flag.ts
  packages/ui/core/src/assets/img/custom/dashboard/plans.svg
  packages/ui/core/src/assets/img/custom/rewards/linkedin.svg
  packages/ui/core/src/assets/img/custom/rewards/referals.svg
  packages/ui/core/src/assets/img/custom/rewards/rewards.svg
  packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/rewards-item/rewards-item.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-route-item/sidenav-route-item.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.html
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🌟 feature, auto-deploy

#4390 feat: add general project settings
  packages/ee/ui-platform/src/lib/components/smtp-settings/smtp-settings.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/update-project-dialog/update-project-dialog.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/update-project-dialog/update-project-dialog.component.ts
  packages/ee/ui-platform/src/lib/ui-ee-platform.module.ts
  packages/server/api/src/app/ee/authentication/rbac/access-control-list.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/ee/projects/platform-project-controller.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/project/project-controller.ts
  packages/server/api/src/app/project/project-module.ts
  packages/server/api/src/app/project/project-service.ts
  packages/shared/src/lib/common/security/permission.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/project/project.ts
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
  packages/ui/common/src/lib/service/platform-project.service.ts
  packages/ui/common/src/lib/store/project/project.reducer.ts
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.html
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts
  packages/ui/feature-dashboard/src/lib/components/project-switcher/project-switcher.component.ts
  packages/ui/feature-dashboard/src/lib/pages/settings-page/settings-page.component.html
  packages/ui/feature-dashboard/src/lib/pages/settings-page/settings-page.component.ts
  packages/ui/feature-pieces/src/lib/project-pieces-table/project-pieces-table.component.html
  packages/ui/feature-pieces/src/lib/project-pieces-table/project-pieces-table.component.ts
Labels: 🌟 feature, auto-deploy

#4391 fix: enable rewards
  packages/server/api/src/app/flags/flag.service.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
Labels: skip-changelog, auto-deploy

#4392 feat: add copy button for webhook trigger
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts
  packages/ui/common/src/lib/components/ap-markdown/ap-markdown.component.html
  packages/ui/common/src/lib/components/ap-markdown/ap-markdown.component.ts
  packages/ui/common/src/lib/components/index.ts
  packages/ui/common/src/lib/components/markdown/markdown.component.html
  packages/ui/common/src/lib/components/markdown/markdown.component.scss
  packages/ui/common/src/lib/components/markdown/markdown.component.ts
  packages/ui/common/src/lib/service/highlight.service.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/core/src/assets/scss/css-reset.scss
  packages/ui/core/src/assets/scss/prism-theme.scss
  packages/ui/core/src/main.ts
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-form-control.component.ts
Labels: ⭐ enhancement, auto-deploy

#4393 feat(embed): ability to hide flow actions
  docs/embedding/configuration/initialize-embed.mdx
  packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts
  packages/ee/embed-sdk/src/index.ts
  packages/ui/common/src/lib/service/embedding.service.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
Labels: ⭐ enhancement, auto-deploy

#4395 fix(mysql): fix delete/find/insert/update row queries
  packages/pieces/community/mysql/package.json
  packages/pieces/community/mysql/src/lib/actions/delete-row.ts
  packages/pieces/community/mysql/src/lib/actions/find-rows.ts
  packages/pieces/community/mysql/src/lib/actions/insert-row.ts
  packages/pieces/community/mysql/src/lib/actions/update-row.ts
Labels: 🔌 pieces

#4394 feat: release 0.23.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#4396 feat(embed): ability to hide flow name in the builder
  docs/embedding/configuration/initialize-embed.mdx
  package.json
  packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts
  packages/ee/embed-sdk/src/index.ts
  packages/ui/common/src/lib/service/embedding.service.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
Labels: ⭐ enhancement, auto-deploy

#4397 feat: revert yaml to json with expandable objects
  package-lock.json
  package.json
  packages/ui/common/src/lib/components/index.ts
  packages/ui/common/src/lib/components/json-view/json-view-dialog/json-view-dialog.component.html
  packages/ui/common/src/lib/components/json-view/json-view-dialog/json-view-dialog.component.ts
  packages/ui/common/src/lib/components/json-view/json-view.component.html
  packages/ui/common/src/lib/components/json-view/json-view.component.ts
  packages/ui/common/src/lib/components/yaml-view/yaml-view-dialog/yaml-view-dialog.component.ts
  packages/ui/common/src/lib/pipe/output-log.pipe.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/core/project.json
  packages/ui/core/src/app/monaco-themes/ap-monaco-theme.ts
  packages/ui/core/src/main.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-action/test-action.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-polling-trigger/test-polling-trigger.component.html
Labels: 🌟 feature, auto-deploy

#4399 feat: make powered by not clickable and less catchy
  packages/ui/common/src/lib/components/powered-by-activepieces/powered-by-activepieces.component.html
Labels: 🐛 bug, auto-deploy

#4402 fix: wasn't able to attach a debugger to the running process
  .vscode/launch.json
Labels: 🧹 clean up

#4409 fix: accept renew configuration in admin pieces endpoint
  packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
Labels: skip-changelog, auto-deploy

#4410 fix: renew configuration is not working on cloud
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: skip-changelog

#4422 fix: add permission to tags
  packages/server/api/src/app/tags/tags-module.ts
Labels: skip-changelog, auto-deploy

#4426 fix: role value in ui
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
  packages/ee/project-members/src/lib/service/project-members.service.ts
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/core/src/app/app.module.ts
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.html
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts
  packages/ui/feature-pieces/package.json
  packages/ui/feature-pieces/src/lib/project-pieces-table/project-pieces-table.component.ts
Labels: skip-changelog, auto-deploy

#4427 fix: role checker in general project settings
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts
Labels: skip-changelog, auto-deploy

#4429 feat: release 0.24.0
  package-lock.json
  package.json
Labels: release

#4431 fix: hide support & community
  packages/ui/feature-dashboard/src/lib/components/sidenav-route-item/sidenav-route-item.component.ts
Labels: 🐛 bug, auto-deploy

#4430 feat: added append text action to google docs piece.
  packages/pieces/community/google-docs/package.json
  packages/pieces/community/google-docs/src/index.ts
  packages/pieces/community/google-docs/src/lib/actions/append-text.ts
  packages/pieces/community/google-docs/src/lib/common/index.ts
Labels: 🔌 pieces

#4432 feat: release 0.24.1
  docker-compose.yml
  docs/about/changelog.mdx
  package-lock.json
  package.json
Labels: release

#4433 docs: improve embed docs and document project pieces filter
  docs/admin-console/appearance.mdx
  docs/admin-console/manage-pieces.mdx
  docs/admin-console/manage-projects.mdx
  docs/admin-console/manage-templates.mdx
  docs/embedding/connections/create-connection.mdx
  docs/embedding/customize-pieces.mdx
  docs/embedding/embed-builder.mdx
  docs/embedding/embed-connections.mdx
  docs/embedding/overview.mdx
  docs/embedding/provision-users.mdx
  docs/mint.json
  docs/resources/screenshots/install-piece.png
  docs/resources/screenshots/manage-pieces.png
  docs/resources/screenshots/tag-pieces.png
Labels: 📚 documentation

#4447 fix: export template not showing correct json
  package-lock.json
  packages/ui/common/src/lib/utils/consts.ts
Labels: 🐛 bug, auto-deploy

#4448 docs: fix typos & improve embedding documentation
  .github/workflows/closed-issue-reply.yaml
  docs/_snippets/enterprise-feature.mdx
  docs/about/changelog.mdx
  docs/admin-console/overview.mdx
  docs/developers/building-pieces/start-building.mdx
  docs/embedding/customize-pieces.mdx
  docs/embedding/embed-builder.mdx
  docs/embedding/embed-connections.mdx
  docs/embedding/overview.mdx
  docs/embedding/provision-users.mdx
  docs/install/configurations/environment-variables.mdx
  docs/install/options/aws.mdx
  docs/install/setup-ssl.mdx
  docs/security/sso.mdx
  packages/ee/ui-platform/src/lib/components/api-keys-table/api-keys-table.component.ts
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
  packages/pieces/community/cal-com/src/lib/triggers/index.ts
  packages/pieces/community/delay/src/index.ts
  packages/pieces/community/delay/src/lib/actions/delay-until-action.ts
  packages/pieces/community/google-calendar/src/lib/actions/update-event.ation.ts
  packages/pieces/community/google-drive/src/lib/action/read-file.ts
  packages/pieces/community/google-drive/src/lib/action/save-file-as-pdf.action.ts
  packages/pieces/community/mailer-lite/src/triggers/triggers.ts
  packages/pieces/community/onfleet/src/lib/triggers/auto-dispatch-completed.ts
  packages/pieces/community/pastebin/src/lib/common/index.ts
  packages/server/api/src/app/ee/connection-keys/connection-key.service.ts
  packages/server/api/src/app/ee/helper/appearance-helper.ts
  packages/ui/common/src/index.ts
  packages/ui/common/src/lib/pipe/comma-separated.pipe.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/core/src/assets/img/custom/rewards/referrals.svg
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.ts
Labels: 📚 documentation, auto-deploy

#4455 chore: merge all discord actions into single pr
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/index.ts
  packages/pieces/community/discord/src/lib/actions/ban-a-guild-member.ts
  packages/pieces/community/discord/src/lib/actions/create-guild-role.ts
  packages/pieces/community/discord/src/lib/actions/delete-guild-role.ts
  packages/pieces/community/discord/src/lib/actions/remove-ban-from-user.ts
Labels: skip-changelog

#4412 feat(discord): add remove ban from user action
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/index.ts
  packages/pieces/community/discord/src/lib/actions/remove-ban-from-user.ts
Labels: 🔌 pieces

#4342 feat(google-drive): allow new file trigger to include content
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/read-file.ts
  packages/pieces/community/google-drive/src/lib/common/get-file-content.ts
  packages/pieces/community/google-drive/src/lib/triggers/new-file.ts
Labels: 🔌 pieces

#4462 fix: stop rewards button from overflowing and add rewards note to flows table
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/retune/package.json
  packages/shared/package.json
  packages/shared/src/lib/common/telemetry.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/feature-dashboard/src/lib/components/rewards-note/rewards-note.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
  packages/ui/feature-flow-builder/package.json
  packages/ui/feature-tags/package.json
  packages/ui/feature-templates/src/lib/template-description-banner-color.pipe.ts
Labels: skip-changelog, auto-deploy

#4467 feat: show updates in admin console
  packages/ee/ui-platform/src/lib/components/updates/updates.component.html
  packages/ee/ui-platform/src/lib/components/updates/updates.component.ts
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ee/ui-platform/src/lib/ui-ee-platform.module.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
Labels: 🌟 feature, auto-deploy

#4465 feat: add report issue to connection dialog for unknown errors
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/index.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/ui/common/src/index.ts
  packages/ui/common/src/lib/components/diagnostic-dialog/diagnostic-dialog.component.html
  packages/ui/common/src/lib/components/diagnostic-dialog/diagnostic-dialog.component.ts
  packages/ui/common/src/lib/components/json-view/json-view.component.html
  packages/ui/common/src/lib/components/json-view/json-view.component.ts
  packages/ui/common/src/lib/components/warning-box/warning-box.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-connections/src/lib/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.ts
  packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.ts
Labels: 🌟 feature, auto-deploy

#4468 fix(embed-sdk): allow copying and pasting inside embedding
  packages/ee/embed-sdk/package.json
  packages/ee/embed-sdk/src/index.ts
Labels: 🐛 bug, Embed

#4469 fix(embed-sdk): add connection iframe only when used
  packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts
  packages/ee/components/src/lib/embedded-connection-dialog/embedded-connection-dialog.component.html
  packages/ee/embed-sdk/src/index.ts
  packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
Labels: 🐛 bug, Embed

#4473 fix: triggering saving in read-only mode
  packages/ui/feature-builder-form-controls/src/lib/components/new-piece-properties-form/properties-controls-helper.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
Labels: 🐛 bug, frontend, auto-deploy

#4470 chore: security upgrade ngx-markdown from 16.0.0 to 17.0.0
  package.json
Labels: 🧹 clean up

#4476 chore: remove unique email and platform null constraints
  packages/server/api/src/app/database/migration/postgres/1713221809186-RemoveUniqueEmailOnUser.ts
  packages/server/api/src/app/database/migration/sqlite/1713222892743-RemoveUniqueEmailOnUser.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/user/user-entity.ts
Labels: 🧹 clean up, auto-deploy

#4461 chore: merge all github prs in single pr
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/index.ts
  packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts
  packages/pieces/community/github/src/lib/actions/get-issue-information.ts
  packages/pieces/community/github/src/lib/actions/lock-issue.ts
  packages/pieces/community/github/src/lib/actions/unlock-issue.ts
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/triggers/new-file.ts
Labels: skip-changelog

#4477 fix(google-drive): exclude folders from file polling
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/common/index.ts
Labels: 🔌 pieces

#4474 feat: self serve custom domains
  packages/ee/shared/src/lib/custom-domains/index.ts
  packages/ee/ui/platform/src/lib/components/custom-domain-table/custom-domain-table.component.html
  packages/ee/ui/platform/src/lib/components/custom-domain-table/custom-domain-table.component.ts
  packages/ee/ui/platform/src/lib/components/dialogs/create-custom-domain-dialog/create-custom-domain-dialog.component.ts
  packages/ee/ui/platform/src/lib/components/dialogs/domain-txt-validation-dialog/domain-txt-validation-dialog.component.html
  packages/ee/ui/platform/src/lib/components/dialogs/domain-txt-validation-dialog/domain-txt-validation-dialog.component.ts
  packages/ee/ui/platform/src/lib/service/custom-domain.service.ts
  packages/ee/ui/platform/src/lib/ui-ee-platform.module.ts
  packages/server/api/src/app/ee/custom-domains/cloudflare-api.service.ts
  packages/server/api/src/app/ee/custom-domains/custom-domain.module.ts
  packages/server/api/src/app/ee/custom-domains/custom-domain.service.ts
  packages/server/api/test/integration/cloud/custom-domain/custom-domain.test.ts
  packages/server/shared/src/lib/system/system-prop.ts
Labels: ⭐ enhancement, auto-deploy

#4491 fix: hide unrequired auth for actions
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
Labels: 🐛 bug

#4490 fix(audit-logs): table had issues loading
  packages/ee/ui/platform/src/lib/components/audit-event-table/audit-event-table.component.html
Labels: 🐛 bug, auto-deploy

#4494 fix: add page views
  packages/shared/src/lib/common/telemetry.ts
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/rewards-note/rewards-note.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
Labels: skip-changelog, auto-deploy

#4495 fix: event tracking
  packages/server/api/src/app/helper/telemetry.utils.ts
Labels: skip-changelog, auto-deploy

#4496 fix: skip embed
  packages/ui/common/src/lib/service/telemetry.service.ts
Labels: skip-changelog, auto-deploy

#4497 fix: inserting suggestions was always invalid
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/ui/common/src/lib/models/flow-item-details.ts
  packages/ui/common/src/lib/utils/utils.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/rewards-dialog/rewards-dialog.component.ts
  packages/ui/feature-pieces/src/lib/services/piece.service.ts
Labels: 🐛 bug, frontend, auto-deploy

#4499 feat: add folder name to flow api
  docs/openapi.json
  packages/server/api/src/app/ee/git-repos/git-sync-helper.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/flows/folder/folder.controller.ts
  packages/server/api/src/app/flows/folder/folder.service.ts
  packages/shared/src/lib/flows/dto/create-flow-request.ts
  packages/ui/common/src/lib/service/flow.service.ts
  packages/ui/feature-dashboard/src/lib/components/rewards-note/rewards-note.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
Labels: ⭐ enhancement, auto-deploy

#4479 feat(google-drive): Move file and set file as public action
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/index.ts
  packages/pieces/community/google-drive/src/lib/action/move-file.ts
  packages/pieces/community/google-drive/src/lib/action/set-public-access.ts
Labels: 🔌 pieces

#4489 feat(straico): Ask AI and Custom API Call Action
  packages/pieces/community/straico/.eslintrc.json
  packages/pieces/community/straico/README.md
  packages/pieces/community/straico/package.json
  packages/pieces/community/straico/project.json
  packages/pieces/community/straico/src/index.ts
  packages/pieces/community/straico/src/lib/actions/prompt-completion.ts
  packages/pieces/community/straico/src/lib/common/common.ts
  packages/pieces/community/straico/tsconfig.json
  packages/pieces/community/straico/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4501 chore: style copy webhook url button and add a better note for testing core webhook trigger
  packages/ui/common/src/lib/components/ap-markdown/ap-markdown.component.html
  packages/ui/core/src/assets/scss/utlis.scss
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.ts
Labels: frontend, 🤷‍♂️ design debt, auto-deploy

#4487 feat(admin-console): release notifications & updates history
  packages/ee/ui/platform/src/lib/components/updates/release-table.datasource.ts
  packages/ee/ui/platform/src/lib/components/updates/updates.component.html
  packages/ee/ui/platform/src/lib/components/updates/updates.component.ts
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ee/ui/platform/src/lib/service/updates.service.ts
  packages/ui/common/src/lib/service/flag.service.ts
  packages/ui/core/src/assets/img/custom/notification_important.svg
  packages/ui/feature-dashboard/src/lib/components/sidenav-route-item/sidenav-route-item.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
Labels: 🌟 feature, auto-deploy

#4502 feat: new date and time format
  packages/ee/ui/billing/src/lib/ee-billing-ui.module.ts
  packages/ee/ui/billing/src/lib/plans-page/plans-page.component.html
  packages/ee/ui/platform/src/lib/components/api-keys-table/api-keys-table.component.html
  packages/ee/ui/platform/src/lib/components/audit-event-table/audit-event-table.component.html
  packages/ee/ui/platform/src/lib/components/custom-domain-table/custom-domain-table.component.html
  packages/ee/ui/platform/src/lib/components/signing-keys-table/signing-keys-table.component.html
  packages/ee/ui/platform/src/lib/components/updates/updates.component.html
  packages/ee/ui/platform/src/lib/components/updates/updates.component.ts
  packages/ee/ui/platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui/platform/src/lib/pages/templates-table/templates-table.component.html
  packages/ee/ui/platform/src/lib/pages/users-table/users-table.component.html
  packages/ee/ui/platform/src/lib/ui-ee-platform.module.ts
  packages/ee/ui/project-members/src/lib/ee-project-members.module.ts
  packages/ee/ui/project-members/src/lib/project-members-table/project-members-table.component.html
  packages/ui/common/src/index.ts
  packages/ui/common/src/lib/pipe/ap-date.pipe.ts
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/ui-feature-builder-test-steps.module.ts
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: ⭐ enhancement, auto-deploy

#4483 feat(google-sheets): New/Updated Row Trigger and Insert Multiple Rows Action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/triggers/helpers.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
Labels: 🔌 pieces, 🌟 feature

#4505 fix: retry update flow request
  packages/pieces/community/shopify/package.json
  packages/pieces/community/shopify/src/index.ts
  packages/ui/common/src/lib/service/flow.service.ts
Labels: 🐛 bug, auto-deploy

#4508 fix: create new folder api
  packages/server/api/src/app/database/migration/postgres/1713643694049-AddUniqueNameToFolder.ts
  packages/server/api/src/app/database/migration/sqlite/1713645171373-AddUniqueNameToFolderSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/folder/folder.entity.ts
  packages/server/api/src/app/flows/folder/folder.service.ts
  packages/ui/feature-dashboard/src/lib/validators/folderName.validator.ts
Labels: 🐛 bug, auto-deploy

#4498 feat(slack): Improve load sample data, find user by email, create channel and update profile action
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/create-channel.ts
  packages/pieces/community/slack/src/lib/actions/find-user-by-email.ts
  packages/pieces/community/slack/src/lib/actions/update-profile.ts
  packages/pieces/community/slack/src/lib/triggers/new-channel.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
Labels: 🔌 pieces, auto-deploy

#4509 docs: improve building pieces section
  docs/developers/building-pieces/piece-authentication.mdx
  docs/developers/building-pieces/piece-definition.mdx
  docs/developers/building-pieces/setup-fork.mdx
  docs/developers/building-pieces/start-building.mdx
  docs/developers/misc/private-fork.mdx
  docs/developers/misc/repo-structure.mdx
  docs/mint.json
  docs/resources/screenshots/fork-repository.jpg
Labels: 📚 documentation

#4512 fix: folder update
  packages/server/api/src/app/flows/folder/folder.service.ts
Labels: skip-changelog, auto-deploy

#4513 feat: reordering items in the array property
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control-text-item.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
Labels: ⭐ enhancement, auto-deploy

#4518 fix: bump slack version
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/actions/upload-file.ts
  packages/server/api/src/app/flows/folder/folder.service.ts
Labels: skip-changelog

#4519 feat(hubspot): add more scopes to hubspot
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/index.ts
Labels: skip-changelog

#4520 fix: UX for reordering array
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control-text-item.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.scss
  packages/ui/feature-builder-form-controls/src/lib/components/dictionary-form-control/dictionary-form-control.component.ts
Labels: 🐛 bug, skip-changelog, auto-deploy

#4525 fix(embed-sdk): stop opening new window in embedding after duplicating a flow
  packages/ui/common/src/lib/service/flow.service.ts
Labels: 🐛 bug, Embed, auto-deploy

#4527 feat: release 0.25.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#4530 fix: re-enable properties array
  packages/ui/common/src/lib/components/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/array-form-control/array-form-control.component.ts
Labels: 🐛 bug, auto-deploy

#4529 fix(google-sheets): Add row number in response and fix find rows action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
Labels: 🔌 pieces

#4532 feat: release 0.25.1
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/api/src/app/database/migration/common/1709581196563-migrate-webhook.ts
Labels: release

#4539 fix: list owned project
  packages/server/api/src/app/ee/projects/platform-project-service.ts
Labels: 🐛 bug, auto-deploy

#4534 feat: add listener to zoom on ctrl+mouse wheel
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
Labels: 🌟 feature, auto-deploy

#4546 feat(notion): find database item by property value action
  packages/pieces/community/notion/package.json
  packages/pieces/community/notion/src/index.ts
  packages/pieces/community/notion/src/lib/action/find-item.ts
  packages/pieces/community/notion/src/lib/common/index.ts
Labels: 🔌 pieces

#4543 chore: move webhook consumption to workers
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/flows/flow-run/flow-response-watcher.ts
  packages/server/api/src/app/flows/flow-run/flow-run-module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/workers/flow-worker/consumer/flow-queue-consumer.ts
  packages/server/api/src/app/workers/flow-worker/consumer/webook-consumer.ts
  packages/server/api/src/app/workers/flow-worker/engine-response-watcher.ts
  packages/server/api/src/app/workers/flow-worker/flow-queue.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker-module.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/server/api/src/app/workers/flow-worker/job-data.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-consumer.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-queue.ts
  packages/server/api/src/app/workers/flow-worker/queues/queue.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-bullboard.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-consumer.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts
  packages/server/shared/src/index.ts
  packages/server/shared/src/lib/semaphore.ts
  packages/server/worker/package.json
  packages/server/worker/src/index.ts
  packages/server/worker/src/lib/queue/ap-memory-queue.ts
Labels: 🧹 clean up

#4549 feat: 0.26.0-rc.1
  package.json
Labels: pre-release

#4544 feat(gmail-dev): new email trigger in gmail developer edition piece
  packages/pieces/community/gmail-dev/.eslintrc.json
  packages/pieces/community/gmail-dev/README.md
  packages/pieces/community/gmail-dev/package.json
  packages/pieces/community/gmail-dev/project.json
  packages/pieces/community/gmail-dev/src/index.ts
  packages/pieces/community/gmail-dev/src/lib/common/data.ts
  packages/pieces/community/gmail-dev/src/lib/common/models.ts
  packages/pieces/community/gmail-dev/src/lib/common/props.ts
  packages/pieces/community/gmail-dev/src/lib/triggers/new-email.ts
  packages/pieces/community/gmail-dev/tsconfig.json
  packages/pieces/community/gmail-dev/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4550 fix: enhance panning in the builder using laptops touchpads
  packages/ui/canvas-utils/src/lib/panning/panner.directive.ts
  packages/ui/canvas-utils/src/lib/panning/panner.service.ts
Labels: 🐛 bug, frontend, auto-deploy

#4536 feat(linear): enrich actions output
  packages/pieces/community/linear/package.json
  packages/pieces/community/linear/src/lib/actions/comments/create-comment.ts
  packages/pieces/community/linear/src/lib/actions/issues/create-issue.ts
  packages/pieces/community/linear/src/lib/actions/issues/update-issue.ts
  packages/pieces/community/linear/src/lib/actions/projects/create-project.ts
  packages/pieces/community/linear/src/lib/actions/projects/update-project.ts
Labels: 🔌 pieces

#4552 chore: metabase
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/lib/common.ts
Labels: skip-changelog

#4554 refactor: add logging for token expired
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.ts
  packages/ui/common/src/lib/service/authentication.service.ts
Labels: 🧹 clean up

#4555 fix: exception null value in header
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
Labels: skip-changelog, auto-deploy

#4507 feat: add connections filters (by name and by piece)
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/shared/src/lib/app-connection/dto/read-app-connection-request.ts
  packages/ui/common/src/lib/service/app-connections.service.ts
  packages/ui/common/src/lib/utils/tables.utils.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🌟 feature, auto-deploy

#4559 fix: allow copying and pasting data pills and undoing/redoing that
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
  packages/shared/src/lib/app-connection/dto/read-app-connection-request.ts
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/common/src/lib/service/contact-sales.service.ts
  packages/ui/common/src/lib/utils/insert-mention-operation.ts
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/fixed-selection-mention.ts
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/interpolating-text-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/interpolating-text-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/mentions-list/mentions-list.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/utils.ts
  packages/ui/feature-dashboard/src/lib/components/contact-sales/contact-sales.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🐛 bug, frontend, auto-deploy

#4560 fix: enhance runs list inside the builder by using better icons and making them clickable
  packages/ui/core/src/assets/img/custom/enter-run.svg
  packages/ui/core/src/assets/img/custom/exit-run.svg
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
Labels: 🐛 bug, frontend

#4566 fix: resolve platform id for managed login
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/authn-provider.ts
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/google-authn-provider.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-service.ts
  packages/server/api/src/app/platform/platform-utils.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/ui/common/src/lib/service/platform.service.ts
Labels: 🐛 bug, auto-deploy

#4567 fix: list templates
  packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
Labels: 🐛 bug, auto-deploy

#4568 fix: list cloud platform template
  packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
  packages/ui/common/src/lib/service/platform.service.ts
Labels: 🐛 bug, auto-deploy

#4576 chore: change table header background color
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.scss
  packages/ui/core/src/assets/scss/flow-builder.scss
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/core/src/assets/scss/variables.scss
  packages/ui/core/src/styles.scss
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.scss
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.css
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.ts
Labels: 🤷‍♂️ design debt, 🧹 clean up

#4573 refactor: remove unused colors & css
  packages/ui/core/src/assets/scss/flow-builder.scss
  packages/ui/core/src/assets/scss/variables.scss
  packages/ui/core/src/styles.scss
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.scss
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.css
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.ts
Labels: 🧹 clean up

#4572 feat(google-calendar): event color option for create/update event action
  packages/pieces/community/google-calendar/package.json
  packages/pieces/community/google-calendar/src/index.ts
  packages/pieces/community/google-calendar/src/lib/actions/create-event.ts
  packages/pieces/community/google-calendar/src/lib/actions/update-event.action.ts
  packages/pieces/community/google-calendar/src/lib/actions/update-event.ation.ts
  packages/pieces/community/google-calendar/src/lib/common/helper.ts
  packages/pieces/community/google-calendar/src/lib/common/index.ts
  packages/pieces/community/google-calendar/src/lib/common/types.ts
Labels: 🔌 pieces

#4581 fix(moxie-crm): Fix Test Trigger Payload Issue
  packages/pieces/community/moxie-crm/package.json
  packages/pieces/community/moxie-crm/src/lib/triggers/register-trigger.ts
Labels: 🔌 pieces

#4589 docs: add code snippets
  docs/developers/sharing-pieces/community.mdx
  docs/developers/sharing-pieces/contribute.mdx
  docs/developers/sharing-pieces/private.mdx
  docs/getting-started/introduction.mdx
  docs/mint.json
  docs/resources/create-action.png
  docs/team/overview.mdx
Labels: 📚 documentation

#4590 feat: release 0.26.0-rc.2
  package.json
Labels: pre-release

#4592 docs: reset password instructions for sqlite3
  docs/install/troubleshooting.mdx
  packages/server/api/src/app/authentication/lib/password-hasher.ts
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
Labels: 📚 documentation, auto-deploy

#4593 fix: github name can be nullable
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
Labels: 🐛 bug, auto-deploy

#4602 feat(segment): identify user
  nx.json
  package-lock.json
  package.json
  packages/pieces/community/apollo/.eslintrc.json
  packages/pieces/community/apollo/README.md
  packages/pieces/community/apollo/package.json
  packages/pieces/community/apollo/project.json
  packages/pieces/community/apollo/src/index.ts
  packages/pieces/community/apollo/src/lib/actions/enrich-company.ts
  packages/pieces/community/apollo/src/lib/actions/match-person.ts
  packages/pieces/community/apollo/tsconfig.json
  packages/pieces/community/apollo/tsconfig.lib.json
  packages/pieces/community/segment/.eslintrc.json
  packages/pieces/community/segment/README.md
  packages/pieces/community/segment/package.json
  packages/pieces/community/segment/project.json
  packages/pieces/community/segment/src/index.ts
  packages/pieces/community/segment/src/lib/actions/identify-user.ts
  packages/pieces/community/segment/tsconfig.json
  packages/pieces/community/segment/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4601 feat(apollo): enrich company / match person action
  nx.json
  package-lock.json
  package.json
  packages/pieces/community/apollo/.eslintrc.json
  packages/pieces/community/apollo/README.md
  packages/pieces/community/apollo/package.json
  packages/pieces/community/apollo/project.json
  packages/pieces/community/apollo/src/index.ts
  packages/pieces/community/apollo/src/lib/actions/enrich-company.ts
  packages/pieces/community/apollo/src/lib/actions/match-person.ts
  packages/pieces/community/apollo/tsconfig.json
  packages/pieces/community/apollo/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces
