Repository activepieces/activepieces, pull requests merged in 2024-01, with the labels that each got.

#3523 fix: skip completed step after resume
  .vscode/settings.json
  packages/backend/src/app/helper/engine-helper.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/main.ts
  packages/shared/src/lib/engine/engine-operation.ts
Labels: 🐛 bug

#3531 chore: bump rc version
  package.json
Labels: pre-release

#3530 fix(ntfy): support unicode api header
  packages/pieces/ntfy/package.json
  packages/pieces/ntfy/src/lib/actions/send-notification.ts
Labels: 🔌 pieces

#3526 feat(vbout): create contact,tag,email list,email campaign,social media post, remove tag, update contact, unsubscribe contact actions
  packages/pieces/vbout/.eslintrc.json
  packages/pieces/vbout/README.md
  packages/pieces/vbout/package.json
  packages/pieces/vbout/project.json
  packages/pieces/vbout/src/index.ts
  packages/pieces/vbout/src/lib/actions/add-contact.ts
  packages/pieces/vbout/src/lib/actions/add-tag-to-contact.ts
  packages/pieces/vbout/src/lib/actions/create-campaign.ts
  packages/pieces/vbout/src/lib/actions/create-email-list.ts
  packages/pieces/vbout/src/lib/actions/create-social-media-message.ts
  packages/pieces/vbout/src/lib/actions/get-contact-by-email.ts
  packages/pieces/vbout/src/lib/actions/get-email-list.ts
  packages/pieces/vbout/src/lib/actions/remove-tag-from-contact.ts
  packages/pieces/vbout/src/lib/actions/unsubscribe-contact.ts
  packages/pieces/vbout/src/lib/actions/update-contact.ts
  packages/pieces/vbout/src/lib/common/client.ts
  packages/pieces/vbout/src/lib/common/index.ts
  packages/pieces/vbout/src/lib/common/models.ts
  packages/pieces/vbout/tsconfig.json
  packages/pieces/vbout/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3281 feat: support version history
  packages/backend/src/app/flows/flow-version/flow-version.service.ts
  packages/backend/src/app/flows/flow.module.ts
  packages/backend/src/app/flows/flow/flow-version.controller.ts
  packages/backend/src/app/flows/folder/folder.controller.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/common/utils/utils.ts
  packages/shared/src/lib/flows/dto/list-flows-request.ts
  packages/shared/src/lib/flows/flow-helper.ts
  packages/shared/src/lib/flows/flow-operations.ts
  packages/shared/src/lib/flows/flow-version.ts
  packages/ui/common/src/lib/components/dialog-title-template/dialog-title-template.component.ts
  packages/ui/common/src/lib/service/flow.service.ts
  packages/ui/core/src/assets/img/custom/draft.svg
  packages/ui/core/src/assets/img/custom/published.svg
  packages/ui/core/src/assets/img/custom/versions.svg
  packages/ui/feature-authentication/src/lib/pages/sign-up/sign-up.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item-tree.component.ts
  packages/ui/feature-builder-header/src/index.ts
  packages/ui/feature-builder-header/src/lib/draft-status/draft-status.component.html
  packages/ui/feature-builder-header/src/lib/draft-status/draft-status.component.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
  packages/ui/feature-builder-header/src/lib/import-flow-dialogue/import-flow-dialogue.component.html
  packages/ui/feature-builder-header/src/lib/publish-button/publish-button.component.html
  packages/ui/feature-builder-header/src/lib/publish-button/publish-button.component.ts
  packages/ui/feature-builder-header/src/lib/ui-feature-builder-header.module.ts
  packages/ui/feature-builder-header/src/lib/version-history-button/version-history-button.component.html
  packages/ui/feature-builder-header/src/lib/version-history-button/version-history-button.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/dialogs/use-as-draft-confirmation-dialog/use-as-draft-confirmation-dialog.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/dialogs/use-as-draft-confirmation-dialog/use-as-draft-confirmation-dialog.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/flow-left-sidebar.component.css
  packages/ui/feature-builder-left-sidebar/src/lib/flow-left-sidebar.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/flow-left-sidebar.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/ui-feature-builder-left-sidebar.module.ts
  packages/ui/feature-builder-left-sidebar/src/lib/version-history/version-history.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/version-history/version-history.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-sidebar.component.ts
  packages/ui/feature-builder-store/src/lib/model/canvas-state.ts
  packages/ui/feature-builder-store/src/lib/model/enums/left-side-bar-type.enum.ts
  packages/ui/feature-builder-store/src/lib/model/enums/view-mode.enum.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.action.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts
  packages/ui/feature-builder-store/src/lib/store/builder/viewmode/view-mode.action.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flows.action.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
  tsconfig.base.json
Labels: 🌟 feature

#3536 fix: build docker image for raspberry pi arm v7/v8
  .github/workflows/release-rc.yml
  .github/workflows/release.yml
Labels: ⭐ enhancement

#3537 fix: navigation icon from the builder
  packages/ui/common/src/lib/service/embedding.service.ts
  packages/ui/core/src/assets/img/custom/dashboard/dashboard.svg
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
Labels: 🐛 bug, frontend, skip-changelog

#3538 fix: automatically refresh runs table when there is a run still being executed
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
Labels: 🐛 bug, frontend

#3539 feat: release rc 3
  package.json
Labels: pre-release, skip-changelog

#3540 fix: export version history component
  packages/ui/feature-builder-header/src/index.ts
Labels: pre-release, skip-changelog

#3541 chore(release): skip building arm/v7 and arm/v8 images for RCs
  .github/workflows/release-rc.yml
Labels: :hammer: CI

#3542 fix: AppSumo authn
  packages/backend/.env.tests
  packages/backend/src/app/core/security/authn/app-sumo-authn-handler.ts
  packages/backend/src/app/core/security/security-handler-chain.ts
  packages/backend/test/integration/cloud/app-sumo/app-sumo.test.ts
Labels: 🐛 bug, backend

#3551 feat(hubspot): fix contact owner dropdown bug / get owner by email action
  packages/pieces/hubspot/package.json
  packages/pieces/hubspot/src/index.ts
  packages/pieces/hubspot/src/lib/actions/search-owner-by-email.ts
  packages/pieces/hubspot/src/lib/common/client.ts
  packages/pieces/hubspot/src/lib/common/index.ts
Labels: 🔌 pieces

#3546 fix: show correct flow status after first publish (on) and refresh runs table after a retry
  packages/ui/feature-builder-store/src/lib/store/flow/flows.reducer.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs.service.ts
Labels: 🐛 bug

#3552 fix: auth property were not validated
  .github/workflows/build-cloud-image.yml
  packages/backend/src/app/flows/flow-version/flow-version.service.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/demo-flow-template.ts
Labels: skip-changelog

#3549 chore: upgrade typeorm from 0.3.17 to 0.3.18
  package.json
Labels: 💻 tech debt

#3555 fix: global api key should be optional
  packages/backend/src/app/core/security/authn/global-api-key-authn-handler.ts
Labels: 🐛 bug

#3558 feat: release 16
  docker-compose.yml
  package-lock.json
  package.json
  packages/backend/src/app/ee/platform/platform.entity.ts
  packages/backend/src/app/ee/platform/platform.service.ts
  packages/backend/test/integration/cloud/platform/admin-platform.test.ts
  packages/backend/test/integration/cloud/platform/platform.test.ts
  packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts
  packages/ui/core/src/app/app.component.ts
  packages/ui/core/src/locale/messages.pt.xlf
Labels: release, skip-changelog

#3554 fix(flow): flow becomes empty on trigger hook failure
  packages/backend/src/app/flows/flow/flow-service-hooks.ts
  packages/backend/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#3545 fix(LinkedIn): no longer truncates posts at the first opening round brackets
  packages/pieces/framework/package.json
  packages/pieces/framework/src/lib/index.ts
  packages/pieces/linkedin/package.json
  packages/pieces/linkedin/src/lib/actions/create-share-update.ts
  packages/pieces/linkedin/src/lib/common/index.ts
Labels: 🔌 pieces

#3560 fix(approval): test step sample data
  packages/pieces/apitable/package.json
  packages/pieces/apitable/src/index.ts
  packages/pieces/approval/package.json
  packages/pieces/approval/src/lib/actions/wait-for-approval.ts
Labels: 🔌 pieces

#3559 feat(shopify): 25 new actions 2 new triggers
  packages/pieces/shopify/package.json
  packages/pieces/shopify/src/index.ts
  packages/pieces/shopify/src/lib/actions/adjust-inventory-level.ts
  packages/pieces/shopify/src/lib/actions/cancel-order.ts
  packages/pieces/shopify/src/lib/actions/close-order.ts
  packages/pieces/shopify/src/lib/actions/create-collect.ts
  packages/pieces/shopify/src/lib/actions/create-customer.ts
  packages/pieces/shopify/src/lib/actions/create-draft-order.ts
  packages/pieces/shopify/src/lib/actions/create-fulfillment-event.ts
  packages/pieces/shopify/src/lib/actions/create-order.ts
  packages/pieces/shopify/src/lib/actions/create-product.ts
  packages/pieces/shopify/src/lib/actions/create-transaction.ts
  packages/pieces/shopify/src/lib/actions/get-asset.ts
  packages/pieces/shopify/src/lib/actions/get-customer-orders.ts
  packages/pieces/shopify/src/lib/actions/get-customer.ts
  packages/pieces/shopify/src/lib/actions/get-fulfillment.ts
  packages/pieces/shopify/src/lib/actions/get-fulfillments.ts
  packages/pieces/shopify/src/lib/actions/get-locations.ts
  packages/pieces/shopify/src/lib/actions/get-product-variant.ts
  packages/pieces/shopify/src/lib/actions/get-product.ts
  packages/pieces/shopify/src/lib/actions/get-products.ts
  packages/pieces/shopify/src/lib/actions/get-transaction.ts
  packages/pieces/shopify/src/lib/actions/get-transactions.ts
  packages/pieces/shopify/src/lib/actions/update-customer.ts
  packages/pieces/shopify/src/lib/actions/update-order.ts
  packages/pieces/shopify/src/lib/actions/update-product.ts
  packages/pieces/shopify/src/lib/actions/upload-product-image.ts
  packages/pieces/shopify/src/lib/common/index.ts
  packages/pieces/shopify/src/lib/common/register-webhook.ts
  packages/pieces/shopify/src/lib/common/types.ts
  packages/pieces/shopify/src/lib/triggers/new-abandoned-checkout.ts
  packages/pieces/shopify/src/lib/triggers/updated-product.ts
Labels: 🔌 pieces

#3528 feat: filter flows by status
  packages/backend/src/app/flows/flow-version/flow-version.service.ts
  packages/backend/src/app/flows/flow/flow-service-hooks.ts
  packages/backend/src/app/flows/flow/flow.controller.ts
  packages/backend/src/app/flows/flow/flow.service.ts
  packages/backend/src/app/webhooks/webhook-service.ts
  packages/backend/test/helpers/mocks/index.ts
  packages/backend/test/integration/ce/flows/flow.test.ts
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/flows/dto/list-flows-request.ts
  packages/shared/src/lib/flows/flow-version.ts
Labels: ⭐ enhancement, backend

#3567 feat(google-documents): create document based on template / read document action
  packages/pieces/google-docs/package.json
  packages/pieces/google-docs/src/index.ts
  packages/pieces/google-docs/src/lib/actions/create-document-based-on-template.action.ts
  packages/pieces/google-docs/src/lib/actions/read-document.action.ts
  packages/pieces/google-docs/src/lib/common/index.ts
  packages/pieces/google-drive/package.json
  packages/pieces/google-drive/src/index.ts
  packages/pieces/google-drive/src/lib/action/duplicate-file.action.ts
Labels: 🔌 pieces

#3570 fix(schedule): add static dropdown for minutes selection to ensure valid values
  packages/pieces/schedule/package.json
  packages/pieces/schedule/src/lib/triggers/every-x-minutes.trigger.ts
Labels: 🐛 bug, 🔌 pieces

#3574 chore: npm start should work on windows
  package-lock.json
  package.json
  packages/backend/src/app/workers/sandbox/file-sandbox.ts
  packages/engine/src/lib/helper/piece-loader.ts
  tools/setup-dev.js
  turbowatch.ts
Labels: 👨‍💻 dev experience

#3569 feat(google-drive): export as pdf action
  packages/pieces/google-drive/package.json
  packages/pieces/google-drive/src/index.ts
  packages/pieces/google-drive/src/lib/action/save-file-as-pdf.action.ts
Labels: 🔌 pieces

#3575 chore: display human readable error when the file is large
  packages/engine/src/lib/services/files.service.ts
Labels: ⭐ enhancement

#3593 fix(airtable): fix auth error message
  packages/pieces/airtable/package.json
  packages/pieces/airtable/src/index.ts
Labels: 🐛 bug

#3589 feat(robolly): generate image action
  packages/pieces/robolly/.eslintrc.json
  packages/pieces/robolly/README.md
  packages/pieces/robolly/package.json
  packages/pieces/robolly/project.json
  packages/pieces/robolly/src/index.ts
  packages/pieces/robolly/src/lib/actions/generate-image.action.ts
  packages/pieces/robolly/tsconfig.json
  packages/pieces/robolly/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3566 feat: enforce login based on allowed domains
  packages/backend/src/app/authentication/authentication-service/hooks/authentication-service-hooks.ts
  packages/backend/src/app/authentication/authentication-service/hooks/community-service-hooks.ts
  packages/backend/src/app/authentication/authentication-service/index.ts
  packages/backend/src/app/ee/authentication/authentication-service/hooks/authentication-helper.ts
  packages/backend/src/app/ee/authentication/authentication-service/hooks/cloud-authentication-service-hooks.ts
  packages/backend/src/app/ee/authentication/authentication-service/hooks/enterprise-authentication-service-hooks.ts
  packages/backend/src/app/ee/helper/license-validator/index.ts
  packages/backend/src/app/ee/helper/license-validator/license-validator.ts
  packages/backend/src/app/ee/platform/platform.controller.ts
  packages/backend/src/app/ee/platform/platform.entity.ts
  packages/backend/src/app/ee/platform/platform.service.ts
  packages/backend/src/app/helper/error-handler.ts
  packages/backend/test/helpers/mocks/index.ts
  packages/backend/test/integration/cloud/authn/cloud-authn.test.ts
  packages/backend/test/integration/cloud/platform/admin-platform.test.ts
  packages/backend/test/integration/cloud/platform/platform.test.ts
  packages/ee/shared/src/lib/platform/platform.model.ts
  packages/ee/shared/src/lib/platform/platform.request.ts
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 🌟 feature

#3597 chore: release 0.17.0-rc
  package.json
Labels: pre-release

#3599 fix: add external id to list projects / create project endpoint
  docs/openapi.json
  packages/backend/src/app/ee/projects/platform-project-controller.ts
  packages/ee/shared/src/lib/project/project-requests.ts
Labels: 🐛 bug

#3602 fix(backend): db index option for redis connection
  docs/install/configurations/environment-variables.mdx
  packages/backend/src/app/database/redis-connection.ts
  packages/backend/src/app/helper/system/system-prop.ts
Labels: ⭐ enhancement

#3608 fix(google-drive): pass folder ID in duplicate file action
  packages/pieces/google-drive/package.json
  packages/pieces/google-drive/src/lib/action/duplicate-file.action.ts
Labels: 🐛 bug

#3605 feat(flowlu): all actions related to task / opportunity / contact
  packages/pieces/flowlu/.eslintrc.json
  packages/pieces/flowlu/README.md
  packages/pieces/flowlu/package.json
  packages/pieces/flowlu/project.json
  packages/pieces/flowlu/src/index.ts
  packages/pieces/flowlu/src/lib/actions/accounts/create-contact.ts
  packages/pieces/flowlu/src/lib/actions/accounts/create-organization.ts
  packages/pieces/flowlu/src/lib/actions/accounts/delete-contact.ts
  packages/pieces/flowlu/src/lib/actions/accounts/update-contact.ts
  packages/pieces/flowlu/src/lib/actions/opportunities/create-opportunity.ts
  packages/pieces/flowlu/src/lib/actions/opportunities/delete-opportunity.ts
  packages/pieces/flowlu/src/lib/actions/opportunities/update-opportunity.ts
  packages/pieces/flowlu/src/lib/actions/tasks/create-task.ts
  packages/pieces/flowlu/src/lib/actions/tasks/delete-task.ts
  packages/pieces/flowlu/src/lib/actions/tasks/get-task.ts
  packages/pieces/flowlu/src/lib/actions/tasks/update-task.ts
  packages/pieces/flowlu/src/lib/common/client.ts
  packages/pieces/flowlu/src/lib/common/constants.ts
  packages/pieces/flowlu/src/lib/common/index.ts
  packages/pieces/flowlu/src/lib/common/props.ts
  packages/pieces/flowlu/src/lib/common/types.ts
  packages/pieces/flowlu/tsconfig.json
  packages/pieces/flowlu/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3609 feat: Add indicator to currently viewed version in builder, Add option to retry successful runs on latest version.
  packages/ee/ui-platform/src/lib/components/allowed-email-domains-list/allowed-email-domains-list.component.html
  packages/ee/ui-platform/src/lib/components/configure-allowing-email-logins-card/configure-allowing-email-logins-card.component.html
  packages/ee/ui-platform/src/lib/components/configure-confederated-authn-card/configure-confederated-authn-card.component.html
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.html
  packages/ui/common/src/lib/directives/card.directive.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/core/src/assets/img/custom/dashboard/dashboard.svg
  packages/ui/core/src/assets/img/custom/dashboard/home.svg
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/actions/duplicate-step-action/duplicate-step-action.component.ts
  packages/ui/feature-builder-form-controls/src/lib/code-artifact-form-control/code-artifact-control-fullscreen/code-artifact-control-fullscreen.component.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/version-history-button/version-history-button.component.html
  packages/ui/feature-builder-header/src/lib/version-history-button/version-history-button.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/version-history/version-history.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/version-history/version-history.component.ts
  packages/ui/feature-builder-store/src/lib/model/index.ts
  packages/ui/feature-builder-store/src/lib/model/vesrion-historical-status.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-test-steps/src/lib/test-action/test-action.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.html
Labels: ⭐ enhancement

#3598 feat: add getter for `externalProjectId` in engine run context
  packages/backend/src/app/helper/engine-helper.ts
  packages/backend/src/app/project/project-module.ts
  packages/backend/src/app/project/project-worker-controller.ts
  packages/backend/test/integration/ce/flows/project-worker.test.ts
  packages/engine/.test.env
  packages/engine/src/lib/constants.ts
  packages/engine/src/lib/handler/base-executor.ts
  packages/engine/src/lib/handler/branch-executor.ts
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/engine-constants-data.ts
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/src/lib/handler/loop-executor.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/services/connections.service.ts
  packages/engine/src/lib/services/files.service.ts
  packages/engine/src/lib/services/storage.service.ts
  packages/engine/src/main.ts
  packages/engine/test/handler/flow-branching-routing.test.ts
  packages/engine/test/handler/flow-branching.test.ts
  packages/engine/test/handler/flow-codes.test.ts
  packages/engine/test/handler/flow-looping.test.ts
  packages/engine/test/handler/flow-piece.test.ts
  packages/engine/test/handler/flow-rerun.test.ts
  packages/engine/test/handler/flow-with-pause.test.ts
  packages/engine/test/handler/flow-with-response.test.ts
  packages/engine/test/handler/test-helper.ts
  packages/pieces/framework/package.json
  packages/pieces/framework/src/lib/context.ts
  packages/shared/package.json
  packages/shared/src/lib/engine/engine-operation.ts
Labels: ⭐ enhancement, engine

#3612 fix: dashboard loaders on /flows
  packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.ts
Labels: 🐛 bug

#3619 fix(shopify): fix authentication issue
  packages/pieces/shopify/package.json
  packages/pieces/shopify/src/index.ts
Labels: 🔌 pieces

#3616 feat(clickup): Get Task Action / Get Tasks Action / Task Tag Updated Trigger
  packages/pieces/clickup/package.json
  packages/pieces/clickup/src/index.ts
  packages/pieces/clickup/src/lib/actions/tasks/get-task.ts
  packages/pieces/clickup/src/lib/actions/tasks/get-tasks.ts
  packages/pieces/clickup/src/lib/common/index.ts
  packages/pieces/clickup/src/lib/triggers/index.ts
  packages/pieces/clickup/src/lib/triggers/task-tag-updated.ts
Labels: 🔌 pieces

#3621 feat(gmail): add capability to change attachment name for send email
  packages/pieces/gmail/package.json
  packages/pieces/gmail/src/index.ts
  packages/pieces/gmail/src/lib/actions/send-email-action.ts
Labels: 🔌 pieces

#3618 docs: add one-click template on the repocloud
  docs/install/options/overview.mdx
Labels: 📚 documentation

#3595 feat: write code with AI
  docker-compose.yml
  package-lock.json
  package.json
  packages/backend/src/app/app.ts
  packages/backend/src/app/copilot/copilot.controller.ts
  packages/backend/src/app/copilot/copilot.module.ts
  packages/backend/src/app/copilot/copilot.service.ts
  packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/backend/src/app/flags/flag.service.ts
  packages/backend/src/app/helper/system/system-prop.ts
  packages/shared/package.json
  packages/shared/src/lib/flag/flag.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer.service.ts
  packages/ui/feature-builder-right-sidebar/src/lib/ui-feature-builder-right-sidebar.module.ts
Labels: 🌟 feature

#3625 fix(authz): remove project check for list app-credentials endpoint
  .github/workflows/build-cloud-image.yml
  packages/backend/src/app/core/security/authz/project-authz-handler.ts
  packages/backend/src/app/ee/app-credentials/app-credentials.module.ts
  packages/backend/src/app/ee/app-credentials/app-credentials.service.ts
Labels: 🐛 bug, backend

#3627 chore: add telemetry to co-pilot
  .github/workflows/build-cloud-image.yml
  packages/shared/src/lib/common/telemetry.ts
  packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.html
  packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
Labels: skip-changelog

#3629 chore: added google sheets telemetry to code generating prompts
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
Labels: skip-changelog

#3626 feat: release 0.17.0
  .devcontainer/Dockerfile
  Dockerfile
  docker-compose.yml
  docs/install/configurations/environment-variables.mdx
  package-lock.json
  package.json
  packages/backend/src/app/workers/sandbox/file-sandbox.ts
Labels: release, skip-changelog

#3633 chore: fixed wrong date in changelog
  docs/about/changelog.mdx
Labels: 📚 documentation

#3630 chore: use db transactions for "update published flow version" request
  packages/backend/.eslintrc.json
  packages/backend/src/app/core/db/repo-factory.ts
  packages/backend/src/app/core/db/transaction.ts
  packages/backend/src/app/ee/git-repos/git-sync-helper.ts
  packages/backend/src/app/flows/flow-version/flow-version.service.ts
  packages/backend/src/app/flows/flow/flow.repo.ts
  packages/backend/src/app/flows/flow/flow.service.ts
  packages/backend/src/app/helper/engine-helper.ts
  packages/backend/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/backend/src/app/pieces/piece-metadata-service/piece-stats-service.ts
  packages/backend/src/app/webhooks/webhook-controller.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/backend/src/app/workers/flow-worker/queues/redis/redis-queue.ts
Labels: backend, 💻 tech debt

#3642 fix: StoreCodeInsideFlow1697969398200 migration
  packages/backend/src/app/database/migration/common/1697969398200-store-code-inside-flow.ts
Labels: 🐛 bug

#3641 feat: add .nvmrc file
  .nvmrc
Labels: 💻 tech debt

#3644 feat: prioritize webhook sync calls
  package-lock.json
  package.json
  packages/backend/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/backend/src/app/workers/flow-worker/queues/queue.ts
  packages/backend/src/app/workers/flow-worker/queues/redis/redis-queue.ts
Labels: ⭐ enhancement

#3631 feat(robolly): add properties for custom modification
  packages/pieces/robolly/package.json
  packages/pieces/robolly/src/lib/actions/generate-image.action.ts
Labels: 🔌 pieces

#3622 feat(frame.io): Asset Created Trigger / Project Created Trigger / Comment Created Trigger
  packages/pieces/frame/.eslintrc.json
  packages/pieces/frame/README.md
  packages/pieces/frame/package.json
  packages/pieces/frame/project.json
  packages/pieces/frame/src/index.ts
  packages/pieces/frame/src/lib/triggers/index.ts
  packages/pieces/frame/src/lib/triggers/register-trigger.ts
  packages/pieces/frame/tsconfig.json
  packages/pieces/frame/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3647 fix(flowlu): make name/title field optional in update actions
  packages/pieces/flowlu/package.json
  packages/pieces/flowlu/src/lib/actions/accounts/update-contact.ts
  packages/pieces/flowlu/src/lib/actions/opportunities/create-opportunity.ts
  packages/pieces/flowlu/src/lib/actions/opportunities/update-opportunity.ts
  packages/pieces/flowlu/src/lib/actions/tasks/create-task.ts
  packages/pieces/flowlu/src/lib/actions/tasks/update-task.ts
  packages/pieces/flowlu/src/lib/common/props.ts
  packages/pieces/flowlu/src/lib/common/types.ts
Labels: 🔌 pieces

#3646 feat(baserow): all actions related to table row
  packages/pieces/baserow/.eslintrc.json
  packages/pieces/baserow/README.md
  packages/pieces/baserow/package.json
  packages/pieces/baserow/project.json
  packages/pieces/baserow/src/index.ts
  packages/pieces/baserow/src/lib/actions/create-row.ts
  packages/pieces/baserow/src/lib/actions/delete-row.ts
  packages/pieces/baserow/src/lib/actions/get-row.ts
  packages/pieces/baserow/src/lib/actions/list-rows.ts
  packages/pieces/baserow/src/lib/actions/update-row.ts
  packages/pieces/baserow/src/lib/common/client.ts
  packages/pieces/baserow/src/lib/common/constants.ts
  packages/pieces/baserow/src/lib/common/index.ts
  packages/pieces/baserow/src/lib/common/types.ts
  packages/pieces/baserow/tsconfig.json
  packages/pieces/baserow/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3651 docs: add update flow documentation
  docs/endpoints/flows/update.mdx
  docs/mint.json
  docs/openapi.json
  packages/backend/src/app/flows/flow/flow.controller.ts
  packages/shared/src/lib/flows/flow-operations.ts
Labels: 📚 documentation

#3650 fix: add instructions for google & github sso
  packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/ee/ui-platform/src/lib/components/configure-confederated-authn-card/configure-confederated-authn-card.component.html
  packages/ee/ui-platform/src/lib/components/dialogs/enable-federated-authn-provider-dialog/enable-federated-authn-provider-dialog.component.html
  packages/ee/ui-platform/src/lib/components/dialogs/enable-federated-authn-provider-dialog/enable-federated-authn-provider-dialog.component.ts
Labels: 🐛 bug

#3648 feat(formbricks): Response Created, Response Updated, Response Finished triggers
  packages/pieces/formbricks/.eslintrc.json
  packages/pieces/formbricks/README.md
  packages/pieces/formbricks/package.json
  packages/pieces/formbricks/project.json
  packages/pieces/formbricks/src/index.ts
  packages/pieces/formbricks/src/lib/triggers/index.ts
  packages/pieces/formbricks/src/lib/triggers/register.ts
  packages/pieces/formbricks/tsconfig.json
  packages/pieces/formbricks/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3660 fix(facebook): list pages
  packages/pieces/facebook-pages/package.json
  packages/pieces/facebook-pages/src/index.ts
  packages/pieces/instagram-business/package.json
  packages/pieces/instagram-business/src/lib/common/index.ts
Labels: 🔌 pieces

#3658 fix: Show failed iteration in case the failed step is within a loop in runs/test
  package-lock.json
  packages/shared/src/lib/flow-run/execution/step-output.ts
  packages/ui/common/src/lib/components/json-view/json-view.component.html
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-connection/big-add-button/big-add-button.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/run-details/run-details.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/iteration-accordion/iteration-accordion.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
Labels: ⭐ enhancement, frontend

#3657 feat(clickup): delete task action, get tasks with ability to filter by a space, a list or a workspace
  packages/pieces/clickup/package.json
  packages/pieces/clickup/src/index.ts
  packages/pieces/clickup/src/lib/actions/tasks/delete-task.ts
  packages/pieces/clickup/src/lib/actions/tasks/get-tasks.ts
  packages/pieces/clickup/src/lib/common/index.ts
Labels: 🔌 pieces

#3668 fix(woocommerce): triggers saving issue
  packages/pieces/woocommerce/package.json
  packages/pieces/woocommerce/src/index.ts
  packages/pieces/woocommerce/src/lib/common/index.ts
  packages/pieces/woocommerce/src/lib/triggers/coupon.ts
  packages/pieces/woocommerce/src/lib/triggers/customer.ts
  packages/pieces/woocommerce/src/lib/triggers/index.ts
  packages/pieces/woocommerce/src/lib/triggers/line-item-in-order.ts
  packages/pieces/woocommerce/src/lib/triggers/order.ts
  packages/pieces/woocommerce/src/lib/triggers/product.ts
  packages/pieces/woocommerce/src/lib/triggers/register-trigger.ts
Labels: 🔌 pieces

#3666 feat(google-drive): add permission action / remove permission action
  packages/pieces/google-drive/package.json
  packages/pieces/google-drive/src/index.ts
  packages/pieces/google-drive/src/lib/action/add-permission.action.ts
  packages/pieces/google-drive/src/lib/action/delete-permission.action.ts
Labels: 🔌 pieces

#3669 chore: view teams in community
  docs/_snippets/enterprise-feature.mdx
  docs/mint.json
  docs/resources/screenshots/team-screenshot.png
  docs/team/overview.mdx
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
  packages/ee/project-members/src/lib/project-members-table/project-members.datasource.ts
  packages/ui/common/src/index.ts
  packages/ui/common/src/lib/components/ap-button/ap-button.component.html
  packages/ui/common/src/lib/components/is-feature-enabled-base/is-feature-enabled-base.component.ts
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.html
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.ts
  packages/ui/common/src/lib/resolvers/index.ts
  packages/ui/common/src/lib/resolvers/is-feature-flag-enabled.resolver.ts
  packages/ui/core/src/app/app.component.ts
  packages/ui/core/src/assets/img/custom/info.svg
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
  packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.html
Labels: 🧹 clean up

#3670 fix: sandbox error on windows
  packages/backend/src/app/workers/sandbox/file-sandbox.ts
Labels: 👨‍💻 dev experience

#3673 feat: filter runs by flow
  packages/ui/common/src/lib/service/instance-run.service.ts
  packages/ui/common/src/lib/utils/tables.utils.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
Labels: 🌟 feature

#3674 fix(copilot): code writer should use import for packages
  packages/backend/src/app/copilot/copilot.service.ts
Labels: 🐛 bug

#3677 feat: release 0.18.0-rc.1
  package.json
Labels: pre-release

#3678 fix: database migration
  package-lock.json
  packages/backend/src/app/database/migration/common/1696245170061-add-piece-type-and-package-type-to-flow-version.ts
  packages/backend/src/app/database/migration/common/1696245170062-add-piece-type-and-package-type-to-flow-template.ts
  packages/backend/src/app/database/migration/common/1697969398200-store-code-inside-flow.ts
  packages/backend/src/app/database/migration/postgres/1674788714498-FlowAndFileProjectId.ts
  packages/backend/src/app/database/migration/postgres/1676649852890-remove-store-action.ts
  packages/backend/src/app/database/migration/postgres/1677521257188-add-version-to-piece-steps.ts
  packages/backend/src/app/database/migration/postgres/1678928503715-bump-fix-piece-versions.ts
  packages/backend/src/app/database/migration/postgres/1679014156667-migrate-schedule.ts
  packages/backend/src/app/database/migration/postgres/1681107443963-AddInputUiInfo.ts
  packages/backend/src/app/database/migration/postgres/1683898241599-ChangeVariableSyntax.ts
  packages/backend/src/app/database/migration/postgres/1686138629812-unifyPieceName.ts
Labels: 💻 tech debt

#3679 fix: handshake metadata
  packages/backend/src/app/ee/pieces/admin-piece-requests.ee.ts
  packages/pieces/framework/src/lib/trigger/trigger.ts
Labels: skip-changelog

#3680 fix: monday & woocommerce & onfleet triggers
  packages/pieces/monday/package.json
  packages/pieces/onfleet/package.json
  packages/pieces/woocommerce/package.json
Labels: 🔌 pieces

#3675 feat(clickup): set custom fields action / get custom fields action
  packages/pieces/clickup/package.json
  packages/pieces/clickup/src/index.ts
  packages/pieces/clickup/src/lib/actions/custom-fields/get-accessible-custom-fields.ts
  packages/pieces/clickup/src/lib/actions/custom-fields/set-custom-fields-value.ts
  packages/pieces/clickup/src/lib/common/index.ts
Labels: 🔌 pieces

#3662 feat: continue on failure and retry on failure
  .github/workflows/build-cloud-image.yml
  packages/engine/package.json
  packages/engine/src/lib/handler/base-executor.ts
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/error-handling.ts
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/engine/test/handler/test-helper.ts
  packages/engine/test/helper/error-handling.test.ts
  packages/pieces/framework/package.json
  packages/pieces/framework/src/lib/action/action.ts
  packages/pieces/framework/src/lib/piece-metadata.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/actions/action.ts
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.scss
  packages/ui/feature-builder-form-controls/src/lib/action-error-handling-form-control/action-error-handling-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-step-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/input-forms-schema.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-action-input-form/piece-action-input-form.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
Labels: 🌟 feature

#3681 fix(embed): prefix should be included in routing
  packages/ee/components/src/lib/iframe-listener/iframe-listener.component.ts
  packages/ee/embed-sdk/src/index.ts
  packages/ui/common/src/lib/service/embedding.service.ts
Labels: 🐛 bug

#3683 feat: release 0.18.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/ui/core/src/locale/messages.pt.xlf
Labels: release

#3690 fix(engine): validate auth is no longer broken in sandboxed mode
  packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
Labels: 🐛 bug

#3692 feat: release 0.18.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#3694 fix: remove unique app name on app credentials
  packages/backend/src/app/database/migration/postgres/1705586178452-RemoveUniqueonAppNameAppCredentials.ts
  packages/backend/src/app/database/postgres-connection.ts
  packages/backend/src/app/ee/app-credentials/app-credentials.entity.ts
  packages/backend/src/app/ee/app-credentials/app-credentials.service.ts
  packages/ee/shared/src/lib/product-embed/app-credentials/app-credentials-requests.ts
Labels: skip-changelog

#3693 feat: arbitrary http request action
  docs/developers/piece-reference/custom-api-calls.mdx
  packages/pieces/common/package.json
  packages/pieces/common/src/lib/helpers/index.ts
  packages/pieces/openai/package.json
  packages/pieces/openai/src/index.ts
Labels: 🌟 feature

#3688 feat(clickup): add filter tasks based on criteria
  packages/pieces/clickup/package.json
  packages/pieces/clickup/src/index.ts
  packages/pieces/clickup/src/lib/actions/custom-fields/set-custom-fields-value.ts
  packages/pieces/clickup/src/lib/actions/tasks/get-tasks.ts
  packages/pieces/clickup/src/lib/common/index.ts
Labels: 🔌 pieces

#3667 feat(engine): use V8's Isolate to sandbox code piece to work with unprivileged docker
  .github/workflows/build-cloud-image.yml
  Dockerfile
  ap-base.dockerfile
  docker-compose.dev.yml
  package-lock.json
  package.json
  packages/backend/src/app/helper/system/system-prop.ts
  packages/backend/src/app/helper/system/system.ts
  packages/backend/src/app/workers/engine/engine-installer.ts
  packages/backend/src/app/workers/sandbox/file-sandbox.ts
  packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
  packages/engine/jest.config.ts
  packages/engine/src/lib/handler/code/code-executor-common.ts
  packages/engine/src/lib/handler/code/code-executor-sandbox.ts
  packages/engine/src/lib/handler/code/code-executor.ts
  packages/engine/src/lib/handler/code/isolate-code-executor-sandbox.ts
  packages/engine/src/lib/handler/code/no-op-code-executor-sandbox.ts
  packages/engine/src/lib/handler/context/test-execution-context.ts
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/main.ts
  packages/engine/test/handler/flow-codes.test.ts
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/engine/test/helper/logging-utils.test.ts
  packages/engine/test/services/variable-service.test.ts
  packages/engine/webpack.config.js
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/engine/code-executor-sandbox-type.ts
  packages/shared/src/lib/engine/index.ts
  packages/shared/src/lib/flow-run/execution/step-output.ts
  packages/ui/feature-builder-left-sidebar/src/lib/run-details/steps-results-list/step-result.component.ts
Labels: 🌟 feature

#3696 fix: show projects of newly invited users
  .github/workflows/release-pieces.yml
  .github/workflows/validate-publishable-packages.yml
  packages/backend/src/app/ee/managed-authn/managed-authn-service.ts
  packages/backend/src/app/ee/project-members/project-member.controller.ts
  packages/backend/src/app/ee/project-members/project-member.service.ts
  tools/scripts/utils/piece-script-utils.ts
  tools/scripts/validate-publishable-packages.ts
Labels: 🐛 bug

#3697 fix: isolate mode with local file pieces
  packages/backend/src/app/flows/common/piece-manager/local-piece-manager.ts
  packages/backend/src/app/helper/package-manager.ts
  packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
Labels: 👨‍💻 dev-experience

#3686 feat(image-helper): convert image to base64 action
  packages/pieces/community/image-helper/.eslintrc.json
  packages/pieces/community/image-helper/README.md
  packages/pieces/community/image-helper/package.json
  packages/pieces/community/image-helper/project.json
  packages/pieces/community/image-helper/src/index.ts
  packages/pieces/community/image-helper/src/lib/actions/image-to-base64.action.ts
  packages/pieces/community/image-helper/tsconfig.json
  packages/pieces/community/image-helper/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🧪 needs-testing

#3635 feat(google-drive): search for file / folder action
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/index.ts
  packages/pieces/community/google-drive/src/lib/action/list-files.action.ts
  packages/pieces/community/google-drive/src/lib/action/read-file.ts
  packages/pieces/community/google-drive/src/lib/action/search-folder.action.ts
Labels: 🔌 pieces

#3689 feat(cli): create piece command
  package-lock.json
  package.json
  packages/cli/.eslintrc.json
  packages/cli/README.md
  packages/cli/jest.config.ts
  packages/cli/package.json
  packages/cli/project.json
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/utils/exec.ts
  packages/cli/src/lib/utils/files.ts
  packages/cli/tsconfig.json
  packages/cli/tsconfig.lib.json
  packages/cli/tsconfig.spec.json
  tools/scripts/pieces/generate-new-piece.ts
  tsconfig.base.json
Labels: 👨‍💻 dev-experience

#3623 feat(cli): add create-action script
  package.json
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/create-action.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/utils/files.ts
  packages/cli/src/lib/utils/piece-utils.ts
Labels: 👨‍💻 dev-experience

#3699 fix: specify maxRetriesPerRequest to null
  packages/backend/src/app/database/redis-connection.ts
Labels: 🐛 bug

#3701 feat(google-drive): get file or folder by id action
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/index.ts
  packages/pieces/community/google-drive/src/lib/action/get-file-by-id.ts
Labels: 🔌 pieces

#3700 feat: release 0.18.2
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#3702 fix: google drive
  packages/pieces/community/google-drive/src/index.ts
Labels: skip-changelog

#3705 feat(google-drive): enrich search for file or folder with more options
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/index.ts
  packages/pieces/community/google-drive/src/lib/action/search-folder-or-file.action.ts
Labels: 🔌 pieces

#3704 feat(cli): create trigger command
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/commands/create-trigger.ts
Labels: 👨‍💻 dev-experience

#3707 docs: fixed typo in local.mdx
  docs/developers/development-setup/local.mdx
Labels: 📚 documentation

#3715 chore: add search input for flows filter in runs table
  packages/ui/common/src/lib/components/pagination/ap-paginator.component.ts
  packages/ui/common/src/lib/pipe/dropdown-search.pipe.ts
  packages/ui/common/src/lib/pipe/index.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/pipes/auth-configs.pipe.ts
  packages/ui/feature-builder-form-controls/src/lib/pipes/dropdown-initial-value.pipe.ts
  packages/ui/feature-builder-form-controls/src/lib/pipes/is-selected.pipe.ts
  packages/ui/feature-builder-form-controls/src/lib/pipes/selected-auth-config.pipe.ts
  packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
Labels: ⭐ enhancement, frontend

#3714 refactor(engine): sandbox variable substitution
  package-lock.json
  package.json
  packages/backend/src/app/flows/common/piece-manager/piece-manager.ts
  packages/backend/src/app/helper/system/system-prop.ts
  packages/backend/src/app/helper/system/system.ts
  packages/backend/src/app/workers/sandbox/cache/cached-sandbox.ts
  packages/backend/src/app/workers/sandbox/file-sandbox.ts
  packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
  packages/engine/jest.config.ts
  packages/engine/src/lib/core/code/code-sandbox-common.ts
  packages/engine/src/lib/core/code/code-sandbox.ts
  packages/engine/src/lib/core/code/no-op-code-sandbox.ts
  packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/code/code-executor-common.ts
  packages/engine/src/lib/handler/code/code-executor-sandbox.ts
  packages/engine/src/lib/handler/code/isolate-code-executor-sandbox.ts
  packages/engine/src/lib/handler/code/no-op-code-executor-sandbox.ts
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/src/lib/services/variable-service.ts
  packages/engine/test/handler/flow-codes.test.ts
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/shared/package.json
  packages/shared/src/lib/engine/code-executor-sandbox-type.ts
  packages/shared/src/lib/engine/code-sandbox-type.ts
  packages/shared/src/lib/engine/index.ts
Labels: ⭐ enhancement, 🔒 security, engine

#3732 docs: update platform docs
  docs/_snippets/enterprise-feature.mdx
  docs/admin-console/appearance.mdx
  docs/admin-console/custom-domain.mdx
  docs/admin-console/customize-emails.mdx
  docs/admin-console/manage-oauth2.mdx
  docs/admin-console/manage-pieces.mdx
  docs/admin-console/manage-projects.mdx
  docs/admin-console/manage-templates.mdx
  docs/admin-console/overview.mdx
  docs/embedding/embed-builder/embed-iframe.mdx
  docs/install/options/overview.mdx
  docs/mint.json
Labels: 📚 documentation

#3733 fix(airtable): fix multilink field property type
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/lib/common/models.ts
Labels: 🔌 pieces

#3724 fix(apitable): new record trigger / data source is now dropdown
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/index.ts
  packages/pieces/community/apitable/src/lib/actions/create-record.ts
  packages/pieces/community/apitable/src/lib/actions/find-record.ts
  packages/pieces/community/apitable/src/lib/actions/update-record.ts
  packages/pieces/community/apitable/src/lib/common/client.ts
  packages/pieces/community/apitable/src/lib/common/constants.ts
  packages/pieces/community/apitable/src/lib/common/index.ts
  packages/pieces/community/apitable/src/lib/triggers/new-record.ts
Labels: 🔌 pieces

#3737 fix: resolve variables in dynamic props
  packages/backend/src/app/pieces/base-piece-module.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/main.ts
  packages/shared/package.json
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
Labels: 🐛 bug

#3736 feat: Add custom API calls for Google Sheets, Jira Cloud, LeadConnector, OpenAI, Shopify, Discord and Slack
  docs/developers/piece-reference/custom-api-calls.mdx
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/helpers/index.ts
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/index.ts
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added.ts
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/index.ts
  packages/pieces/community/lead-connector/package.json
  packages/pieces/community/lead-connector/src/index.ts
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/shopify/package.json
  packages/pieces/community/shopify/src/index.ts
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
Labels: 🌟 feature

#2960 feat(piece-framework): support array of objects
  .devcontainer/devcontainer.json
  packages/ee/components/src/lib/share-flow-template-dialog/share-flow-template-dialog.component.html
  packages/pieces/community/framework/src/lib/property/input/array-property.ts
  packages/pieces/community/hackernews/src/lib/actions/top-stories-in-hacker-news.ts
  packages/pieces/framework/src/lib/property/array-prop.ts
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.scss
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
  packages/ui/feature-builder-form-controls/src/lib/shared.ts
Labels: 🛠️ piece-framework

#3739 feat: add external id to execute property
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/main.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
Labels: 🛠️ piece-framework

#3740 docs: fix broken links. Changes to links to point to new community folder
  docs/developers/piece-reference/examples.mdx
Labels: 📚 documentation

#3741 feat(crypto): hash to text action / generate random password action
  packages/pieces/community/crypto/.eslintrc.json
  packages/pieces/community/crypto/README.md
  packages/pieces/community/crypto/package.json
  packages/pieces/community/crypto/project.json
  packages/pieces/community/crypto/src/index.ts
  packages/pieces/community/crypto/src/lib/actions/generate-password.ts
  packages/pieces/community/crypto/src/lib/actions/hash-text.ts
  packages/pieces/community/crypto/tsconfig.json
  packages/pieces/community/crypto/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#3745 feat: set base url as default value in custom api call action
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/helpers/index.ts
  packages/pieces/community/discord/package.json
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/slack/package.json
Labels: ⭐ enhancement

#3729 feat(mautic): new contact,contcat updated, contact channel/company subscription change triggers
  packages/pieces/community/mautic/package.json
  packages/pieces/community/mautic/src/index.ts
  packages/pieces/community/mautic/src/lib/triggers/index.ts
Labels: 🔌 pieces

#3750 feat: add custom api call for clickup
  packages/pieces/community/clickup/package.json
  packages/pieces/community/clickup/src/index.ts
Labels: 🔌 pieces

#3751 fix: bump clickup
  packages/pieces/community/clickup/package.json
  packages/pieces/community/clickup/src/index.ts
Labels: skip-changelog

#3752 feat(clickup): list tasks and list time entries action
  packages/pieces/community/clickup/package.json
  packages/pieces/community/clickup/src/index.ts
  packages/pieces/community/clickup/src/lib/actions/tasks/filter-workspace-tasks.ts
  packages/pieces/community/clickup/src/lib/actions/tasks/filter-workspace-time-entries.ts
Labels: 🔌 pieces

#3754 fix(matomo): Ensure compatibility with v5 API
  packages/pieces/community/matomo/package.json
  packages/pieces/community/matomo/src/lib/api.ts
Labels: 🔌 pieces

#3756 feat: add user identity to the commit on push / multiple project support in same repo / push single flow / document pull api
  docs/endpoints/git-repos/pull.mdx
  docs/endpoints/git-repos/schema.mdx
  docs/mint.json
  docs/openapi.json
  packages/backend/src/app/app.ts
  packages/backend/src/app/ee/git-repos/git-repo.controller.ts
  packages/backend/src/app/ee/git-repos/git-repo.service.ts
  packages/backend/src/app/flows/flow-version/flow-version-side-effects.ts
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/ee/ui-platform/src/lib/platform.resolver.ts
  packages/ui/common/src/lib/components/user-avatar/user-avatar.component.html
  packages/ui/common/src/lib/store/common-state.model.ts
  packages/ui/common/src/lib/store/project/project.action.ts
  packages/ui/common/src/lib/store/project/project.effects.ts
  packages/ui/common/src/lib/store/project/project.reducer.ts
  packages/ui/common/src/lib/store/project/project.selector.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/core/src/assets/img/custom/sync.svg
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/ui-feature-builder-header.module.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/push-dialog/push-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.ts
  packages/ui/feature-dashboard/src/lib/resolvers/repo.resolver.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
  packages/ui/feature-git-sync/.eslintrc.json
  packages/ui/feature-git-sync/README.md
  packages/ui/feature-git-sync/jest.config.ts
  packages/ui/feature-git-sync/ng-package.json
  packages/ui/feature-git-sync/package.json
  packages/ui/feature-git-sync/project.json
  packages/ui/feature-git-sync/src/index.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/pull-from-git-dialog/pull-from-git-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/pull-from-git-dialog/pull-from-git-dialog.component.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/push-to-git-dialog/push-to-git-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/push-to-git-dialog/push-to-git-dialog.component.ts
  packages/ui/feature-git-sync/src/lib/components/push-flow-to-git-button/push-flow-to-git-button.component.html
  packages/ui/feature-git-sync/src/lib/components/push-flow-to-git-button/push-flow-to-git-button.component.ts
  packages/ui/feature-git-sync/src/lib/services/sync-project.service.ts
  packages/ui/feature-git-sync/src/lib/ui-feature-git-sync.module.ts
  packages/ui/feature-git-sync/src/test-setup.ts
  packages/ui/feature-git-sync/tsconfig.json
  packages/ui/feature-git-sync/tsconfig.lib.json
  packages/ui/feature-git-sync/tsconfig.lib.prod.json
  packages/ui/feature-git-sync/tsconfig.spec.json
  tsconfig.base.json
Labels: 🌟 feature

#3764 feat: release 0.19.0-rc.1
  package.json
Labels: pre-release

#3765 fix: show edit project button
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
Labels: 🐛 bug

#3766 chore: pre release 0.19.0-rc.2
  package.json
Labels: pre-release

#3769 feat: bump to 19 rc3
  package.json
Labels: pre-release

#3757 feat(google-calendar): update event / delete event / custom api call action
  packages/pieces/community/google-calendar/package.json
  packages/pieces/community/google-calendar/src/index.ts
  packages/pieces/community/google-calendar/src/lib/actions/delete-event.action.ts
  packages/pieces/community/google-calendar/src/lib/actions/update-event.ation.ts
Labels: 🔌 pieces

#3762 refactor(backend): conditionally bind dirs for isolate engine sandbox
  packages/backend/src/app/flows/flow-version/flow-version-side-effects.ts
  packages/backend/src/app/workers/sandbox/isolate-sandbox.ts
Labels: backend, 🔒 security

#3760 fix(storage-piece): "Key <key> is not an array" error when using add-to-list action
  packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
Labels: 🔌 pieces

#3725 feat: realtime flow run feedback via websockets
  package-lock.json
  package.json
  packages/backend/src/app/app.ts
  packages/backend/src/app/flows/flow-run/flow-run-controller.ts
  packages/backend/src/app/flows/flow-run/flow-run-service.ts
  packages/backend/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/backend/src/app/webhooks/webhook-service.ts
  packages/backend/src/app/websockets/websockets.service.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/backend/src/app/workers/flow-worker/job-data.ts
  packages/backend/types/fastify.d.ts
  packages/ui/core/nginx.standard.conf
  packages/ui/core/src/app/app.component.ts
  packages/ui/core/src/app/app.module.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.html
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
Labels: 🌟 feature

#3755 feat(pieces-framework): add auto renew webhook
  packages/backend/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/backend/src/app/flows/flow/flow-service-hooks.ts
  packages/backend/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/backend/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/backend/src/app/flows/trigger/hooks/execute-trigger-hooks.ts
  packages/backend/src/app/flows/trigger/hooks/handshake-trigger.hook.ts
  packages/backend/src/app/flows/trigger/hooks/renew-trigger-hook.ts
  packages/backend/src/app/flows/trigger/hooks/trigger-utils.ts
  packages/backend/src/app/flows/trigger/index.ts
  packages/backend/src/app/helper/trigger-utils.ts
  packages/backend/src/app/webhooks/webhook-service.ts
  packages/backend/src/app/webhooks/webhook-simulation/webhook-simulation-side-effects.ts
  packages/backend/src/app/workers/flow-worker/flow-queue-consumer.ts
  packages/backend/src/app/workers/flow-worker/flow-worker.ts
  packages/backend/src/app/workers/flow-worker/job-data.ts
  packages/backend/src/app/workers/flow-worker/queues/memory/memory-queue.ts
  packages/backend/src/app/workers/flow-worker/queues/queue.ts
  packages/backend/src/app/workers/flow-worker/queues/redis/redis-queue.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/trigger/trigger.ts
  packages/shared/src/lib/engine/engine-operation.ts
Labels: 🛠️ piece-framework

#3773 feat: show previous runs inside the builder, and make tables restore viewed data depending on parameters in the URL
  packages/ui/common/src/lib/components/pagination/ap-paginator.component.html
  packages/ui/common/src/lib/components/pagination/ap-paginator.component.ts
  packages/ui/common/src/lib/utils/tables.utils.ts
  packages/ui/core/src/assets/scss/utlis.scss
  packages/ui/feature-builder-canvas/src/lib/components/widgets/incomplete-steps-widget/incomplete-steps-widget.component.html
  packages/ui/feature-builder-canvas/src/lib/components/widgets/incomplete-steps-widget/incomplete-steps-widget.component.ts
  packages/ui/feature-builder-header/src/index.ts
  packages/ui/feature-builder-header/src/lib/components/feedback/support.component.html
  packages/ui/feature-builder-header/src/lib/components/feedback/support.component.ts
  packages/ui/feature-builder-header/src/lib/components/publish-button/publish-button.component.html
  packages/ui/feature-builder-header/src/lib/components/publish-button/publish-button.component.scss
  packages/ui/feature-builder-header/src/lib/components/publish-button/publish-button.component.ts
  packages/ui/feature-builder-header/src/lib/components/runs-button/runs-button.component.html
  packages/ui/feature-builder-header/src/lib/components/runs-button/runs-button.component.ts
  packages/ui/feature-builder-header/src/lib/components/toggle-instance-state/toggle-instance-state.component.html
  packages/ui/feature-builder-header/src/lib/components/toggle-instance-state/toggle-instance-state.component.ts
  packages/ui/feature-builder-header/src/lib/components/version-history-button/version-history-button.component.html
  packages/ui/feature-builder-header/src/lib/components/version-history-button/version-history-button.component.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/ui-feature-builder-header.module.ts
  packages/ui/feature-builder-header/src/lib/version-history-button/version-history-button.component.html
  packages/ui/feature-builder-left-sidebar/src/index.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/dialogs/use-as-draft-confirmation-dialog/use-as-draft-confirmation-dialog.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/dialogs/use-as-draft-confirmation-dialog/use-as-draft-confirmation-dialog.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/iteration-details.service.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/iteration-accordion/iteration-accordion.component.css
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/iteration-accordion/iteration-accordion.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/iteration-accordion/iteration-accordion.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.scss
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/steps-results-list/step-result.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/flow-left-sidebar.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/flow-left-sidebar.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/ui-feature-builder-left-sidebar.module.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.scss
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-list/step-type-list.component.ts
  packages/ui/feature-builder-store/src/lib/model/enums/left-side-bar-type.enum.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.action.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.reducer.ts
  packages/ui/feature-builder-store/src/lib/store/builder/viewmode/view-mode.reducer.ts
  packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.ts
  packages/ui/feature-dashboard/src/lib/pages/connections-table/connections-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
Labels: 🌟 feature

#3778 feat: enhanced the user experience for code writer with revamped interface
  packages/ui/common/src/lib/components/ap-button/ap-button.component.scss
  packages/ui/common/src/lib/service/index.ts
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/core/src/assets/scss/prism-theme.scss
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/ui-feature-builder-right-sidebar.module.ts
Labels: ⭐ enhancement, frontend

#3770 chore: smooth the cobranding
  .devcontainer/devcontainer.json
  packages/backend/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/ui/common/src/lib/components/powered-by-activepieces/powered-by-activepieces.component.html
  packages/ui/common/src/lib/store/project/project.effects.ts
  packages/ui/core/src/assets/img/custom/full-logo.svg
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.html
Labels: 🤷‍♂️ design debt, 🧹 clean up

#3782 feat: while viewing a run, users have the choice to navigate to the flow itself
  packages/ui/core/src/assets/img/custom/enter-run.svg
  packages/ui/core/src/assets/img/custom/exit-run.svg
  packages/ui/feature-builder-header/src/index.ts
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.html
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.scss
  packages/ui/feature-builder-header/src/lib/components/publish-or-edit-flow-button/publish-or-edit-flow-button.component.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/ui-feature-builder-header.module.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.html
  packages/ui/feature-builder-left-sidebar/src/lib/components/runs-list/runs-list.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/version-history/version-history.component.html
  packages/ui/feature-builder-store/src/lib/store/builder/viewmode/view-mode.reducer.ts
Labels: ⭐ enhancement, frontend

#3781 feat: added ability to move flow to folder from inside the builder
  packages/ui/common/src/lib/resolvers/connections.resolver.ts
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
  packages/ui/feature-builder-store/src/lib/model/flow-state.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.action.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.reducer.ts
  packages/ui/feature-dashboard/src/index.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/move-flow-to-folder-dialog/move-flow-to-folder-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-folder-dialog/new-folder-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-folder-dialog/new-folder-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/rename-folder-dialog/rename-folder-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard.routing.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/folders-list/folders-list.component.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
  packages/ui/feature-flow-builder/src/lib/flow-builder.routing.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
  packages/ui/feature-flow-builder/src/lib/resolvers/builder-route-data.ts
  packages/ui/feature-flow-builder/src/lib/resolvers/flow.resolver.ts
  packages/ui/feature-flow-builder/src/lib/resolvers/instance-run.resolver.ts
  packages/ui/feature-flow-builder/src/lib/ui-feature-flow-builder.module.ts
  packages/ui/feature-folders-store/.eslintrc.json
  packages/ui/feature-folders-store/README.md
  packages/ui/feature-folders-store/ng-package.json
  packages/ui/feature-folders-store/package.json
  packages/ui/feature-folders-store/project.json
  packages/ui/feature-folders-store/src/index.ts
  packages/ui/feature-folders-store/src/lib/components/dialogs/move-flow-to-folder-dialog/move-flow-to-folder-dialog.component.html
  packages/ui/feature-folders-store/src/lib/components/dialogs/move-flow-to-folder-dialog/move-flow-to-folder-dialog.component.ts
  packages/ui/feature-folders-store/src/lib/resolvers/folders.resolver.ts
  packages/ui/feature-folders-store/src/lib/store/folders.actions.ts
  packages/ui/feature-folders-store/src/lib/store/folders.effects.ts
  packages/ui/feature-folders-store/src/lib/store/folders.reducer.ts
  packages/ui/feature-folders-store/src/lib/store/folders.selectors.ts
  packages/ui/feature-folders-store/src/lib/ui-feature-folders-store.module.ts
  packages/ui/feature-folders-store/tsconfig.json
  packages/ui/feature-folders-store/tsconfig.lib.json
  packages/ui/feature-folders-store/tsconfig.lib.prod.json
  tsconfig.base.json
Labels: ⭐ enhancement, frontend

#3784 fix: provide updated token each time on web socket connect
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/common/src/lib/service/index.ts
  packages/ui/common/src/lib/service/websocket.service.ts
  packages/ui/core/src/app/app.module.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
Labels: 🐛 bug

#3763 feat: authn rate limit
  package-lock.json
  package.json
  packages/backend/src/app/app.ts
  packages/backend/src/app/authentication/authentication.controller.ts
  packages/backend/src/app/core/security/rate-limit.ts
  packages/backend/src/app/database/redis-connection.ts
  packages/backend/src/app/helper/system/system-prop.ts
  packages/backend/src/app/helper/system/system.ts
Labels: 💻 tech debt, 🔒 security

#3783 feat: allow to sync custom pieces folder to platform
  package.json
  packages/backend/src/app/ee/pieces/platform-piece-module.ts
  packages/backend/src/app/helper/error-handler.ts
  packages/backend/src/app/pieces/base-piece-module.ts
  packages/backend/src/app/pieces/piece-service/index.ts
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/sync-pieces.ts
  packages/cli/src/lib/utils/piece-utils.ts
Labels: dev-experience

#3788 fix: notify on flow run fail toggle wasn't being turned back on
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
Labels: 🐛 bug

#3780 fix: merge the docker into single image
  Dockerfile
  ap-base.dockerfile
Labels: 🧹 clean up
