Repository activepieces/activepieces, pull requests merged in 2024-03, with the labels that each got.

#4064 feat(git-sync): add dryrun + support publishing flow
  docs/endpoints/git-repos/pull.mdx
  docs/openapi.json
  docs/operations/git-sync.mdx
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/ee/git-repos/git-repo.controller.ts
  packages/server/api/src/app/ee/git-repos/git-repo.entity.ts
  packages/server/api/src/app/ee/git-repos/git-repo.module.ts
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/src/app/ee/git-repos/git-sync-helper.ts
  packages/server/api/src/app/ee/git-repos/operations/project-diff.service.ts
  packages/server/api/src/app/ee/git-repos/operations/sync-operations.ts
  packages/server/api/src/app/ee/helper/redis-system-job.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.html
  packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/pull-from-git-dialog/pull-from-git-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/pull-from-git-dialog/pull-from-git-dialog.component.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/push-to-git-dialog/push-to-git-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/push-to-git-dialog/push-to-git-dialog.component.ts
  packages/ui/feature-git-sync/src/lib/components/push-flow-to-git-button/push-flow-to-git-button.component.ts
  packages/ui/feature-git-sync/src/lib/services/sync-project.service.ts
Labels: ⭐ enhancement, auto-deploy

#4068 fix: wootric name
  packages/pieces/community/wootric/package.json
  packages/pieces/community/wootric/src/index.ts
  packages/pieces/community/wootric/src/lib/actions/create-survey.ts
  tsconfig.base.json
Labels: skip-changelog

#4045 refactor(api): rbac authz logic
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/project-members/project-member-role.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/authentication/authorization.ts
  packages/server/api/src/app/ee/authentication/rbac-auth-middleware.ts
  packages/server/api/src/app/ee/authentication/rbac/access-control-list.ts
  packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
  packages/server/api/src/app/ee/authentication/rbac/resources.ts
  packages/server/api/test/integration/cloud/activity/activity.test.ts
  packages/server/api/test/integration/cloud/app-connection/app-connection.test.ts
  packages/server/api/test/integration/cloud/flow/flow.test.ts
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 🐛 bug, 🔒 security, 🖥️ api

#4071 refactor: move permission config to route level
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/ee/activity/activity-controller.ts
  packages/server/api/src/app/ee/authentication/rbac/access-control-list.ts
  packages/server/api/src/app/ee/authentication/rbac/rbac-middleware.ts
  packages/server/api/src/app/ee/authentication/rbac/resources.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/test/integration/cloud/app-connection/app-connection.test.ts
  packages/server/api/test/integration/cloud/flow/flow.test.ts
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
  packages/server/api/types/fastify.d.ts
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/common/index.ts
  packages/shared/src/lib/common/security/index.ts
  packages/shared/src/lib/common/security/permission.ts
Labels: 💻 tech debt, 🔒 security, 🖥️ api

#4070 feat: show template description in templates dialog
  packages/ee/ui-platform/src/lib/components/dialogs/create-or-update-template-dialogue/create-or-update-template-dialogue.component.html
  packages/ee/ui-platform/src/lib/components/dialogs/create-or-update-template-dialogue/create-or-update-template-dialogue.component.ts
  packages/ui/common/src/lib/service/flow.service.ts
  packages/ui/core/src/assets/img/custom/piece/activtiy_mention.png
  packages/ui/core/src/assets/img/custom/piece/approval_mention.png
  packages/ui/core/src/assets/img/custom/piece/branch_mention.png
  packages/ui/core/src/assets/img/custom/piece/code_mention.png
  packages/ui/core/src/assets/img/custom/piece/connections_mention.png
  packages/ui/core/src/assets/img/custom/piece/crypto_mention.png
  packages/ui/core/src/assets/img/custom/piece/data-mapper_mention.png
  packages/ui/core/src/assets/img/custom/piece/date-helper_mention.png
  packages/ui/core/src/assets/img/custom/piece/delay_mention.png
  packages/ui/core/src/assets/img/custom/piece/file-helper_mention.png
  packages/ui/core/src/assets/img/custom/piece/http_mention.png
  packages/ui/core/src/assets/img/custom/piece/image-helper_mention.png
  packages/ui/core/src/assets/img/custom/piece/loop_mention.png
  packages/ui/core/src/assets/img/custom/piece/math-helper_mention.png
  packages/ui/core/src/assets/img/custom/piece/schedule_mention.png
  packages/ui/core/src/assets/img/custom/piece/sftp_mention.png
  packages/ui/core/src/assets/img/custom/piece/smtp_mention.png
  packages/ui/core/src/assets/img/custom/piece/store_mention.png
  packages/ui/core/src/assets/img/custom/piece/tags_mention.png
  packages/ui/core/src/assets/img/custom/piece/text-helper_mention.png
  packages/ui/core/src/assets/img/custom/piece/webhook_mention.png
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
  packages/ui/feature-pieces/src/lib/pieces-icons-from-flow/pieces-icons-from-flow.component.html
  packages/ui/feature-pieces/src/lib/pieces-icons-from-flow/pieces-icons-from-flow.component.ts
  packages/ui/feature-pieces/src/lib/pieces-icons/piece-icon-container/piece-icon-container.component.html
  packages/ui/feature-pieces/src/lib/pieces-icons/piece-icon-container/piece-icon-container.component.ts
  packages/ui/feature-pieces/src/lib/services/piece-meta.service.ts
  packages/ui/feature-templates/src/lib/template-card/template-card.component.html
  packages/ui/feature-templates/src/lib/template-card/template-card.component.ts
  packages/ui/feature-templates/src/lib/template-description-banner-color.pipe.ts
  packages/ui/feature-templates/src/lib/templates-dialog/template-description/template-description.component.html
  packages/ui/feature-templates/src/lib/templates-dialog/template-description/template-description.component.ts
  packages/ui/feature-templates/src/lib/templates-dialog/templates-dialog.component.html
  packages/ui/feature-templates/src/lib/templates-dialog/templates-dialog.component.ts
  packages/ui/feature-templates/src/lib/ui-feature-templates.module.ts
Labels: frontend, 🌟 feature

#4074 chore: fix all principal types variable typo
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/authentication/authentication.controller.ts
  packages/server/api/src/app/ee/app-credentials/app-credentials.module.ts
  packages/server/api/src/app/ee/authentication/enterprise-local-authn/enterprise-local-authn-controller.ts
  packages/server/api/src/app/ee/authentication/federated-authn/federated-authn-controller.ts
  packages/server/api/src/app/ee/billing/appsumo/appsumo.module.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/connection-keys/connection-key.module.ts
  packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-controller.ts
  packages/server/api/src/app/ee/otp/otp-controller.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
  packages/server/api/src/app/flags/flag.module.ts
  packages/server/api/src/app/flow-templates/community-flow-template.module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/step-file/step-file.module.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-controller.ts
  packages/shared/package.json
  packages/shared/src/lib/authentication/model/principal-type.ts
Labels: 💻 tech debt, 🧹 clean up

#4069 feat: move templates dialog to dashboard
  packages/ui/feature-pieces/src/lib/pieces-icons-from-flow/pieces-icons-from-flow.component.ts
Labels: ⭐ enhancement, frontend

#4073 feat(forms): make forms publicly accessible
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flows/flow/form/form.controller.ts
  packages/server/api/src/app/flows/flow/form/form.module.ts
  packages/server/api/src/app/flows/flow/form/form.service.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/flows/form.ts
  packages/shared/src/lib/flows/index.ts
  packages/ui/core/src/app/modules/forms/forms.component.html
  packages/ui/core/src/app/modules/forms/forms.component.ts
  packages/ui/core/src/app/modules/forms/forms.service.ts
Labels: ⭐ enhancement, auto-deploy

#4076 refactor: lint forms and fix typo
  packages/server/api/src/app/flows/flow/form/form.controller.ts
  packages/ui/feature-templates/src/index.ts
Labels: skip-changelog, auto-deploy

#4078 fix: remove unused index
  packages/server/api/src/app/database/migration/1709505632771-SetNotNullOnPlatform.ts
  packages/server/api/src/app/database/migration/postgres/1709500873378-DropUnusedPlatformIndex.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/project/project-entity.ts
Labels: 🧹 clean up, auto-deploy

#4079 refactor: remove ExecutionOutput
  docs/endpoints/flow-runs/get.mdx
  docs/endpoints/flow-runs/list.mdx
  docs/endpoints/flow-runs/schema.mdx
  docs/mint.json
  docs/openapi.json
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/main.ts
  packages/engine/test/handler/flow-with-pause.test.ts
  packages/engine/test/handler/flow-with-response.test.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/flow-worker/cloud-flow-worker-hooks.ts
  packages/server/api/src/app/flows/flow-run/flow-response-watcher.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/helper/engine-helper.ts
  packages/server/api/src/app/helper/notifications.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-queue.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/ce/flows/flow-worker.test.ts
  packages/server/worker/src/lib/log-serializer.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
  packages/shared/src/lib/flow-run/execution/execution-output.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
  packages/shared/src/lib/flow-run/flow-run.ts
  packages/ui/common/src/lib/components/status-icon/state-icon.component.ts
  packages/ui/common/src/lib/models/flow-run.interface.ts
  packages/ui/common/src/lib/service/flow.service.ts
  packages/ui/common/src/lib/service/instance-run.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/run-details.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/test-run-bar/test-run-bar.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs-table/runs-table.datasource.ts
  packages/ui/feature-flow-builder/src/lib/page/flow-builder/flow-builder.component.ts
Labels: 🧹 clean up

#4082 chore: revert removing foreign key for `project.platformId`
  packages/server/api/src/app/database/migration/postgres/1709566642531-add-platform-foreign-key-to-project-postgres.ts
  packages/server/api/src/app/database/migration/sqlite/1709566629593-add-platform-foreign-key-to-project-sqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/project/project-entity.ts
  packages/server/api/test/integration/ce/flows/flow.test.ts
  packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts
Labels: 💻 tech debt, 🖥️ api

#4085 refactor: move webhook into pieces
  package.json
  packages/engine/src/lib/handler/context/test-execution-context.ts
  packages/engine/src/lib/helper/logging-utils.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/webhook/.eslintrc.json
  packages/pieces/community/webhook/README.md
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/project.json
  packages/pieces/community/webhook/src/index.ts
  packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts
  packages/pieces/community/webhook/tsconfig.json
  packages/pieces/community/webhook/tsconfig.lib.json
  packages/server/api/src/app/database/migration/common/1709581196563-migrate-webhook.ts
  packages/server/api/src/app/database/migration/postgres/1709505632771-SetNotNullOnPlatform.ts
  packages/server/api/src/app/database/migration/postgres/1709581196564-migrate-webhook-templates.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
  packages/server/api/test/integration/ce/flows/flow-worker.test.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/flows/flow-helper.ts
  packages/shared/src/lib/flows/flow-operations.ts
  packages/shared/src/lib/flows/triggers/trigger.ts
  packages/ui/common/src/lib/utils/utils.ts
  packages/ui/feature-builder-canvas/src/lib/components/flow-item-tree/flow-item/flow-item-content/flow-item-content.component.ts
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/mentions-list.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/webhook-trigger-mention-item/webhook-trigger-mention-item.component.html
  packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/mentions-list/webhook-trigger-mention-item/webhook-trigger-mention-item.component.ts
  packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/edit-step-sidebar/edit-step-form-container/edit-step-form-container.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/common.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/builder.selector.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
  packages/ui/feature-builder-test-steps/src/index.ts
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.ts
  packages/ui/feature-builder-test-steps/src/lib/test-webhook-trigger/test-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-webhook-trigger/test-webhook-trigger.component.ts
  packages/ui/feature-builder-test-steps/src/lib/ui-feature-builder-test-steps.module.ts
  packages/ui/feature-dashboard/src/lib/pipes/trigger-icon.pipe.ts
  packages/ui/feature-dashboard/src/lib/pipes/trigger-tooltip.pipe.ts
  packages/ui/feature-pieces/src/lib/services/piece-meta.service.ts
  tsconfig.base.json
Labels: 💻 tech debt, 🧹 clean up

#4086 chore: filter noisy error
  packages/server/shared/src/lib/exception-handler.ts
Labels: 🧹 clean up, auto-deploy

#4087 fix: fallback to full search for removing job key
  packages/server/api/src/app/ee/flow-worker/cloud-flow-worker-hooks.ts
  packages/server/api/src/app/flows/trigger/hooks/execute-trigger-hooks.ts
  packages/server/api/src/app/workers/flow-worker/flow-queue-consumer.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts
  packages/server/shared/src/lib/exception-handler.ts
Labels: 🐛 bug, auto-deploy

#4088 fix: noisy errors and stale jobs
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-queue.ts
Labels: skip-changelog, auto-deploy

#4091 fix: webhook migration
  packages/server/api/src/app/database/migration/common/1709581196563-migrate-webhook.ts
Labels: skip-changelog

#4094 chore: improve activity piece properties descriptions and displayed names
  packages/pieces/community/activity/package.json
  packages/pieces/community/activity/src/index.ts
  packages/pieces/community/activity/src/lib/actions/create-activity.ts
  packages/pieces/community/activity/src/lib/actions/shared.ts
  packages/pieces/community/activity/src/lib/actions/update-activity.ts
  packages/ui/core/src/assets/img/custom/piece/activity_mention.png
  packages/ui/core/src/assets/img/custom/piece/activtiy_mention.png
  packages/ui/feature-dashboard/src/lib/pages/activity-table/activity-table.component.html
Labels: ⭐ enhancement, 🔌 pieces, auto-deploy

#4095 chore: show templates dialog after clicking "Build Flow" in "Create Your First Flow" screen
  packages/ui/common/src/lib/components/dialogs/delete-enity-dialog/delete-entity-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-connection-dialog/new-connection-dialog.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/empty-flows-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-templates/src/lib/templates-dialog/templates-dialog.component.html
  packages/ui/feature-templates/src/lib/templates-dialog/templates-dialog.component.ts
Labels: ⭐ enhancement, frontend

#4093 fix: re-enable demo flow tour for cloud
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/core/src/app/app.component.ts
  packages/ui/feature-builder-form-controls/src/lib/array-form-control/array-form-control.component.ts
Labels: 🐛 bug, frontend, auto-deploy

#4097 feat(mailerlite): custom fields for subscribers action ,find subscriber,add/remove subscriber from group action
  packages/pieces/community/mailer-lite/package.json
  packages/pieces/community/mailer-lite/src/index.ts
  packages/pieces/community/mailer-lite/src/lib/actions/add-subscriber-to-group.ts
  packages/pieces/community/mailer-lite/src/lib/actions/create-or-update-subscription.ts
  packages/pieces/community/mailer-lite/src/lib/actions/find-subscriber.ts
  packages/pieces/community/mailer-lite/src/lib/actions/remove-subscriber-from-group.ts
  packages/pieces/community/mailer-lite/src/lib/common/index.ts
  packages/pieces/community/mailer-lite/src/triggers/triggers.ts
Labels: 🔌 pieces

#4100 chore: build 0.21.0-rc.2
  package.json
Labels: pre-release

#4117 fix(git-sync): move mapping state to db
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/server/api/src/app/database/migration/postgres/1709753080714-AddMappingStateToGit.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/git-repos/git-repo.entity.ts
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/ui/feature-dashboard/src/lib/pages/sync-project/sync-project.component.html
Labels: 🐛 bug, Enterprise

#4118 chore: change code piece icon
  packages/ui/core/src/assets/img/custom/piece/code.svg
  packages/ui/core/src/assets/img/custom/piece/code_mention.png
Labels: ⭐ enhancement

#4098 fix(google-calendar): Resolve issue with multiple payloads for recurring events
  packages/pieces/community/google-calendar/package.json
  packages/pieces/community/google-calendar/src/lib/common/helper.ts
  packages/pieces/community/google-calendar/src/lib/triggers/calendar-event.ts
Labels: 🔌 pieces

#4116 feat: support pagination in dynamic dropdown
  docs/developers/piece-reference/properties.mdx
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/main.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/framework/src/lib/property/input/dropdown/dropdown-prop.ts
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/shared/package.json
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  packages/ui/common/src/lib/pipe/dropdown-search.pipe.ts
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
Labels: ⭐ enhancement, auto-deploy

#4121 feat(dust): add action for upserting a document into a database
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
  packages/pieces/community/dust/src/lib/actions/upsert-document.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#4120 feat(dust): new action to reply to existing conversation
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#4124 fix: valid undefined
  packages/shared/src/lib/flows/flow-helper.ts
Labels: skip-changelog

#4125 chore: bump to 0.21.0-rc.3
  package.json
Labels: pre-release

#4128 fix: static dropdowns were not opening inside list inputs
  packages/ui/core/src/assets/scss/ng-material-override.scss
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.ts
Labels: 🐛 bug, frontend, auto-deploy

#4127 feat(copilot): allow using azure openai deployment instead of openai api
  docs/install/configurations/environment-variables.mdx
  packages/server/api/src/app/copilot/copilot.service.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
Labels: ⭐ enhancement

#4129 fix: rerun run
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: 🐛 bug

#4132 chore: add admin platform module
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/platform/admin-platform.controller.ts
  packages/server/api/src/app/ee/platform/admin-platform.service.ts
Labels: skip-changelog, auto-deploy

#4135 fix: response 200s for stripe instead of 204
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
Labels: skip-changelog, auto-deploy

#4136 fix: enrich errors in the failure
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/connections.service.ts
  packages/engine/src/lib/services/storage.service.ts
Labels: skip-changelog, auto-deploy

#4138 feat: expose authors in piece
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/piece.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/shared/package.json
Labels: 🧹 clean up, auto-deploy

#4139 revert: "feat: expose authors in piece"
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/piece.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/shared/package.json
Labels: skip-changelog

#4083 feat(json): convert json to text / convert text to json
  packages/pieces/community/json/.eslintrc.json
  packages/pieces/community/json/README.md
  packages/pieces/community/json/package.json
  packages/pieces/community/json/project.json
  packages/pieces/community/json/src/index.ts
  packages/pieces/community/json/src/lib/actions/convert-json-to-text.ts
  packages/pieces/community/json/src/lib/actions/convert-text-to-json.ts
  packages/pieces/community/json/tsconfig.json
  packages/pieces/community/json/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4122 feat: add property to hide folders in embedding sdk
  packages/ee/components/src/index.ts
  packages/ee/components/src/lib/embed-redirect/embed-redirect.component.ts
  packages/ee/components/src/lib/embedded-connection-dialog/embedded-connection-dialog.component.html
  packages/ee/components/src/lib/embedded-connection-dialog/embedded-connection-dialog.component.ts
  packages/ee/embed-sdk/package.json
  packages/ee/embed-sdk/src/index.ts
  packages/ui/common/src/lib/service/embedding.service.ts
  packages/ui/core/src/app/app-routing.module.ts
  packages/ui/core/src/app/app.component.html
  packages/ui/core/src/app/app.component.scss
  packages/ui/core/src/app/app.component.ts
  packages/ui/core/src/assets/scss/utlis.scss
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.html
  packages/ui/feature-builder-header/src/lib/flow-builder-header.component.ts
  packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table-title/flows-table-title.component.ts
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/flows-table/flows-table.component.ts
  packages/ui/feature-pieces/src/lib/services/piece-meta.service.ts
Labels: ⭐ enhancement, frontend, Embed

#4141 fix: add author to piece
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/piece.ts
  packages/server/api/src/app/database/migration/postgres/1710098373707-AddAuthorsToPieces.ts
  packages/server/api/src/app/database/migration/sqlite/1710098009544-AddAuthorsToPieces.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
  packages/server/api/src/app/pieces/piece-metadata-entity.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/shared/package.json
Labels: ⭐ enhancement, auto-deploy

#4142 fix: bump json
  packages/pieces/community/json/package.json
Labels: 🔌 pieces, skip-changelog

#4115 chore: add an embedded connections dialog
  packages/ee/components/src/lib/embedded-connection-dialog/embedded-connection-dialog.component.html
  packages/ee/components/src/lib/embedded-connection-dialog/embedded-connection-dialog.component.ts
  packages/ee/embed-sdk/src/index.ts
  packages/ui/feature-connections/src/lib/add-edit-connection-button/add-edit-connection-button.component.ts
Labels: frontend, ☁️ Paid Feature, Embed, 🌟 feature

#4140 feat: add new documentation for connections in embedded SDK
  docs/embedding/configuration/generate-jwt.mdx
  docs/embedding/configuration/initialize-embed.mdx
  docs/embedding/connection-cards/frontend-sdk.mdx
  docs/embedding/connection-cards/overview.mdx
  docs/embedding/connection-cards/user-authentication.mdx
  docs/embedding/connection-cards/user-flows.mdx
  docs/embedding/connections/create-connection.mdx
  docs/embedding/embed-builder/embed-iframe.mdx
  docs/install/options/docker-compose.mdx
  docs/install/options/docker.mdx
  docs/mint.json
  docs/resources/screenshots/connections-piece-usage.png
  docs/resources/screenshots/connections-piece.png
  docs/resources/screenshots/product-embed-send-notification.png
  docs/resources/screenshots/product-embed-slack.png
Labels: 📚 documentation

#4151 chore: enabled dynamic inputs for triggers
  packages/ui/feature-builder-form-controls/src/lib/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/input-forms-schema.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-forms/piece-trigger-input-form/piece-trigger-input-form.component.ts
Labels: auto-deploy

#4154 fix: test flow stuck on running status
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flows/flow-run/flow-response-watcher.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/websockets/websockets.service.ts
  packages/ui/common/src/lib/service/websocket.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-builder-store/src/lib/store/builder/canvas/canvas.effects.ts
Labels: 🐛 bug, auto-deploy

#4152 feat(image-helper): added compress image action
  packages/pieces/community/image-helper/package.json
  packages/pieces/community/image-helper/src/index.ts
  packages/pieces/community/image-helper/src/lib/actions/compress-image.actions.ts
Labels: 🔌 pieces

#4153 feat(iframe): retry if failed to find container
  docs/embedding/configuration/initialize-embed.mdx
  docs/embedding/connections/create-connection.mdx
  packages/ee/embed-sdk/package.json
  packages/ee/embed-sdk/src/index.ts
Labels: ⭐ enhancement, Embed

#4155 chore: bump version to 0.21.0-rc.4
  package.json
Labels: pre-release

#4156 feat(api): sort pieces by create date
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
Labels: 🖥️ api, auto-deploy

#4157 fix(google-my-business): show all locations instead of 10
  packages/pieces/community/google-my-business/package.json
  packages/pieces/community/google-my-business/src/lib/common/common.ts
  packages/pieces/community/google-my-business/src/lib/triggers/new-review.ts
Labels: 🔌 pieces

#4159 fix: no longer internal error status on runs with large payloads
  .github/workflows/automate-deploy.yml
  packages/engine/src/lib/helper/logging-utils.ts
Labels: 🐛 bug, auto-deploy

#4163 feat: release 0.21.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#4161 fix(slack): properly propagate Slack API errors
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/actions/upload-file.ts
  packages/pieces/community/slack/src/lib/common/utils.ts
Labels: 🔌 pieces

#4170 feat(hubspot): create deal, update deal action and deal stage updated trigger
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/index.ts
  packages/pieces/community/hubspot/src/lib/actions/create-deal.ts
  packages/pieces/community/hubspot/src/lib/actions/update-deal.ts
  packages/pieces/community/hubspot/src/lib/common/client.ts
  packages/pieces/community/hubspot/src/lib/common/models.ts
  packages/pieces/community/hubspot/src/lib/triggers/deal-stage-updated.ts
Labels: 🔌 pieces

#4164 fix: test step no longer timeout after 30 seconds
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/flows/step-run/step-run-controller.ts
  packages/server/api/src/app/flows/step-run/step-run-service.ts
  packages/server/api/src/app/websockets/websockets.service.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/step-run/dto/test-step-request.ts
  packages/ui/common/src/lib/service/test-step.service.ts
Labels: 🌟 feature, auto-deploy

#4173 fix(billing): don't send project usage if the subscription is cancelled.
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
Labels: skip-changelog

#4174 fix(google-sheets): improve error message
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
Labels: 🔌 pieces

#4099 feat: support run scope for storage piece / framework
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/services/storage.service.ts
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/polling/index.ts
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
  packages/pieces/community/metabase/src/lib/common.ts
  packages/pieces/community/rss/src/lib/triggers/new-item-trigger.ts
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
  packages/pieces/community/store/src/lib/actions/store-append-action.ts
  packages/pieces/community/store/src/lib/actions/store-get-action.ts
  packages/pieces/community/store/src/lib/actions/store-put-action.ts
  packages/pieces/community/store/src/lib/actions/store-remove-from-list.ts
  packages/pieces/community/store/src/lib/actions/store-remove-value.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
Labels: 🔌 pieces, 🛠️ piece-framework

#4176 docs: Include instructions for setting up piece sources variable in development environment
  docs/developers/development-setup/codespaces.mdx
  docs/developers/development-setup/dev-container.mdx
  docs/developers/development-setup/local.mdx
Labels: 📚 documentation

#4177 fix(piece-framework): axios http client to support array query parameter multiple times
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts
  packages/pieces/community/common/src/lib/http/core/base-http-client.ts
Labels: 🛠️ piece-framework

#4171 feat: retryable errors for engine execution
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/error-handling.ts
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/connections.service.ts
  packages/engine/src/lib/services/storage.service.ts
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/engine/test/handler/flow-piece.test.ts
  packages/server/api/src/app/store-entry/store-entry.controller.ts
  packages/server/api/src/app/workers/flow-worker/flow-worker.ts
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
  packages/shared/src/lib/store-entry/dto/store-entry-request.ts
Labels: 🐛 bug, ⭐ enhancement, engine

#4172 fix(google-sheets): fix duplicated runs for new row instant
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/trigger/trigger.ts
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added.ts
  packages/server/api/src/app/database/redis-connection.ts
  packages/server/api/src/app/flows/trigger/dedupe/index.ts
  packages/server/api/src/app/project/usage/project-usage-service.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
  packages/server/api/src/app/workers/flow-worker/flow-queue-consumer.ts
Labels: 🔌 pieces, auto-deploy

#4181 revert: run scope for the storage in framework
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/services/storage.service.ts
  packages/pieces/community/common/src/lib/polling/index.ts
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
  packages/pieces/community/metabase/src/lib/common.ts
  packages/pieces/community/rss/src/lib/triggers/new-item-trigger.ts
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/lib/actions/common.ts
  packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
  packages/pieces/community/store/src/lib/actions/store-append-action.ts
  packages/pieces/community/store/src/lib/actions/store-get-action.ts
  packages/pieces/community/store/src/lib/actions/store-put-action.ts
  packages/pieces/community/store/src/lib/actions/store-remove-from-list.ts
  packages/pieces/community/store/src/lib/actions/store-remove-value.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: 🐛 bug, auto-deploy

#4183 feat: 0.22.0-rc.1
  package.json
  packages/server/api/src/app/flows/trigger/dedupe/index.ts
Labels: pre-release

#4186 fix: connection expired should be user error
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/helper/execution-errors.ts
  packages/engine/src/lib/services/connections.service.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🐛 bug, auto-deploy

#4188 fix: throw error if polling key is not found
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/polling/index.ts
Labels: 🛠️ piece-framework

#4196 fix: stop retry for failed connections
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts
Labels: 🐛 bug, auto-deploy

#4197 fix: increase plugin timeout
  packages/server/api/src/app/app.ts
  packages/server/api/src/main.ts
Labels: 🐛 bug, auto-deploy

#4194 feat(freshdesk): Get Contacts and Get all Tickets by Status actions
  packages/pieces/community/freshdesk/package.json
  packages/pieces/community/freshdesk/src/index.ts
  packages/pieces/community/freshdesk/src/lib/actions/get-all-tickets-by-status.ts
  packages/pieces/community/freshdesk/src/lib/actions/get-contacts.ts
Labels: 🔌 pieces

#4146 feat: delete project from the admin console
  packages/ee/shared/src/lib/billing/index.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/server/api/src/app/database/migration/postgres/1710243591721-add-deleted-to-project-postgres.ts
  packages/server/api/src/app/database/migration/postgres/1710720610669-cascade-project-delete-to-activity-and-app-credentials-and-connection-key.ts
  packages/server/api/src/app/database/migration/sqlite/1710248182409-add-deleted-to-project-sqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/activity/activity-entity.ts
  packages/server/api/src/app/ee/app-credentials/app-credentials.entity.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/connection-keys/connection-key.entity.ts
  packages/server/api/src/app/ee/helper/redis-system-job.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
  packages/server/api/src/app/ee/projects/platform-project-controller.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/ee/projects/platform-project-side-effects.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow-service-hooks.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/project/project-entity.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/src/main.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/ce/flows/project-worker.test.ts
  packages/server/api/test/integration/cloud/project/platform-project-service.test.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/shared/package.json
  packages/shared/src/lib/project/project.ts
  packages/ui/common/src/lib/service/platform-project.service.ts
Labels: 🌟 feature, auto-deploy

#4202 fix: framework piece metadata backward compatibility
  packages/engine/src/lib/helper/piece-helper.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/piece.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/main.ts
Labels: 🐛 bug, 🛠️ piece-framework

#4212 fix: display # of actions / triggers
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
Labels: 🐛 bug, auto-deploy

#4210 feat(slack): add search message action
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/search-messages.ts
Labels: 🔌 pieces

#4209 fix: move ask ai to websocket to avoid http timeout
  docs/install/configurations/environment-variables.mdx
  packages/server/api/src/app/copilot/copilot.controller.ts
  packages/server/api/src/app/copilot/copilot.module.ts
  packages/server/api/src/app/flows/flow.module.ts
  packages/server/api/src/app/websockets/websockets.service.ts
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/copilot/index.ts
  packages/shared/src/lib/websocket/index.ts
  packages/ui/common/src/lib/service/test-step.service.ts
  packages/ui/feature-builder-canvas/src/lib/components/widgets/test-flow-widget/test-flow-widget.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer.service.ts
Labels: 🐛 bug, auto-deploy

#4199 test: e2e execution flow test
  packages/server/api/src/app/authentication/authentication-service/hooks/community-service-hooks.ts
  packages/tests-e2e/.env.e2e
  packages/tests-e2e/.env.sample
  packages/tests-e2e/config.ts
  packages/tests-e2e/helper/test-utils.ts
  packages/tests-e2e/page/authentication.ts
  packages/tests-e2e/page/builder.ts
  packages/tests-e2e/page/dashboard.ts
  packages/tests-e2e/page/flows.ts
  packages/tests-e2e/playwright.config.ts
  packages/tests-e2e/project.json
  packages/tests-e2e/tests/send-slack-message.spec.ts
  packages/tests-e2e/tests/sign-up.spec.ts
  packages/tests-e2e/tests/test-flow.spec.ts
Labels: 🧹 clean up, 🧪 testing

#4220 fix(tally): test sample data is no longer returns empty object
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/validators/validators.ts
  packages/pieces/community/google-gemini/package.json
  packages/pieces/community/tally/package.json
  packages/pieces/community/tally/src/lib/triggers/new-submission.ts
Labels: 🐛 bug

#4222 fix: has triggers and has actions
  packages/ui/feature-pieces/src/lib/services/piece.service.ts
Labels: skip-changelog, auto-deploy

#4223 docs: change text to empty trigger
  packages/ui/feature-pieces/src/lib/services/piece.service.ts
Labels: skip-changelog, auto-deploy

#4178 fix: trimming large payload of jsons
  package-lock.json
  package.json
  packages/engine/src/lib/helper/logging-utils.ts
Labels: 🐛 bug, auto-deploy

#4231 feat: prerelease 0.22.0 rc2
  package.json
Labels: pre-release

#4233 fix: caching piece versions in front end
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.datasource.ts
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.html
  packages/ui/feature-pieces/src/lib/services/piece.service.ts
Labels: 🐛 bug, frontend

#4225 chore: clean up and add 14 days retention for trigger events
  docs/install/configurations/environment-variables.mdx
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/authentication/federated-authn/authn-provider/github-authn-provider.ts
  packages/server/api/src/app/ee/helper/redis-system-job.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.service.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
Labels: 🧹 clean up, auto-deploy

#4248 fix: list only non deleted projects
  packages/server/api/src/app/ee/project-members/project-member.service.ts
Labels: 🐛 bug, auto-deploy

#4246 fix: error handling for delete entity dialog
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ui/common/src/lib/components/dialogs/delete-enity-dialog/delete-entity-dialog.component.ts
Labels: 🐛 bug

#4251 feat: prevent deletion of current project
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/server/api/src/app/ee/projects/platform-project-controller.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/ui/common/src/lib/components/dialogs/delete-enity-dialog/delete-entity-dialog.component.ts
Labels: 🐛 bug

#4221 fix(freshdesk): updated JSON structure for get all tickets action
  packages/pieces/community/freshdesk/package.json
  packages/pieces/community/freshdesk/src/lib/actions/get-all-tickets-by-status.ts
Labels: 🔌 pieces

#4264 test: add list git repos with api key / user
  packages/server/api/src/app/ee/git-repos/git-repo.module.ts
  packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts
Labels: 🧹 clean up, 🧪 testing

#4265 feat: add paginator for projects in admin console
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.datasource.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.datasource.ts
  packages/server/api/src/app/ee/projects/platform-project-controller.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/shared/src/lib/project/project.ts
  packages/ui/common/src/index.ts
  packages/ui/common/src/lib/guards/user-logged-in.guard.ts
  packages/ui/common/src/lib/service/platform-project.service.ts
  packages/ui/common/src/lib/service/project.service.ts
Labels: ⭐ enhancement

#4207 feat(wedof): 11 actions / 8 triggers
  packages/pieces/community/wedof/.eslintrc.json
  packages/pieces/community/wedof/README.md
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/project.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/bill-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/cancel-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-intraining.ts
  packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-servicedone.ts
  packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-terminated.ts
  packages/pieces/community/wedof/src/lib/actions/get-minimal-session-dates.ts
  packages/pieces/community/wedof/src/lib/actions/get-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/refuse-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/search-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/update-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/validate-registration-folder.ts
  packages/pieces/community/wedof/src/lib/common/wedof.ts
  packages/pieces/community/wedof/src/lib/triggers/new-registration-folder-created.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-accepted.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-inTraining.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-paid.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-selected.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-terminated.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-tobill.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-updated.ts
  packages/pieces/community/wedof/tsconfig.json
  packages/pieces/community/wedof/tsconfig.lib.json
Labels: 🔌 pieces

#4268 feat: add branch type to git configuration
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts
  packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.html
  packages/ui/feature-git-sync/src/lib/components/dialogs/configure-repo-dialog/configure-repo-dialog.component.ts
Labels: ⭐ enhancement

#4243 feat(file-helper): create file from text action
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/index.ts
  packages/pieces/community/file-helper/src/lib/actions/create-file.ts
Labels: 🔌 pieces

#4245 feat(slack): add action to update message
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/update-message.ts
Labels: 🔌 pieces

#4270 fix: rename wedof to internal repo
  packages/pieces/community/wedof/.eslintrc.json
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/project.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/bill-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/cancel-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-intraining.ts
  packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-servicedone.ts
  packages/pieces/community/wedof/src/lib/actions/declare-registration-folder-terminated.ts
  packages/pieces/community/wedof/src/lib/actions/get-minimal-session-dates.ts
  packages/pieces/community/wedof/src/lib/actions/get-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/refuse-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/search-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/update-registration-folder.ts
  packages/pieces/community/wedof/src/lib/actions/validate-registration-folder.ts
  packages/pieces/community/wedof/src/lib/common/wedof.ts
  packages/pieces/community/wedof/src/lib/triggers/new-registration-folder-created.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-accepted.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-inTraining.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-paid.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-selected.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-terminated.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-tobill.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folder-updated.ts
  tsconfig.base.json
Labels: skip-changelog

#4269 chore(dust): remove log
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
Labels: skip-changelog

#4242 feat(dust): add support for fragments
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#4271 fix: checkly test
  packages/ui/common/src/lib/components/dialogs/delete-enity-dialog/delete-entity-dialog.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/action-or-trigger-dropdown/action-or-trigger-dropdown.component.html
Labels: skip-changelog, auto-deploy

#4240 feat(microsoft-sharepoint): create folder, create list and all list item actions
  package-lock.json
  package.json
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/brilliant-directories/package.json
  packages/pieces/community/convertkit/package.json
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/microsoft-sharepoint/.eslintrc.json
  packages/pieces/community/microsoft-sharepoint/README.md
  packages/pieces/community/microsoft-sharepoint/package.json
  packages/pieces/community/microsoft-sharepoint/project.json
  packages/pieces/community/microsoft-sharepoint/src/index.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/create-folder.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/create-list-item.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/create-list.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/delete-list-item.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/search-list-item.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/update-list-item.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/common/index.ts
  packages/pieces/community/microsoft-sharepoint/tsconfig.json
  packages/pieces/community/microsoft-sharepoint/tsconfig.lib.json
  packages/pieces/community/retune/package.json
  packages/pieces/community/saastic/package.json
  tsconfig.base.json
Labels: 🔌 pieces

#4214 feat(microsoft-teams): create channel, send chat message and send channel message action
  packages/pieces/community/microsoft-teams/.eslintrc.json
  packages/pieces/community/microsoft-teams/README.md
  packages/pieces/community/microsoft-teams/package.json
  packages/pieces/community/microsoft-teams/project.json
  packages/pieces/community/microsoft-teams/src/index.ts
  packages/pieces/community/microsoft-teams/src/lib/actions/create-channel.ts
  packages/pieces/community/microsoft-teams/src/lib/actions/send-channel-message.ts
  packages/pieces/community/microsoft-teams/src/lib/actions/send-chat-message.ts
  packages/pieces/community/microsoft-teams/src/lib/common/index.ts
  packages/pieces/community/microsoft-teams/tsconfig.json
  packages/pieces/community/microsoft-teams/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4272 fix: put empty string as default value for optional json without default value
  packages/ui/feature-builder-form-controls/src/lib/components/new-piece-properties-form/properties-controls-helper.ts
Labels: auto-deploy

#4257 feat: add video showcase for projects / appearance / templates
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.ts
  packages/ee/ui-platform/src/lib/components/api-keys-table/api-keys-table.component.html
  packages/ee/ui-platform/src/lib/components/api-keys-table/api-keys-table.component.ts
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.html
  packages/ee/ui-platform/src/lib/components/audit-event-table/audit-event-table.component.ts
  packages/ee/ui-platform/src/lib/components/custom-domain-table/custom-domain-table.component.html
  packages/ee/ui-platform/src/lib/components/custom-domain-table/custom-domain-table.component.ts
  packages/ee/ui-platform/src/lib/components/signing-keys-table/signing-keys-table.component.html
  packages/ee/ui-platform/src/lib/components/signing-keys-table/signing-keys-table.component.ts
  packages/ee/ui-platform/src/lib/components/smtp-settings/smtp-settings.component.html
  packages/ee/ui-platform/src/lib/components/smtp-settings/smtp-settings.component.ts
  packages/ee/ui-platform/src/lib/components/sso-settings/sso-settings.component.html
  packages/ee/ui-platform/src/lib/components/sso-settings/sso-settings.component.ts
  packages/ee/ui-platform/src/lib/components/terms-and-services-settings/terms-and-services-settings.component.html
  packages/ee/ui-platform/src/lib/components/terms-and-services-settings/terms-and-services-settings.component.ts
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.html
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
  packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.html
  packages/ee/ui-platform/src/lib/pages/platform-appearance/platform-appearance.component.ts
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/templates-table/templates-table.component.html
  packages/ee/ui-platform/src/lib/pages/templates-table/templates-table.component.ts
  packages/ee/ui-platform/src/lib/pages/users-table/users-table.component.html
  packages/ee/ui-platform/src/lib/pages/users-table/users-table.component.ts
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.html
  packages/ui/common/src/lib/components/upgrade-note/upgrade-note.component.ts
  packages/ui/feature-dashboard/src/lib/components/sidenav-routes-list/sidenav-routes-list.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-git-sync/src/lib/components/sync-project/sync-project.component.html
  packages/ui/feature-git-sync/src/lib/components/sync-project/sync-project.component.ts
Labels: ⭐ enhancement, auto-deploy

#4276 fix: add missing inputUiInfo for all triggers
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.datasource.ts
  packages/server/api/src/app/database/migration/postgres/1711411372480-migrateInputUiInfo.ts
  packages/server/api/src/app/database/migration/sqlite/1711412511624-AddMissingInputUiInfoSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
Labels: 🐛 bug, auto-deploy

#4277 fix: remove console error in google drive
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts
  packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts
  packages/pieces/community/google-drive/src/lib/common/index.ts
Labels: skip-changelog

#4244 fix(google-drive): add missing option to support team drives
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts
  packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts
  packages/pieces/community/google-drive/src/lib/common/index.ts
Labels: 🔌 pieces

#4280 fix: projects loading in admin console
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui-platform/src/lib/pages/projects-table/projects-table.datasource.ts
Labels: skip-changelog, auto-deploy

#4284 chore: update scheduler trigger version in demo flow
  packages/ui/feature-dashboard/src/lib/pages/flows-table/empty-flows-table/demo-flow-template.ts
Labels: skip-changelog, auto-deploy

#4281 feat(smtp): add html message body option
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🔌 pieces

#4287 fix: steps being shown as invalid when they are not after refreshing the browser
  packages/ui/common/src/lib/utils/utils.ts
  packages/ui/feature-builder-form-controls/src/index.ts
  packages/ui/feature-builder-form-controls/src/lib/components/new-piece-properties-form/properties-controls-helper.ts
  packages/ui/feature-builder-form-controls/src/lib/shared.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
  packages/ui/feature-builder-store/src/lib/store/flow/flow.effects.ts
Labels: frontend, auto-deploy

#4291 refactor: delete terms & privacy urls customization
  packages/ee/ui-platform/src/lib/components/terms-and-services-settings/terms-and-services-settings.component.html
  packages/ee/ui-platform/src/lib/components/terms-and-services-settings/terms-and-services-settings.component.ts
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/ee/ui-platform/src/lib/pages/platform-settings/platform-settings.component.ts
  packages/ee/ui-platform/src/lib/ui-ee-platform.module.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/shared/src/lib/platform/platform.request.ts
Labels: 🧹 clean up

#4283 feat(WordPress): rename piece to WordPress, with a capital P
  docs/about/changelog.mdx
  packages/pieces/community/wordpress/package.json
  packages/pieces/community/wordpress/src/index.ts
  packages/pieces/community/wordpress/src/lib/actions/create-page.action.ts
  packages/pieces/community/wordpress/src/lib/actions/create-post.action.ts
  packages/pieces/community/wordpress/src/lib/actions/get-post.action.ts
  packages/pieces/community/wordpress/src/lib/common/index.ts
  packages/pieces/community/wordpress/src/lib/trigger/new-post.trigger.ts
Labels: 🔌 pieces

#4227 feat(pdf): parse pdf
  .eslintrc.base.json
  package-lock.json
  package.json
  packages/pieces/community/pdf/.eslintrc.json
  packages/pieces/community/pdf/README.md
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/project.json
  packages/pieces/community/pdf/src/index.ts
  packages/pieces/community/pdf/src/lib/actions/parse-pdf.ts
  packages/pieces/community/pdf/tsconfig.json
  packages/pieces/community/pdf/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4293 chore: rename parse pdf to extract text
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/project.json
  packages/pieces/community/pdf/src/index.ts
  packages/pieces/community/pdf/src/lib/actions/extract-text.ts
Labels: skip-changelog

#4297 fix(mysql/postgres): add markdown warning how to prevent sql injections
  package-lock.json
  package.json
  packages/pieces/community/mysql/package.json
  packages/pieces/community/mysql/src/lib/actions/delete-row.ts
  packages/pieces/community/mysql/src/lib/actions/execute-query.ts
  packages/pieces/community/mysql/src/lib/actions/find-rows.ts
  packages/pieces/community/mysql/src/lib/actions/insert-row.ts
  packages/pieces/community/mysql/src/lib/actions/update-row.ts
  packages/pieces/community/mysql/src/lib/common/index.ts
  packages/pieces/community/postgres/package.json
  packages/pieces/community/postgres/src/lib/actions/run-query.ts
Labels: 🔌 pieces

#4296 fix(gmail): use attachment name when it is available
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/lib/actions/send-email-action.ts
Labels: 🐛 bug, 🔌 pieces

#4285 feat: sync pieces from cloud to db
  docs/install/configurations/environment-variables.mdx
  package-lock.json
  package.json
  packages/ee/embed-sdk/src/index.ts
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.html
  packages/ee/ui-platform/src/lib/pages/pieces-table/pieces-table.component.ts
  packages/server/api/.env
  packages/server/api/.env.tests
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/projects/platform-project-side-effects.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/flows/trigger-events/trigger-event.module.ts
  packages/server/api/src/app/helper/json-validator.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
  packages/server/api/src/app/helper/system-jobs/index.ts
  packages/server/api/src/app/helper/system-jobs/memory-system-jobs.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-metadata-entity.ts
  packages/server/api/src/app/pieces/piece-metadata-service/aggregated-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/cloud-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-sync-service.ts
  packages/server/api/test/integration/cloud/piece-metadata/piece-metadata.test.ts
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  packages/shared/src/lib/pieces/index.ts
  packages/ui/core/src/assets/img/custom/sync.svg
  packages/ui/feature-pieces/src/lib/services/piece.service.ts
Labels: ⭐ enhancement

#4303 feat: bump 0.22.0-rc.3
  package.json
Labels: pre-release

#4305 fix: project members table wasn't loading
  packages/ee/project-members/src/lib/project-members-table/project-members-table.component.html
Labels: 🐛 bug, auto-deploy

#4306 fix(git): use filename as unique id for flows in repo
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/src/app/ee/git-repos/git-sync-helper.ts
  packages/server/api/src/app/ee/git-repos/project-diff/project-diff.service.ts
Labels: 🐛 bug

#4307 feat: release 0.22.0-rc.4
  package.json
Labels: pre-release

#4308 feat(platform): add analytics api module
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/analytics/analytics-controller.ts
  packages/server/api/src/app/ee/analytics/analytics-module.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
  packages/server/api/src/app/helper/dayjs-helper.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
Labels: ⭐ enhancement, auto-deploy

#4310 feat: sort pieces by popularity
  packages/server/api/src/app/database/migration/postgres/1711768296861-AddProjectUsageColumnToPiece.ts
  packages/server/api/src/app/database/migration/sqlite/1711768479150-AddProjectUsageColumnToPieceSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/analytics/analytics-controller.ts
  packages/server/api/src/app/ee/analytics/analytics-module.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
  packages/server/api/src/app/ee/git-repos/git-repo.entity.ts
  packages/server/api/src/app/pieces/piece-metadata-entity.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-sorting.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
Labels: ⭐ enhancement, auto-deploy

#4312 fix: updated / created
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
Labels: skip-changelog, auto-deploy

#4313 fix: piece tests
  packages/server/api/test/helpers/mocks/index.ts
Labels: skip-changelog

#4300 feat(nocodb): all table record actions
  packages/pieces/community/nocodb/.eslintrc.json
  packages/pieces/community/nocodb/README.md
  packages/pieces/community/nocodb/package.json
  packages/pieces/community/nocodb/project.json
  packages/pieces/community/nocodb/src/index.ts
  packages/pieces/community/nocodb/src/lib/actions/create-record.ts
  packages/pieces/community/nocodb/src/lib/actions/delete-record.ts
  packages/pieces/community/nocodb/src/lib/actions/get-record.ts
  packages/pieces/community/nocodb/src/lib/actions/search-records.ts
  packages/pieces/community/nocodb/src/lib/actions/update-record.ts
  packages/pieces/community/nocodb/src/lib/common/client.ts
  packages/pieces/community/nocodb/src/lib/common/index.ts
  packages/pieces/community/nocodb/src/lib/common/types.ts
  packages/pieces/community/nocodb/tsconfig.json
  packages/pieces/community/nocodb/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4314 fix: markdown validation
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
Labels: 🐛 bug, auto-deploy

#4315 fix: markdown validation
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/ui/common/src/lib/utils/utils.ts
Labels: 🐛 bug, auto-deploy

#4317 fix: initially on adding a step, steps were being perceived as valid when they were not
  packages/ui/common/src/lib/utils/utils.ts
  packages/ui/feature-builder-form-controls/src/lib/components/interpolating-text-form-control/interpolating-text-form-control.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/piece-input-form/piece-input-form.component.ts
Labels: 🐛 bug, frontend, auto-deploy

#4301 feat: use YAML instead of JSON when showing steps output
  package-lock.json
  package.json
  packages/server/api/.env
  packages/ui/common/src/lib/components/index.ts
  packages/ui/common/src/lib/components/json-view/json-view-dialog/json-view-dialog.component.ts
  packages/ui/common/src/lib/components/json-view/json-view.component.html
  packages/ui/common/src/lib/components/json-view/json-view.component.scss
  packages/ui/common/src/lib/components/json-view/json-view.component.ts
  packages/ui/common/src/lib/components/yaml-view/yaml-view-dialog/yaml-view-dialog.component.html
  packages/ui/common/src/lib/components/yaml-view/yaml-view-dialog/yaml-view-dialog.component.ts
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.html
  packages/ui/common/src/lib/components/yaml-view/yaml-view.component.ts
  packages/ui/common/src/lib/pipe/output-log.pipe.ts
  packages/ui/common/src/lib/ui-common.module.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/core/esbuild-plugin.js
  packages/ui/core/project.json
  packages/ui/core/src/assets/scss/horizontal-sidebar-separator.scss
  packages/ui/core/src/main.ts
  packages/ui/feature-builder-left-sidebar/src/lib/components/run-details/selected-step-result/selected-step-result.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/flow-right-sidebar.component.scss
  packages/ui/feature-builder-test-steps/src/lib/test-action/test-action.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-piece-webhook-trigger/test-piece-webhook-trigger.component.html
  packages/ui/feature-builder-test-steps/src/lib/test-polling-trigger/test-polling-trigger.component.html
Labels: frontend, auto-deploy

#4321 fix: importing assets for monaco yaml
  packages/ui/common/src/lib/pipe/output-log.pipe.ts
  packages/ui/core/project.json
  packages/ui/core/src/app/monaco-themes/ap-monaco-theme.ts
  packages/ui/core/src/main.ts
Labels: skip-changelog, auto-deploy
