Repository activepieces/activepieces, pull requests merged in 2024-06, with the labels that each got.

#4844 fix(notion): fix timeout on trigger enable
  packages/pieces/community/notion/package.json
  packages/pieces/community/notion/src/lib/triggers/new-database-item.ts
  packages/pieces/community/notion/src/lib/triggers/updated-database-item.ts
Labels: 🔌 pieces

#4845 fix(delay): lower the threshold to push back to the queue
  packages/pieces/community/delay/package.json
  packages/pieces/community/delay/src/lib/actions/delay-for-action.ts
Labels: 🔌 pieces

#4843 feat(twitter): create reply for existing tweet action
  packages/pieces/community/twitter/package.json
  packages/pieces/community/twitter/src/index.ts
  packages/pieces/community/twitter/src/lib/actions/create-reply.ts
  packages/pieces/community/twitter/src/lib/actions/create-tweet.ts
  packages/pieces/community/twitter/src/lib/common/index.ts
Labels: 🔌 pieces

#4820 feat: add alerts section and send email by alert channel
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/alerts/alerts-dto.ts
  packages/ee/shared/src/lib/alerts/alerts-requests.ts
  packages/ee/shared/src/lib/alerts/index.ts
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/brilliant-directories/package.json
  packages/pieces/community/convertkit/package.json
  packages/pieces/community/retune/package.json
  packages/pieces/community/saastic/package.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts
  packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/alerts/alerts-controller.ts
  packages/server/api/src/app/ee/alerts/alerts-entity.ts
  packages/server/api/src/app/ee/alerts/alerts-module.ts
  packages/server/api/src/app/ee/alerts/alerts-service.ts
  packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-sender/log-email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/ee/helper/license-validator/index.ts
  packages/server/api/src/app/ee/helper/license-validator/license-validator.ts
  packages/server/api/src/app/ee/helper/license-validator/network-license-validator.ts
  packages/server/api/src/app/ee/issues/issues-service.ts
  packages/server/api/src/app/ee/projects/ee-project-hooks.ts
  packages/server/api/src/app/helper/error-handler.ts
  packages/server/api/src/app/platform/platform.entity.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/src/app/project/project-hooks.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/src/assets/emails/issue-created.html
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/platform/platform.model.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.datasource.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-alert-dialog/new-alert-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/new-alert-dialog/new-alert-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
  packages/ui/feature-dashboard/src/lib/pages/settings-page/settings-page.component.html
  packages/ui/feature-dashboard/src/lib/pages/settings-page/settings-page.component.ts
  packages/ui/feature-dashboard/src/lib/services/alerts.service.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🌟 feature, auto-deploy

#4848 fix: add double quotes on insertions and primary key postgres
  packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts
  packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts
Labels: auto-deploy

#4849 fix: adding the EMAIL channel as string
  packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts
  packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts
Labels: auto-deploy

#4850 feat: run alerts migration in single query
  packages/server/api/src/app/database/migration/postgres/1716989780835-AddAlertsEntityPostgres.ts
  packages/server/api/src/app/database/migration/sqlite/1717239613259-AddAlertsEntitySqlite.ts
Labels: auto-deploy

#4852 feat(zoho-crm): Add scope to Zoho CRM to get backup URLs and download backup file
  packages/pieces/community/zoho-crm/package.json
  packages/pieces/community/zoho-crm/src/index.ts
Labels: 🔌 pieces

#4856 fix: alerts issues tooltip
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
Labels: 🐛 bug, auto-deploy

#4859 feat(zoho-books): custom api call action
  packages/pieces/community/zoho-books/.eslintrc.json
  packages/pieces/community/zoho-books/README.md
  packages/pieces/community/zoho-books/package.json
  packages/pieces/community/zoho-books/project.json
  packages/pieces/community/zoho-books/src/index.ts
  packages/pieces/community/zoho-books/tsconfig.json
  packages/pieces/community/zoho-books/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4860 feat(zoho-crm): Read file action
  packages/pieces/community/zoho-crm/package.json
  packages/pieces/community/zoho-crm/src/index.ts
  packages/pieces/community/zoho-crm/src/lib/actions/read-file.ts
Labels: 🔌 pieces

#4863 fix(saml): login url error
  package-lock.json
  package.json
Labels: 🐛 bug, auto-deploy

#4864 fix: redis use ssl
  packages/server/api/src/app/database/redis-connection.ts
Labels: 🐛 bug

#4862 feat: add set alerts button on runs page
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Labels: ⭐ enhancement, auto-deploy

#4866 feat: release 0.27.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#4868 docs: update easypanel instructions
  docs/install/options/aws.mdx
  docs/install/options/easypanel.mdx
  docs/install/options/overview.mdx
Labels: 📚 documentation

#4821 docs: Adding stacksnap as option for deploying Activepieces to AWS
  docs/install/options/aws.mdx
Labels: 📚 documentation

#4855 feat: streamline premium pieces
  packages/ee/pieces/microsoft-dynamics-crm/package.json
  packages/ee/pieces/microsoft-dynamics-crm/src/index.ts
  packages/server/api/src/app/database/migration/postgres/1717370717678-AddPremiumPiecesColumnPostgres.ts
  packages/server/api/src/app/database/migration/sqlite/1717443603235-AddPremiumPiecesColumnSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/helper/license-validator/index.ts
  packages/server/api/src/app/ee/helper/license-validator/license-validator.ts
  packages/server/api/src/app/ee/helper/license-validator/network-license-validator.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/server/api/src/app/platform/platform.entity.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/piece-metadata/piece-metadata.test.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/shared/src/lib/pieces/piece.ts
  packages/shared/src/lib/platform/platform.model.ts
  tools/scripts/pieces/publish-pieces-to-npm.ts
  tools/scripts/utils/piece-script-utils.ts
  tools/scripts/validate-publishable-packages.ts
Labels: auto-deploy

#4801 feat(snowflake): insert row action
  packages/ee/pieces/microsoft-dynamics-crm/package.json
  packages/ee/pieces/microsoft-dynamics-crm/src/index.ts
  packages/ee/pieces/snowflake/.eslintrc.json
  packages/ee/pieces/snowflake/README.md
  packages/ee/pieces/snowflake/package.json
  packages/ee/pieces/snowflake/project.json
  packages/ee/pieces/snowflake/src/index.ts
  packages/ee/pieces/snowflake/src/lib/actions/insert-row.ts
  packages/ee/pieces/snowflake/src/lib/actions/run-query.ts
  packages/ee/pieces/snowflake/src/lib/common/index.ts
  packages/ee/pieces/snowflake/tsconfig.json
  packages/ee/pieces/snowflake/tsconfig.lib.json
  packages/pieces/community/snowflake/.eslintrc.json
  tools/scripts/utils/piece-script-utils.ts
  tsconfig.base.json
Labels: 🔌 pieces, ☁️ Paid Feature

#4722 feat(business-central): New or Updated Record Trigger and CRUD Actions for Record
  packages/ee/pieces/microsoft-dynamics-365-business-central/.eslintrc.json
  packages/ee/pieces/microsoft-dynamics-365-business-central/README.md
  packages/ee/pieces/microsoft-dynamics-365-business-central/package.json
  packages/ee/pieces/microsoft-dynamics-365-business-central/project.json
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/index.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/actions/create-record.action.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/actions/delete-record.action.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/actions/get-record.action.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/actions/search-records.action.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/actions/update-record.action.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/client.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/constants.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/index.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/bankAccounts.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/contacts.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/currencies.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/customers.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/disputeStatus.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/employees.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/itemCategories.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/itemVariants.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/items.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/journals.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/locations.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/paymentMethods.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/paymentTerms.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/projects.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/salesInvoiceLines.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/salesInvoices.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/salesOrderLines.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/salesOrders.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/salesQuoteLines.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/salesQuotes.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/shipmentMethods.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/props/vendors.entity.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/common/types.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/lib/triggers/new-or-updated-record.trigger.ts
  packages/ee/pieces/microsoft-dynamics-365-business-central/tsconfig.json
  packages/ee/pieces/microsoft-dynamics-365-business-central/tsconfig.lib.json
  packages/ee/pieces/snowflake/package.json
  packages/ee/pieces/snowflake/src/index.ts
  tools/scripts/utils/piece-script-utils.ts
  tsconfig.base.json
Labels: 🔌 pieces

#4872 fix: add correct click listener to install piece button
  packages/ui/feature-pieces/src/lib/project-pieces-table/project-pieces-table.component.html
Labels: skip-changelog, auto-deploy

#4873 chore: admin console button clean up
  packages/ee/ui/platform/src/lib/pages/platform-settings/platform-settings.component.html
  packages/server/api/src/app/flags/theme.ts
  packages/ui/core/src/assets/img/custom/notification_important.svg
  packages/ui/core/src/assets/scss/variables.scss
  packages/ui/feature-dashboard/src/lib/components/admin-console-button/admin-console-button.component.ts
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.html
  packages/ui/feature-dashboard/src/lib/dashboard-container.component.ts
  packages/ui/feature-dashboard/src/lib/ui-feature-dashboard.module.ts
Labels: 🧹 clean up, skip-changelog

#4875 feat(lever): improve add-feedback action
  packages/pieces/community/lever/package.json
  packages/pieces/community/lever/src/lib/common.ts
Labels: 🔌 pieces

#4874 feat(google-drive): add support for all drives to pdf export action
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/save-file-as-pdf.action.ts
  packages/pieces/community/google-drive/src/lib/action/upload-file.ts
Labels: 🔌 pieces

#4851 chore: parameterise createCustomApiCallAction parameters to be able t…
  packages/pieces/community/common/src/lib/helpers/index.ts
Labels: blocked: waiting-response

#4878 fix(auth): email flooding and shorten otp expiry
  packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/ee/otp/otp-service.ts
  packages/server/api/src/assets/emails/reset-password.html
  packages/server/api/src/assets/emails/verify-email.html
Labels: 🔒 security, 🧹 clean up, auto-deploy

#4879 feat(customer-io): create event / custom track api call / custom api call action
  packages/pieces/community/customer-io/.eslintrc.json
  packages/pieces/community/customer-io/README.md
  packages/pieces/community/customer-io/package.json
  packages/pieces/community/customer-io/project.json
  packages/pieces/community/customer-io/src/index.ts
  packages/pieces/community/customer-io/src/lib/actions/create_event.ts
  packages/pieces/community/customer-io/src/lib/common/index.ts
  packages/pieces/community/customer-io/tsconfig.json
  packages/pieces/community/customer-io/tsconfig.lib.json
Labels: 🔌 pieces

#4882 fix: duration default value is 0 now
  packages/ui/common/src/lib/pipe/duration-formatter.pipe.ts
Labels: skip-changelog, auto-deploy

#4880 feat(odoo): get custom records
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/validators/validators.ts
  packages/pieces/community/odoo/package.json
  packages/pieces/community/odoo/src/commom/index.ts
  packages/pieces/community/odoo/src/commom/type.ts
  packages/pieces/community/odoo/src/lib/actions/get-records.ts
  packages/pieces/community/odoo/src/lib/actions/index.ts
Labels: 🔌 pieces

#4877 feat: add alerts for quota
  packages/server/api/src/app/ee/alerts/alerts-service.ts
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/ee/helper/email/email-sender/email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/ee/issues/issues-service.ts
  packages/server/api/src/app/ee/project-plan/tasks-limit.ts
  packages/server/api/src/assets/emails/issue-created.html
  packages/server/api/src/assets/emails/quota-100.html
  packages/server/api/src/assets/emails/quota-50.html
  packages/server/api/src/assets/emails/quota-90.html
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html
Labels: 🐛 bug, auto-deploy

#4886 fix: add descriptions for pieces
  packages/ee/pieces/microsoft-dynamics-365-business-central/package.json
  packages/ee/pieces/microsoft-dynamics-365-business-central/src/index.ts
  packages/ee/pieces/microsoft-dynamics-crm/package.json
  packages/ee/pieces/microsoft-dynamics-crm/src/index.ts
  packages/ee/pieces/zuora/package.json
  packages/ee/pieces/zuora/src/index.ts
  packages/pieces/community/customer-io/package.json
  packages/pieces/community/customer-io/src/index.ts
  packages/pieces/community/lever/package.json
  packages/pieces/community/lever/src/index.ts
Labels: skip-changelog

#4887 fix: darken warn palette
  packages/server/api/src/app/flags/theme.ts
Labels: skip-changelog, auto-deploy

#4891 fix: run automate deploy on merge
  .github/workflows/automate-deploy.yml
Labels: skip-changelog

#4871 feat(KrispCall): New Contact / New MMS / New Voice Mail / Add Action / Delete Contact / Send SMS / MMS Actions
  packages/pieces/community/krisp-call/.eslintrc.json
  packages/pieces/community/krisp-call/README.md
  packages/pieces/community/krisp-call/package.json
  packages/pieces/community/krisp-call/project.json
  packages/pieces/community/krisp-call/src/index.ts
  packages/pieces/community/krisp-call/src/lib/actions/add-contact.ts
  packages/pieces/community/krisp-call/src/lib/actions/delete-contacts.ts
  packages/pieces/community/krisp-call/src/lib/actions/send-mms.ts
  packages/pieces/community/krisp-call/src/lib/actions/send-sms.ts
  packages/pieces/community/krisp-call/src/lib/triggers/index.ts
  packages/pieces/community/krisp-call/tsconfig.json
  packages/pieces/community/krisp-call/tsconfig.lib.json
  packages/server/.gitignore
  tsconfig.base.json
Labels: 🔌 pieces

#4900 chore: sort projects alphabetically in project switcher
  packages/ui/common/src/lib/service/project.service.ts
Labels: auto-deploy

#4901 feat: selectable status filter in runs and correct redirection on failed issues
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
  packages/ui/common/src/lib/service/instance-run.service.ts
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.ts
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.html
  packages/ui/feature-dashboard/src/lib/components/runs-table/runs-table.component.ts
  packages/ui/feature-dashboard/src/lib/pages/runs/runs.component.ts
Labels: ⭐ enhancement

#4902 feat: remove team member limit on non-cloud
  packages/ee/shared/src/lib/project/project-requests.ts
  packages/ee/ui/billing/src/lib/upgrade-dialog/upgrade-dialog.component.ts
  packages/ee/ui/platform/src/lib/pages/projects-table/projects-table.component.html
  packages/ee/ui/platform/src/lib/pages/projects-table/projects-table.component.ts
  packages/ee/ui/platform/src/lib/pages/users-table/users-table.component.html
  packages/ee/ui/platform/src/lib/pages/users-table/users-table.component.ts
  packages/server/api/src/app/ee/project-members/project-member.service.ts
  packages/server/api/src/app/ee/project-plan/members-limit.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/project/usage/project-usage-service.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
  packages/shared/src/lib/common/telemetry.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.ts
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.html
  packages/ui/feature-dashboard/src/lib/components/general-settings/general-settings.component.ts
Labels: ⭐ enhancement

#4904 chore: remove iframe options temporary
  packages/ui/core/nginx.standard.conf
Labels: 🐛 bug

#4906 docs: streamline pieces ci/cd
  docs/developers/building-pieces/piece-definition.mdx
  docs/developers/misc/pieces-ci-cd.mdx
  docs/embedding/embed-connections.mdx
  docs/mint.json
Labels: 📚 documentation

#4908 chore(facebook): update auth instructions
  packages/pieces/community/facebook-pages/package.json
  packages/pieces/community/facebook-pages/src/index.ts
Labels: 🔌 pieces

#4815 feat(messagebird): send SMS action
  packages/pieces/community/messagebird/.eslintrc.json
  packages/pieces/community/messagebird/README.md
  packages/pieces/community/messagebird/package.json
  packages/pieces/community/messagebird/project.json
  packages/pieces/community/messagebird/src/index.ts
  packages/pieces/community/messagebird/src/lib/actions/send-sms.action.ts
  packages/pieces/community/messagebird/tsconfig.json
  packages/pieces/community/messagebird/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4911 feat(gmail): new email trigger
  packages/pieces/community/gmail-dev/package.json
  packages/pieces/community/gmail-dev/src/index.ts
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/index.ts
  packages/pieces/community/gmail/src/lib/common/data.ts
  packages/pieces/community/gmail/src/lib/common/props.ts
  packages/pieces/community/gmail/src/lib/triggers/new-email.ts
Labels: 🔌 pieces

#4909 feat: invitation links when smtp not configured
  packages/server/api/.env.tests
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/shared/src/lib/invitations/index.ts
  packages/ui/common/src/lib/service/user-invitations.service.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.ts
Labels: 🌟 feature

#4912 feat: allow to invite admins on cloud for free
  packages/ee/shared/src/lib/billing/index.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-hooks.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/app-connections/cloud-app-connection-service.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/ee/project-members/project-member.service.ts
  packages/server/api/src/app/ee/project-plan/connections-limits.ts
  packages/server/api/src/app/ee/project-plan/members-limit.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/user-invitations/user-invitation.module.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/flag/flag.ts
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/dialogs/invite-user-dialog/invite-user-dialog.component.ts
Labels: ⭐ enhancement

#4918 feat(linear): add pagination for dropdown
  packages/pieces/community/linear/package.json
  packages/pieces/community/linear/src/lib/common/client.ts
  packages/pieces/community/linear/src/lib/common/props.ts
Labels: 🔌 pieces

#4919 feat: entities ownership pre serialization hook
  packages/server/api/src/app/ee/alerts/alerts-module.ts
  packages/server/api/src/app/ee/git-repos/git-repo.module.ts
  packages/server/api/src/app/ee/issues/issues-module.ts
  packages/server/api/src/app/ee/project-members/project-member.module.ts
Labels: 🔒 security, 🧹 clean up

#4916 feat: update ee pieces readme and bump versions
  packages/ee/pieces/microsoft-dynamics-365-business-central/README.md
  packages/ee/pieces/microsoft-dynamics-365-business-central/package.json
  packages/ee/pieces/microsoft-dynamics-crm/README.md
  packages/ee/pieces/microsoft-dynamics-crm/package.json
  packages/ee/pieces/sharepoint/README.md
  packages/ee/pieces/sharepoint/package.json
  packages/ee/pieces/snowflake/README.md
  packages/ee/pieces/snowflake/package.json
  packages/ee/pieces/zuora/README.md
  packages/ee/pieces/zuora/package.json
Labels: 🧹 clean up

#4920 fix: remove contact sales on non- premium piece
  packages/ee/pieces/zuora/package.json
  packages/ee/pieces/zuora/src/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/piece-filtering.ts
  packages/ui/common/src/lib/service/contact-sales.service.ts
  packages/ui/common/src/lib/service/platform.service.ts
  packages/ui/common/src/lib/utils/consts.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.html
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-item/step-type-item.component.ts
  packages/ui/feature-builder-right-sidebar/src/lib/step-type-sidebar/step-type-sidebar.component.ts
Labels: skip-changelog

#4923 feat(maileroo): send email / send email from template
  packages/pieces/community/maileroo/.eslintrc.json
  packages/pieces/community/maileroo/README.md
  packages/pieces/community/maileroo/package.json
  packages/pieces/community/maileroo/project.json
  packages/pieces/community/maileroo/src/index.ts
  packages/pieces/community/maileroo/src/lib/actions/send-email.ts
  packages/pieces/community/maileroo/src/lib/actions/send-from-template.ts
  packages/pieces/community/maileroo/src/lib/common/send-utils.ts
  packages/pieces/community/maileroo/tsconfig.json
  packages/pieces/community/maileroo/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4928 chore(dev): remove docker-compose dev
  docker-compose.dev.yml
Labels: 🧹 clean up

#4841 fix: webhook production url save sample data
  packages/pieces/community/gravityforms/package.json
  packages/pieces/community/gravityforms/src/index.ts
  packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts
  packages/pieces/community/tally/package.json
  packages/pieces/community/tally/src/index.ts
  packages/pieces/community/tally/src/lib/triggers/new-submission.ts
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/index.ts
  packages/pieces/community/webhook/src/lib/triggers/catch-hook.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
  packages/server/api/src/app/workers/flow-worker/consumer/webhook-consumer.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-consumer.ts
  packages/server/api/src/app/workers/flow-worker/queues/redis/redis-consumer.ts
Labels: 🐛 bug

#4929 fix(tally): update webhook instructions
  packages/pieces/community/gravityforms/package.json
  packages/pieces/community/gravityforms/src/lib/triggers/new-submission.ts
  packages/pieces/community/tally/package.json
  packages/pieces/community/tally/src/lib/triggers/new-submission.ts
Labels: 🔌 pieces

#4933 fix: reduce docker image size by 2gb
  Dockerfile
Labels: 🧹 clean up

#4936 feat(amazon-sqs): send message action
  nx.json
  package-lock.json
  package.json
  packages/pieces/community/amazon-sqs/.eslintrc.json
  packages/pieces/community/amazon-sqs/README.md
  packages/pieces/community/amazon-sqs/package.json
  packages/pieces/community/amazon-sqs/project.json
  packages/pieces/community/amazon-sqs/src/index.ts
  packages/pieces/community/amazon-sqs/src/lib/actions/send-message.ts
  packages/pieces/community/amazon-sqs/tsconfig.json
  packages/pieces/community/amazon-sqs/tsconfig.lib.json
  packages/ui/feature-tags/package.json
  tsconfig.base.json
Labels: 🔌 pieces

#4937 fix(git): remove sample data on push
  packages/server/api/src/app/ee/git-repos/git-repo.service.ts
  packages/server/api/src/app/ee/git-repos/git-sync-helper.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/webhooks/webhook-service.ts
Labels: 🐛 bug

#4938 fix: allow delete flow with piece not found
  packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/server/api/src/app/flows/trigger/hooks/execute-trigger-hooks.ts
  packages/server/api/src/app/flows/trigger/hooks/handshake-trigger.hook.ts
  packages/server/api/src/app/flows/trigger/hooks/trigger-utils.ts
  packages/server/api/src/app/workers/flow-worker/queues/memory/memory-queue.ts
Labels: 🐛 bug

#4930 feat(reoon-verifier): single email and bulk email verification actions
  packages/pieces/community/reoon-verifier/.eslintrc.json
  packages/pieces/community/reoon-verifier/README.md
  packages/pieces/community/reoon-verifier/package.json
  packages/pieces/community/reoon-verifier/project.json
  packages/pieces/community/reoon-verifier/src/index.ts
  packages/pieces/community/reoon-verifier/src/lib/actions/bulk-email-verification-status.ts
  packages/pieces/community/reoon-verifier/src/lib/actions/bulk-email-verification.ts
  packages/pieces/community/reoon-verifier/src/lib/actions/verify-email.ts
  packages/pieces/community/reoon-verifier/src/lib/common/send-util.ts
  packages/pieces/community/reoon-verifier/tsconfig.json
  packages/pieces/community/reoon-verifier/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4940 feat(photoroom): add action to remove the background of an arbitrary image
  packages/pieces/community/photoroom/.eslintrc.json
  packages/pieces/community/photoroom/README.md
  packages/pieces/community/photoroom/package.json
  packages/pieces/community/photoroom/project.json
  packages/pieces/community/photoroom/src/index.ts
  packages/pieces/community/photoroom/src/lib/actions/remove-background.ts
  packages/pieces/community/photoroom/tsconfig.json
  packages/pieces/community/photoroom/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4931 feat(maileroo): verify email action
  packages/pieces/community/maileroo/package.json
  packages/pieces/community/maileroo/src/index.ts
  packages/pieces/community/maileroo/src/lib/actions/send-email.ts
  packages/pieces/community/maileroo/src/lib/actions/send-from-template.ts
  packages/pieces/community/maileroo/src/lib/actions/verify-email.ts
  packages/pieces/community/maileroo/src/lib/common/send-utils.ts
Labels: 🔌 pieces

#4943 feat(wedof): update certificationFolder action
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts
Labels: 🔌 pieces

#4951 fix: exit instance on missing jwt secret
  packages/server/api/src/app/app.ts
Labels: 🐛 bug

#4932 feat(fliqr-ai): Get Account Details and Get Account Flows actions
  packages/pieces/community/fliqr-ai/.eslintrc.json
  packages/pieces/community/fliqr-ai/README.md
  packages/pieces/community/fliqr-ai/package.json
  packages/pieces/community/fliqr-ai/project.json
  packages/pieces/community/fliqr-ai/src/index.ts
  packages/pieces/community/fliqr-ai/src/lib/actions/get-account-details.ts
  packages/pieces/community/fliqr-ai/src/lib/actions/get-account-flows.ts
  packages/pieces/community/fliqr-ai/src/lib/common/models.ts
  packages/pieces/community/fliqr-ai/tsconfig.json
  packages/pieces/community/fliqr-ai/tsconfig.lib.json
  packages/server/api/.env
  tsconfig.base.json
Labels: 🔌 pieces

#4953 feat(postgres): new row trigger
  package-lock.json
  package.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/postgres/package.json
  packages/pieces/community/postgres/src/index.ts
  packages/pieces/community/postgres/src/lib/actions/run-query.ts
  packages/pieces/community/postgres/src/lib/common.ts
  packages/pieces/community/postgres/src/lib/triggers/new-row.ts
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
Labels: 🔌 pieces

#4958 feat(smtp): add custom headers field
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🔌 pieces

#4966 fix: material expand icons
  packages/ui/core/src/assets/scss/ng-material-override.scss
Labels: skip-changelog, auto-deploy

#4968 fix: remove check marks from toggler mat buttons
  packages/ui/common/src/lib/ui-common.module.ts
Labels: skip-changelog, auto-deploy

#4969 chore: upgrade posthog js
  package-lock.json
  package.json
Labels: 🧹 clean up, auto-deploy

#4970 chore: identify unverified user sign ups
  packages/ui/common/src/lib/service/authentication.service.ts
  packages/ui/common/src/lib/service/telemetry.service.ts
  packages/ui/feature-templates/src/lib/templates-dialog/template-apps-dropdown/template-apps-dropdown.component.ts
Labels: skip-changelog, auto-deploy

#4972 chore: remove lodash and add it blocklist
  .eslintrc.json
  package-lock.json
  package.json
  packages/pieces/community/airtable/src/lib/common/index.ts
  packages/pieces/community/common/package.json
  packages/pieces/community/connections/src/lib/actions/read-connection.ts
  packages/pieces/community/contentful/src/lib/actions/records/create-record.ts
  packages/pieces/community/contentful/src/lib/common/utils.ts
  packages/pieces/community/contentful/src/lib/properties/content-model.ts
  packages/pieces/community/contentful/src/lib/properties/dynamic-fields.ts
  packages/pieces/community/contentful/src/lib/properties/locale.ts
  packages/pieces/community/contentful/src/lib/properties/select-fields.ts
  packages/pieces/community/data-mapper/package.json
  packages/pieces/community/data-mapper/src/lib/data-mapper.mdx
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/validators/validators.ts
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/notion/src/lib/triggers/new-database-item.ts
  packages/pieces/community/retable/src/lib/common/index.ts
  packages/pieces/community/stable-diffusion-webui/src/lib/actions/text-to-image.ts
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/vtiger/src/lib/triggers/new-or-updated-record.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/authentication/authentication-service/hooks/community-authentication-hooks.ts
  packages/server/api/src/app/ee/authentication/saml-authn/authn-sso-saml-service.ts
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/ee/project-plan/project-plan.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/shared/package.json
  packages/shared/src/lib/common/utils/utils.ts
  packages/ui/feature-flow-builder/package.json
  packages/ui/feature-tags/package.json
Labels: 🔌 pieces

#4973 fix: build issues in lodash
  packages/pieces/community/convertkit/package.json
  packages/pieces/community/framework/src/lib/validators/validators.ts
  packages/pieces/community/http/package.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/retune/package.json
  packages/pieces/community/saastic/package.json
  packages/pieces/community/vtiger/package.json
  packages/pieces/community/webhook/package.json
  packages/shared/src/lib/common/utils/utils.ts
Labels: skip-changelog

#4971 fix: improve form trigger UI/UX and made file inputs upload files in correct base64 format
  packages/ee/ui/platform/src/lib/components/dialogs/create-custom-domain-dialog/create-custom-domain-dialog.component.html
  packages/ee/ui/platform/src/lib/components/dialogs/domain-txt-validation-dialog/domain-txt-validation-dialog.component.html
  packages/ee/ui/platform/src/lib/components/dialogs/edit-add-piece-oauth-2-credentials-dialog/edit-add-piece-oauth-2-credentials-dialog.component.html
  packages/ee/ui/platform/src/lib/components/dialogs/enable-federated-authn-provider-dialog/enable-federated-authn-provider-dialog.component.html
  packages/ee/ui/platform/src/lib/components/dialogs/enable-saml-authn-provider-dialog.component/enable-saml-authn-provider-dialog.component.html
  packages/ee/ui/platform/src/lib/components/smtp-settings/smtp-settings.component.html
  packages/ui/common/src/lib/components/ap-markdown/ap-markdown.component.html
  packages/ui/common/src/lib/components/control-description/control-description.component.ts
  packages/ui/common/src/lib/components/upload-file-control/upload-file-control.component.ts
  packages/ui/common/src/lib/directives/check-overflow.directive.ts
  packages/ui/core/src/app/app-routing.module.ts
  packages/ui/core/src/app/app.module.ts
  packages/ui/core/src/app/modules/forms/forms.component.html
  packages/ui/core/src/app/modules/forms/forms.component.ts
  packages/ui/core/src/app/modules/forms/forms.resolver.ts
  packages/ui/core/src/app/modules/forms/forms.service.ts
  packages/ui/core/src/app/modules/forms/input-form-control.pipe.ts
  packages/ui/feature-builder-form-controls/src/index.ts
  packages/ui/feature-builder-form-controls/src/lib/components/code-artifact-form-control/code-artifact-control-fullscreen/add-npm-package-modal/add-npm-package-modal.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/piece-properties-form/piece-properties-form.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/piece-properties-form/properties-controls-helper.ts
  packages/ui/feature-builder-form-controls/src/lib/ui-feature-builder-form-controls.module.ts
  packages/ui/feature-builder-right-sidebar/src/lib/input-forms/code-step-input-form/code-writer-dialog/code-writer-dialog.component.html
  packages/ui/feature-connections/src/lib/components/dialogs/basic-auth-connection-dialog/basic-auth-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/components/dialogs/custom-auth-connection-dialog/custom-auth-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/components/dialogs/oauth2-connection-dialog/oauth2-connection-dialog.component.html
  packages/ui/feature-connections/src/lib/components/dialogs/secret-text-connection-dialog/secret-text-connection-dialog.component.html
  packages/ui/feature-dashboard/src/lib/components/alerts-table/alerts-table.component.html
  packages/ui/feature-dashboard/src/lib/components/issues-table/issues-table.component.html
  packages/ui/feature-pieces/src/lib/install-community-piece/install-community-piece-modal.component.html
Labels: auto-deploy

#4975 fix: mark all inputs as touched on submission in flow form
  packages/ui/core/src/app/modules/forms/forms.component.ts
Labels: skip-changelog, auto-deploy

#4915 feat(whatsapp): Send Template Message Action
  packages/pieces/community/whatsapp/package.json
  packages/pieces/community/whatsapp/src/index.ts
  packages/pieces/community/whatsapp/src/lib/actions/send-from-template.ts
  packages/pieces/community/whatsapp/src/lib/actions/send-media.ts
  packages/pieces/community/whatsapp/src/lib/actions/send-message.ts
  packages/pieces/community/whatsapp/src/lib/common/utils.ts
Labels: 🔌 pieces

#4976 fix: make "Toggle" input's value show up as a boolean instead of a string
  packages/ui/core/src/app/modules/forms/forms.component.ts
  packages/ui/core/src/app/modules/forms/forms.service.ts
Labels: auto-deploy

#4978 feat: option allow to propagate env variables to sandbox
  docs/install/configurations/environment-variables.mdx
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/src/lib/sandbox/file-sandbox.ts
  packages/server/worker/src/lib/sandbox/isolate-sandbox.ts
Labels: ⭐ enhancement

#4962 feat: add option to propagate some env vars to sandbox
  packages/server/shared/src/lib/system/system-prop.ts
  packages/server/shared/src/lib/system/system.ts
  packages/server/worker/src/lib/sandbox/file-sandbox.ts
  packages/server/worker/src/lib/sandbox/isolate-sandbox.ts
Labels: skip-changelog

#4974 feat(csv): revamp all actions
  package-lock.json
  package.json
  packages/pieces/community/csv/package.json
  packages/pieces/community/csv/src/index.ts
  packages/pieces/community/csv/src/lib/actions/convert-csv-to-json.ts
  packages/pieces/community/csv/src/lib/actions/convert-json-to-csv.ts
  packages/pieces/community/csv/src/lib/utils.ts
Labels: 🔌 pieces

#4983 feat: 0.28.0-rc.1
  package.json
Labels: pre-release

#4984 feat(worker): reuse same worker across runs
  packages/engine/src/main.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/server/worker/src/lib/engine/threads/worker.ts
Labels: 🌟 feature

#4989 fix: switching between "insert row" and "insert multiple row" steps, don't reset the values array anymore
  packages/ui/common/src/lib/components/loading-icon/loading-icon.component.scss
  packages/ui/feature-builder-form-controls/src/lib/components/dynamic-property-control/dynamic-property-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/piece-properties-form/piece-properties-form.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/piece-properties-form/piece-properties-form.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.html
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-dropdown-control/refreshable-dropdown-control.component.ts
  packages/ui/feature-builder-form-controls/src/lib/components/refreshable-property-core/refreshable-property-core-control.component.ts
Labels: 🐛 bug, auto-deploy

#4992 fix: show error message when template file is invalid in (import template dialog)
  packages/engine/test/handler/flow-with-response.test.ts
  packages/ui/common/src/lib/components/dialogs/import-flow-dialog/import-flow-dialog.component.html
  packages/ui/common/src/lib/components/dialogs/import-flow-dialog/import-flow-dialog.component.ts
Labels: 🐛 bug, auto-deploy

#5004 feat(google-sheets): add starting row option for get rows action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
Labels: 🔌 pieces

#4986 feat(gmail): add attachments in mail response
  packages/pieces/community/gmail-dev/package.json
  packages/pieces/community/gmail-dev/src/lib/triggers/new-email.ts
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/index.ts
  packages/pieces/community/gmail/src/lib/triggers/new-email.ts
Labels: 🔌 pieces

#5012 fix(intercom): merge with main
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
Labels: skip-changelog

#5013 fix: add author to gameball
  packages/pieces/community/gameball/.eslintrc.json
  packages/pieces/community/gameball/README.md
  packages/pieces/community/gameball/package.json
  packages/pieces/community/gameball/project.json
  packages/pieces/community/gameball/src/index.ts
  packages/pieces/community/gameball/src/lib/actions/send-event.ts
  packages/pieces/community/gameball/tsconfig.json
  packages/pieces/community/gameball/tsconfig.lib.json
  tsconfig.base.json
Labels: skip-changelog

#5011 feat(smtp): add senderName property
  packages/pieces/community/smtp/package.json
  packages/pieces/community/smtp/src/index.ts
  packages/pieces/community/smtp/src/lib/actions/send-email.ts
Labels: 🔌 pieces

#4985 feat(form): add generate sample data experience for form triggers
  packages/pieces/community/forms/package.json
  packages/pieces/community/forms/src/index.ts
  packages/pieces/community/forms/src/lib/triggers/file-trigger.ts
  packages/pieces/community/forms/src/lib/triggers/form-trigger.ts
  packages/pieces/community/math-helper/package.json
  packages/pieces/community/retune/package.json
  packages/pieces/community/vtiger/package.json
  packages/server/api/src/app/flows/flow/form/form.controller.ts
  packages/server/api/src/app/flows/flow/form/form.service.ts
  packages/server/api/src/app/flows/trigger/hooks/disable-trigger-hook.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/form.ts
  packages/ui/core/src/app/modules/forms/forms.component.ts
  packages/ui/core/src/app/modules/forms/forms.resolver.ts
  packages/ui/core/src/app/modules/forms/forms.service.ts
  packages/ui/feature-flow-builder/package.json
  packages/ui/feature-tags/package.json
Labels: 🌟 feature

#5008 feat(datocms): custom api call action
  packages/pieces/community/datocms/.eslintrc.json
  packages/pieces/community/datocms/README.md
  packages/pieces/community/datocms/package.json
  packages/pieces/community/datocms/project.json
  packages/pieces/community/datocms/src/index.ts
  packages/pieces/community/datocms/tsconfig.json
  packages/pieces/community/datocms/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#4950 feat(dynamics-crm): add port field for authentication
  packages/ee/pieces/microsoft-dynamics-crm/package.json
  packages/ee/pieces/microsoft-dynamics-crm/src/index.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/create-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/delete-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/get-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/actions/update-record.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/client.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/constants.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/index.ts
  packages/ee/pieces/microsoft-dynamics-crm/src/lib/common/types.ts
Labels: 🔌 pieces

#5016 fix: slack piece
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/add-reaction-to-message.ts
  packages/pieces/community/slack/src/lib/actions/create-channel.ts
  packages/pieces/community/slack/src/lib/actions/find-user-by-email.ts
  packages/pieces/community/slack/src/lib/actions/get-channel-history.ts
  packages/pieces/community/slack/src/lib/actions/request-action-message.ts
  packages/pieces/community/slack/src/lib/actions/request-approval-message.ts
  packages/pieces/community/slack/src/lib/actions/search-messages.ts
  packages/pieces/community/slack/src/lib/actions/send-direct-message-action.ts
  packages/pieces/community/slack/src/lib/actions/send-message-action.ts
  packages/pieces/community/slack/src/lib/actions/update-message.ts
  packages/pieces/community/slack/src/lib/actions/update-profile.ts
  packages/pieces/community/slack/src/lib/actions/upload-file.ts
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/common/utils.ts
  packages/pieces/community/slack/src/lib/triggers/new-channel.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
  packages/pieces/community/slack/src/lib/triggers/new-reaction-added.ts
Labels: skip-changelog

#5006 feat(slack): revamp the piece to use offical sdk / listing channels is now fixed.
  packages/pieces/community/framework/src/lib/property/input/index.ts
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/add-reaction-to-message.ts
  packages/pieces/community/slack/src/lib/actions/create-channel.ts
  packages/pieces/community/slack/src/lib/actions/find-user-by-email.ts
  packages/pieces/community/slack/src/lib/actions/get-channel-history.ts
  packages/pieces/community/slack/src/lib/actions/request-action-message.ts
  packages/pieces/community/slack/src/lib/actions/request-approval-message.ts
  packages/pieces/community/slack/src/lib/actions/search-messages.ts
  packages/pieces/community/slack/src/lib/actions/send-direct-message-action.ts
  packages/pieces/community/slack/src/lib/actions/send-message-action.ts
  packages/pieces/community/slack/src/lib/actions/update-message.ts
  packages/pieces/community/slack/src/lib/actions/update-profile.ts
  packages/pieces/community/slack/src/lib/actions/upload-file.ts
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/common/utils.ts
  packages/pieces/community/slack/src/lib/triggers/new-channel.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
  packages/pieces/community/slack/src/lib/triggers/new-reaction-added.ts
Labels: 🔌 pieces
