Repository activepieces/activepieces, pull requests merged in 2025-09, with the labels that each got.

#9009 fix: file properties inside dynamic props weren't working
  packages/pieces/community/video-ai/package.json
  packages/pieces/community/video-ai/src/index.ts
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/lib/navigation-utils.tsx
Labels: 🐛 bug

#8997 fix(project-releases): ignore table id in diff
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/table-diff.service.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/table-diff.test.ts
Labels: 🐛 bug

#8955 feat(piece-twilio): add new triggers and actions for #8953
  packages/pieces/community/twilio/package.json
  packages/pieces/community/twilio/src/index.ts
  packages/pieces/community/twilio/src/lib/action/download-recording-media.ts
  packages/pieces/community/twilio/src/lib/action/get-message.ts
  packages/pieces/community/twilio/src/lib/action/make-call.ts
  packages/pieces/community/twilio/src/lib/action/phone-number-lookup.ts
  packages/pieces/community/twilio/src/lib/trigger/new-call.ts
  packages/pieces/community/twilio/src/lib/trigger/new-phone-number.ts
  packages/pieces/community/twilio/src/lib/trigger/new-recording.ts
  packages/pieces/community/twilio/src/lib/trigger/new-transcription.ts
Labels: 🔌 pieces, 🙋 Bounty claim

#8965 feat: avoma piece
  packages/pieces/community/avoma/.eslintrc.json
  packages/pieces/community/avoma/README.md
  packages/pieces/community/avoma/package.json
  packages/pieces/community/avoma/project.json
  packages/pieces/community/avoma/src/index.ts
  packages/pieces/community/avoma/src/lib/actions/create-call.ts
  packages/pieces/community/avoma/src/lib/actions/get-meeting-recording.ts
  packages/pieces/community/avoma/src/lib/actions/get-meeting-transcription.ts
  packages/pieces/community/avoma/src/lib/actions/index.ts
  packages/pieces/community/avoma/src/lib/common/index.ts
  packages/pieces/community/avoma/src/lib/triggers/index.ts
  packages/pieces/community/avoma/src/lib/triggers/meeting-cancelled.ts
  packages/pieces/community/avoma/src/lib/triggers/meeting-rescheduled.ts
  packages/pieces/community/avoma/src/lib/triggers/new-meeting-scheduled.ts
  packages/pieces/community/avoma/src/lib/triggers/new-note.ts
  packages/pieces/community/avoma/tsconfig.json
  packages/pieces/community/avoma/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9015 feat: browserless piece
  packages/pieces/community/browserless/.eslintrc.json
  packages/pieces/community/browserless/README.md
  packages/pieces/community/browserless/package.json
  packages/pieces/community/browserless/project.json
  packages/pieces/community/browserless/src/index.ts
  packages/pieces/community/browserless/src/lib/actions/capture-screenshot.ts
  packages/pieces/community/browserless/src/lib/actions/generate-pdf.ts
  packages/pieces/community/browserless/src/lib/actions/get-website-performance.ts
  packages/pieces/community/browserless/src/lib/actions/run-bql-query.ts
  packages/pieces/community/browserless/src/lib/actions/scrape-url.ts
  packages/pieces/community/browserless/src/lib/common/auth.ts
  packages/pieces/community/browserless/src/lib/common/client.ts
  packages/pieces/community/browserless/tsconfig.json
  packages/pieces/community/browserless/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8976 feat: toggl piece
  packages/pieces/community/toggl-track/.eslintrc.json
  packages/pieces/community/toggl-track/README.md
  packages/pieces/community/toggl-track/package.json
  packages/pieces/community/toggl-track/project.json
  packages/pieces/community/toggl-track/src/index.ts
  packages/pieces/community/toggl-track/src/lib/actions/create-client.ts
  packages/pieces/community/toggl-track/src/lib/actions/create-project.ts
  packages/pieces/community/toggl-track/src/lib/actions/create-tag.ts
  packages/pieces/community/toggl-track/src/lib/actions/create-task.ts
  packages/pieces/community/toggl-track/src/lib/actions/create-time-entry.ts
  packages/pieces/community/toggl-track/src/lib/actions/find-client.ts
  packages/pieces/community/toggl-track/src/lib/actions/find-project.ts
  packages/pieces/community/toggl-track/src/lib/actions/find-tag.ts
  packages/pieces/community/toggl-track/src/lib/actions/find-task.ts
  packages/pieces/community/toggl-track/src/lib/actions/find-time-entry.ts
  packages/pieces/community/toggl-track/src/lib/actions/find-user.ts
  packages/pieces/community/toggl-track/src/lib/actions/start-time-entry.ts
  packages/pieces/community/toggl-track/src/lib/actions/stop-time-entry.ts
  packages/pieces/community/toggl-track/src/lib/common/index.ts
  packages/pieces/community/toggl-track/src/lib/common/webhook-instructions.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-client.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-project.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-tag.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-task.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-time-entry-started.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-time-entry.ts
  packages/pieces/community/toggl-track/src/lib/triggers/new-workspace.ts
  packages/pieces/community/toggl-track/tsconfig.json
  packages/pieces/community/toggl-track/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9025 feat: New translation files
  packages/pieces/community/avoma/src/i18n/translation.json
  packages/pieces/community/browserless/src/i18n/translation.json
  packages/pieces/community/predict-leads/src/i18n/translation.json
  packages/pieces/community/toggl-track/src/i18n/translation.json
  packages/pieces/community/twilio/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9026 New Crowdin updates
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/activepieces/src/i18n/fr.json
  packages/pieces/community/avoma/package.json
  packages/pieces/community/avoma/src/i18n/de.json
  packages/pieces/community/avoma/src/i18n/es.json
  packages/pieces/community/avoma/src/i18n/fr.json
  packages/pieces/community/avoma/src/i18n/ja.json
  packages/pieces/community/avoma/src/i18n/nl.json
  packages/pieces/community/avoma/src/i18n/pt.json
  packages/pieces/community/avoma/src/i18n/zh.json
  packages/pieces/community/browserless/package.json
  packages/pieces/community/browserless/src/i18n/de.json
  packages/pieces/community/browserless/src/i18n/es.json
  packages/pieces/community/browserless/src/i18n/fr.json
  packages/pieces/community/browserless/src/i18n/ja.json
  packages/pieces/community/browserless/src/i18n/nl.json
  packages/pieces/community/browserless/src/i18n/pt.json
  packages/pieces/community/browserless/src/i18n/zh.json
  packages/pieces/community/predict-leads/package.json
  packages/pieces/community/predict-leads/src/i18n/de.json
  packages/pieces/community/predict-leads/src/i18n/es.json
  packages/pieces/community/predict-leads/src/i18n/fr.json
  packages/pieces/community/predict-leads/src/i18n/ja.json
  packages/pieces/community/predict-leads/src/i18n/nl.json
  packages/pieces/community/predict-leads/src/i18n/pt.json
  packages/pieces/community/predict-leads/src/i18n/zh.json
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/i18n/fr.json
  packages/pieces/community/toggl-track/package.json
  packages/pieces/community/toggl-track/src/i18n/de.json
  packages/pieces/community/toggl-track/src/i18n/es.json
  packages/pieces/community/toggl-track/src/i18n/fr.json
  packages/pieces/community/toggl-track/src/i18n/ja.json
  packages/pieces/community/toggl-track/src/i18n/nl.json
  packages/pieces/community/toggl-track/src/i18n/pt.json
  packages/pieces/community/toggl-track/src/i18n/zh.json
  packages/pieces/community/twilio/package.json
  packages/pieces/community/twilio/src/i18n/de.json
  packages/pieces/community/twilio/src/i18n/es.json
  packages/pieces/community/twilio/src/i18n/fr.json
  packages/pieces/community/twilio/src/i18n/ja.json
  packages/pieces/community/twilio/src/i18n/nl.json
  packages/pieces/community/twilio/src/i18n/pt.json
  packages/pieces/community/twilio/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9024 fix: google drive read file from shared drive
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/common/get-file-content.ts
Labels: 💫 priority, 🧩 area/third-party-pieces

#9033 ci: build requires pieces for tests
  packages/engine/project.json
Labels: 🧹 clean up

#8986 feat: wealthbox piece
  packages/pieces/community/wealthbox/.eslintrc.json
  packages/pieces/community/wealthbox/README.md
  packages/pieces/community/wealthbox/package.json
  packages/pieces/community/wealthbox/project.json
  packages/pieces/community/wealthbox/src/index.ts
  packages/pieces/community/wealthbox/src/lib/actions/add-household-member.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-contact.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-event.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-household.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-note.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-opportunity.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-project.ts
  packages/pieces/community/wealthbox/src/lib/actions/create-task.ts
  packages/pieces/community/wealthbox/src/lib/actions/find-contact.ts
  packages/pieces/community/wealthbox/src/lib/actions/find-task.ts
  packages/pieces/community/wealthbox/src/lib/actions/index.ts
  packages/pieces/community/wealthbox/src/lib/actions/start-workflow.ts
  packages/pieces/community/wealthbox/src/lib/common/api-helpers.ts
  packages/pieces/community/wealthbox/src/lib/common/constants.ts
  packages/pieces/community/wealthbox/src/lib/common/index.ts
  packages/pieces/community/wealthbox/src/lib/common/types.ts
  packages/pieces/community/wealthbox/src/lib/triggers/index.ts
  packages/pieces/community/wealthbox/src/lib/triggers/new-contact.ts
  packages/pieces/community/wealthbox/src/lib/triggers/new-event.ts
  packages/pieces/community/wealthbox/src/lib/triggers/new-opportunity.ts
  packages/pieces/community/wealthbox/src/lib/triggers/new-task.ts
  packages/pieces/community/wealthbox/tsconfig.json
  packages/pieces/community/wealthbox/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9023 feat: adds (Nano Banana) to use in (generate image) action in (Image AI) piece
  .devcontainer/devcontainer.json
  docs/handbook/engineering/playbooks/run-ee.mdx
  package-lock.json
  packages/pieces/community/common-ai/package.json
  packages/pieces/community/common-ai/src/lib/ai-sdk.ts
  packages/pieces/community/common-ai/src/lib/pieces-props.ts
  packages/pieces/community/common-ai/src/lib/supported-ai-providers.ts
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/index.ts
  packages/pieces/community/image-ai/src/lib/actions/generate-image.ts
  packages/server/api/src/app/ai/providers/google.ts
  packages/server/api/src/app/database/seeds/dev-seeds.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/api/test/integration/cloud/ai/proxy.test.ts
  packages/server/worker/package.json
Labels: 🔌 pieces

#9034 chore: bump releases
  docker-compose.yml
  package.json
Labels: release

#9036 fix(google-sheets): handle onDisable error to allow flow saving
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: 🔌 pieces

#9039 feat: New translation files
  packages/pieces/community/predict-leads/src/i18n/translation.json
  packages/pieces/community/shopify/src/i18n/translation.json
  packages/pieces/community/wealthbox/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9043 feat: release 0.68.3
  docker-compose.yml
  package.json
Labels: release

#9050 feat: New translation files
  packages/pieces/community/netlify/src/i18n/translation.json
  packages/pieces/community/webscraping-ai/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9053 New Crowdin updates
  packages/pieces/community/netlify/package.json
  packages/pieces/community/netlify/src/i18n/de.json
  packages/pieces/community/netlify/src/i18n/es.json
  packages/pieces/community/netlify/src/i18n/fr.json
  packages/pieces/community/netlify/src/i18n/ja.json
  packages/pieces/community/netlify/src/i18n/nl.json
  packages/pieces/community/netlify/src/i18n/pt.json
  packages/pieces/community/netlify/src/i18n/zh.json
  packages/pieces/community/webscraping-ai/package.json
  packages/pieces/community/webscraping-ai/src/i18n/de.json
  packages/pieces/community/webscraping-ai/src/i18n/es.json
  packages/pieces/community/webscraping-ai/src/i18n/fr.json
  packages/pieces/community/webscraping-ai/src/i18n/ja.json
  packages/pieces/community/webscraping-ai/src/i18n/nl.json
  packages/pieces/community/webscraping-ai/src/i18n/pt.json
  packages/pieces/community/webscraping-ai/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9061 feat: textcortex-ai piece
  packages/pieces/community/textcortex-ai/.eslintrc.json
  packages/pieces/community/textcortex-ai/README.md
  packages/pieces/community/textcortex-ai/package.json
  packages/pieces/community/textcortex-ai/project.json
  packages/pieces/community/textcortex-ai/src/index.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-code.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-email.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-paraphrase.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-product-description.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-social-caption.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-summary.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/create-translation.ts
  packages/pieces/community/textcortex-ai/src/lib/actions/send-prompt.ts
  packages/pieces/community/textcortex-ai/src/lib/common/auth.ts
  packages/pieces/community/textcortex-ai/src/lib/common/client.ts
  packages/pieces/community/textcortex-ai/src/lib/common/common.ts
  packages/pieces/community/textcortex-ai/tsconfig.json
  packages/pieces/community/textcortex-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9075 feat: New translation files
  packages/pieces/community/assembled/src/i18n/translation.json
  packages/pieces/community/bika/src/i18n/translation.json
  packages/pieces/community/dittofeed/src/i18n/translation.json
  packages/pieces/community/predict-leads/src/i18n/translation.json
  packages/pieces/community/simpliroute/src/i18n/translation.json
  packages/pieces/community/textcortex-ai/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9079 fix: remove db call on check for pieces cache
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/helper/local-piece-cache.ts
Labels: 🐛 bug

#9095 chore: use pm2 to cluster app server instances (process per core)
  Dockerfile
  docker-entrypoint.sh
Labels: 🛠️ area/infrastructure

#9097 fix(ai providers): non search anthropic requests
  packages/server/api/src/app/ai/providers/anthropic.ts
  packages/server/api/test/integration/cloud/ai/proxy.test.ts
Labels: 🐛 bug

#9098 refactor: remove cleanup queue from redis rate limiter
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
  packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
Labels: 🐛 bug

#9101 feat: New translation files
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9105 fix: rate limit clean up
  packages/server/api/src/app/workers/queue/migration/unify-old-queues-to-one.ts
  packages/server/api/src/app/workers/redis/redis-consumer.ts
  packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
Labels: 🐛 bug

#9059 feat(pieces): docsbot
  packages/pieces/community/docsbot/.eslintrc.json
  packages/pieces/community/docsbot/README.md
  packages/pieces/community/docsbot/package.json
  packages/pieces/community/docsbot/project.json
  packages/pieces/community/docsbot/src/index.ts
  packages/pieces/community/docsbot/src/lib/actions/ask-question.ts
  packages/pieces/community/docsbot/src/lib/actions/create-bot.ts
  packages/pieces/community/docsbot/src/lib/actions/create-source.ts
  packages/pieces/community/docsbot/src/lib/actions/find-bot.ts
  packages/pieces/community/docsbot/src/lib/actions/upload-source-file.ts
  packages/pieces/community/docsbot/src/lib/common/index.ts
  packages/pieces/community/docsbot/src/lib/common/properties.ts
  packages/pieces/community/docsbot/src/lib/common/schemas.ts
  packages/pieces/community/docsbot/src/lib/common/types.ts
  packages/pieces/community/docsbot/tsconfig.json
  packages/pieces/community/docsbot/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9107 chore(docsbot): bump piece version to 0.0.2
  packages/pieces/community/docsbot/package.json
Labels: 🔌 pieces

#9072 feat(microsoft-outlook): new 7 actions and 2 triggers
  packages/pieces/community/microsoft-outlook/package.json
  packages/pieces/community/microsoft-outlook/src/index.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/add-label-to-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/create-draft-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/find-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/forward-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/move-email-to-folder.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/remove-label-from-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/reply-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/actions/send-draft-email.ts
  packages/pieces/community/microsoft-outlook/src/lib/common/props.ts
  packages/pieces/community/microsoft-outlook/src/lib/triggers/new-attachment.ts
  packages/pieces/community/microsoft-outlook/src/lib/triggers/new-email-in-folder.ts
Labels: 🔌 pieces, 🙋 Bounty claim

#9106 feat: murf api
  packages/pieces/community/murf-api/.eslintrc.json
  packages/pieces/community/murf-api/README.md
  packages/pieces/community/murf-api/package.json
  packages/pieces/community/murf-api/project.json
  packages/pieces/community/murf-api/src/index.ts
  packages/pieces/community/murf-api/src/lib/actions/list-voices.ts
  packages/pieces/community/murf-api/src/lib/actions/text-to-speech.ts
  packages/pieces/community/murf-api/src/lib/actions/translate-text.ts
  packages/pieces/community/murf-api/src/lib/actions/voice-change.ts
  packages/pieces/community/murf-api/src/lib/common/auth.ts
  packages/pieces/community/murf-api/src/lib/common/client.ts
  packages/pieces/community/murf-api/src/lib/common/dropdown.ts
  packages/pieces/community/murf-api/tsconfig.json
  packages/pieces/community/murf-api/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#9102 feat(piece): Zoho Campaigns
  packages/pieces/community/zoho-campaigns/.eslintrc.json
  packages/pieces/community/zoho-campaigns/README.md
  packages/pieces/community/zoho-campaigns/package.json
  packages/pieces/community/zoho-campaigns/project.json
  packages/pieces/community/zoho-campaigns/src/index.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/add-contact-to-mailing-list.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/add-tag-to-contact.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/add-update-contact.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/clone-campaign.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/create-campaign.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/find-campaign.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/find-contact.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/remove-tag.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/send-campaign.ts
  packages/pieces/community/zoho-campaigns/src/lib/actions/unsubscribe-contact.ts
  packages/pieces/community/zoho-campaigns/src/lib/common/index.ts
  packages/pieces/community/zoho-campaigns/src/lib/common/properties.ts
  packages/pieces/community/zoho-campaigns/src/lib/common/schemas.ts
  packages/pieces/community/zoho-campaigns/src/lib/common/types.ts
  packages/pieces/community/zoho-campaigns/src/lib/triggers/new-campaign.ts
  packages/pieces/community/zoho-campaigns/src/lib/triggers/new-contact.ts
  packages/pieces/community/zoho-campaigns/src/lib/triggers/unsubscribe.ts
  packages/pieces/community/zoho-campaigns/tsconfig.json
  packages/pieces/community/zoho-campaigns/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9130 fix: importing templates was broken
  packages/server/api/src/app/flows/flow/flow.controller.ts
Labels: 🐛 bug

#9150 fix: squash crowdin pr before merge
  .github/workflows/crowdin-pr-merger.yml
Labels: skip-changelog

#9136 fix(bika): fix missing fields on create and update
  packages/pieces/community/bika/package.json
  packages/pieces/community/bika/src/lib/common/index.ts
Labels: 🔌 pieces

#9161 New Crowdin updates
  packages/pieces/community/cometapi/package.json
  packages/pieces/community/cometapi/src/i18n/de.json
  packages/pieces/community/cometapi/src/i18n/es.json
  packages/pieces/community/cometapi/src/i18n/fr.json
  packages/pieces/community/cometapi/src/i18n/ja.json
  packages/pieces/community/cometapi/src/i18n/nl.json
  packages/pieces/community/cometapi/src/i18n/pt.json
  packages/pieces/community/cometapi/src/i18n/zh.json
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/i18n/de.json
  packages/pieces/community/github/src/i18n/es.json
  packages/pieces/community/github/src/i18n/fr.json
  packages/pieces/community/github/src/i18n/ja.json
  packages/pieces/community/github/src/i18n/nl.json
  packages/pieces/community/github/src/i18n/pt.json
  packages/pieces/community/github/src/i18n/zh.json
  packages/pieces/community/googlechat/package.json
  packages/pieces/community/googlechat/src/i18n/de.json
  packages/pieces/community/googlechat/src/i18n/es.json
  packages/pieces/community/googlechat/src/i18n/fr.json
  packages/pieces/community/googlechat/src/i18n/ja.json
  packages/pieces/community/googlechat/src/i18n/nl.json
  packages/pieces/community/googlechat/src/i18n/pt.json
  packages/pieces/community/googlechat/src/i18n/zh.json
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/i18n/de.json
  packages/pieces/community/jira-cloud/src/i18n/es.json
  packages/pieces/community/jira-cloud/src/i18n/fr.json
  packages/pieces/community/jira-cloud/src/i18n/ja.json
  packages/pieces/community/jira-cloud/src/i18n/nl.json
  packages/pieces/community/jira-cloud/src/i18n/pt.json
  packages/pieces/community/jira-cloud/src/i18n/zh.json
  packages/pieces/community/shopify/package.json
  packages/pieces/community/shopify/src/i18n/de.json
  packages/pieces/community/shopify/src/i18n/es.json
  packages/pieces/community/shopify/src/i18n/fr.json
  packages/pieces/community/shopify/src/i18n/ja.json
  packages/pieces/community/shopify/src/i18n/nl.json
  packages/pieces/community/shopify/src/i18n/pt.json
  packages/pieces/community/shopify/src/i18n/zh.json
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/i18n/fr.json
  packages/pieces/community/twilio/package.json
  packages/pieces/community/twilio/src/i18n/de.json
  packages/pieces/community/twilio/src/i18n/es.json
  packages/pieces/community/twilio/src/i18n/fr.json
  packages/pieces/community/twilio/src/i18n/ja.json
  packages/pieces/community/twilio/src/i18n/nl.json
  packages/pieces/community/twilio/src/i18n/pt.json
  packages/pieces/community/twilio/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9164 fix(project releases): update stale UI diff state and compare using deep-equal
  packages/react-ui/src/app/routes/project-release/apply-plan.tsx
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/flow-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/table-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-state-helper.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-state.service.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/flow-diff.test.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/table-diff.test.ts
  packages/server/api/test/unit/app/ee/project-state/flow-apply.test.ts
Labels: 🐛 bug

#9162 feat(copper): implemented piece
  packages/pieces/community/copper/.eslintrc.json
  packages/pieces/community/copper/README.md
  packages/pieces/community/copper/package.json
  packages/pieces/community/copper/project.json
  packages/pieces/community/copper/src/index.ts
  packages/pieces/community/copper/src/lib/actions/convert-lead.ts
  packages/pieces/community/copper/src/lib/actions/create-activity.ts
  packages/pieces/community/copper/src/lib/actions/create-company.ts
  packages/pieces/community/copper/src/lib/actions/create-lead.ts
  packages/pieces/community/copper/src/lib/actions/create-opportunity.ts
  packages/pieces/community/copper/src/lib/actions/create-person.ts
  packages/pieces/community/copper/src/lib/actions/create-project.ts
  packages/pieces/community/copper/src/lib/actions/create-task.ts
  packages/pieces/community/copper/src/lib/actions/search-for-a-company.ts
  packages/pieces/community/copper/src/lib/actions/search-for-a-lead.ts
  packages/pieces/community/copper/src/lib/actions/search-for-a-person.ts
  packages/pieces/community/copper/src/lib/actions/search-for-a-project.ts
  packages/pieces/community/copper/src/lib/actions/search-for-an-activity.ts
  packages/pieces/community/copper/src/lib/actions/search-for-an-opportunity.ts
  packages/pieces/community/copper/src/lib/actions/update-company.ts
  packages/pieces/community/copper/src/lib/actions/update-lead.ts
  packages/pieces/community/copper/src/lib/actions/update-opportunity.ts
  packages/pieces/community/copper/src/lib/actions/update-person.ts
  packages/pieces/community/copper/src/lib/actions/update-project.ts
  packages/pieces/community/copper/src/lib/common/constants.ts
  packages/pieces/community/copper/src/lib/common/props.ts
  packages/pieces/community/copper/src/lib/common/requests.ts
  packages/pieces/community/copper/src/lib/triggers/new-activity.ts
  packages/pieces/community/copper/src/lib/triggers/new-lead.ts
  packages/pieces/community/copper/src/lib/triggers/new-person.ts
  packages/pieces/community/copper/src/lib/triggers/new-task.ts
  packages/pieces/community/copper/src/lib/triggers/updated-lead-status.ts
  packages/pieces/community/copper/src/lib/triggers/updated-lead.ts
  packages/pieces/community/copper/src/lib/triggers/updated-opportunity-stage.ts
  packages/pieces/community/copper/src/lib/triggers/updated-opportunity-status.ts
  packages/pieces/community/copper/src/lib/triggers/updated-opportunity.ts
  packages/pieces/community/copper/src/lib/triggers/updated-project.ts
  packages/pieces/community/copper/src/lib/triggers/updated-task.ts
  packages/pieces/community/copper/tsconfig.json
  packages/pieces/community/copper/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces

#9200 fix: make flows table scrollable on small screens
  packages/react-ui/src/app/routes/flows/flows-table/index.tsx
Labels: 🐛 bug

#9201 fix: make flows table take full available width
  packages/react-ui/src/app/routes/flows/flows-table/index.tsx
Labels: skip-changelog

#9202 fix: step saving was getting triggered on viewing step without any change
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
  packages/react-ui/src/features/pieces/lib/form-utils.tsx
  packages/react-ui/src/features/pieces/lib/piece-selector-utils.ts
Labels: 🐛 bug

#9209 fix: create folder dialog was creating folder if you clicked cancel + dragging step wasn't function properly with the navigation sidebar expanded
  packages/react-ui/src/app/builder/builder-flow-status-section/index.tsx
  packages/react-ui/src/app/builder/flow-canvas/flow-drag-layer.tsx
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/app/builder/flow-canvas/step-drag-overlay.tsx
  packages/react-ui/src/app/builder/flow-canvas/utils/consts.ts
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
  packages/react-ui/src/app/builder/flow-versions/index.tsx
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/components/sidebar/builder/flows-navigation.tsx
  packages/react-ui/src/app/components/sidebar/builder/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/components/json-viewer.tsx
  packages/react-ui/src/components/ui/resizable-panel.tsx
  packages/react-ui/src/components/ui/sidebar-shadcn.tsx
  packages/react-ui/src/features/flows/components/flow-version-state-dot.tsx
  packages/react-ui/src/features/folders/component/create-folder-dialog.tsx
  packages/react-ui/src/features/pieces/lib/form-utils.tsx
Labels: 🐛 bug

#9222 feat: New translation files
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9230 feat: release 0.69.0
  docker-compose.yml
  package.json
Labels: release

#9238 fix: "apply tags" button was not showing when you have a long list of tags under platform admin -> pieces page
  package-lock.json
  packages/react-ui/src/app/routes/platform/setup/pieces/apply-tags.tsx
Labels: 🐛 bug

#9224 feat(aidbase): Implement piece
  packages/pieces/community/aidbase/.eslintrc.json
  packages/pieces/community/aidbase/README.md
  packages/pieces/community/aidbase/package.json
  packages/pieces/community/aidbase/project.json
  packages/pieces/community/aidbase/src/index.ts
  packages/pieces/community/aidbase/src/lib/actions/add-faq-item.ts
  packages/pieces/community/aidbase/src/lib/actions/add-video.ts
  packages/pieces/community/aidbase/src/lib/actions/add-website.ts
  packages/pieces/community/aidbase/src/lib/actions/create-chatbot-reply.ts
  packages/pieces/community/aidbase/src/lib/actions/create-faq.ts
  packages/pieces/community/aidbase/src/lib/actions/start-training.ts
  packages/pieces/community/aidbase/src/lib/common/auth.ts
  packages/pieces/community/aidbase/src/lib/common/client.ts
  packages/pieces/community/aidbase/src/lib/common/props.ts
  packages/pieces/community/aidbase/src/lib/common/types.ts
  packages/pieces/community/aidbase/src/lib/triggers/email-priority-changed.ts
  packages/pieces/community/aidbase/src/lib/triggers/email-received.ts
  packages/pieces/community/aidbase/src/lib/triggers/email-sent.ts
  packages/pieces/community/aidbase/src/lib/triggers/email-status-changed.ts
  packages/pieces/community/aidbase/src/lib/triggers/ticket-created.ts
  packages/pieces/community/aidbase/src/lib/triggers/ticket-new-comment.ts
  packages/pieces/community/aidbase/src/lib/triggers/ticket-priority-changed.ts
  packages/pieces/community/aidbase/src/lib/triggers/ticket-status-changed.ts
  packages/pieces/community/aidbase/tsconfig.json
  packages/pieces/community/aidbase/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#9242 fix(jire): new issue trigger
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/lib/common/index.ts
Labels: 🔌 pieces

#9241 fix: don't parse stringified jsons for sample data + save null/undefined sample data response
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/step-run/sample-data.service.ts
  packages/server/worker/src/index.ts
  packages/shared/package.json
  packages/shared/src/lib/flows/sample-data/index.ts
Labels: 🐛 bug

#9249 New Crowdin updates
  packages/pieces/community/aidbase/package.json
  packages/pieces/community/aidbase/src/i18n/de.json
  packages/pieces/community/aidbase/src/i18n/es.json
  packages/pieces/community/aidbase/src/i18n/fr.json
  packages/pieces/community/aidbase/src/i18n/ja.json
  packages/pieces/community/aidbase/src/i18n/nl.json
  packages/pieces/community/aidbase/src/i18n/pt.json
  packages/pieces/community/aidbase/src/i18n/zh.json
  packages/pieces/community/bumpups/package.json
  packages/pieces/community/bumpups/src/i18n/de.json
  packages/pieces/community/bumpups/src/i18n/es.json
  packages/pieces/community/bumpups/src/i18n/fr.json
  packages/pieces/community/bumpups/src/i18n/ja.json
  packages/pieces/community/bumpups/src/i18n/nl.json
  packages/pieces/community/bumpups/src/i18n/pt.json
  packages/pieces/community/bumpups/src/i18n/zh.json
  packages/pieces/community/jogg-ai/package.json
  packages/pieces/community/jogg-ai/src/i18n/de.json
  packages/pieces/community/jogg-ai/src/i18n/es.json
  packages/pieces/community/jogg-ai/src/i18n/fr.json
  packages/pieces/community/jogg-ai/src/i18n/ja.json
  packages/pieces/community/jogg-ai/src/i18n/nl.json
  packages/pieces/community/jogg-ai/src/i18n/pt.json
  packages/pieces/community/jogg-ai/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9250 fix: move Contiguity to v2 of API
  packages/pieces/community/contiguity/.gitignore
  packages/pieces/community/contiguity/package.json
  packages/pieces/community/contiguity/src/index.ts
  packages/pieces/community/contiguity/src/lib/actions/send-sms.ts
  packages/pieces/community/contiguity/src/lib/actions/send/imessage.ts
  packages/pieces/community/contiguity/src/lib/actions/send/text.ts
  packages/pieces/community/contiguity/src/lib/common/http-client.ts
  packages/pieces/community/contiguity/src/lib/common/request.ts
Labels: 🔌 pieces, 🧩 area/third-party-pieces

#9232 feat(pieces): implement VLM Run piece
  packages/pieces/community/vlm-run/.eslintrc.json
  packages/pieces/community/vlm-run/README.md
  packages/pieces/community/vlm-run/package.json
  packages/pieces/community/vlm-run/project.json
  packages/pieces/community/vlm-run/src/index.ts
  packages/pieces/community/vlm-run/src/lib/actions/analyze-audio.ts
  packages/pieces/community/vlm-run/src/lib/actions/analyze-document.ts
  packages/pieces/community/vlm-run/src/lib/actions/analyze-image.ts
  packages/pieces/community/vlm-run/src/lib/actions/analyze-video.ts
  packages/pieces/community/vlm-run/src/lib/actions/get-file.ts
  packages/pieces/community/vlm-run/src/lib/common/index.ts
  packages/pieces/community/vlm-run/src/lib/common/properties.ts
  packages/pieces/community/vlm-run/src/lib/common/schemas.ts
  packages/pieces/community/vlm-run/src/lib/common/types.ts
  packages/pieces/community/vlm-run/tsconfig.json
  packages/pieces/community/vlm-run/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces

#9259 feat: Slidespeak
  packages/pieces/community/slidespeak/.eslintrc.json
  packages/pieces/community/slidespeak/README.md
  packages/pieces/community/slidespeak/package.json
  packages/pieces/community/slidespeak/project.json
  packages/pieces/community/slidespeak/src/index.ts
  packages/pieces/community/slidespeak/src/lib/actions/create-presentation.ts
  packages/pieces/community/slidespeak/src/lib/actions/edit-presentation.ts
  packages/pieces/community/slidespeak/src/lib/actions/get-task-status.ts
  packages/pieces/community/slidespeak/src/lib/actions/upload-document.ts
  packages/pieces/community/slidespeak/src/lib/common/constants.ts
  packages/pieces/community/slidespeak/src/lib/triggers/new-presentation.ts
  packages/pieces/community/slidespeak/tsconfig.json
  packages/pieces/community/slidespeak/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#9264 New Crowdin updates
  packages/pieces/community/contiguity/package.json
  packages/pieces/community/contiguity/src/i18n/de.json
  packages/pieces/community/contiguity/src/i18n/es.json
  packages/pieces/community/contiguity/src/i18n/fr.json
  packages/pieces/community/contiguity/src/i18n/ja.json
  packages/pieces/community/contiguity/src/i18n/nl.json
  packages/pieces/community/contiguity/src/i18n/pt.json
  packages/pieces/community/contiguity/src/i18n/zh.json
  packages/pieces/community/foreplay-co/package.json
  packages/pieces/community/foreplay-co/src/i18n/de.json
  packages/pieces/community/foreplay-co/src/i18n/es.json
  packages/pieces/community/foreplay-co/src/i18n/fr.json
  packages/pieces/community/foreplay-co/src/i18n/ja.json
  packages/pieces/community/foreplay-co/src/i18n/nl.json
  packages/pieces/community/foreplay-co/src/i18n/pt.json
  packages/pieces/community/foreplay-co/src/i18n/zh.json
  packages/pieces/community/gamma/package.json
  packages/pieces/community/gamma/src/i18n/de.json
  packages/pieces/community/gamma/src/i18n/es.json
  packages/pieces/community/gamma/src/i18n/fr.json
  packages/pieces/community/gamma/src/i18n/ja.json
  packages/pieces/community/gamma/src/i18n/nl.json
  packages/pieces/community/gamma/src/i18n/pt.json
  packages/pieces/community/gamma/src/i18n/zh.json
  packages/pieces/community/magical-api/package.json
  packages/pieces/community/magical-api/src/i18n/de.json
  packages/pieces/community/magical-api/src/i18n/es.json
  packages/pieces/community/magical-api/src/i18n/fr.json
  packages/pieces/community/magical-api/src/i18n/ja.json
  packages/pieces/community/magical-api/src/i18n/nl.json
  packages/pieces/community/magical-api/src/i18n/pt.json
  packages/pieces/community/magical-api/src/i18n/zh.json
  packages/pieces/community/slidespeak/package.json
  packages/pieces/community/slidespeak/src/i18n/de.json
  packages/pieces/community/slidespeak/src/i18n/es.json
  packages/pieces/community/slidespeak/src/i18n/fr.json
  packages/pieces/community/slidespeak/src/i18n/ja.json
  packages/pieces/community/slidespeak/src/i18n/nl.json
  packages/pieces/community/slidespeak/src/i18n/pt.json
  packages/pieces/community/slidespeak/src/i18n/zh.json
  packages/pieces/community/vlm-run/package.json
  packages/pieces/community/vlm-run/src/i18n/de.json
  packages/pieces/community/vlm-run/src/i18n/es.json
  packages/pieces/community/vlm-run/src/i18n/fr.json
  packages/pieces/community/vlm-run/src/i18n/ja.json
  packages/pieces/community/vlm-run/src/i18n/nl.json
  packages/pieces/community/vlm-run/src/i18n/pt.json
  packages/pieces/community/vlm-run/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9271 fix: handshake timing issue
  packages/server/api/src/app/database/migration/postgres/1758108135968-DeleteHandshakeFromTriggerSource.ts
  packages/server/api/src/app/database/migration/sqlite/1758108281602-DeleteHandshakeFromTriggerSourceSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/trigger/trigger-source/flow-trigger-side-effect.ts
  packages/server/api/src/app/trigger/trigger-source/trigger-source-entity.ts
  packages/server/api/src/app/trigger/trigger-source/trigger-source-service.ts
  packages/server/api/src/app/trigger/trigger-source/trigger-utils.ts
  packages/server/api/src/app/webhooks/handshake-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/shared/src/lib/trigger/index.ts
Labels: 🐛 bug

#9268 feat: Added a load more button in the runs list inside the builder
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
  packages/react-ui/src/app/builder/run-details/index.tsx
  packages/react-ui/src/app/builder/run-list/flow-run-card.tsx
  packages/react-ui/src/app/builder/run-list/index.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/components/platform-layout.tsx
  packages/react-ui/src/app/components/project-dashboard-layout.tsx
  packages/react-ui/src/components/ui/virtualized-scroll-area.tsx
  packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx
  packages/server/api/src/app/flows/flow-run/flow-run-hooks.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
  packages/server/api/src/app/flows/flow-run/step-run-progress.handler.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🌟 feature

#9272 fix(tables): update record data fields should not depend on record id
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/lib/actions/update-record.ts
  packages/pieces/community/tables/src/lib/triggers/updated-record.ts
Labels: 🔌 pieces

#9278 fix: inserting templates in platform admin
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/builder/run-list/index.tsx
  packages/react-ui/src/app/components/sidebar/builder/flows-navigation.tsx
  packages/react-ui/src/app/routes/platform/setup/templates/upsert-template-dialog.tsx
  packages/react-ui/src/features/flows/lib/flows-hooks.ts
Labels: 🐛 bug

#9283 feat: enhance preview environments github actions
  .github/workflows/remove-environment.yml
  .github/workflows/setup-environment.yml
  packages/engine/src/main.ts
Labels: preview

#9292 fix: stop linking packages that aren't built for development mode
  packages/server/worker/src/lib/piece-manager/local-piece-manager.ts
Labels: 🐛 bug, skip-changelog

#9252 fix(hubspot): Avoid triggering on non-stage related changes
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/lib/triggers/deal-stage-updated.ts
Labels: 🔌 pieces, 💫 priority

#9323 feat: add parameter for embed sdk to hide page headers
  docs/embedding/embed-builder.mdx
  docs/embedding/sdk-changelog.mdx
  packages/ee/ui/embed-sdk/src/index.ts
  packages/react-ui/src/app/components/sidebar/dashboard/index.tsx
  packages/react-ui/src/app/components/sidebar/sidebar-user.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/app/routes/project-release/index.tsx
  packages/react-ui/src/components/custom/dashboard-page-header.tsx
  packages/react-ui/src/components/embed-provider.tsx
  packages/react-ui/src/components/ui/data-table/data-table-toolbar.tsx
Labels: embedding

#9345 feat: New translation files
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9350 New Crowdin updates
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9269 feat(airtable): peice
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/index.ts
  packages/pieces/community/airtable/src/lib/actions/add-comment-to-record.ts
  packages/pieces/community/airtable/src/lib/actions/create-base.ts
  packages/pieces/community/airtable/src/lib/actions/create-table.ts
  packages/pieces/community/airtable/src/lib/actions/find-base.ts
  packages/pieces/community/airtable/src/lib/actions/find-record-by-id.ts
  packages/pieces/community/airtable/src/lib/actions/find-table-by-id.ts
  packages/pieces/community/airtable/src/lib/actions/find-table.ts
  packages/pieces/community/airtable/src/lib/actions/get-base-schema.ts
  packages/pieces/community/airtable/src/lib/common/index.ts
  packages/pieces/community/airtable/src/lib/common/models.ts
Labels: 🙋 Bounty claim

#9358 fix(woocommerce): add test data func for triggers
  packages/pieces/community/woocommerce/package.json
  packages/pieces/community/woocommerce/src/lib/triggers/index.ts
  packages/pieces/community/woocommerce/src/lib/triggers/register-trigger.ts
Labels: 🔌 pieces

#9303 feat: front
  packages/pieces/community/front/.eslintrc.json
  packages/pieces/community/front/README.md
  packages/pieces/community/front/package.json
  packages/pieces/community/front/project.json
  packages/pieces/community/front/src/index.ts
  packages/pieces/community/front/src/lib/actions/add-comment.ts
  packages/pieces/community/front/src/lib/actions/add-contact-handle.ts
  packages/pieces/community/front/src/lib/actions/add-conversation-links.ts
  packages/pieces/community/front/src/lib/actions/add-conversation-tags.ts
  packages/pieces/community/front/src/lib/actions/assign-unassign-conversation.ts
  packages/pieces/community/front/src/lib/actions/create-account.ts
  packages/pieces/community/front/src/lib/actions/create-contact.ts
  packages/pieces/community/front/src/lib/actions/create-draft-reply.ts
  packages/pieces/community/front/src/lib/actions/create-draft.ts
  packages/pieces/community/front/src/lib/actions/create-link.ts
  packages/pieces/community/front/src/lib/actions/find-account.ts
  packages/pieces/community/front/src/lib/actions/find-contact.ts
  packages/pieces/community/front/src/lib/actions/find-conversation.ts
  packages/pieces/community/front/src/lib/actions/remove-contact-handle.ts
  packages/pieces/community/front/src/lib/actions/remove-conversation-links.ts
  packages/pieces/community/front/src/lib/actions/remove-conversation-tags.ts
  packages/pieces/community/front/src/lib/actions/send-message.ts
  packages/pieces/community/front/src/lib/actions/send-reply.ts
  packages/pieces/community/front/src/lib/actions/update-account.ts
  packages/pieces/community/front/src/lib/actions/update-contact.ts
  packages/pieces/community/front/src/lib/actions/update-conversation.ts
  packages/pieces/community/front/src/lib/actions/update-link.ts
  packages/pieces/community/front/src/lib/common/auth.ts
  packages/pieces/community/front/src/lib/common/client.ts
  packages/pieces/community/front/src/lib/common/dropdown.ts
  packages/pieces/community/front/src/lib/triggers/new-comment.ts
  packages/pieces/community/front/src/lib/triggers/new-conversation-state-change.ts
  packages/pieces/community/front/src/lib/triggers/new-inbound-message.ts
  packages/pieces/community/front/src/lib/triggers/new-outbound-message.ts
  packages/pieces/community/front/src/lib/triggers/new-tag-added-to-message.ts
  packages/pieces/community/front/tsconfig.json
  packages/pieces/community/front/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces

#9363 docs: update contributing guide link to the building pieces section
  CONTRIBUTING.md
Labels: 📚 documentation

#9373 New Crowdin updates
  packages/pieces/community/airtable/package.json
  packages/pieces/community/airtable/src/i18n/de.json
  packages/pieces/community/airtable/src/i18n/es.json
  packages/pieces/community/airtable/src/i18n/fr.json
  packages/pieces/community/airtable/src/i18n/ja.json
  packages/pieces/community/airtable/src/i18n/nl.json
  packages/pieces/community/airtable/src/i18n/pt.json
  packages/pieces/community/airtable/src/i18n/zh.json
  packages/pieces/community/front/package.json
  packages/pieces/community/front/src/i18n/de.json
  packages/pieces/community/front/src/i18n/es.json
  packages/pieces/community/front/src/i18n/fr.json
  packages/pieces/community/front/src/i18n/ja.json
  packages/pieces/community/front/src/i18n/nl.json
  packages/pieces/community/front/src/i18n/pt.json
  packages/pieces/community/front/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9307 feat: revamp e2e testing
  .github/workflows/e2e-tests-checkly.yml
  .github/workflows/e2e.yml
  .github/workflows/tests-e2e-ce.yml
  .github/workflows/tests-e2e-cloud.yml
  .github/workflows/tests-e2e-ee.yml
  .github/workflows/unified-automate-deploy.yml
  package.json
  packages/react-ui/src/app/builder/flow-canvas/edges/add-button.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-card-item.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/first-time-testing-section.tsx
  packages/react-ui/src/components/ui/search-input.tsx
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
  packages/react-ui/src/features/authentication/components/sign-up-form.tsx
  packages/react-ui/src/features/billing/components/trial-dialog.tsx
  packages/server/api/src/app/authentication/authentication-utils.ts
  packages/server/api/src/app/authentication/authentication.service.ts
  packages/server/worker/src/lib/utils/machine.ts
  packages/tests-e2e/.env.e2e
  packages/tests-e2e/checkly.config.ts
  packages/tests-e2e/fixtures/index.ts
  packages/tests-e2e/fixtures/users.ts
  packages/tests-e2e/helper/config.ts
  packages/tests-e2e/pages/agent.page.ts
  packages/tests-e2e/pages/authentication.page.ts
  packages/tests-e2e/pages/base.ts
  packages/tests-e2e/pages/builder.page.ts
  packages/tests-e2e/pages/flows.page.ts
  packages/tests-e2e/pages/index.ts
  packages/tests-e2e/playwright.config.ts
  packages/tests-e2e/project.json
  packages/tests-e2e/scenarios/ce/authentication/signin.check.ts
  packages/tests-e2e/scenarios/ce/authentication/signin.spec.ts
  packages/tests-e2e/scenarios/ce/authentication/signup.check.ts
  packages/tests-e2e/scenarios/ce/authentication/signup.spec.ts
  packages/tests-e2e/scenarios/ce/flows/webhook-should-return-response.check.ts
  packages/tests-e2e/scenarios/ce/flows/webhook-should-return-response.spec.ts
  packages/tests-e2e/scenarios/flows/send-slack-message.check.ts
  packages/tests-e2e/scenarios/flows/send-slack-message.spec.ts
  packages/tests-e2e/scenarios/flows/webhook-should-return-response.spec.ts
Labels: ✨ polishing, 🛠️ area/infrastructure

#9394 refactor: test CI
  .github/workflows/e2e.yml
Labels: 🐛 bug, ready-for-e2e

#9402 fix: navigating between loop in a run with different iterations length wasn't working
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/run-details/loop-iteration-input.tsx
  packages/react-ui/src/app/builder/run-details/run-step-card-item.tsx
  packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts
Labels: 🐛 bug

#9403 fix: test ci
  .github/workflows/tests-e2e-ce.yml
  packages/server/api/src/app/authentication/authentication-utils.ts
  packages/tests-e2e/pages/builder.page.ts
Labels: ready-for-e2e

#9412 feat: release 0.70.1
  docker-compose.yml
  package.json
Labels: release

#9410 chore(e2e): replace direct Playwright command with npm script in CI
  .github/workflows/e2e.yml
  .github/workflows/pr-e2e.yml
  .github/workflows/tests-e2e-ce.yml
  .github/workflows/tests-e2e-cloud.yml
  .github/workflows/tests-e2e-ee.yml
  packages/tests-e2e/playwright.config.ts
Labels: ready-for-e2e

#9415 chore: test e2e ci
  .github/workflows/e2e.yml
  .github/workflows/tests-e2e-ce.yml
  .github/workflows/tests-e2e-cloud.yml
  .github/workflows/tests-e2e-ee.yml
  packages/tests-e2e/playwright.config.ts
  packages/tests-e2e/scenarios/cloud/dummy.spec.ts
  packages/tests-e2e/scenarios/ee/dummy.spec.ts
Labels: ready-for-e2e

#9416 fix: checkly automate deploy using force
  .github/workflows/automate-deploy.yml
Labels: 🐛 bug, 🛠️ area/infrastructure

#9257 feat(snowflake): Private key pair auth
  packages/pieces/community/snowflake/package.json
  packages/pieces/community/snowflake/src/index.ts
  packages/pieces/community/snowflake/src/lib/actions/run-multiple-queries.ts
  packages/pieces/community/snowflake/src/lib/actions/run-query.ts
  packages/pieces/community/snowflake/src/lib/common/index.ts
Labels: 🔌 pieces, 💫 priority

#9419 fix: checkly test failing on cloud
  packages/react-ui/src/features/flows/lib/create-flow-dropdown.tsx
  packages/tests-e2e/scenarios/ce/authentication/signin.check.ts
  packages/tests-e2e/scenarios/ce/authentication/signup.check.ts
  packages/tests-e2e/scenarios/ce/flows/webhook-should-return-response.spec.ts
Labels: 🐛 bug

#9420 fix: update webhook test to use waitFor method
  packages/tests-e2e/scenarios/ce/flows/webhook-should-return-response.spec.ts
Labels: 🐛 bug

#9445 feat: New translation files
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9446 fix: allow scrolling to the end of a step result
  packages/react-ui/src/app/builder/run-details/flow-step-io/flow-step-input-output.tsx
  packages/react-ui/src/app/builder/run-details/index.tsx
Labels: skip-changelog

#9455 fix: db logs for runs
  packages/server/api/src/app/workers/engine-controller.ts
Labels: skip-changelog

#9456 feat: New translation files
  packages/pieces/community/microsoft-excel-365/src/i18n/translation.json
Labels: skip-changelog, auto-merge, translations

#9458 New Crowdin updates
  packages/pieces/community/microsoft-excel-365/package.json
  packages/pieces/community/microsoft-excel-365/src/i18n/de.json
  packages/pieces/community/microsoft-excel-365/src/i18n/es.json
  packages/pieces/community/microsoft-excel-365/src/i18n/fr.json
  packages/pieces/community/microsoft-excel-365/src/i18n/ja.json
  packages/pieces/community/microsoft-excel-365/src/i18n/nl.json
  packages/pieces/community/microsoft-excel-365/src/i18n/pt.json
  packages/pieces/community/microsoft-excel-365/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9461 fix: test-step results that were string were getting stringified again
  packages/pieces/community/json/package.json
  packages/pieces/community/json/src/lib/actions/convert-json-to-text.ts
  packages/pieces/community/json/src/lib/actions/convert-text-to-json.ts
  packages/react-ui/src/app/builder/pieces-selector/generic-piece-selector-item.tsx
  packages/server/api/src/app/flows/step-run/sample-data.service.ts
Labels: 🐛 bug

#9439 feat(pieces): implement TimelinesAI piece
  packages/pieces/community/timelines-ai/.eslintrc.json
  packages/pieces/community/timelines-ai/README.md
  packages/pieces/community/timelines-ai/package.json
  packages/pieces/community/timelines-ai/project.json
  packages/pieces/community/timelines-ai/src/index.ts
  packages/pieces/community/timelines-ai/src/lib/actions/close-chat.ts
  packages/pieces/community/timelines-ai/src/lib/actions/find-chat.ts
  packages/pieces/community/timelines-ai/src/lib/actions/find-message-status.ts
  packages/pieces/community/timelines-ai/src/lib/actions/find-message.ts
  packages/pieces/community/timelines-ai/src/lib/actions/find-uploaded-file.ts
  packages/pieces/community/timelines-ai/src/lib/actions/find-whatsapp-account.ts
  packages/pieces/community/timelines-ai/src/lib/actions/send-file-to-existing-chat.ts
  packages/pieces/community/timelines-ai/src/lib/actions/send-message-to-existing-chat.ts
  packages/pieces/community/timelines-ai/src/lib/actions/send-message-to-new-chat.ts
  packages/pieces/community/timelines-ai/src/lib/actions/send-uploaded-file-to-existing-chat.ts
  packages/pieces/community/timelines-ai/src/lib/common/index.ts
  packages/pieces/community/timelines-ai/src/lib/common/properties.ts
  packages/pieces/community/timelines-ai/src/lib/common/schemas.ts
  packages/pieces/community/timelines-ai/src/lib/common/types.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/chat-closed.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/new-incoming-chat.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/new-outgoing-chat.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/new-received-message.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/new-sent-message.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/new-uploaded-file.ts
  packages/pieces/community/timelines-ai/src/lib/triggers/new-whatsapp-account.ts
  packages/pieces/community/timelines-ai/tsconfig.json
  packages/pieces/community/timelines-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces

#9465 feat: New translation files
  packages/pieces/community/json/src/i18n/translation.json
  packages/pieces/community/timelines-ai/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9464 feat(pieces): add new piece for Datadog integration and logs API actions
  package-lock.json
  package.json
  packages/pieces/community/datadog/.eslintrc.json
  packages/pieces/community/datadog/README.md
  packages/pieces/community/datadog/package.json
  packages/pieces/community/datadog/project.json
  packages/pieces/community/datadog/src/index.ts
  packages/pieces/community/datadog/src/lib/actions/send-multiple-logs.ts
  packages/pieces/community/datadog/src/lib/actions/send-one-log.ts
  packages/pieces/community/datadog/src/lib/common.ts
  packages/pieces/community/datadog/tsconfig.json
  packages/pieces/community/datadog/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 💫 priority

#9481 feat: Hedy piece
  packages/pieces/community/hedy/.eslintrc.json
  packages/pieces/community/hedy/README.md
  packages/pieces/community/hedy/package.json
  packages/pieces/community/hedy/project.json
  packages/pieces/community/hedy/src/index.ts
  packages/pieces/community/hedy/src/lib/actions/highlights/get-highlight.ts
  packages/pieces/community/hedy/src/lib/actions/highlights/index.ts
  packages/pieces/community/hedy/src/lib/actions/highlights/list-highlights.ts
  packages/pieces/community/hedy/src/lib/actions/index.ts
  packages/pieces/community/hedy/src/lib/actions/sessions/get-session.ts
  packages/pieces/community/hedy/src/lib/actions/sessions/index.ts
  packages/pieces/community/hedy/src/lib/actions/sessions/list-sessions.ts
  packages/pieces/community/hedy/src/lib/actions/todos/index.ts
  packages/pieces/community/hedy/src/lib/actions/todos/list-session-todos.ts
  packages/pieces/community/hedy/src/lib/actions/todos/list-todos.ts
  packages/pieces/community/hedy/src/lib/actions/topics/get-topic.ts
  packages/pieces/community/hedy/src/lib/actions/topics/index.ts
  packages/pieces/community/hedy/src/lib/actions/topics/list-topic-sessions.ts
  packages/pieces/community/hedy/src/lib/actions/topics/list-topics.ts
  packages/pieces/community/hedy/src/lib/auth/index.ts
  packages/pieces/community/hedy/src/lib/common/client.ts
  packages/pieces/community/hedy/src/lib/common/errors.ts
  packages/pieces/community/hedy/src/lib/common/load-options.ts
  packages/pieces/community/hedy/src/lib/common/props.ts
  packages/pieces/community/hedy/src/lib/common/types.ts
  packages/pieces/community/hedy/src/lib/common/validation.ts
  packages/pieces/community/hedy/src/lib/triggers/index.ts
  packages/pieces/community/hedy/src/lib/triggers/webhook/factory.ts
  packages/pieces/community/hedy/src/lib/triggers/webhook/highlight-created.ts
  packages/pieces/community/hedy/src/lib/triggers/webhook/index.ts
  packages/pieces/community/hedy/src/lib/triggers/webhook/session-created.ts
  packages/pieces/community/hedy/src/lib/triggers/webhook/session-ended.ts
  packages/pieces/community/hedy/src/lib/triggers/webhook/todo-exported.ts
  packages/pieces/community/hedy/tsconfig.json
  packages/pieces/community/hedy/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces
