Repository activepieces/activepieces, pull requests merged in 2025-01, with the labels that each got.

#6436 feat(discord): new member trigger
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/index.ts
  packages/pieces/community/discord/src/lib/triggers/new-member.ts
  packages/pieces/community/discord/src/lib/triggers/new-message.ts
Labels: 🔌 pieces

#6443 feat(google-drive): add includeTrashed option to googleDriveListFiles action
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/list-files.action.ts
Labels: 🔌 pieces

#6445 remove public schema from migration file.
  packages/server/api/src/app/database/migration/postgres/1734418823028-CreateProjectReleaseTable.ts
Labels: 🧹 clean up

#6447 fix: enforce assigning global connection to at least one project
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/connections/reconnect-button-dialog.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/components/ui/assign-global-connection-to-projects.tsx
  packages/react-ui/src/components/ui/copy-button.tsx
  packages/react-ui/src/components/ui/permission-needed-tooltip.tsx
  packages/react-ui/src/features/connections/components/edit-global-connection-dialog.tsx
  packages/react-ui/src/features/connections/components/rename-connection-dialog.tsx
  packages/react-ui/src/features/connections/lib/utils.ts
Labels: 🐛 bug

#6438 fix(google-my-business): add pagination for location dropdown
  packages/pieces/community/google-my-business/package.json
  packages/pieces/community/google-my-business/src/lib/common/common.ts
Labels: 🔌 pieces

#6416 feat(intercom): find conversation action
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/actions/find-conversation.ts
Labels: 🔌 pieces

#6441 docs: update Enivroments & Releases docs
  docs/operations/git-sync.mdx
Labels: 📚 documentation

#6449 fix: remove invalid caching logic for flows to be executed
  packages/server/worker/src/lib/api/server-api.service.ts
Labels: 🐛 bug

#6452 fix(google-sheets): issue with finding sheets when id is text not number
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/common/common.ts
Labels: 🐛 bug, 🔌 pieces

#6456 feat: new version 0.38.6 with bug fixes
  docker-compose.yml
  package.json
  packages/react-ui/src/components/custom/markdown.tsx
Labels: release

#6461 fix(spotify): spotify offset labels
  packages/pieces/community/spotify/package.json
  packages/pieces/community/spotify/src/lib/actions/get-playlist-items.ts
  packages/pieces/community/spotify/src/lib/actions/get-playlists.ts
Labels: 🔌 pieces

#6472 fix: casting the mapping in externalId migration
  packages/server/api/src/app/database/migration/postgres/1735262417593-AddExternalIdForFlow.ts
Labels: 🐛 bug

#6474 fix: use date and time regardless of time zone for tasks
  packages/pieces/community/asana/package.json
  packages/pieces/community/asana/src/lib/actions/create-task.ts
Labels: 🐛 bug, 🔌 pieces

#6477 fix: bump hubspot version
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/lib/actions/add-contact-to-workflow.ts
Labels: skip-changelog

#6478 fix: ai tokens billing
  packages/server/api/src/app/ai/ai-provider-proxy.ts
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/ee/platform-billing/usage/usage-service.ts
Labels: 🐛 bug

#6481 chore: add global error handler
  packages/react-ui/src/lib/api.ts
Labels: 🐛 bug

#6487 chore: merge init & start in one function
  packages/server/api/src/app/worker.ts
  packages/server/worker/src/lib/flow-worker.ts
Labels: 🧹 clean up

#6479 feat(supadata): Get Transcript Action
  packages/pieces/community/supadata/.eslintrc.json
  packages/pieces/community/supadata/package.json
  packages/pieces/community/supadata/project.json
  packages/pieces/community/supadata/src/index.ts
  packages/pieces/community/supadata/src/lib/actions/get-transcript.ts
  packages/pieces/community/supadata/src/lib/config.ts
  packages/pieces/community/supadata/tsconfig.json
  packages/pieces/community/supadata/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6493 fix(Perplexity): add citations to Ask AI step output
  packages/pieces/community/perplexity-ai/package.json
  packages/pieces/community/perplexity-ai/src/index.ts
  packages/pieces/community/perplexity-ai/src/lib/actions/create-chat-completion.action.ts
Labels: 🔌 pieces

#6491 feat: switch to child_process instead of worker threads
  packages/engine/src/main.ts
  packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx
  packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts
  packages/server/api/src/app/database/migration/postgres/1735590074879-AddUserIdentity.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/worker/src/lib/engine/engine-runner.ts
  packages/server/worker/src/lib/engine/threads/worker.ts
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🐛 bug

#6494 feat: support creating a project release using an api key
  docs/openapi.json
  packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx
  packages/server/api/src/app/authentication/authentication-utils.ts
  packages/server/api/src/app/ee/audit-logs/audit-event-service.ts
  packages/server/api/src/app/ee/project-release/git-sync/git-sync.service.ts
  packages/server/api/src/app/ee/project-release/project-release.controller.ts
  packages/server/api/src/app/ee/project-release/project-release.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/test/integration/cloud/project-release/project-release.test.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/shared/src/lib/project-release/project-release.request.ts
Labels: 📚 documentation, ✨ polishing

#6496 feat: release 0.39.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#6498 feat: release 0.39.1
  docker-compose.yml
  package.json
Labels: release

#6499 fix: rollback request
  docs/openapi.json
  package-lock.json
  packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx
  packages/server/api/src/app/ee/project-release/git-sync/git-sync.module.ts
  packages/server/api/src/app/server.ts
  packages/shared/src/lib/common/base-model.ts
  packages/shared/src/lib/project-release/project-release.request.ts
Labels: 🐛 bug

#6501 fix: user identity migration for ce postgres
  packages/server/api/src/app/database/migration/postgres/1735590074879-AddUserIdentity.ts
Labels: 🐛 bug

#6500 feat: release 0.39.2
  docker-compose.yml
  package.json
Labels: release

#6505 fix(todoist): fix task completed trigger
  packages/pieces/community/todoist/package.json
  packages/pieces/community/todoist/src/lib/triggers/task-completed-trigger.ts
Labels: 🔌 pieces

#6513 fix: stop /options endpoint from crashing frontend if it fails
  packages/react-ui/src/features/pieces/lib/pieces-api.ts
Labels: skip-changelog

#6523 fix(Google-Drive): Show latest files when testing New File trigger
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/common/index.ts
Labels: 🔌 pieces

#6514 feat: show button next to selection rectangle that users can click on instead of left clicking
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/app/builder/flow-canvas/utils/consts.ts
  packages/react-ui/src/app/builder/flow-canvas/widgets/selection-chevron-button.tsx
Labels: ✨ polishing

#6531 feat: allow users to drag their steps anywhere they want in the canvas
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/flow-canvas/flow-drag-layer.tsx
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/app/builder/flow-canvas/nodes/step-node.tsx
  packages/react-ui/src/app/builder/flow-canvas/step-drag-overlay.tsx
  packages/react-ui/src/app/builder/flow-canvas/utils/consts.ts
  packages/react-ui/src/app/builder/flow-canvas/utils/flow-canvas-utils.ts
  packages/react-ui/src/app/builder/flow-canvas/utils/types.ts
Labels: ✨ polishing

#6535 Revert "Revert "docs: add jmgb27 as a contributor for plugin""
  .all-contributorsrc
  README.md
Labels: skip-changelog

#6527 feat(cryto): add SHA3-512 hash
  packages/pieces/community/crypto/package.json
  packages/pieces/community/crypto/src/index.ts
  packages/pieces/community/crypto/src/lib/actions/hash-text.ts
Labels: 🔌 pieces

#6538 feat(PDF piece): convert image to PDF file
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/index.ts
  packages/pieces/community/pdf/src/lib/actions/image-to-pdf.ts
Labels: 🔌 pieces

#6536 feat(claude): extract structured data action with PDF support
  package-lock.json
  package.json
  packages/pieces/community/claude/package.json
  packages/pieces/community/claude/src/index.ts
  packages/pieces/community/claude/src/lib/actions/extract-structured-data.ts
Labels: 🔌 pieces

#6530 feat: rename git repo permission to project release
  packages/ee/shared/src/lib/authn/access-control-list.ts
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/components/project-settings-layout.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
  packages/server/api/src/app/database/migration/postgres/1736813103505-RenameGitRepoPermission.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/project-release/git-sync/git-sync.module.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/common/security/permission.ts
Labels: ✨ polishing

#6465 feat(pipedrive): create and update actions for Deal, Person, Org and Lead
  packages/pieces/community/pipedrive/package.json
  packages/pieces/community/pipedrive/src/index.ts
  packages/pieces/community/pipedrive/src/lib/actions/add-label-to-person.ts
  packages/pieces/community/pipedrive/src/lib/actions/add-person.action/add-person.action.ts
  packages/pieces/community/pipedrive/src/lib/actions/add-product-to-deal.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-deal.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-lead.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-organization.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-person.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-product.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-deal.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-lead.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-organization.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-person.ts
  packages/pieces/community/pipedrive/src/lib/common/index.ts
  packages/pieces/community/pipedrive/src/lib/common/props.ts
  packages/pieces/community/pipedrive/src/lib/common/types.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-deal.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-lead.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-organization.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-person.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-deal-stage.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-organization.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-person.ts
Labels: 🔌 pieces

#6547 feat: bump release version
  docker-compose.yml
  package.json
Labels: release

#6553 fix: custom domain url
  packages/server/api/src/app/ee/custom-domains/domain-helper.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/shared/src/lib/system-props.ts
Labels: 🐛 bug

#6554 fix: custom domain is no longer required for saml
  packages/server/api/src/app/ee/authentication/saml-authn/saml-client.ts
  packages/server/api/src/app/ee/custom-domains/domain-helper.ts
Labels: 🐛 bug

#6564 chore: improve UI for folders in flows table + add sorting button for folders
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/react-ui/tailwind.config.js
Labels: ✨ polishing

#6562 fix: show correct connections when switching to another project via URL
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/builder/builder-state-provider.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/components/sidebar-layout.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/default-route.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/flows/id/index.tsx
  packages/react-ui/src/features/connections/lib/app-connections-hooks.ts
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
  packages/react-ui/src/hooks/project-hooks.ts
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/ee/custom-domains/domain-helper.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#6560 feat(tavily): search and extract content actions
  packages/pieces/community/tavily/.eslintrc.json
  packages/pieces/community/tavily/README.md
  packages/pieces/community/tavily/package.json
  packages/pieces/community/tavily/project.json
  packages/pieces/community/tavily/src/index.ts
  packages/pieces/community/tavily/src/lib/actions/extract.ts
  packages/pieces/community/tavily/src/lib/actions/search.ts
  packages/pieces/community/tavily/tsconfig.json
  packages/pieces/community/tavily/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6552 feat(krisp-call): new call log trigger
  packages/pieces/community/krisp-call/package.json
  packages/pieces/community/krisp-call/src/lib/triggers/index.ts
Labels: 🔌 pieces

#6556 feat(seven): send SMS, lookup numbers, send voice call actions and new SMS trigger
  packages/pieces/community/seven/.eslintrc.json
  packages/pieces/community/seven/README.md
  packages/pieces/community/seven/package.json
  packages/pieces/community/seven/project.json
  packages/pieces/community/seven/src/action/lookup.ts
  packages/pieces/community/seven/src/action/send-voice-call.ts
  packages/pieces/community/seven/src/action/sms-send.ts
  packages/pieces/community/seven/src/common/index.ts
  packages/pieces/community/seven/src/index.ts
  packages/pieces/community/seven/src/trigger/sms-inbound.ts
  packages/pieces/community/seven/tsconfig.json
  packages/pieces/community/seven/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6548 feat(groq): Ask AI, translate audio and transcribe audio actions
  packages/pieces/community/groq/.eslintrc.json
  packages/pieces/community/groq/README.md
  packages/pieces/community/groq/package.json
  packages/pieces/community/groq/project.json
  packages/pieces/community/groq/src/index.ts
  packages/pieces/community/groq/src/lib/actions/ask-groq.ts
  packages/pieces/community/groq/src/lib/actions/transcribe-audio.ts
  packages/pieces/community/groq/src/lib/actions/translate-audio.ts
  packages/pieces/community/groq/tsconfig.json
  packages/pieces/community/groq/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6569 fix: unify footer in all emails we send and make it white labelled
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
  packages/server/api/src/assets/emails/footer.html
  packages/server/api/src/assets/emails/invitation-email.html
  packages/server/api/src/assets/emails/issue-created.html
  packages/server/api/src/assets/emails/issues-reminder.html
  packages/server/api/src/assets/emails/quota-100.html
  packages/server/api/src/assets/emails/quota-50.html
  packages/server/api/src/assets/emails/quota-90.html
  packages/server/api/src/assets/emails/reset-password.html
  packages/server/api/src/assets/emails/trigger-failure.html
  packages/server/api/src/assets/emails/verify-email.html
Labels: 🐛 bug

#6557 fix(dropbox): fix support of UTF-8 characters in Dropbox-API-Arg header
  packages/pieces/community/dropbox/package.json
  packages/pieces/community/dropbox/src/lib/actions/upload-file.ts
Labels: 🔌 pieces

#6561 feat(scrapegraphapi ): smart scraper, local scraper and Markdownify actions
  packages/pieces/community/scrapegrapghai/.eslintrc.json
  packages/pieces/community/scrapegrapghai/README.md
  packages/pieces/community/scrapegrapghai/package.json
  packages/pieces/community/scrapegrapghai/project.json
  packages/pieces/community/scrapegrapghai/src/index.ts
  packages/pieces/community/scrapegrapghai/src/lib/actions/local-scraper.ts
  packages/pieces/community/scrapegrapghai/src/lib/actions/markdownify.ts
  packages/pieces/community/scrapegrapghai/src/lib/actions/smart-scraper.ts
  packages/pieces/community/scrapegrapghai/tsconfig.json
  packages/pieces/community/scrapegrapghai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6572 feat: release v0.39.5
  docker-compose.yml
  package.json
Labels: release

#6575 feat(openai): output file name property for text to speech action
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/lib/actions/text-to-speech.ts
Labels: 🔌 pieces

#6581 fix: empty divs take up space on license key page.
  packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx
Labels: 🐛 bug

#6593 feat: release 0.39.6
  docker-compose.yml
  package.json
Labels: release

#6550 feat: support IRSA for s3
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/file/s3-helper.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/shared/src/lib/system-props.ts
Labels: ✨ polishing

#6600 fix: stripe webhook for activating subscriptions
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/platform-billing/platform-billing.controller.ts
  packages/server/api/src/app/ee/stripe-billing/stripe-billing.controller.ts
  packages/server/api/src/app/ee/stripe-billing/stripe-billing.module.ts
Labels: 🐛 bug

#6601 fix: "Manage Payment Details" was failing in platform billing
  packages/server/api/src/app/ee/platform-billing/platform-billing.controller.ts
  packages/server/api/src/app/ee/platform-billing/stripe-helper.ts
Labels: 🐛 bug

#6579 fix(text-helper): update markdown library for HTML to Markdown action
  package-lock.json
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/text-helper/src/lib/actions/html-to-markdown.ts
Labels: 🔌 pieces

#6582 fix(csv): escape delimiter for JSON to CSV actions
  package-lock.json
  package.json
  packages/pieces/community/csv/package.json
  packages/pieces/community/csv/src/lib/actions/convert-csv-to-json.ts
  packages/pieces/community/csv/src/lib/actions/convert-json-to-csv.ts
Labels: 🔌 pieces

#6613 fix(onedrive): fix new file trigger
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/lib/triggers/new-file.ts
Labels: 🔌 pieces

#6608 feat(krisp-call): new outbound sms/mms trigger
  packages/pieces/community/krisp-call/package.json
  packages/pieces/community/krisp-call/src/lib/triggers/index.ts
Labels: 🔌 pieces

#6620 feat: allow using relative url instead of only full url when executing custom api requests
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/helpers/index.ts
Labels: 🔌 pieces

#6532 feat(surrealdb): run query action and new row trigger
  packages/pieces/community/surrealdb/.eslintrc.json
  packages/pieces/community/surrealdb/README.md
  packages/pieces/community/surrealdb/package.json
  packages/pieces/community/surrealdb/project.json
  packages/pieces/community/surrealdb/src/index.ts
  packages/pieces/community/surrealdb/src/lib/actions/run-query.ts
  packages/pieces/community/surrealdb/src/lib/common.ts
  packages/pieces/community/surrealdb/src/lib/triggers/new-row.ts
  packages/pieces/community/surrealdb/tsconfig.json
  packages/pieces/community/surrealdb/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6565 feat(graphql): send GraphQL request action
  packages/pieces/community/graphql/.eslintrc.json
  packages/pieces/community/graphql/README.md
  packages/pieces/community/graphql/package.json
  packages/pieces/community/graphql/project.json
  packages/pieces/community/graphql/src/index.ts
  packages/pieces/community/graphql/src/lib/actions/query.ts
  packages/pieces/community/graphql/src/lib/common/props.ts
  packages/pieces/community/graphql/tsconfig.json
  packages/pieces/community/graphql/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6644 chore: add platform switcher
  packages/react-ui/src/app/components/header.tsx
  packages/react-ui/src/features/platform-switcher/components/platform-switcher.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
Labels: 🌟 feature

#6648 fix: read platform id from the jwt
  packages/react-ui/src/lib/authentication-session.ts
Labels: 🐛 bug

#6637 chore: remove project billing
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/billing/index.ts
  packages/ee/shared/src/lib/billing/project-billing.ts
  packages/react-ui/src/app/components/usage-limits-button.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/task-limit-alert.tsx
  packages/react-ui/src/app/routes/plans/index.tsx
  packages/react-ui/src/app/routes/platform/billing/api/billing-api.ts
  packages/react-ui/src/app/routes/platform/billing/index.tsx
  packages/react-ui/src/features/plans/api/billing-api.ts
  packages/react-ui/src/features/plans/components/ai-credits-and-tasks-progress.tsx
  packages/react-ui/src/features/plans/components/plan-data.tsx
  packages/react-ui/src/features/plans/components/plans.tsx
  packages/react-ui/src/features/project-version/lib/project-release-api.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/ee/billing/appsumo/appsumo.service.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.entity.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.module.ts
  packages/server/api/src/app/ee/billing/project-billing/project-billing.service.ts
  packages/server/api/src/app/ee/billing/project-billing/stripe-helper.ts
  packages/server/api/src/app/ee/platform-billing/usage/usage-service.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/assets/emails/quota-100.html
Labels: 🧹 clean up

#6622 chore: make the retry strategy of from failed step to retry the same run
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: 🌟 feature

#6529 feat: replace request trial button with contact sales, passing user d…
  packages/react-ui/src/app/components/request-trial.tsx
Labels: ✨ polishing

#6653 fix: stripe helper tests
  packages/server/api/src/app/authentication/authentication.service.ts
  packages/server/api/src/app/ee/project-members/project-member.service.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/authn/cloud-authn.test.ts
  packages/server/api/test/integration/cloud/managed-authn/external-token.test.ts
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/server/api/test/integration/ee/authn/ee-authn.test.ts
Labels: 🐛 bug

#6657 feat: release 0.39.7
  docker-compose.yml
  package.json
Labels: release

#6546 feat(pipedrive): activity, note and find actions
  packages/pieces/community/pipedrive/package.json
  packages/pieces/community/pipedrive/src/index.ts
  packages/pieces/community/pipedrive/src/lib/actions/add-follower.ts
  packages/pieces/community/pipedrive/src/lib/actions/attach-file.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-activity.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-deal.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-lead.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-note.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-organization.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-person.ts
  packages/pieces/community/pipedrive/src/lib/actions/create-product.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-activity.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-deal.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-deals-associated-with-person.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-notes.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-organization.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-person.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-product.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-products.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-user.ts
  packages/pieces/community/pipedrive/src/lib/actions/get-note.ts
  packages/pieces/community/pipedrive/src/lib/actions/get-product.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-activity.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-deal.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-lead.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-organization.ts
  packages/pieces/community/pipedrive/src/lib/actions/update-person.ts
  packages/pieces/community/pipedrive/src/lib/common/index.ts
  packages/pieces/community/pipedrive/src/lib/common/props.ts
  packages/pieces/community/pipedrive/src/lib/common/types.ts
  packages/pieces/community/pipedrive/src/lib/trigger/activity-matching-filter.ts
  packages/pieces/community/pipedrive/src/lib/trigger/deal-matching-filter.ts
  packages/pieces/community/pipedrive/src/lib/trigger/new-note.ts
  packages/pieces/community/pipedrive/src/lib/trigger/organization-matching-filter.ts
  packages/pieces/community/pipedrive/src/lib/trigger/person-matching-filter.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-deal-stage.ts
Labels: 🔌 pieces

#6384 feat(postgres): add query source comment
  packages/pieces/community/postgres/package.json
  packages/pieces/community/postgres/src/lib/actions/run-query.ts
Labels: 🔌 pieces

#6630 fix(beamer): fix create vote action
  packages/pieces/community/beamer/package.json
  packages/pieces/community/beamer/src/index.ts
  packages/pieces/community/beamer/src/lib/actions/create-vote.ts
Labels: 🔌 pieces

#6580 feat(google-sheets): find spreadsheet(s) by name
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-spreadsheets.ts
Labels: 🔌 pieces

#6666 fix: overview text in docs/install/architecture/overview
  docs/install/architecture/overview.mdx
Labels: 📚 documentation

#6669 feat(jotform): add HIPPA API url for authentication
  packages/pieces/community/jotform/package.json
  packages/pieces/community/jotform/src/index.ts
  packages/pieces/community/jotform/src/lib/common/index.ts
Labels: 🔌 pieces

#6649 feat(kallabot-ai): make call and get call details action
  packages/pieces/community/kallabot-ai/.eslintrc.json
  packages/pieces/community/kallabot-ai/README.md
  packages/pieces/community/kallabot-ai/package.json
  packages/pieces/community/kallabot-ai/project.json
  packages/pieces/community/kallabot-ai/src/index.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/get-call-details.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/make-call.ts
  packages/pieces/community/kallabot-ai/tsconfig.json
  packages/pieces/community/kallabot-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6670 fix: sync input field value with search params on page load
  packages/react-ui/src/components/ui/data-table/data-table-options-filter.tsx
Labels: 🐛 bug

#6684 fix: styling for manage pieces button, delete empty spaces
  packages/react-ui/src/app/routes/settings/pieces/index.tsx
Labels: ✨ polishing

#6679 feat: add multi-query transaction support to snowflake piece
  packages/pieces/community/snowflake/package.json
  packages/pieces/community/snowflake/src/index.ts
  packages/pieces/community/snowflake/src/lib/actions/run-multiple-queries.ts
Labels: 🔌 pieces

#6690 fix: empty externalId should make unable to update project
  packages/react-ui/src/app/routes/settings/general/index.tsx
  packages/server/api/src/app/project/project-service.ts
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
Labels: 🐛 bug

#6691 feat: deploy a new release 0.39.8
  docker-compose.yml
  package.json
  packages/server/api/src/app/authentication/authentication.service.ts
  packages/server/api/src/app/authentication/user-identity/user-identity-service.ts
Labels: release

#6699 fix: add searching filter for projects when creating a release from one
  package-lock.json
  packages/react-ui/src/app/routes/project-release/apply-plan.tsx
  packages/react-ui/src/app/routes/project-release/index.tsx
  packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx
Labels: 🐛 bug

#6638 feat: add project home route
  packages/react-ui/src/app/builder/builder-state-provider.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/router/default-route.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/hooks/project-hooks.ts
  packages/server/api/src/app/authentication/user-identity/user-identity-service.ts
Labels: ✨ polishing

#6692 feat(confluence): new page trigger and custom API call action
  packages/pieces/community/confluence/package.json
  packages/pieces/community/confluence/src/index.ts
  packages/pieces/community/confluence/src/lib/common/index.ts
  packages/pieces/community/confluence/src/lib/common/props.ts
  packages/pieces/community/confluence/src/lib/triggers/new-page.ts
Labels: 🔌 pieces

#6678 fix(google-sheets): fix csv parsing for multiple rows action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
Labels: 🔌 pieces

#6700 feat: release 0.39.9
  docker-compose.yml
  package.json
Labels: release

#6704 fix: batch start runs
  package-lock.json
  package.json
  packages/react-ui/src/app/routes/flows/task-limit-alert.tsx
  packages/server/worker/src/lib/api/server-api.service.ts
Labels: skip-changelog

#6705 fix: wrong error for missing projectId in api key authn
  package-lock.json
  packages/server/api/src/app/authentication/authorization.ts
  packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/api/server-api.service.ts
Labels: 🐛 bug

#6707 feat: pre-release 0.40.0-rc.1
  package.json
Labels: pre-release

#6702 feat(confluence): improve get-page-content to fetch recursive children
  packages/pieces/community/confluence/package.json
  packages/pieces/community/confluence/src/lib/actions/get-page-content.ts
Labels: 🔌 pieces

#6709 fix: increase p limit and remove linear search
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/worker/src/lib/api/server-api.service.ts
Labels: 🐛 bug

#6658 feat(wedof-piece): updating wedof actions/trigers piece
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner-audit/create-certification-partner-audit.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner-audit/create-general-audit.ts
  packages/pieces/community/wedof/src/lib/common/wedof.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-initial-experience-answered.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-initial-experience-available.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-long-experience-answered.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-long-experience-available.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-six-month-experience-answered.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folder-survey/certification-folder-survey-six-month-experience-available.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-registred.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-selected.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-success.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-tocontrol.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-toretake.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-totake.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/certification-folder-updated.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-folders/new-certification-folder-created.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/new-registration-folder-created.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-accepted.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-inTraining.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-paid.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-selected.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-terminated.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-tobill.ts
  packages/pieces/community/wedof/src/lib/triggers/registration-folders/registration-folder-updated.ts
Labels: 🔌 pieces

#6713 fix: migrate bullmq repeatable to new api
  packages/server/api/src/app/workers/memory/memory-queue.ts
  packages/server/api/src/app/workers/queue/queue-manager.ts
  packages/server/api/src/app/workers/redis/redis-migration.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/api/src/app/workers/redis/redis-rate-limiter.ts
Labels: 🐛 bug

#6618 feat(nocodb): add compatibility with self-hosted NocoDB instances
  packages/pieces/community/nocodb/package.json
  packages/pieces/community/nocodb/src/index.ts
  packages/pieces/community/nocodb/src/lib/actions/create-record.ts
  packages/pieces/community/nocodb/src/lib/actions/delete-record.ts
  packages/pieces/community/nocodb/src/lib/actions/get-record.ts
  packages/pieces/community/nocodb/src/lib/actions/search-records.ts
  packages/pieces/community/nocodb/src/lib/actions/update-record.ts
  packages/pieces/community/nocodb/src/lib/common/client.ts
  packages/pieces/community/nocodb/src/lib/common/index.ts
  packages/pieces/community/nocodb/src/lib/common/types.ts
Labels: 🔌 pieces

#6682 fix: change publish-piece command to use inquirer
  docs/developers/misc/publish-piece.mdx
  package.json
  packages/cli/src/lib/commands/publish-piece.ts
Labels: 📚 documentation, ✨ polishing

#6717 feat: release v0.40.0
  docker-compose.yml
  package.json
Labels: release

#6723 fix: broken jobs in redis
  packages/server/api/src/app/workers/redis/redis-migration.ts
Labels: 🐛 bug
