Repository activepieces/activepieces, pull requests merged in 2025-07, with the labels that each got.

#8210 fix: ai credits redis increment floats
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
Labels: 🐛 bug

#8220 fix: openai streaming always include usage
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/ai/providers/openai.ts
Labels: 🐛 bug

#8222 fix: hide use agent button inside flow builder
  packages/react-ui/src/app/builder/pieces-selector/create-agent-action-item.tsx
  packages/react-ui/src/app/builder/step-settings/edit-agent-inside-flow-builder-button.tsx
  packages/react-ui/src/app/routes/agents/builder/agent-settings.tsx
  packages/react-ui/src/app/routes/agents/builder/index.tsx
  packages/react-ui/src/features/agents/use-agent-button.tsx
Labels: skip-changelog

#8195 feat: resolve dynamic properties in MCP tools
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/test-execution-context.ts
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-piece-tool-dialog/index.tsx
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/flows/step-run/sample-data.controller.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/api/src/app/websockets/websockets.service.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/runner/engine-runner-types.ts
  packages/server/worker/src/lib/runner/process/engine-process-manager.ts
  packages/shared/src/lib/agents/agent-response-utils.ts
  packages/shared/src/lib/agents/response.ts
  packages/shared/src/lib/engine/engine-constants.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/engine/index.ts
  packages/shared/src/lib/mcp/mcp.ts
Labels: ✨ polishing

#8223 feat: refactor trial
  packages/ee/shared/src/lib/billing/plan-limits.ts
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/sidebar/usage-limits-button.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/features/billing/components/trial-dialog.tsx
  packages/react-ui/src/features/billing/lib/api.ts
  packages/react-ui/src/features/billing/lib/billing-hooks.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/migration/1751394161203-AddTrialFlagInPlatform.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.entity.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.service.ts
  packages/server/api/src/app/ee/platform/platform-plan/stripe-billing.controller.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/flows/step-run/sample-data.controller.ts
  packages/server/api/src/app/websockets/websockets.service.ts
  packages/shared/src/lib/platform/platform.model.ts
  packages/shared/src/lib/project/project.ts
Labels: 🌟 feature

#8224 fix: agent error handling
  packages/pieces/community/agent/package.json
  packages/pieces/community/agent/src/lib/agent-executor.ts
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/shared/package.json
  packages/shared/src/lib/ai/index.ts
Labels: 🐛 bug

#8227 feat: resolve dynamic properties in MCP tools
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/context/test-execution-context.ts
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-piece-tool-dialog/index.tsx
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/runner/engine-runner-types.ts
  packages/server/worker/src/lib/runner/process/engine-process-manager.ts
  packages/shared/src/lib/engine/engine-constants.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/engine/index.ts
Labels: ✨ polishing

#8245 feat: optmize code builds
  packages/engine/src/lib/handler/code-executor.ts
  packages/server/shared/src/lib/crypto.ts
  packages/server/worker/src/lib/cache/code-builder.ts
  packages/server/worker/src/lib/cache/execution-files.ts
Labels: 🐛 bug

#8246 feat: add inputs and code mirror json viewer to agent tool block
  packages/pieces/community/agent/package.json
  packages/pieces/community/agent/src/lib/agent-tools.ts
  packages/react-ui/src/features/agents/agent-tool-block.tsx
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/worker/src/lib/cache/code-builder.ts
  packages/shared/package.json
Labels: ✨ polishing

#8255 fix(s3): update trigger strategy to time based for duplicate file issue
  packages/pieces/community/amazon-s3/package.json
  packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts
Labels: 🔌 pieces

#8253 fix: improve MCP parameter extraction prompt
  packages/react-ui/src/features/agents/agent-tool-block.tsx
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
Labels: 🐛 bug

#8263 fix: user can't dismiss changelog announcement to themselves
  packages/react-ui/src/app/builder/piece-properties/array-property.tsx
  packages/react-ui/src/app/components/changelog-provider.tsx
  packages/react-ui/src/lib/changelog-api.ts
  packages/server/api/src/app/changelog/changelog.controller.ts
  packages/server/api/src/app/user-invitations/user-invitation.service.ts
  packages/shared/src/lib/changelog/changelog.request.ts
  packages/shared/src/lib/changelog/changelog.ts
  packages/shared/src/lib/changelog/index.ts
Labels: 🐛 bug

#8233 fix(ai-providers): gemini 2.5 pro pricing model
  packages/server/api/src/app/ai/providers/google.ts
  packages/shared/src/lib/ai/supported-ai-providers.ts
Labels: 🐛 bug

#8265 refactor: clean up run status
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/test/handler/flow-with-response.test.ts
  packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/index.tsx
  packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts
  packages/server/api/src/app/database/index.ts
  packages/server/api/src/app/database/migration/postgres/1751394161203-AddTrialFlagInPlatform.ts
  packages/server/api/src/app/database/migration/postgres/1751728035816-RemoveTerminationReason.ts
  packages/server/api/src/app/database/migration/sqlite/1751727630516-RemoveTerminationReasonSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
  packages/shared/src/lib/flow-run/flow-run.ts
Labels: 🧹 clean up

#8238 fix(elevenlabs): update library and support API regions
  package-lock.json
  package.json
  packages/pieces/community/elevenlabs/package.json
  packages/pieces/community/elevenlabs/src/index.ts
  packages/pieces/community/elevenlabs/src/lib/actions/text-to-speech-action.ts
  packages/pieces/community/elevenlabs/src/lib/common.ts
Labels: 🙋 Bounty claim

#8240 feat: Fillout forms piece
  nx.json
  packages/pieces/community/fillout-forms/.eslintrc.json
  packages/pieces/community/fillout-forms/README.md
  packages/pieces/community/fillout-forms/package.json
  packages/pieces/community/fillout-forms/project.json
  packages/pieces/community/fillout-forms/src/index.ts
  packages/pieces/community/fillout-forms/src/lib/actions/find-form-by-title.ts
  packages/pieces/community/fillout-forms/src/lib/actions/get-form-responses.ts
  packages/pieces/community/fillout-forms/src/lib/actions/get-single-response.ts
  packages/pieces/community/fillout-forms/src/lib/common/index.ts
  packages/pieces/community/fillout-forms/src/lib/common/props.ts
  packages/pieces/community/fillout-forms/src/lib/triggers/new-form-response.ts
  packages/pieces/community/fillout-forms/tsconfig.json
  packages/pieces/community/fillout-forms/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#8293 feat(executors): add duration tracking for action execution steps
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/flow-executor.ts
  packages/engine/src/lib/handler/loop-executor.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/handler/router-executor.ts
  packages/shared/src/lib/flow-run/execution/step-output.ts
Labels: 🐛 bug, ✨ polishing

#8296 fix: inline items in sandbox code only
  package-lock.json
  package.json
  packages/engine/src/lib/core/code/code-sandbox-common.ts
  packages/engine/src/lib/core/code/no-op-code-sandbox.ts
  packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/variables/props-resolver.ts
Labels: 🐛 bug

#8271 chore: implement integration tests for AI providers
  package-lock.json
  package.json
  packages/server/api/.env.tests
  packages/server/api/jest.setup.js
  packages/server/api/project.json
  packages/server/api/src/app/ai/providers/replicate.ts
  packages/server/api/src/app/database/migration/sqlite/1751475726665-AddPlatformIdToAIUsageSqlite.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/ai/proxy.test.ts
Labels: ✨ polishing

#8321 fix(dimo): fix vehicle token generation function and telemetry API props
  packages/pieces/community/dimo/package.json
  packages/pieces/community/dimo/src/lib/actions/identity/action.ts
  packages/pieces/community/dimo/src/lib/actions/telemetry/action.ts
  packages/pieces/community/dimo/src/lib/common/helpers.ts
Labels: 🔌 pieces

#8290 feat: wufoo piece
  packages/pieces/community/wufoo/README.md
  packages/pieces/community/wufoo/package.json
  packages/pieces/community/wufoo/project.json
  packages/pieces/community/wufoo/src/index.ts
  packages/pieces/community/wufoo/src/lib/actions/create-form-entry.ts
  packages/pieces/community/wufoo/src/lib/actions/find-form.ts
  packages/pieces/community/wufoo/src/lib/actions/find-submission-by-field.ts
  packages/pieces/community/wufoo/src/lib/actions/get-entry-details.ts
  packages/pieces/community/wufoo/src/lib/common/client.ts
  packages/pieces/community/wufoo/src/lib/common/props.ts
  packages/pieces/community/wufoo/src/lib/triggers/new-form-entry.ts
  packages/pieces/community/wufoo/src/lib/triggers/new-form.ts
  packages/pieces/community/wufoo/tsconfig.json
  packages/pieces/community/wufoo/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8319 feat(notion): improve error management when generating dynamic input properties
  packages/pieces/community/notion/package.json
  packages/pieces/community/notion/src/lib/common/index.ts
Labels: 🔌 pieces

#8323 release: 0.65.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/react-ui/src/app/builder/data-selector/data-selector-node-content.tsx
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
  packages/react-ui/src/app/builder/piece-properties/dictionary-property.tsx
  packages/react-ui/src/app/builder/run-list/flow-run-card.tsx
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/simulation-section.tsx
  packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx
  packages/react-ui/src/app/routes/flows/id/index.tsx
  packages/react-ui/src/app/routes/forms/index.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx
  packages/react-ui/src/app/routes/runs/id/index.tsx
  packages/react-ui/src/app/routes/settings/environment/index.tsx
  packages/react-ui/src/components/ui/button.tsx
  packages/react-ui/src/components/ui/loading-screen.tsx
  packages/react-ui/src/components/ui/select.tsx
  packages/react-ui/src/components/ui/spinner.tsx
  packages/react-ui/src/features/authentication/components/verify-email.tsx
  packages/react-ui/src/features/flow-runs/lib/flow-run-utils.ts
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
  packages/react-ui/src/features/flows/lib/use-flows-bulk-actions.tsx
  packages/react-ui/src/features/team/component/accept-invitation.tsx
  packages/react-ui/src/features/templates/components/share-template.tsx
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/test/integration/cloud/ai/proxy.test.ts
Labels: release

#8327 chore: add Helm Chart
  deploy/activepieces-helm/.helmignore
  deploy/activepieces-helm/Chart.lock
  deploy/activepieces-helm/Chart.yaml
  deploy/activepieces-helm/charts/kubernetes-secret-generator-3.4.1.tgz
  deploy/activepieces-helm/charts/postgresql-11.7.2.tgz
  deploy/activepieces-helm/charts/redis-17.4.2.tgz
  deploy/activepieces-helm/templates/NOTES.txt
  deploy/activepieces-helm/templates/_helpers.tpl
  deploy/activepieces-helm/templates/deployment.yaml
  deploy/activepieces-helm/templates/hpa.yaml
  deploy/activepieces-helm/templates/ingress.yaml
  deploy/activepieces-helm/templates/pvc.yaml
  deploy/activepieces-helm/templates/secret.yaml
  deploy/activepieces-helm/templates/service.yaml
  deploy/activepieces-helm/templates/serviceaccount.yaml
  deploy/activepieces-helm/templates/tests/test-connection.yaml
  deploy/activepieces-helm/values.yaml
  docs/docs.json
  docs/install/options/helm.mdx
  docs/install/overview.mdx
Labels: 🌟 feature

#8325 feat(slack): add action to list all users of a workspace
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/list-users.ts
Labels: 🔌 pieces, 💫 priority

#7948 feat: pandadoc piece
  packages/pieces/community/pandadoc/.eslintrc.json
  packages/pieces/community/pandadoc/README.md
  packages/pieces/community/pandadoc/package.json
  packages/pieces/community/pandadoc/project.json
  packages/pieces/community/pandadoc/src/index.ts
  packages/pieces/community/pandadoc/src/lib/actions/create-attachment.ts
  packages/pieces/community/pandadoc/src/lib/actions/create-document-from-template.ts
  packages/pieces/community/pandadoc/src/lib/actions/create-or-update-contact.ts
  packages/pieces/community/pandadoc/src/lib/actions/download-document.ts
  packages/pieces/community/pandadoc/src/lib/actions/find-document.ts
  packages/pieces/community/pandadoc/src/lib/actions/get-document-attachments.ts
  packages/pieces/community/pandadoc/src/lib/actions/get-document-details.ts
  packages/pieces/community/pandadoc/src/lib/common/auth.ts
  packages/pieces/community/pandadoc/src/lib/common/dynamic-dropdowns.ts
  packages/pieces/community/pandadoc/src/lib/common/index.ts
  packages/pieces/community/pandadoc/src/lib/triggers/document-completed.ts
  packages/pieces/community/pandadoc/src/lib/triggers/document-state-changed.ts
  packages/pieces/community/pandadoc/src/lib/triggers/document-updated.ts
  packages/pieces/community/pandadoc/tsconfig.json
  packages/pieces/community/pandadoc/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8331 feat: checkout piece
  packages/pieces/community/checkout/README.md
  packages/pieces/community/checkout/package.json
  packages/pieces/community/checkout/project.json
  packages/pieces/community/checkout/src/index.ts
  packages/pieces/community/checkout/src/lib/actions/create-customer.ts
  packages/pieces/community/checkout/src/lib/actions/create-payment-link.ts
  packages/pieces/community/checkout/src/lib/actions/create-payout.ts
  packages/pieces/community/checkout/src/lib/actions/get-payment-actions.ts
  packages/pieces/community/checkout/src/lib/actions/get-payment-details.ts
  packages/pieces/community/checkout/src/lib/actions/refund-payment.ts
  packages/pieces/community/checkout/src/lib/actions/update-customer.ts
  packages/pieces/community/checkout/src/lib/common/auth.ts
  packages/pieces/community/checkout/src/lib/triggers/dispute-events.ts
  packages/pieces/community/checkout/src/lib/triggers/payment-events.ts
  packages/pieces/community/checkout/tsconfig.json
  packages/pieces/community/checkout/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8342 feat: polish tables
  packages/react-ui/src/app/routes/tables/id/index.tsx
  packages/react-ui/src/components/ui/drawer.tsx
  packages/react-ui/src/features/tables/components/ap-table-header.tsx
  packages/react-ui/src/features/tables/components/new-field-popup.tsx
  packages/react-ui/src/features/tables/components/table-columns.tsx
Labels: ✨ polishing

#8273 fix: decouple agent piece version from mcp tool naming
  packages/pieces/community/agent/package.json
  packages/pieces/community/agent/src/index.ts
  packages/pieces/community/agent/src/lib/agent-executor.ts
  packages/pieces/community/agent/src/lib/agent-tools.ts
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-flow-tool.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-piece-tool.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-flow-tool-dialog/index.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-piece-tool-dialog/index.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-piece-tool-dialog/mcp-piece-actions.tsx
  packages/react-ui/src/features/agents/use-agent-button.tsx
  packages/react-ui/src/features/mcp/lib/mcp-hooks.ts
  packages/server/api/src/app/database/migration/common/1752004202722-SplitUpPieceMetadataIntoTools.ts
  packages/server/api/src/app/database/migration/postgres/1752151941009-AddIndexForSchemaVersionInFlowVersion.ts
  packages/server/api/src/app/database/migration/sqlite/1752152069517-AddIndexForSchemaVersionInFlowVersionSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/analytics/pieces-analytics.service.ts
  packages/server/api/src/app/flows/flow-version/flow-version-entity.ts
  packages/server/api/src/app/flows/flow-version/flow-version-migration.service.ts
  packages/server/api/src/app/flows/flow-version/flow-version-repo-wrapper.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flows/flow-version.ts
  packages/shared/src/lib/flows/operations/migrations/index.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v0-branch-to-router.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v1-connection-ids.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v2-agent-piece.ts
  packages/shared/src/lib/mcp/mcp.request.ts
  packages/shared/src/lib/mcp/mcp.ts
  packages/shared/src/lib/mcp/tools/mcp-tool.ts
Labels: ✨ polishing

#8358 fix: piece selector
  packages/react-ui/src/app/builder/pieces-selector/explore-tab-content.tsx
  packages/react-ui/src/app/builder/pieces-selector/generic-piece-selector-item.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-intro.tsx
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
  packages/react-ui/src/components/ui/search-input.tsx
  packages/react-ui/src/features/pieces/components/piece-selector-search.tsx
  packages/react-ui/src/features/pieces/components/piece-selector-tabs.tsx
  packages/react-ui/src/features/pieces/lib/piece-selector-tabs-provider.tsx
  packages/react-ui/src/features/pieces/lib/piece-selector-utils.ts
  packages/react-ui/src/features/pieces/lib/pieces-hooks.ts
  packages/react-ui/src/lib/types.ts
Labels: skip-changelog

#8363 chore: add mcp to universal ai category
  packages/pieces/community/mcp/package.json
  packages/pieces/community/mcp/src/index.ts
Labels: 🔌 pieces, skip-changelog

#8335 feat(amazon-s3): move file action
  packages/pieces/community/amazon-s3/package.json
  packages/pieces/community/amazon-s3/src/index.ts
  packages/pieces/community/amazon-s3/src/lib/actions/move-file.ts
Labels: 🔌 pieces, 💫 priority

#8364 chore: add better categorization under AI and Agents tab in the piece selector
  packages/react-ui/src/app/builder/flow-canvas/widgets/selection-chevron-button.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/features/pieces/lib/piece-search-utils.ts
  packages/react-ui/src/features/pieces/lib/pieces-hooks.ts
Labels: ✨ polishing

#8367 feat: add flows sidebar flag embedding
  docs/embedding/embed-builder.mdx
  docs/embedding/sdk-changelog.mdx
  packages/ee/ui/embed-sdk/package.json
  packages/ee/ui/embed-sdk/src/index.ts
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/components/embed-provider.tsx
Labels: skip-changelog

#8362 feat: group mcp tools by piece name
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-flow-tool.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-piece-tool.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-config/mcp-tools-section.tsx
  packages/react-ui/src/app/routes/mcp-servers/mcp-tools-icon.tsx
  packages/react-ui/src/features/mcp/lib/mcp-hooks.ts
Labels: ✨ polishing

#8295 feat: formstack piece
  packages/pieces/community/formstack/.eslintrc.json
  packages/pieces/community/formstack/README.md
  packages/pieces/community/formstack/package.json
  packages/pieces/community/formstack/project.json
  packages/pieces/community/formstack/src/index.ts
  packages/pieces/community/formstack/src/lib/actions/create-submission.ts
  packages/pieces/community/formstack/src/lib/actions/find-form-by-name-or-id.ts
  packages/pieces/community/formstack/src/lib/actions/find-submission-by-field-value.ts
  packages/pieces/community/formstack/src/lib/actions/get-submission-details.ts
  packages/pieces/community/formstack/src/lib/common/auth.ts
  packages/pieces/community/formstack/src/lib/common/client.ts
  packages/pieces/community/formstack/src/lib/common/props.ts
  packages/pieces/community/formstack/src/lib/triggers/new-form.ts
  packages/pieces/community/formstack/src/lib/triggers/new-submission.ts
  packages/pieces/community/formstack/tsconfig.json
  packages/pieces/community/formstack/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8377 fix: show simulation testing section for pieces like slack
  packages/react-ui/src/app/builder/test-step/test-trigger-section/index.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/trigger-event-utils.ts
Labels: skip-changelog

#8379 chore: added saving indicator for agent builder
  package-lock.json
  packages/react-ui/src/app/builder/test-step/test-trigger-section/index.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/trigger-event-utils.ts
  packages/react-ui/src/app/routes/agents/builder/add-field-popover.tsx
  packages/react-ui/src/app/routes/agents/builder/agent-settings-output.tsx
  packages/react-ui/src/app/routes/agents/builder/agent-settings.tsx
  packages/react-ui/src/app/routes/agents/builder/index.tsx
  packages/react-ui/src/app/routes/platform/projects/edit-project-dialog.tsx
  packages/react-ui/src/features/agents/use-agent-button.tsx
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.module.ts
Labels: 🧹 clean up

#8370 feat: mistral-ai piece
  packages/pieces/community/mistral-ai/.eslintrc.json
  packages/pieces/community/mistral-ai/README.md
  packages/pieces/community/mistral-ai/package.json
  packages/pieces/community/mistral-ai/project.json
  packages/pieces/community/mistral-ai/src/index.ts
  packages/pieces/community/mistral-ai/src/lib/actions/create-chat-completion.ts
  packages/pieces/community/mistral-ai/src/lib/actions/create-embeddings.ts
  packages/pieces/community/mistral-ai/src/lib/actions/list-models.ts
  packages/pieces/community/mistral-ai/src/lib/actions/upload-file.ts
  packages/pieces/community/mistral-ai/src/lib/common/auth.ts
  packages/pieces/community/mistral-ai/src/lib/common/props.ts
  packages/pieces/community/mistral-ai/tsconfig.json
  packages/pieces/community/mistral-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8398 fix: testing mcp trigger wasn't showing required dialog
  docs/docs.json
  docs/endpoints/projects/delete.mdx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/index.tsx
Labels: 🐛 bug

#8401 feat: release 0.66.1
  docker-compose.yml
  package.json
Labels: release

#8402 fix: add image version for sdk 0.6.0 notes
  docs/about/breaking-changes.mdx
  docs/embedding/sdk-changelog.mdx
Labels: skip-changelog

#8410 feat: add pre-prod automate deploy workflow
  .github/workflows/pre-prod-automate-deploy.yml
Labels: skip-changelog

#8411 feat: release 0.66.2
  docker-compose.yml
  package.json
Labels: release

#7911 feat: add platform operator role
  packages/react-ui/src/app/routes/platform/users/index.tsx
  packages/react-ui/src/app/routes/platform/users/update-user-dialog.tsx
  packages/react-ui/src/features/team/component/platform-role-select.tsx
  packages/server/api/src/app/ee/projects/project-members/project-member.service.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/shared/src/lib/user/user.ts
Labels: 🌟 feature

#8412 fix: chats were infinitely loading for people not logged in
  packages/react-ui/src/app/routes/chat/flow-chat.tsx
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/forms/index.tsx
  packages/react-ui/src/features/flows/lib/flows-hooks.ts
Labels: 🐛 bug

#8413 fix: lint
  packages/react-ui/src/app/routes/chat/flow-chat.tsx
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/forms/index.tsx
  packages/react-ui/src/features/billing/components/features-status.tsx
  packages/react-ui/src/features/flows/lib/flows-hooks.ts
  packages/react-ui/src/lib/oauth2-utils.ts
Labels: skip-changelog

#8395 feat: fireberry piece
  packages/pieces/community/fireberry/README.md
  packages/pieces/community/fireberry/package.json
  packages/pieces/community/fireberry/project.json
  packages/pieces/community/fireberry/src/index.ts
  packages/pieces/community/fireberry/src/lib/actions/create-record.action.ts
  packages/pieces/community/fireberry/src/lib/actions/delete-record.action.ts
  packages/pieces/community/fireberry/src/lib/actions/find-record.action.ts
  packages/pieces/community/fireberry/src/lib/actions/update-record.action.ts
  packages/pieces/community/fireberry/src/lib/common/client.ts
  packages/pieces/community/fireberry/src/lib/common/props.ts
  packages/pieces/community/fireberry/src/lib/triggers/record-created-updated.trigger.ts
  packages/pieces/community/fireberry/tsconfig.json
  packages/pieces/community/fireberry/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8414 fix: disable (Test Step) button while inputs like dropdown are still loading
  packages/react-ui/src/app/app.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-dropdown-piece-property.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-properties-context.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
  packages/react-ui/src/app/builder/test-step/test-step-tooltip.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/first-time-testing-section.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/index.tsx
  packages/react-ui/src/features/pieces/lib/pieces-hooks.ts
Labels: 🐛 bug

#8382 fix: column external id isn't used in tables actions/triggers in table releases
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/lib/actions/create-records.ts
  packages/pieces/community/tables/src/lib/actions/update-record.ts
  packages/pieces/community/tables/src/lib/common/index.ts
  packages/pieces/community/tables/src/lib/triggers/new-record.ts
  packages/react-ui/src/app/routes/project-release/index.tsx
  packages/shared/src/lib/flows/operations/migrations/index.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v0-branch-to-router.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v1-connection-ids.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v2-agent-piece.ts
Labels: 🐛 bug

#8415 chore: improve global error handling
  packages/react-ui/src/app/app.tsx
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/react-ui/src/app/routes/platform/projects/edit-project-dialog.tsx
  packages/react-ui/src/app/routes/platform/projects/new-project-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/api-keys/new-api-key-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/templates/upsert-template-dialog.tsx
  packages/react-ui/src/app/routes/platform/users/update-user-dialog.tsx
  packages/react-ui/src/app/routes/project-release/apply-plan.tsx
  packages/react-ui/src/app/routes/settings/pieces/manage-pieces-dialog.tsx
  packages/react-ui/src/components/ui/toast.tsx
  packages/react-ui/src/features/alerts/lib/alert-hooks.ts
  packages/react-ui/src/features/billing/lib/billing-hooks.ts
  packages/react-ui/src/features/connections/lib/app-connections-hooks.ts
  packages/react-ui/src/features/connections/lib/global-connections-hooks.ts
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
  packages/react-ui/src/features/folders/component/create-folder-dialog.tsx
  packages/react-ui/src/features/folders/component/rename-folder-dialog.tsx
  packages/react-ui/src/features/platform-admin/components/new-signing-key-dialog.tsx
Labels: skip-changelog

#8416 feat: connect checkly to github action and run e2e tests
  .github/workflows/e2e-tests.yml
  docs/handbook/engineering/playbooks/e2e-tests.mdx
  package-lock.json
  package.json
  packages/tests-e2e/checkly.config.ts
  packages/tests-e2e/helper/config.ts
  packages/tests-e2e/project.json
  packages/tests-e2e/scenarios/flows/send-slack-message.check.ts
  packages/tests-e2e/scenarios/flows/webhook-should-return-response.check.ts
  tools/scripts/format-checkly-report.js
Labels: ✨ polishing

#8425 fix(piece.dimo): telemetry actions, typos
  packages/pieces/community/dimo/package.json
  packages/pieces/community/dimo/src/index.ts
  packages/pieces/community/dimo/src/lib/actions/telemetry/action.ts
  packages/pieces/community/dimo/src/lib/common/queries.ts
Labels: 🔌 pieces

#8356 feat: ninox piece
  packages/pieces/community/ninox/.eslintrc.json
  packages/pieces/community/ninox/README.md
  packages/pieces/community/ninox/package.json
  packages/pieces/community/ninox/project.json
  packages/pieces/community/ninox/src/index.ts
  packages/pieces/community/ninox/src/lib/actions/create-record.ts
  packages/pieces/community/ninox/src/lib/actions/delete-record.ts
  packages/pieces/community/ninox/src/lib/actions/download-file-from-record-.ts
  packages/pieces/community/ninox/src/lib/actions/find-record.ts
  packages/pieces/community/ninox/src/lib/actions/list-files-from-record.ts
  packages/pieces/community/ninox/src/lib/actions/update-record.ts
  packages/pieces/community/ninox/src/lib/actions/upload-file.ts
  packages/pieces/community/ninox/src/lib/common/auth.ts
  packages/pieces/community/ninox/src/lib/common/client.ts
  packages/pieces/community/ninox/src/lib/common/props.ts
  packages/pieces/community/ninox/src/lib/triggers/new-record.ts
  packages/pieces/community/ninox/tsconfig.json
  packages/pieces/community/ninox/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8427 feat: eden-ai piece
  packages/pieces/community/eden-ai/README.md
  packages/pieces/community/eden-ai/package.json
  packages/pieces/community/eden-ai/project.json
  packages/pieces/community/eden-ai/src/index.ts
  packages/pieces/community/eden-ai/src/lib/actions/detect-language.ts
  packages/pieces/community/eden-ai/src/lib/actions/extract-entities.ts
  packages/pieces/community/eden-ai/src/lib/actions/extract-keywords.ts
  packages/pieces/community/eden-ai/src/lib/actions/generate-text.ts
  packages/pieces/community/eden-ai/src/lib/actions/image-generation.ts
  packages/pieces/community/eden-ai/src/lib/actions/invoice-parser.ts
  packages/pieces/community/eden-ai/src/lib/actions/moderate-text.ts
  packages/pieces/community/eden-ai/src/lib/actions/ocr-image.ts
  packages/pieces/community/eden-ai/src/lib/actions/receipt-parser.ts
  packages/pieces/community/eden-ai/src/lib/actions/spell-check.ts
  packages/pieces/community/eden-ai/src/lib/actions/summarize-text.ts
  packages/pieces/community/eden-ai/src/lib/actions/text-to-speech.ts
  packages/pieces/community/eden-ai/src/lib/actions/translate-text.ts
  packages/pieces/community/eden-ai/src/lib/common/client.ts
  packages/pieces/community/eden-ai/src/lib/common/providers.ts
  packages/pieces/community/eden-ai/tsconfig.json
  packages/pieces/community/eden-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#8373 feat(messagebird): dayjs usage for datetime fields and Custom API action
  packages/pieces/community/messagebird/package.json
  packages/pieces/community/messagebird/src/index.ts
  packages/pieces/community/messagebird/src/lib/actions/list-messages.ts
Labels: 🔌 pieces

#7524 feat: quickbooks piece
  packages/pieces/community/quickbooks/.eslintrc.json
  packages/pieces/community/quickbooks/README.md
  packages/pieces/community/quickbooks/package.json
  packages/pieces/community/quickbooks/project.json
  packages/pieces/community/quickbooks/src/actions/create-expense.ts
  packages/pieces/community/quickbooks/src/actions/create-invoice.ts
  packages/pieces/community/quickbooks/src/actions/find-customer.ts
  packages/pieces/community/quickbooks/src/actions/find-invoice.ts
  packages/pieces/community/quickbooks/src/actions/find-payment.ts
  packages/pieces/community/quickbooks/src/index.ts
  packages/pieces/community/quickbooks/src/lib/common.ts
  packages/pieces/community/quickbooks/src/lib/types.ts
  packages/pieces/community/quickbooks/src/triggers/new-customer.ts
  packages/pieces/community/quickbooks/src/triggers/new-deposit.ts
  packages/pieces/community/quickbooks/src/triggers/new-expense.ts
  packages/pieces/community/quickbooks/src/triggers/new-invoice.ts
  packages/pieces/community/quickbooks/src/triggers/new-transfer.ts
  packages/pieces/community/quickbooks/tsconfig.json
  packages/pieces/community/quickbooks/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8448 feat: added needed permission to download captions for Youtube piece
  package-lock.json
  packages/pieces/community/youtube/package.json
  packages/pieces/community/youtube/src/lib/common/auth.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: 🔌 pieces

#8449 feat(eden-ai): improve piece metadata and bump version
  packages/pieces/community/eden-ai/.eslintrc.json
  packages/pieces/community/eden-ai/package.json
  packages/pieces/community/eden-ai/src/index.ts
Labels: 🔌 pieces

#8354 feat: sendpulse piece
  packages/pieces/community/sendpulse/README.md
  packages/pieces/community/sendpulse/package.json
  packages/pieces/community/sendpulse/project.json
  packages/pieces/community/sendpulse/src/index.ts
  packages/pieces/community/sendpulse/src/lib/actions/add-subscriber.ts
  packages/pieces/community/sendpulse/src/lib/actions/change-variable-for-subscriber.ts
  packages/pieces/community/sendpulse/src/lib/actions/delete-contact.ts
  packages/pieces/community/sendpulse/src/lib/actions/unsubscribe-user.ts
  packages/pieces/community/sendpulse/src/lib/actions/update-subscriber.ts
  packages/pieces/community/sendpulse/src/lib/common/auth.ts
  packages/pieces/community/sendpulse/src/lib/common/client.ts
  packages/pieces/community/sendpulse/src/lib/common/props.ts
  packages/pieces/community/sendpulse/src/lib/triggers/new-subscriber.ts
  packages/pieces/community/sendpulse/src/lib/triggers/new-unsubscriber.ts
  packages/pieces/community/sendpulse/src/lib/triggers/updated-subscriber.ts
  packages/pieces/community/sendpulse/tsconfig.json
  packages/pieces/community/sendpulse/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8450 fix: ai usage sqlite migration
  packages/server/api/src/app/database/migration/sqlite/1751475726665-AddPlatformIdToAIUsageSqlite.ts
Labels: 🐛 bug

#8452 fix: keyboard navigation between cells in Activepieces tables product
  packages/react-ui/src/app/routes/tables/id/index.tsx
  packages/react-ui/src/app/routes/tables/index.tsx
  packages/react-ui/src/components/ui/drawer.tsx
  packages/react-ui/src/features/tables/components/editable-cell.tsx
  packages/react-ui/src/features/tables/lib/table-hooks.ts
Labels: 🐛 bug

#8453 fix: pass environment to discord notifications on e2e tests failure
  .github/workflows/e2e-tests.yml
  tools/scripts/format-checkly-report.js
Labels: skip-changelog

#8430 fix(dimo.piece): target_uri fix, naming conventions refactor
  packages/pieces/community/dimo/package.json
  packages/pieces/community/dimo/src/lib/actions/attestation/action.ts
  packages/pieces/community/dimo/src/lib/actions/device-definitions/action.ts
  packages/pieces/community/dimo/src/lib/actions/identity/action.ts
  packages/pieces/community/dimo/src/lib/actions/telemetry/action.ts
  packages/pieces/community/dimo/src/lib/actions/token-exchange/action.ts
  packages/pieces/community/dimo/src/lib/actions/vehicle-events/actions.ts
  packages/pieces/community/dimo/src/lib/common/helpers.ts
  packages/pieces/community/dimo/src/lib/common/types.ts
  packages/pieces/community/dimo/src/lib/triggers/battery-charging/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/battery-power/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/charge-level/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/fuel-absolute-level/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/fuel-relative-level/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/ignition/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/odometer/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/speed/trigger.ts
  packages/pieces/community/dimo/src/lib/triggers/tire-pressure/trigger.ts
Labels: 🔌 pieces

#8463 fix: analytics was showing random projects in the top projects by active flows section
  package-lock.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/analytics/platform-analytics-report.service.ts
  packages/server/api/src/app/ee/analytics/platform-analytics.module.ts
Labels: 🐛 bug

#8339 feat(peekshot): capture screenshot action
  packages/pieces/community/peekshot/.eslintrc.json
  packages/pieces/community/peekshot/README.md
  packages/pieces/community/peekshot/package.json
  packages/pieces/community/peekshot/project.json
  packages/pieces/community/peekshot/src/index.ts
  packages/pieces/community/peekshot/src/lib/actions/capture-screenshot.ts
  packages/pieces/community/peekshot/src/lib/common/props.ts
  packages/pieces/community/peekshot/src/lib/common/types.ts
  packages/pieces/community/peekshot/tsconfig.json
  packages/pieces/community/peekshot/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#8459 feat(pdf): extract PDF pages and get page count actions
  packages/pieces/community/pdf/jest.config.ts
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/project.json
  packages/pieces/community/pdf/src/index.ts
  packages/pieces/community/pdf/src/lib/actions/extract-pdf-pages.ts
  packages/pieces/community/pdf/src/lib/actions/pdf-page-count.ts
  packages/pieces/community/pdf/test/extract-pdf-pages.test.ts
  packages/pieces/community/pdf/tsconfig.spec.json
Labels: 🔌 pieces, 💫 priority

#8490 feat: added alert in dashboard for AI credits
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/project-settings-dropdown-menu.tsx
  packages/react-ui/src/app/components/project-settings-layout.tsx
  packages/react-ui/src/app/components/sidebar/index.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/flows/task-limit-alert.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/settings/alerts/alerts-email-list-card.tsx
  packages/react-ui/src/app/routes/settings/alerts/alerts-frequency-card.tsx
  packages/react-ui/src/app/routes/settings/environment/index.tsx
  packages/react-ui/src/app/routes/settings/project-members/index.tsx
  packages/react-ui/src/components/ui/avatar.tsx
  packages/react-ui/src/features/billing/components/ai-credits-limit-alert.tsx
  packages/react-ui/src/features/billing/components/limit-alert.tsx
  packages/react-ui/src/features/billing/components/project-locked-alert.tsx
  packages/react-ui/src/features/billing/components/task-limit-alert.tsx
  packages/react-ui/src/features/projects/components/edit-project-dialog.tsx
  packages/react-ui/src/hooks/project-hooks.ts
Labels: 🌟 feature

#8493 feat: release 0.66.4
  docker-compose.yml
  package.json
Labels: release

#8497 fix: handle optional props, support string/object in MCP dropdown
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
Labels: 🐛 bug

#8487 feat: bitly piece
  packages/pieces/community/bitly/README.md
  packages/pieces/community/bitly/package.json
  packages/pieces/community/bitly/project.json
  packages/pieces/community/bitly/src/index.ts
  packages/pieces/community/bitly/src/lib/actions/archive-bitlink.ts
  packages/pieces/community/bitly/src/lib/actions/create-bitlink.ts
  packages/pieces/community/bitly/src/lib/actions/create-qr-code.ts
  packages/pieces/community/bitly/src/lib/actions/get-bitlink-details.ts
  packages/pieces/community/bitly/src/lib/actions/update-bitlink.ts
  packages/pieces/community/bitly/src/lib/common/auth.ts
  packages/pieces/community/bitly/src/lib/common/client.ts
  packages/pieces/community/bitly/src/lib/common/props.ts
  packages/pieces/community/bitly/src/lib/triggers/new-bitlink-created.ts
  packages/pieces/community/bitly/tsconfig.json
  packages/pieces/community/bitly/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#8469 fix(pieces.dimo): Webhooks
  packages/pieces/community/dimo/package.json
  packages/pieces/community/dimo/src/lib/actions/vehicle-events/actions.ts
  packages/pieces/community/dimo/src/lib/common/helpers.ts
  packages/pieces/community/dimo/src/lib/common/types.ts
  packages/pieces/community/dimo/src/lib/triggers/ignition/trigger.ts
Labels: 🔌 pieces

#8517 feat: add runCompleted property to Agent and AgentCard components,
  packages/react-ui/src/app/routes/agents/index.tsx
  packages/react-ui/src/features/agents/agent-card.tsx
  packages/server/api/src/app/agents/agent-runs/agent-run.entity.ts
  packages/server/api/src/app/agents/agent-runs/agent-runs-service.ts
  packages/server/api/src/app/agents/agents-service.ts
  packages/server/api/src/app/database/migration/postgres/1753400133786-AddIndexForAgentTable.ts
  packages/server/api/src/app/database/migration/sqlite/1753400496920-AddIndexForAgentTableSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/shared/src/lib/agents/index.ts
Labels: ✨ polishing

#8477 feat: systeme-io piece
  packages/pieces/community/systeme-io/README.md
  packages/pieces/community/systeme-io/package.json
  packages/pieces/community/systeme-io/project.json
  packages/pieces/community/systeme-io/src/index.ts
  packages/pieces/community/systeme-io/src/lib/actions/add-tag-to-contact.ts
  packages/pieces/community/systeme-io/src/lib/actions/create-contact.ts
  packages/pieces/community/systeme-io/src/lib/actions/find-contact-by-email.ts
  packages/pieces/community/systeme-io/src/lib/actions/remove-tag-from-contact.ts
  packages/pieces/community/systeme-io/src/lib/actions/update-contact.ts
  packages/pieces/community/systeme-io/src/lib/common/auth.ts
  packages/pieces/community/systeme-io/src/lib/common/client.ts
  packages/pieces/community/systeme-io/src/lib/common/index.ts
  packages/pieces/community/systeme-io/src/lib/common/props.ts
  packages/pieces/community/systeme-io/src/lib/triggers/new-contact.ts
  packages/pieces/community/systeme-io/src/lib/triggers/new-sale.ts
  packages/pieces/community/systeme-io/src/lib/triggers/new-tag-added-to-contact.ts
  packages/pieces/community/systeme-io/tsconfig.json
  packages/pieces/community/systeme-io/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#8524 feat: add throwErrorOnFailure option to trigger execution and enhance…
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/cloud-oauth2-service.ts
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
  packages/server/shared/src/index.ts
  packages/server/shared/src/lib/ap-axios.ts
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
  packages/server/worker/src/lib/executors/trigger/hooks/extract-trigger-payload-hooks.ts
  packages/server/worker/src/lib/utils/webhook-utils.ts
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 🐛 bug

#8533 fix(tables): enrich agent in tables
  packages/server/api/src/app/tables/table/table.service.ts
Labels: 🐛 bug

#8540 fix: renaming table wasn't working inside the table editor
  packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx
  packages/react-ui/src/features/tables/lib/store/ap-tables-server-state.ts
Labels: 🐛 bug

#8522 chore: new translations for sendfox, spotify and date helper
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/date-helper/src/i18n/de.json
  packages/pieces/community/sendfox/package.json
  packages/pieces/community/sendfox/src/i18n/ru.json
  packages/pieces/community/spotify/package.json
  packages/pieces/community/spotify/src/i18n/ru.json
Labels: 🔌 pieces

#8552 feat: ai credits usage table for enterprise
  packages/react-ui/src/app/routes/platform/billing/index.tsx
Labels: 🌟 feature

#8551 fix(ai proxy): utility ai openai moderation requests
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/lib/actions/check-moderation.ts
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
  packages/server/api/src/app/ai/ai-provider-service.ts
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/ai/providers/openai.ts
  packages/server/api/src/app/ai/providers/types.ts
Labels: 🐛 bug

#8549 feat(utility ai): support pdf in extract structured data action
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
Labels: 🔌 pieces

#8556 fix: agent table for sqlite
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1753366163403-MakeTriggerNullable.ts
  packages/server/api/src/app/database/migration/sqlite/1753400496920-AddIndexForAgentTableSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
Labels: 🐛 bug

#8545 fix(subflows): handle failed subflow responses to prevent main flow hanging
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/error-handling.ts
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/index.ts
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/actions/respond.ts
  packages/pieces/community/subflows/src/lib/common.ts
  packages/server/api/src/app/database/migration/postgres/1753699877817-AddParentRunIdToFlowRun.ts
  packages/server/api/src/app/database/migration/postgres/1753727379513-AddCascadeOnAgents.ts
  packages/server/api/src/app/database/migration/sqlite/1753719777841-AddParentRunIdToFlowRunSqlite.ts
  packages/server/api/src/app/database/migration/sqlite/1753727589109-AddCascadeOnAgentsSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-run/flow-run-entity.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/shared/package.json
  packages/server/shared/src/lib/job/index.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/flow-run/flow-run.ts
Labels: 🐛 bug, 🔌 pieces

#8558 fix: import csv dialog not showing up
  packages/react-ui/src/features/tables/components/ap-table-header.tsx
  packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
Labels: 🐛 bug

#8559 fix: allow piece to work with api
  packages/server/api/src/app/pieces/base-piece-module.ts
Labels: 🧹 clean up

#8527 feat: grok-xai piece
  packages/pieces/community/grok-xai/.eslintrc.json
  packages/pieces/community/grok-xai/README.md
  packages/pieces/community/grok-xai/package.json
  packages/pieces/community/grok-xai/project.json
  packages/pieces/community/grok-xai/src/index.ts
  packages/pieces/community/grok-xai/src/lib/actions/ask-grok.ts
  packages/pieces/community/grok-xai/src/lib/actions/categorize-text.ts
  packages/pieces/community/grok-xai/src/lib/actions/extract-data.ts
  packages/pieces/community/grok-xai/src/lib/actions/generate-image.ts
  packages/pieces/community/grok-xai/src/lib/common/auth.ts
  packages/pieces/community/grok-xai/src/lib/common/constants.ts
  packages/pieces/community/grok-xai/src/lib/common/utils.ts
  packages/pieces/community/grok-xai/tsconfig.json
  packages/pieces/community/grok-xai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8553 feat(amazon-s3): delete file
  packages/pieces/community/amazon-s3/package.json
  packages/pieces/community/amazon-s3/src/index.ts
  packages/pieces/community/amazon-s3/src/lib/actions/delete-file.ts
Labels: 🔌 pieces, 💫 priority

#8532 fix(pieces.dimo): webhookDefinition required error
  packages/pieces/community/dimo/package.json
  packages/pieces/community/dimo/src/lib/actions/vehicle-events/actions.ts
  packages/pieces/community/dimo/src/lib/actions/vehicle-events/constant.ts
Labels: 🔌 pieces

#8528 feat(flow-helper): add stop flow execution action
  packages/pieces/community/flow-helper/package.json
  packages/pieces/community/flow-helper/src/index.ts
  packages/pieces/community/flow-helper/src/lib/actions/stop-flow.ts
Labels: 🔌 pieces

#8550 feat: teamleader piece
  packages/pieces/community/teamleader/.eslintrc.json
  packages/pieces/community/teamleader/README.md
  packages/pieces/community/teamleader/package.json
  packages/pieces/community/teamleader/project.json
  packages/pieces/community/teamleader/src/index.ts
  packages/pieces/community/teamleader/src/lib/actions/create-company.ts
  packages/pieces/community/teamleader/src/lib/actions/create-contact.ts
  packages/pieces/community/teamleader/src/lib/actions/create-deal.ts
  packages/pieces/community/teamleader/src/lib/actions/link-contact-to-company.ts
  packages/pieces/community/teamleader/src/lib/actions/search-companies.ts
  packages/pieces/community/teamleader/src/lib/actions/search-contacts.ts
  packages/pieces/community/teamleader/src/lib/actions/search-deals.ts
  packages/pieces/community/teamleader/src/lib/actions/search-invoices.ts
  packages/pieces/community/teamleader/src/lib/actions/unlink-contact-from-company.ts
  packages/pieces/community/teamleader/src/lib/actions/update-company.ts
  packages/pieces/community/teamleader/src/lib/actions/update-contact.ts
  packages/pieces/community/teamleader/src/lib/actions/update-deal.ts
  packages/pieces/community/teamleader/src/lib/common/auth.ts
  packages/pieces/community/teamleader/src/lib/common/client.ts
  packages/pieces/community/teamleader/src/lib/triggers/deal-accepted.ts
  packages/pieces/community/teamleader/src/lib/triggers/new-company.ts
  packages/pieces/community/teamleader/src/lib/triggers/new-contact.ts
  packages/pieces/community/teamleader/src/lib/triggers/new-deal.ts
  packages/pieces/community/teamleader/src/lib/triggers/new-invoice.ts
  packages/pieces/community/teamleader/tsconfig.json
  packages/pieces/community/teamleader/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8564 fix(ai usage): remove duplicate table on cloud
  packages/react-ui/src/app/routes/platform/billing/index.tsx
Labels: 🐛 bug

#8572 revert: add back eslint to new pieces
  packages/cli/src/lib/commands/create-piece.ts
Labels: skip-changelog

#8571 fix: refactor flow cache / piece cache & remove package type
  packages/engine/src/lib/operations.ts
  packages/engine/test/handler/test-helper.ts
  packages/react-ui/src/app/builder/piece-properties/dynamic-dropdown-piece-property.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/features/pieces/lib/piece-selector-utils.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/pieces/piece-metadata-service/index.ts
  packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts
  packages/server/worker/src/lib/api/flow-worker-cache.ts
  packages/server/worker/src/lib/api/piece-worker-cache.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
  packages/server/worker/src/lib/executors/user-interaction-job-executor.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
  packages/server/worker/src/lib/runner/index.ts
  packages/server/worker/src/lib/utils/flow-engine-util.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/flows/actions/action.ts
  packages/shared/src/lib/flows/triggers/trigger.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  packages/shared/test/flow/flow-helper.test.ts
Labels: 🧹 clean up

#8502 feat: knack piece
  packages/pieces/community/knack/.eslintrc.json
  packages/pieces/community/knack/README.md
  packages/pieces/community/knack/package.json
  packages/pieces/community/knack/project.json
  packages/pieces/community/knack/src/index.ts
  packages/pieces/community/knack/src/lib/actions/create-record.ts
  packages/pieces/community/knack/src/lib/actions/delete-record.ts
  packages/pieces/community/knack/src/lib/actions/find-record.ts
  packages/pieces/community/knack/src/lib/actions/update-record.ts
  packages/pieces/community/knack/src/lib/common/auth.ts
  packages/pieces/community/knack/src/lib/common/client.ts
  packages/pieces/community/knack/src/lib/common/props.ts
  packages/pieces/community/knack/tsconfig.json
  packages/pieces/community/knack/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8480 fix(oAuth): ability to alter prompt query parameter
  packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts
  packages/pieces/community/microsoft-dynamics-365-business-central/src/index.ts
  packages/pieces/community/microsoft-dynamics-crm/src/index.ts
  packages/pieces/community/microsoft-excel-365/src/index.ts
  packages/pieces/community/microsoft-onedrive/src/index.ts
  packages/pieces/community/microsoft-outlook-calendar/src/index.ts
  packages/pieces/community/microsoft-outlook/src/lib/common/auth.ts
  packages/pieces/community/microsoft-power-bi/src/index.ts
  packages/pieces/community/microsoft-sharepoint/src/index.ts
  packages/pieces/community/microsoft-teams/src/index.ts
  packages/pieces/community/microsoft-todo/src/index.ts
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
  packages/react-ui/src/lib/oauth2-utils.ts
Labels: 💫 priority

#8575 fix: use external id in call flow action
  packages/engine/src/lib/services/flows.service.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/common.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flows/dto/list-flows-request.ts
Labels: ✨ polishing

#8514 feat: hunter piece
  packages/pieces/community/hunter/.eslintrc.json
  packages/pieces/community/hunter/README.md
  packages/pieces/community/hunter/package.json
  packages/pieces/community/hunter/project.json
  packages/pieces/community/hunter/src/index.ts
  packages/pieces/community/hunter/src/lib/actions/add-recipients.ts
  packages/pieces/community/hunter/src/lib/actions/count-emails.ts
  packages/pieces/community/hunter/src/lib/actions/create-lead.ts
  packages/pieces/community/hunter/src/lib/actions/delete-lead.ts
  packages/pieces/community/hunter/src/lib/actions/find-email.ts
  packages/pieces/community/hunter/src/lib/actions/get-lead.ts
  packages/pieces/community/hunter/src/lib/actions/search-leads.ts
  packages/pieces/community/hunter/src/lib/actions/update-lead.ts
  packages/pieces/community/hunter/src/lib/actions/verify-email.ts
  packages/pieces/community/hunter/src/lib/common/index.ts
  packages/pieces/community/hunter/src/lib/common/props.ts
  packages/pieces/community/hunter/src/lib/common/types.ts
  packages/pieces/community/hunter/src/lib/triggers/new-lead.ts
  packages/pieces/community/hunter/tsconfig.json
  packages/pieces/community/hunter/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8582 feat(stripe): subscription search action
  packages/pieces/community/stripe/package.json
  packages/pieces/community/stripe/src/index.ts
  packages/pieces/community/stripe/src/lib/actions/search-subscriptions.ts
Labels: 🔌 pieces

#8567 fix(amazon s3): improve content type and file extension handling
  packages/pieces/community/amazon-s3/package.json
  packages/pieces/community/amazon-s3/src/lib/actions/upload-file.ts
Labels: 🔌 pieces, 💫 priority

#8593 fix: install piece from registry timing out
  packages/server/worker/src/lib/runner/index.ts
  packages/server/worker/src/lib/utils/flow-engine-util.ts
Labels: 🐛 bug

#8603 fix: enhance claude instructions in mcp connect
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-connect/config-display.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-connect/index.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-connect/mcp-connect-utils.tsx
Labels: ✨ polishing
