Repository activepieces/activepieces, pull requests merged in 2025-03, with the labels that each got.

#6978 fix: query piece larger than 1.0.0
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
  packages/shared/src/lib/flows/operations/flow-piece-util.ts
  packages/shared/src/lib/flows/util/flow-piece-util.ts
Labels: 🐛 bug

#6979 fix: add body limit again after accidental remove
  packages/server/api/src/app/server.ts
Labels: 🐛 bug

#6977 feat: add respond piece framework and return response action
  packages/engine/src/lib/handler/piece-executor.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/lib/actions/return-response.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🌟 feature

#6930 feat: show input data for testing a step
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/operations.ts
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/builder-state-provider.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
  packages/react-ui/src/app/builder/run-details/flow-step-input-output.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/app/routes/flows/id/index.tsx
  packages/react-ui/src/app/routes/runs/id/index.tsx
  packages/react-ui/src/components/json-viewer.tsx
  packages/react-ui/src/features/flows/lib/sample-data-hooks.ts
  packages/server/api/src/app/database/migration/common/1731019013340-switch-to-router.ts
  packages/server/api/src/app/file/file.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow-version/flow-version-side-effects.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow-service-side-effects.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/step-run/sample-data.controller.ts
  packages/server/api/src/app/flows/step-run/sample-data.service.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/file/index.ts
  packages/shared/src/lib/flows/operations/add-action-util.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-branch-to-router.ts
  packages/shared/src/lib/flows/sample-data/index.ts
Labels: 🌟 feature

#6983 chore: release 0.46.0
  docker-compose.yml
  package.json
Labels: release

#6984 feat(auto-trial-activation): automatically activate a trial key when the platform is deployed on the cloud
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/ee/license-keys/license-keys-trial.service.ts
Labels: 🐛 bug

#6985 fix: missing Write project permission for alert settings & missing folders/alerts in project role dialog
  package-lock.json
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
  packages/react-ui/src/app/routes/settings/alerts/alerts-frequency-card.tsx
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
Labels: 🐛 bug

#6986 fix: we should always use importFresh in code executor
  packages/engine/src/lib/handler/code-executor.ts
Labels: 🐛 bug

#6987 feat: new release 0.46.1
  docker-compose.yml
  package-lock.json
  package.json
  packages/engine/src/lib/handler/code-executor.ts
Labels: release

#6988 fix: editorTheme typo
  packages/react-ui/src/components/custom/json-editor.tsx
Labels: skip-changelog

#6992 feat: add respond to webhook return response action
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/index.ts
  packages/pieces/community/webhook/src/lib/actions/return-response.ts
Labels: 🔌 pieces

#6993 fix: UI error when using AI generated code before ever testing the step.
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
Labels: 🐛 bug

#6999 fix: get used piecess
  packages/shared/src/lib/flows/util/flow-piece-util.ts
Labels: 🐛 bug

#6994 fix: saving SSO providers + show trial license key expiration date
  packages/react-ui/src/app/builder/piece-properties/array-property.tsx
  packages/react-ui/src/app/builder/step-settings/branch-settings/branch-single-condition.tsx
  packages/react-ui/src/app/routes/platform/security/sso/allowed-domain.tsx
  packages/react-ui/src/app/routes/platform/security/sso/oauth2-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/sso/saml-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/copilot/configure-provider-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/copilot/index.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/index.tsx
  packages/react-ui/src/lib/platforms-api.ts
  packages/react-ui/vite.config.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/federated-authn/index.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: 🐛 bug

#7001 feat: optimize fetching /options for pieces by using cache
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
  packages/server/worker/src/lib/piece-manager/local-piece-manager.ts
Labels: ✨ polishing

#7002 feat: release v0.46.2
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#6957 fix(cli): fix gelato piece creation command
  packages/cli/src/lib/commands/create-trigger.ts
  tsconfig.base.json
Labels: 🐛 bug

#7004 feat: redis config
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/api/src/app/helper/system/system.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
  packages/server/shared/src/lib/system-props.ts
Labels: 🐛 bug

#7003 feat: release 0.46.3
  docker-compose.yml
  package.json
Labels: release

#7006 fix: add folder permission to default roles
  packages/ee/shared/src/lib/authn/access-control-list.ts
  packages/react-ui/src/hooks/authorization-hooks.ts
  packages/react-ui/src/lib/authentication-api.ts
Labels: 🐛 bug

#7007 fix: show dynamic value toggle in trigger input settings
  package-lock.json
  packages/react-ui/src/app/builder/step-settings/piece-settings/index.tsx
Labels: 🐛 bug

#7008 feat: release v0.46.4
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7010 fix: remove project id from sdk route changed event
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/lib/utils.ts
Labels: 🐛 bug

#7011 fix: stop flickering on SDK connect method call
  docs/about/breaking-changes.mdx
  docs/embedding/navigation.mdx
  docs/embedding/sdk-changelog.mdx
  packages/react-ui/src/app/components/initial-data-guard.tsx
  packages/react-ui/src/app/components/loading-screen.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/components/embed-provider.tsx
  packages/react-ui/src/components/ui/dialog.tsx
Labels: 🐛 bug

#7015 feat: release 0.46.5
  docker-compose.yml
  package.json
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/flows/flow-version/flow-version-validator-util.ts
Labels: release

#7025 fix: Array of properties inside a dynamic property wasn't always saving input
  packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx
  packages/react-ui/src/app/builder/piece-properties/custom-property.tsx
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
Labels: 🐛 bug

#7026 feat: release 0.46.6
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7027 feat: release 0.46.7
  docker-compose.yml
  package.json
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
Labels: release

#7030 fix: nullable project id
  packages/server/api/src/app/database/migration/1741357285896-ProjectIdNullableInTemplate.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/flow-template/flow-template.entity.ts
  packages/server/api/src/app/ee/flow-template/flow-template.service.ts
  packages/shared/src/lib/flows/dto/flow-template-request.ts
Labels: 🐛 bug

#7029 feat: add support for claude 3.7 sonnet model
  packages/pieces/community/claude/package.json
  packages/pieces/community/claude/src/lib/actions/extract-structured-data.ts
  packages/pieces/community/claude/src/lib/actions/send-prompt.ts
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/providers/index.ts
Labels: 🔌 pieces

#7016 fix(google-drive): support shared drive files in list files action
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/list-files.action.ts
Labels: 🔌 pieces

#7033 fix: respond on continue in webhook
  package-lock.json
  packages/engine/src/lib/handler/context/flow-execution-context.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/services/progress.service.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/worker/package.json
  packages/shared/src/lib/engine/requests.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🐛 bug

#6956 feat(hubspot): delete/get landing page/ site page actions
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/index.ts
  packages/pieces/community/hubspot/src/lib/actions/create-page.ts
  packages/pieces/community/hubspot/src/lib/actions/delete-page.ts
  packages/pieces/community/hubspot/src/lib/actions/get-page.ts
  packages/pieces/community/hubspot/src/lib/common/props.ts
Labels: 🔌 pieces

#7061 fix: data selector breaking when results contained null values
  packages/react-ui/src/app/builder/data-selector/type.ts
  packages/react-ui/src/app/builder/data-selector/utils.ts
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
Labels: 🐛 bug

#7071 fix: sync flow status with project state in project release
  packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts
  packages/server/shared/package.json
Labels: 🐛 bug

#7073 feat: release v0.46.8
  docker-compose.yml
  package.json
Labels: release

#7078 fix: revert stop response type for webhook piece
  packages/pieces/community/assemblyai/package.json
  packages/pieces/community/assemblyai/src/lib/actions/transcripts/transcribe.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🐛 bug

#7079 feat: release v0.46.9
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7080 feat(slack): new command trigger and get file action
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/get-file.ts
  packages/pieces/community/slack/src/lib/triggers/new-command.ts
Labels: 🔌 pieces

#7072 fix: support duplicate query params for arrays
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/http/axios/axios-http-client.ts
  packages/pieces/community/http/package.json
Labels: 🔌 pieces

#7086 fix: allow deleting single tables + introduce actions menu in /tables route
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/index.ts
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/ap-tables/id/index.tsx
  packages/react-ui/src/app/routes/ap-tables/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx
  packages/react-ui/src/components/ui/dropdown-menu.tsx
  packages/react-ui/src/features/flows/lib/flows-hooks.ts
  packages/react-ui/src/features/flows/lib/flows-utils.tsx
  packages/react-ui/src/features/tables/components/ap-table-actions-menu.tsx
  packages/react-ui/src/features/tables/components/column-header.tsx
  packages/react-ui/src/features/tables/components/new-field-popup.tsx
  packages/react-ui/src/features/tables/components/rename-table-dialog.tsx
  packages/react-ui/src/features/tables/lib/utils.tsx
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/tables/dto/tables.dto.ts
Labels: ✨ polishing

#7091 fix: progress bar value usage limits
  packages/react-ui/src/app/components/usage-limits-button.tsx
Labels: 🐛 bug

#7096 feat: allow to manual override notify status for embed users
  packages/server/api/src/app/database/migration/postgres/1741963410825-UpdateNotifyStatusOnEmbedding.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/alerts/alerts-handler.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
  packages/server/api/src/app/ee/projects/ee-project-hooks.ts
  packages/server/api/src/app/project/project-service.ts
Labels: ✨ polishing

#7099 fix: check if jwt expired in current user
  packages/react-ui/src/hooks/user-hooks.ts
  packages/react-ui/src/lib/authentication-session.ts
  packages/shared/src/lib/authentication/model/principal.ts
Labels: 🐛 bug

#7100 feat: release 0.47.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7103 fix: upgrade all deps
  package-lock.json
  package.json
Labels: 🧹 clean up, dependencies

#7104 [Snyk] Security upgrade react-syntax-highlighter from 5.8.0 to 15.4.2
  package-lock.json
  package.json
Labels: 🧹 clean up

#7105 feat: release 0.47.1
  package.json
Labels: release

#7108 fix: add back license key link in platform admin dashboard
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/platform-admin-container.tsx
Labels: 🐛 bug

#7112 chore: bump release version
  docker-compose.yml
  package.json
Labels: release

#7114 fix(tables): fix find records action
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/lib/actions/find-records.ts
Labels: 🔌 pieces

#7125 fix: project switcher enterprise is filtering wrong projects
  packages/react-ui/src/app/components/sidebar.tsx
  packages/server/api/src/app/ee/projects/platform-user-project-controller.ts
Labels: 🐛 bug

#7126 feat: release v0.47.3
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7127 fix: image to pdf extension check
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/src/lib/actions/image-to-pdf.ts
Labels: 🔌 pieces

#7047 fix(onedrive): fix download file and list files action
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/lib/actions/download-file.ts
  packages/pieces/community/microsoft-onedrive/src/lib/actions/list-files.ts
Labels: 🔌 pieces

#7128 feat: new google slide piece
  packages/pieces/community/google-slides/.eslintrc.json
  packages/pieces/community/google-slides/README.md
  packages/pieces/community/google-slides/package.json
  packages/pieces/community/google-slides/project.json
  packages/pieces/community/google-slides/src/index.ts
  packages/pieces/community/google-slides/tsconfig.json
  packages/pieces/community/google-slides/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7129 feat(slack): retrieve slack thread messages action
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/retrieve-thread-messages.ts
Labels: 🔌 pieces

#7142 feat(Tables): added ability to rename fields
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/ap-tables/id/index.tsx
  packages/react-ui/src/components/ui/dropdown-menu.tsx
  packages/react-ui/src/features/tables/components/ap-field-header.tsx
  packages/react-ui/src/features/tables/components/column-header.tsx
  packages/react-ui/src/features/tables/components/field-action-menu-item-renderer.tsx
  packages/react-ui/src/features/tables/components/rename-field-popovercontent.tsx
  packages/react-ui/src/features/tables/lib/fields-api.ts
  packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx
  packages/react-ui/src/features/tables/lib/store/ap-tables-server-state.ts
  packages/react-ui/src/features/tables/lib/utils.tsx
  packages/server/api/src/app/tables/field/field.controller.ts
  packages/server/api/src/app/tables/field/field.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/tables/dto/fields.dto.ts
Labels: 🌟 feature

#6951 feat(pieces): Add Chainalysis Screening API integration piece
  packages/pieces/community/chainalysis-api/.eslintrc.json
  packages/pieces/community/chainalysis-api/README.md
  packages/pieces/community/chainalysis-api/package.json
  packages/pieces/community/chainalysis-api/project.json
  packages/pieces/community/chainalysis-api/src/index.ts
  packages/pieces/community/chainalysis-api/src/lib/actions/check-address-sanction.ts
  packages/pieces/community/chainalysis-api/tsconfig.json
  packages/pieces/community/chainalysis-api/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7138 fix(hubspot): convert checkbox property to static dropdown
  packages/pieces/community/hubspot/package.json
  packages/pieces/community/hubspot/src/lib/common/props.ts
Labels: 🔌 pieces

#7143 feat(sftp): add option to allow connecting to ftps server with a self-signed certificate
  packages/pieces/community/sftp/package.json
  packages/pieces/community/sftp/src/index.ts
Labels: 🔌 pieces

#7137 fix: get license key from db for usage job
  packages/react-ui/src/lib/request-trial-api.ts
  packages/server/api/src/app/ee/license-keys/license-keys-controller.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
  packages/server/api/src/app/helper/system-jobs/common.ts
Labels: 🐛 bug

#7139 feat: add rawBody to webhook trigger payload
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/shared/src/lib/engine/engine-operation.ts
Labels: ✨ polishing

#7044 fix(docs): change `AP_ENCRYPTION_KEY` parameter length
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/helper/system-validator.ts
Labels: 📚 documentation

#7038 fix(google-sheets): fix special characters breaking columns dropdown
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/find-spreadsheets.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
Labels: 🔌 pieces

#6847 fix(grist): fix default workspace
  packages/pieces/community/grist/package.json
  packages/pieces/community/grist/src/index.ts
  packages/pieces/community/grist/src/lib/common/helpers.ts
  packages/pieces/community/grist/src/lib/common/types.ts
Labels: 🔌 pieces

#7145 feat: bump release
  docker-compose.yml
  package.json
Labels: release

#7147 fix: smtp port not found when inviting user
  packages/server/api/src/app/ee/helper/email/email-sender/smtp-email-sender.ts
Labels: 🐛 bug

#7149 fix: prevent crashing in data selector
  packages/react-ui/src/app/builder/data-selector/utils.ts
Labels: 🐛 bug

#7152 feat: release 0.48.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7154 feat: release 0.48.1
  docker-compose.yml
  package.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1742432827826-ChangeManualTasksToTodo.ts
  packages/server/api/src/app/database/migration/postgres/1742433144687-ChangeManualTasksCommentsToTodoComments.ts
  packages/server/api/src/app/database/migration/sqlite/1742432169253-ChangeManualTasksToTodoSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/todos/todo.entity.ts
  packages/server/api/src/app/todos/todo.service.ts
Labels: release

#7155 fix: remove exported database connection
  packages/server/api/src/app/database/database-connection.ts
Labels: 🐛 bug

#7156 feat: release 0.48.2
  docker-compose.yml
  package.json
Labels: release

#7157 feat: improve sidebar
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/platform-second-sidebar-layout.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/ap-tables/index.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/infra/health/index.tsx
  packages/react-ui/src/app/routes/platform/infra/workers/index.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/platform/security/api-keys/index.tsx
  packages/react-ui/src/app/routes/platform/security/audit-logs/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-users-table.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-roles-table.tsx
  packages/react-ui/src/app/routes/platform/security/signing-keys/index.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/index.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/app/routes/platform/setup/templates/index.tsx
  packages/react-ui/src/app/routes/platform/users/index.tsx
  packages/react-ui/src/app/routes/project-release/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/app/routes/settings/pieces/index.tsx
  packages/react-ui/src/app/routes/todos/index.tsx
  packages/react-ui/src/components/custom/beta-badge.tsx
  packages/react-ui/src/components/ui/data-table/index.tsx
  packages/react-ui/src/components/ui/table-title.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/styles.css
  packages/react-ui/tailwind.config.js
Labels: ✨ polishing

#6955 feat(ethereum name service): List ENS Domains action
  packages/pieces/community/eth-name-service/.eslintrc.json
  packages/pieces/community/eth-name-service/README.md
  packages/pieces/community/eth-name-service/package.json
  packages/pieces/community/eth-name-service/project.json
  packages/pieces/community/eth-name-service/src/index.ts
  packages/pieces/community/eth-name-service/src/lib/actions/list-ens-domains.ts
  packages/pieces/community/eth-name-service/src/lib/common/common.ts
  packages/pieces/community/eth-name-service/tsconfig.json
  packages/pieces/community/eth-name-service/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7163 fix(pipedrive): add api version for webhook
  packages/pieces/community/pipedrive/package.json
  packages/pieces/community/pipedrive/src/lib/common/index.ts
  packages/pieces/community/pipedrive/src/lib/trigger/updated-deal-stage.ts
Labels: 🔌 pieces

#7166 fix(data-selector): show child properties when searching for a step name
  packages/react-ui/src/app/builder/data-selector/utils.ts
Labels: 🐛 bug

#7167 fix: make sure all flows are published before pushing to git
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/features/flows/lib/use-flows-bulk-actions.tsx
  packages/react-ui/src/features/git-sync/components/published-tooltip.tsx
  packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx
  packages/server/api/src/app/ee/project-release/git-sync/git-sync.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
Labels: 🐛 bug

#7172 feat: release v0.48.5
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7183 feat: add new routes (tables + todos) documentation for sdk navigation
  docs/embedding/navigation.mdx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/todos/id/index.tsx
Labels: 📚 documentation

#7187 chore: added endpoint to retry all runs between two dates in admin controller
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/platform/admin-platform.controller.ts
  packages/server/api/src/app/ee/platform/admin-platform.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/platform/platform.request.ts
Labels: skip-changelog

#7188 feat: bumped release
  docker-compose.yml
  package.json
Labels: release

#7181 feat(wedof): updating wedof piece
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner-audit/create-certification-partner-audit.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner/create-partnership.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner/delete-partnership.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner/get-partnership.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner/list-partnership.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner/reset-partnership.ts
  packages/pieces/community/wedof/src/lib/actions/certification-partner/update-partnership.ts
  packages/pieces/community/wedof/src/lib/actions/registration-folders/declare-registration-folder-servicedone.ts
  packages/pieces/community/wedof/src/lib/actions/registration-folders/declare-registration-folder-terminated.ts
  packages/pieces/community/wedof/src/lib/actions/registration-folders/update-registration-folder.ts
  packages/pieces/community/wedof/src/lib/common/wedof.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-partner/certificationPartner-aborted.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-partner/certificationPartner-active.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-partner/certificationPartner-processing.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-partner/certificationPartner-refused.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-partner/certificationPartner-revoked.ts
  packages/pieces/community/wedof/src/lib/triggers/certification-partner/certificationPartner-suspended.ts
Labels: 🔌 pieces

#6953 feat: TrueLayer Payments Integration Piece
  packages/pieces/community/bitcoin/src/lib/api.ts
  packages/pieces/community/truelayer-payments/.eslintrc.json
  packages/pieces/community/truelayer-payments/README.md
  packages/pieces/community/truelayer-payments/package.json
  packages/pieces/community/truelayer-payments/project.json
  packages/pieces/community/truelayer-payments/src/index.ts
  packages/pieces/community/truelayer-payments/src/lib/action/general/submit-payments-provider-return-parameters.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/confirm-mandate-funds.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/create-mandate.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/get-constraints.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/get-mandate.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/list-mandate.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/revoke-mandate.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/start-mandate-authorization-flow.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/submit-consent-mandate.ts
  packages/pieces/community/truelayer-payments/src/lib/action/mandates/submit-mandate-provider-selection.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/get-merchant-account-payment-sources.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/get-operating-account.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/list-operating-accounts.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/merchant-account-disable-sweeping.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/merchant-account-get-sweeping.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/merchant-account-get-transactions.ts
  packages/pieces/community/truelayer-payments/src/lib/action/merchants/merchant-account-setup-sweeping.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payment-links/create-payment-link.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payment-links/get-payment-link-payments.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payment-links/get-payment-link.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments-providers/get-payment-provider.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments-providers/search-payment-providers.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/cancel-payment.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/create-payment-refund.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/create-payment.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/get-payment-refund.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/get-payment-refunds.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/get-payment.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/save-user-account-payment.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/start-payment-authorization-flow.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/submit-consent.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/submit-form.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/submit-provider-selection.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/submit-scheme-selection.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payments/submit-user-account-selection.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payouts/create-payout.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payouts/get-payout.ts
  packages/pieces/community/truelayer-payments/src/lib/action/payouts/start-payout-authorization-flow.ts
  packages/pieces/community/truelayer-payments/src/lib/common/common.ts
  packages/pieces/community/truelayer-payments/tsconfig.json
  packages/pieces/community/truelayer-payments/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6959 feat: add personal ai piece
  packages/pieces/community/personal-ai/.eslintrc.json
  packages/pieces/community/personal-ai/.gitignore
  packages/pieces/community/personal-ai/README.md
  packages/pieces/community/personal-ai/package.json
  packages/pieces/community/personal-ai/project.json
  packages/pieces/community/personal-ai/src/index.ts
  packages/pieces/community/personal-ai/src/lib/actions/ai_interaction/create-chatgpt-instruction.ts
  packages/pieces/community/personal-ai/src/lib/actions/ai_interaction/create-custom-training.ts
  packages/pieces/community/personal-ai/src/lib/actions/documents/get-document.ts
  packages/pieces/community/personal-ai/src/lib/actions/documents/update-document.ts
  packages/pieces/community/personal-ai/src/lib/actions/documents/upload-document.ts
  packages/pieces/community/personal-ai/src/lib/actions/documents/upload-file.ts
  packages/pieces/community/personal-ai/src/lib/actions/documents/upload-url.ts
  packages/pieces/community/personal-ai/src/lib/actions/memory/create-memory.ts
  packages/pieces/community/personal-ai/src/lib/actions/messaging/create-message.ts
  packages/pieces/community/personal-ai/src/lib/actions/messaging/get-conversation.ts
  packages/pieces/community/personal-ai/tsconfig.json
  packages/pieces/community/personal-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6961 feat: add mempool space piece
  packages/pieces/mempool-space/.eslintrc.json
  packages/pieces/mempool-space/README.md
  packages/pieces/mempool-space/package.json
  packages/pieces/mempool-space/project.json
  packages/pieces/mempool-space/src/index.ts
  packages/pieces/mempool-space/src/lib/actions/addresses/get-address-details.ts
  packages/pieces/mempool-space/src/lib/actions/addresses/get-address-transactions-chain.ts
  packages/pieces/mempool-space/src/lib/actions/addresses/get-address-transactions-mempool.ts
  packages/pieces/mempool-space/src/lib/actions/addresses/get-address-transactions.ts
  packages/pieces/mempool-space/src/lib/actions/addresses/get-address-utxo.ts
  packages/pieces/mempool-space/src/lib/actions/addresses/validate-address.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-header.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-height.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-raw.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-status.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-timestamp.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-tip-hash.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-tip-height.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-transaction-id.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-transaction-ids.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block-transactions.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-block.ts
  packages/pieces/mempool-space/src/lib/actions/blocks/get-blocks-bulk.ts
  packages/pieces/mempool-space/src/lib/actions/fees/get-mempool-blocks-fees.ts
  packages/pieces/mempool-space/src/lib/actions/fees/get-recommended-fees.ts
  packages/pieces/mempool-space/src/lib/actions/general/get-difficulty-adjustment.ts
  packages/pieces/mempool-space/src/lib/actions/general/get-historical-price.ts
  packages/pieces/mempool-space/src/lib/actions/general/get-price.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-hex.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-merkle-proof.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-merkleblock-proof.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-outspend.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-outspends.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-raw.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-rbf-timeline.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-status.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction-times.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/get-transaction.ts
  packages/pieces/mempool-space/src/lib/actions/transactions/post-transaction.ts
  packages/pieces/mempool-space/src/lib/common/common.ts
  packages/pieces/mempool-space/tsconfig.json
  packages/pieces/mempool-space/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6962 feat: add blockscout piece
  packages/pieces/community/blockscout/.eslintrc.json
  packages/pieces/community/blockscout/README.md
  packages/pieces/community/blockscout/package.json
  packages/pieces/community/blockscout/project.json
  packages/pieces/community/blockscout/src/index.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-blocks-validated.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-by-hash.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-coin-balance-history-by-day.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-coin-balance-history.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-counters.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-internal-transactions.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-logs.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-token-balances.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-token-transfers.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-tokens.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-transactions.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/address-withdrawals.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/addresses.ts
  packages/pieces/community/blockscout/src/lib/actions/addresses/index.ts
  packages/pieces/community/blockscout/src/lib/actions/blocks/block-by-hash.ts
  packages/pieces/community/blockscout/src/lib/actions/blocks/block-transactions.ts
  packages/pieces/community/blockscout/src/lib/actions/blocks/block-withdrawals.ts
  packages/pieces/community/blockscout/src/lib/actions/blocks/blocks.ts
  packages/pieces/community/blockscout/src/lib/actions/blocks/index.ts
  packages/pieces/community/blockscout/src/lib/actions/blocks/main-page-blocks.ts
  packages/pieces/community/blockscout/src/lib/actions/index.ts
  packages/pieces/community/blockscout/src/lib/actions/search-redirect/check-redirect.ts
  packages/pieces/community/blockscout/src/lib/actions/search-redirect/index.ts
  packages/pieces/community/blockscout/src/lib/actions/search/index.ts
  packages/pieces/community/blockscout/src/lib/actions/search/search.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/index.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/token-by-address.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/token-counters.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/token-holders.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/token-instances.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/token-transfers.ts
  packages/pieces/community/blockscout/src/lib/actions/tokens/tokens.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/index.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/main-page-transactions.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-by-hash.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-internal-transactions.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-logs.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-raw-trace.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-state-changes.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-summary.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transaction-token-transfers.ts
  packages/pieces/community/blockscout/src/lib/actions/transactions/transactions.ts
  packages/pieces/community/blockscout/tsconfig.json
  packages/pieces/community/blockscout/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6964 feat(pieces): AnyHook Integration for Activepieces (GraphQL & WebSocket)
  packages/pieces/community/anyhook-graphql/.eslintrc.json
  packages/pieces/community/anyhook-graphql/README.md
  packages/pieces/community/anyhook-graphql/package.json
  packages/pieces/community/anyhook-graphql/project.json
  packages/pieces/community/anyhook-graphql/src/index.ts
  packages/pieces/community/anyhook-graphql/src/lib/common/common.ts
  packages/pieces/community/anyhook-graphql/src/lib/triggers/graphql-subscription-trigger.ts
  packages/pieces/community/anyhook-graphql/src/lib/triggers/helpers.ts
  packages/pieces/community/anyhook-graphql/tsconfig.json
  packages/pieces/community/anyhook-graphql/tsconfig.lib.json
  packages/pieces/community/anyhook-websocket/.eslintrc.json
  packages/pieces/community/anyhook-websocket/README.md
  packages/pieces/community/anyhook-websocket/package.json
  packages/pieces/community/anyhook-websocket/project.json
  packages/pieces/community/anyhook-websocket/src/index.ts
  packages/pieces/community/anyhook-websocket/src/lib/common/common.ts
  packages/pieces/community/anyhook-websocket/src/lib/triggers/helpers.ts
  packages/pieces/community/anyhook-websocket/src/lib/triggers/websocket-subscription-trigger.ts
  packages/pieces/community/anyhook-websocket/tsconfig.json
  packages/pieces/community/anyhook-websocket/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6952 feat(pieces): Add Mailchain integration piece
  package-lock.json
  package.json
  packages/pieces/community/mailchain/.eslintrc.json
  packages/pieces/community/mailchain/README.md
  packages/pieces/community/mailchain/package.json
  packages/pieces/community/mailchain/project.json
  packages/pieces/community/mailchain/src/index.ts
  packages/pieces/community/mailchain/src/lib/actions/get-authenticated-user.ts
  packages/pieces/community/mailchain/src/lib/actions/send-email.ts
  packages/pieces/community/mailchain/src/lib/common/common.ts
  packages/pieces/community/mailchain/tsconfig.json
  packages/pieces/community/mailchain/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7207 fix: allow for getting piece metadata with API key and project ID
  package-lock.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/pieces/dto/piece-requests.ts
Labels: 🐛 bug

#7208 feat: release 0.48.7
  docker-compose.yml
  package.json
Labels: release

#7209 fix: broken community test
  packages/server/api/src/app/user/user-service.ts
  packages/server/worker/package.json
Labels: 🧹 clean up

#7204 feat(lusha): custom API call, enrich/search actions
  packages/pieces/community/lusha/.eslintrc.json
  packages/pieces/community/lusha/README.md
  packages/pieces/community/lusha/package.json
  packages/pieces/community/lusha/project.json
  packages/pieces/community/lusha/src/index.ts
  packages/pieces/community/lusha/src/lib/actions/companies/enrich.ts
  packages/pieces/community/lusha/src/lib/actions/companies/search.ts
  packages/pieces/community/lusha/tsconfig.json
  packages/pieces/community/lusha/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7212 feat(google-gemini): add gemini 2.0 flash models
  packages/pieces/community/google-gemini/package.json
  packages/pieces/community/google-gemini/src/lib/common/common.ts
Labels: 🔌 pieces

#7196 fix(jira-cloud): fix assignee field update action
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/lib/common/props.ts
Labels: 🔌 pieces

#7131 fix: return undefined for empty text inputs
  packages/engine/src/lib/variables/processors/number.ts
  packages/engine/src/lib/variables/processors/text.ts
Labels: 🧹 clean up, pre-release

#7177 fix(facebook-leads): add payload verification
  packages/pieces/community/facebook-leads/package.json
  packages/pieces/community/facebook-leads/src/index.ts
Labels: 🔌 pieces

#7214 fix: check if project were soft deleted in webhooks
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/src/app/user/user-service.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
Labels: 🐛 bug

#7215 fix: improve logo visuals in the sidebar
  packages/react-ui/src/app/components/sidebar.tsx
Labels: ✨ polishing

#7077 feat(http-oauth2): add http request piece with oauth2
  packages/pieces/community/http-oauth2/.eslintrc.json
  packages/pieces/community/http-oauth2/README.md
  packages/pieces/community/http-oauth2/package.json
  packages/pieces/community/http-oauth2/project.json
  packages/pieces/community/http-oauth2/src/index.ts
  packages/pieces/community/http-oauth2/src/lib/actions/send-oauth2-http-request.ts
  packages/pieces/community/http-oauth2/tsconfig.json
  packages/pieces/community/http-oauth2/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7226 fix: hide wait for approval step in pieces selector and handle adding steps
  packages/react-ui/src/app/builder/pieces-selector/dialog-guides/create-todo-guide.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
  packages/react-ui/src/app/builder/pieces-selector/steps-card-list.tsx
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flows/util/flow-structure-util.ts
Labels: 🐛 bug

#7228 feat: release v0.49.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7231 fix: hide actions in search suggestions and enhance create todo guide
  packages/react-ui/src/app/builder/pieces-selector/dialog-guides/create-todo-guide.tsx
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
  packages/react-ui/src/app/builder/pieces-selector/steps-card-list.tsx
Labels: ✨ polishing

#7248 feat: add claude 3.7 in Universal AI pieces
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/utility-ai/package.json
Labels: 🔌 pieces

#7223 fix(troubleshooting): update PostgreSQL commands and password reset instructions
  docs/install/configuration/troubleshooting.mdx
Labels: 📚 documentation

#7224 feat: added limits to tables
  docs/install/configuration/environment-variables.mdx
  package-lock.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/ap-tables/id/index.tsx
  packages/react-ui/src/app/routes/ap-tables/index.tsx
  packages/react-ui/src/components/custom/beta-badge.tsx
  packages/react-ui/src/features/flows/components/import-flow-dialog.tsx
  packages/react-ui/src/features/tables/components/ap-table-footer.tsx
  packages/react-ui/src/features/tables/components/ap-table-header.tsx
  packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx
  packages/react-ui/src/lib/api.ts
  packages/react-ui/src/lib/utils.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/api/src/app/helper/system/system.ts
  packages/server/api/src/app/tables/field/field.service.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/tables/table/table.controller.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/shared/src/lib/system-props.ts
  packages/shared/src/lib/flag/flag.ts
Labels: 🌟 feature

#7252 fix: dialog doesn't open when clicking on create todo action from search suggestions
  packages/react-ui/src/app/builder/pieces-selector/piece-search-suggestions.tsx
Labels: 🐛 bug

#7253 feat: issues is now moved to runs and available to everyone.
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/sidebar-invite-user.tsx
  packages/react-ui/src/app/components/sidebar-platform-admin.tsx
  packages/react-ui/src/app/components/sidebar-user.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/routes/issues/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/app/routes/settings/mcp/index.tsx
  packages/react-ui/src/components/custom/beta-badge.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/features/issues/hooks/issue-hooks.tsx
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/ee/alerts/alerts-handler.ts
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/flows/issues/issues-controller.ts
  packages/server/api/src/app/flows/issues/issues-entity.ts
  packages/server/api/src/app/flows/issues/issues-module.ts
  packages/server/api/src/app/flows/issues/issues-service.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: 🌟 feature

#7255 feat: enhance sidebar and fix some ui bugs
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/header.tsx
  packages/react-ui/src/app/components/help-and-feedback.tsx
  packages/react-ui/src/app/components/sidebar-invite-user.tsx
  packages/react-ui/src/app/components/sidebar-platform-admin.tsx
  packages/react-ui/src/app/components/sidebar-user.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/components/usage-limits-button.tsx
  packages/react-ui/src/app/routes/issues/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/app/routes/settings/mcp/index.tsx
  packages/react-ui/src/components/custom/beta-badge.tsx
  packages/react-ui/src/components/ui/table-title.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table.tsx
  packages/react-ui/src/features/issues/components/issues-table.tsx
  packages/react-ui/src/features/issues/hooks/issue-hooks.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/ee/alerts/alerts-handler.ts
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/ee/helper/email/email-service.ts
  packages/server/api/src/app/flows/issues/issues-controller.ts
  packages/server/api/src/app/flows/issues/issues-entity.ts
  packages/server/api/src/app/flows/issues/issues-module.ts
  packages/server/api/src/app/flows/issues/issues-service.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: ✨ polishing

#7251 fix(bird): fix messagebird for new APIs
  packages/pieces/community/messagebird/package.json
  packages/pieces/community/messagebird/src/index.ts
  packages/pieces/community/messagebird/src/lib/actions/send-sms.action.ts
  packages/pieces/community/messagebird/src/lib/auth.ts
Labels: 🔌 pieces

#7258 feat: release v0.49.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7263 feat: release 0.50.0
  docker-compose.yml
  package.json
  packages/react-ui/src/app/routes/settings/mcp/index.tsx
Labels: release

#7266 feat: Update wedof pieces
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts
  packages/pieces/community/wedof/src/lib/actions/me.ts
  packages/pieces/community/wedof/src/lib/actions/my-organism.ts
Labels: 🔌 pieces

#7225 feat(groq): add better handling for reasoning models
  packages/pieces/community/groq/package.json
  packages/pieces/community/groq/src/lib/actions/ask-groq.ts
Labels: 🔌 pieces
