Repository activepieces/activepieces, pull requests merged in 2025-08, with the labels that each got.

#8513 feat: bluesky
  package-lock.json
  package.json
  packages/pieces/community/bluesky/.eslintrc.json
  packages/pieces/community/bluesky/README.md
  packages/pieces/community/bluesky/package.json
  packages/pieces/community/bluesky/project.json
  packages/pieces/community/bluesky/src/index.ts
  packages/pieces/community/bluesky/src/lib/actions/create-post.ts
  packages/pieces/community/bluesky/src/lib/actions/find-post.ts
  packages/pieces/community/bluesky/src/lib/actions/find-thread.ts
  packages/pieces/community/bluesky/src/lib/actions/like-post.ts
  packages/pieces/community/bluesky/src/lib/actions/repost.ts
  packages/pieces/community/bluesky/src/lib/common/auth.ts
  packages/pieces/community/bluesky/src/lib/common/client.ts
  packages/pieces/community/bluesky/src/lib/common/props.ts
  packages/pieces/community/bluesky/src/lib/triggers/new-follower-on-account.ts
  packages/pieces/community/bluesky/src/lib/triggers/new-post.ts
  packages/pieces/community/bluesky/src/lib/triggers/new-posts-by-author.ts
  packages/pieces/community/bluesky/src/lib/triggers/new-timeline-posts.ts
  packages/pieces/community/bluesky/tsconfig.json
  packages/pieces/community/bluesky/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8632 fix: multiselect dropdown was reseting to intial value after clearing it
  package-lock.json
  packages/react-ui/src/app/builder/piece-properties/array-property.tsx
  packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx
  packages/react-ui/src/components/custom/multi-select-piece-property.tsx
  packages/react-ui/src/components/custom/multi-select.tsx
  packages/react-ui/src/features/pieces/lib/form-utils.tsx
Labels: 🐛 bug

#8623 fix: skip flow migration if already on latest version
  packages/server/api/src/app/flows/flow-version/flow-version-migration.service.ts
Labels: 🐛 bug

#8635 chore: integrate OpenTelemetry and Axiom
  package-lock.json
  package.json
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/api/src/app/helper/system/system.ts
  packages/server/api/src/app/server.ts
  packages/server/api/src/app/workers/machine/machine-controller.ts
  packages/server/api/src/instrumentation.ts
  packages/server/api/src/main.ts
  packages/server/api/types/fastify-otel.d.ts
  packages/server/api/types/fastify.d.ts
  packages/server/shared/package.json
  packages/server/shared/src/lib/logger/axiom-pino.ts
  packages/server/shared/src/lib/logger/index.ts
  packages/server/shared/src/lib/system-props.ts
  packages/shared/src/lib/workers/index.ts
Labels: DevOps

#8636 chore: separate OpenTelemetry env
  deploy/activepieces-helm/templates/deployment.yaml
  deploy/activepieces-helm/values.yaml
  docs/install/configuration/environment-variables.mdx
  package-lock.json
  package.json
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/api/src/app/helper/system/system.ts
  packages/server/api/src/app/workers/machine/machine-controller.ts
  packages/server/api/src/instrumentation.ts
  packages/server/shared/src/lib/logger/axiom-pino.ts
  packages/server/shared/src/lib/logger/hyperdx-pino.ts
  packages/server/shared/src/lib/logger/index.ts
  packages/server/shared/src/lib/system-props.ts
  packages/shared/src/lib/workers/index.ts
Labels: DevOps

#8639 feat: introduce open telemetry for bullmq
  package-lock.json
  package.json
  packages/server/api/src/app/workers/redis/redis-consumer.ts
  packages/server/api/src/app/workers/redis/redis-queue.ts
Labels: 🌟 feature

#8641 fix(google-drive): team drive update permission not working
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/action/add-permission.action.ts
Labels: 🔌 pieces, 💫 priority

#8642 fix: show pinned pieces at the top under (Highlights)
  packages/react-ui/src/features/pieces/lib/pieces-hooks.ts
Labels: 🐛 bug

#8614 feat: softr piece
  packages/pieces/community/softr/.eslintrc.json
  packages/pieces/community/softr/README.md
  packages/pieces/community/softr/package.json
  packages/pieces/community/softr/project.json
  packages/pieces/community/softr/src/index.ts
  packages/pieces/community/softr/src/lib/actions/create-app-user.ts
  packages/pieces/community/softr/src/lib/actions/create-database-record.ts
  packages/pieces/community/softr/src/lib/actions/delete-app-user.ts
  packages/pieces/community/softr/src/lib/actions/delete-database-record.ts
  packages/pieces/community/softr/src/lib/actions/find-database-record.ts
  packages/pieces/community/softr/src/lib/actions/update-database-record.ts
  packages/pieces/community/softr/src/lib/common/auth.ts
  packages/pieces/community/softr/src/lib/common/client.ts
  packages/pieces/community/softr/src/lib/common/props.ts
  packages/pieces/community/softr/src/lib/common/types.ts
  packages/pieces/community/softr/src/lib/triggers/new-database-record.ts
  packages/pieces/community/softr/tsconfig.json
  packages/pieces/community/softr/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8607 feat: paperform piece
  packages/pieces/community/paperform/.eslintrc.json
  packages/pieces/community/paperform/README.md
  packages/pieces/community/paperform/package.json
  packages/pieces/community/paperform/project.json
  packages/pieces/community/paperform/src/index.ts
  packages/pieces/community/paperform/src/lib/actions/create-form-coupon.ts
  packages/pieces/community/paperform/src/lib/actions/create-form-product-.ts
  packages/pieces/community/paperform/src/lib/actions/create-space.ts
  packages/pieces/community/paperform/src/lib/actions/delete-form-coupon.ts
  packages/pieces/community/paperform/src/lib/actions/delete-form-product.ts
  packages/pieces/community/paperform/src/lib/actions/delete-form-submission.ts
  packages/pieces/community/paperform/src/lib/actions/delete-partial-form-submission.ts
  packages/pieces/community/paperform/src/lib/actions/find-form-product.ts
  packages/pieces/community/paperform/src/lib/actions/find-form.ts
  packages/pieces/community/paperform/src/lib/actions/find-space.ts
  packages/pieces/community/paperform/src/lib/actions/update-form-coupon.ts
  packages/pieces/community/paperform/src/lib/actions/update-form-product.ts
  packages/pieces/community/paperform/src/lib/actions/update-space.ts
  packages/pieces/community/paperform/src/lib/common/auth.ts
  packages/pieces/community/paperform/src/lib/common/client.ts
  packages/pieces/community/paperform/src/lib/common/props.ts
  packages/pieces/community/paperform/src/lib/common/types.ts
  packages/pieces/community/paperform/src/lib/triggers/new-form-submission-.ts
  packages/pieces/community/paperform/src/lib/triggers/new-partial-form-submission.ts
  packages/pieces/community/paperform/tsconfig.json
  packages/pieces/community/paperform/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8622 feat: missive piece
  packages/pieces/community/missive/.eslintrc.json
  packages/pieces/community/missive/README.md
  packages/pieces/community/missive/package.json
  packages/pieces/community/missive/project.json
  packages/pieces/community/missive/src/index.ts
  packages/pieces/community/missive/src/lib/actions/create-contact.ts
  packages/pieces/community/missive/src/lib/actions/create-draft-post.ts
  packages/pieces/community/missive/src/lib/actions/create-task.ts
  packages/pieces/community/missive/src/lib/actions/find-contact.ts
  packages/pieces/community/missive/src/lib/actions/update-contact.ts
  packages/pieces/community/missive/src/lib/common/auth.ts
  packages/pieces/community/missive/src/lib/common/client.ts
  packages/pieces/community/missive/src/lib/common/dynamic-dropdowns.ts
  packages/pieces/community/missive/src/lib/triggers/new-comment.ts
  packages/pieces/community/missive/src/lib/triggers/new-contact-book.ts
  packages/pieces/community/missive/src/lib/triggers/new-contact-group.ts
  packages/pieces/community/missive/src/lib/triggers/new-contact.ts
  packages/pieces/community/missive/src/lib/triggers/new-message.ts
  packages/pieces/community/missive/tsconfig.json
  packages/pieces/community/missive/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8664 fix(markdown): properly render tables in markdown output
  package-lock.json
  package.json
  packages/react-ui/src/components/custom/markdown.tsx
Labels: ✨ polishing

#8261 feat: add autocalls piece
  packages/pieces/community/autocalls/.eslintrc.json
  packages/pieces/community/autocalls/README.md
  packages/pieces/community/autocalls/package.json
  packages/pieces/community/autocalls/project.json
  packages/pieces/community/autocalls/src/index.ts
  packages/pieces/community/autocalls/src/lib/actions/add-lead.ts
  packages/pieces/community/autocalls/src/lib/actions/campaign-control.ts
  packages/pieces/community/autocalls/src/lib/actions/delete-lead.ts
  packages/pieces/community/autocalls/src/lib/actions/make-phone-call.ts
  packages/pieces/community/autocalls/src/lib/actions/send-sms.ts
  packages/pieces/community/autocalls/src/lib/triggers/get-assistants.ts
  packages/pieces/community/autocalls/src/lib/triggers/inbound-call.ts
  packages/pieces/community/autocalls/src/lib/triggers/phone-call-ended.ts
  packages/pieces/community/autocalls/tsconfig.json
  packages/pieces/community/autocalls/tsconfig.lib.json
Labels: 🔌 pieces

#8675 feat(image-ai): add gpt-image-1
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/lib/actions/generate-image.ts
  packages/server/api/src/app/ai/providers/openai.ts
  packages/server/api/test/integration/cloud/ai/proxy.test.ts
  packages/server/shared/package.json
  packages/shared/src/lib/ai/supported-ai-providers.ts
Labels: 🔌 pieces

#8682 feat: release 0.66.7
  docker-compose.yml
  package.json
  packages/engine/test/handler/flow-codes.test.ts
  packages/engine/test/handler/flow-looping.test.ts
  packages/engine/test/handler/flow-piece.test.ts
  packages/engine/test/handler/router-branching.test.ts
  packages/engine/test/handler/test-helper.ts
  packages/engine/test/helper/logging-utils.test.ts
  packages/engine/test/services/props-resolver.test.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts
  packages/shared/test/flow/flow-helper.test.ts
Labels: release

#8691 fix: autoplay tutorials on opening dialog
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/assets/img/custom/mcp.tsx
  packages/react-ui/src/components/custom/tutorials-dialog.tsx
  packages/react-ui/src/features/billing/components/usage-cards.tsx
Labels: 🐛 bug

#8692 fix: data selector values not being visible when deeply nested
  packages/react-ui/src/app/builder/data-selector/data-selector-node-content.tsx
  packages/react-ui/src/app/builder/data-selector/data-selector-size-togglers.tsx
  packages/react-ui/src/app/builder/flow-canvas/canvas-controls.tsx
  packages/react-ui/src/app/builder/flow-canvas/index.tsx
  packages/react-ui/src/components/custom/tutorials-dialog.tsx
Labels: 🐛 bug

#8694 chore: moved agents tab to be second
  packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/router/default-route.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/components/custom/tutorials-dialog.tsx
  packages/react-ui/src/lib/utils.ts
Labels: skip-changelog

#8684 chore: remove leftover TRIGGER_FAILURES_THRESHOLD variables
  deploy/activepieces-helm/templates/deployment.yaml
  deploy/activepieces-helm/values.yaml
Labels: 🧹 clean up

#8706 feat: add gpt-5 models
  package-lock.json
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
  packages/pieces/community/openai/src/lib/common/common.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/lib/actions/ask-ai.ts
  packages/pieces/community/text-ai/src/lib/actions/summarize-text.ts
  packages/react-ui/src/app/routes/platform/billing/index.tsx
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/ai/supported-ai-providers.ts
  packages/shared/test/flow/flow-helper.test.ts
Labels: 🔌 pieces, 🌟 feature

#8708 chore: bump minimumSupportedRelease
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/index.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/index.ts
  packages/shared/package.json
Labels: 🔌 pieces

#8597 feat: aircall piece
  packages/pieces/community/aircall/.eslintrc.json
  packages/pieces/community/aircall/README.md
  packages/pieces/community/aircall/package.json
  packages/pieces/community/aircall/project.json
  packages/pieces/community/aircall/src/index.ts
  packages/pieces/community/aircall/src/lib/actions/comment-a-call.ts
  packages/pieces/community/aircall/src/lib/actions/create-a-contact.ts
  packages/pieces/community/aircall/src/lib/actions/find-calls.ts
  packages/pieces/community/aircall/src/lib/actions/find-contact.ts
  packages/pieces/community/aircall/src/lib/actions/get-call.ts
  packages/pieces/community/aircall/src/lib/actions/tag-a-call.ts
  packages/pieces/community/aircall/src/lib/actions/update-contact.ts
  packages/pieces/community/aircall/src/lib/common/auth.ts
  packages/pieces/community/aircall/src/lib/common/client.ts
  packages/pieces/community/aircall/src/lib/common/props.ts
  packages/pieces/community/aircall/src/lib/triggers/call-ended.ts
  packages/pieces/community/aircall/src/lib/triggers/new-contact.ts
  packages/pieces/community/aircall/src/lib/triggers/new-note.ts
  packages/pieces/community/aircall/src/lib/triggers/new-number-created.ts
  packages/pieces/community/aircall/src/lib/triggers/new-sms.ts
  packages/pieces/community/aircall/tsconfig.json
  packages/pieces/community/aircall/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8712 fix: slow database queries
  packages/server/api/src/app/ee/pieces/filters/piece-filtering-utils.ts
  packages/server/api/test/integration/ce/flows/flow.test.ts
Labels: 🐛 bug

#8713 chore: bump minimumSupportedRelease for openai
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
Labels: 🔌 pieces

#8716 rever: bump minimumSupportedRelease for openai
  packages/pieces/community/openai/package.json
  packages/pieces/community/openai/src/index.ts
  packages/pieces/community/openai/src/lib/actions/send-prompt.ts
Labels: skip-changelog

#8715 fix: speed up usage
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/src/app/platform/platform.controller.ts
  packages/server/api/src/app/platform/platform.service.ts
Labels: 🐛 bug

#8718 chore: bump openai version
  packages/pieces/community/openai/package.json
Labels: 🔌 pieces

#8722 feat: release 0.67.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/api/src/app/ee/pieces/filters/piece-filtering-utils.ts
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/test/integration/ce/flows/flow.test.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: release

#8417 feat: help-scout piece
  packages/pieces/community/help-scout/.eslintrc.json
  packages/pieces/community/help-scout/README.md
  packages/pieces/community/help-scout/package.json
  packages/pieces/community/help-scout/project.json
  packages/pieces/community/help-scout/src/index.ts
  packages/pieces/community/help-scout/src/lib/actions/add-note.ts
  packages/pieces/community/help-scout/src/lib/actions/create-conversation.ts
  packages/pieces/community/help-scout/src/lib/actions/create-customer.ts
  packages/pieces/community/help-scout/src/lib/actions/find-conversation.ts
  packages/pieces/community/help-scout/src/lib/actions/find-customer.ts
  packages/pieces/community/help-scout/src/lib/actions/find-user.ts
  packages/pieces/community/help-scout/src/lib/actions/send-reply.ts
  packages/pieces/community/help-scout/src/lib/actions/update-customer-properties.ts
  packages/pieces/community/help-scout/src/lib/common/api.ts
  packages/pieces/community/help-scout/src/lib/common/auth.ts
  packages/pieces/community/help-scout/src/lib/common/props.ts
  packages/pieces/community/help-scout/src/lib/triggers/conversation-assigned.ts
  packages/pieces/community/help-scout/src/lib/triggers/conversation-created.ts
  packages/pieces/community/help-scout/src/lib/triggers/new-customer.ts
  packages/pieces/community/help-scout/src/lib/triggers/tags-updated.ts
  packages/pieces/community/help-scout/tsconfig.json
  packages/pieces/community/help-scout/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8738 New translation files
  logs/.8929a066e1e20cab48ddbfa9c509b48984514299-audit.json
  logs/scrapeless-2025-08-10.log
  logs/scrapeless.log
  packages/pieces/community/aircall/src/i18n/translation.json
  packages/pieces/community/help-scout/src/i18n/translation.json
  packages/pieces/community/image-ai/src/i18n/translation.json
  packages/pieces/community/metabase/src/i18n/translation.json
  packages/pieces/community/respond-io/src/i18n/translation.json
  packages/pieces/community/supabase/src/i18n/translation.json
Labels: skip-changelog, auto-merge, translations

#8605 feat: introduce solutions
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/react-ui/src/app/components/sidebar/index.tsx
  packages/react-ui/src/app/routes/project-release/apply-plan.tsx
  packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx
  packages/react-ui/src/app/routes/project-release/create-release-dialog/operation-change.tsx
  packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx
  packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx
  packages/server/api/src/app/agents/agent-controller.ts
  packages/server/api/src/app/agents/agent-entity.ts
  packages/server/api/src/app/agents/agents-service.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/migration/postgres/1754214833292-AddExternalidToMCPToolPostgres.ts
  packages/server/api/src/app/database/migration/postgres/1754863565929-RemoveAgentTestPrompt.ts
  packages/server/api/src/app/database/migration/sqlite/1754220095236-AddExternalidToMCPToolSQLite.ts
  packages/server/api/src/app/database/migration/sqlite/1754863757450-RemoveAgentTestPromptSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-helper.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-handler.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-helper.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-release.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/agent-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/connection-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/flow-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/table-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-state-helper.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-state.service.ts
  packages/server/api/src/app/ee/solutions/solution.service.ts
  packages/server/api/src/app/ee/solutions/solutions.controller.ts
  packages/server/api/src/app/ee/solutions/solutions.module.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/server/api/src/app/mcp/tool/mcp-tool.entity.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/api/test/helpers/agent-generator.ts
  packages/server/api/test/helpers/table-generator.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/agent-diff.test.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/flow-diff.test.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/table-diff.test.ts
  packages/shared/src/index.ts
  packages/shared/src/lib/agents/index.ts
  packages/shared/src/lib/common/utils/object-utils.ts
  packages/shared/src/lib/flows/dto/flow-template-request.ts
  packages/shared/src/lib/mcp/tools/mcp-tool.ts
  packages/shared/src/lib/project-release/project-state.ts
  packages/shared/src/lib/solutions/index.ts
  packages/shared/src/lib/solutions/solution.ts
Labels: 🌟 feature

#8741 refactor: clean up imports and improve code formatting
  packages/server/api/src/app/ee/solutions/solutions.controller.ts
  packages/shared/src/lib/common/utils/object-utils.ts
  packages/shared/src/lib/project-release/project-state.ts
Labels: skip-changelog

#8739 New Crowdin updates
  packages/pieces/community/aircall/package.json
  packages/pieces/community/aircall/src/i18n/de.json
  packages/pieces/community/aircall/src/i18n/es.json
  packages/pieces/community/aircall/src/i18n/fr.json
  packages/pieces/community/aircall/src/i18n/ja.json
  packages/pieces/community/aircall/src/i18n/nl.json
  packages/pieces/community/aircall/src/i18n/pt.json
  packages/pieces/community/aircall/src/i18n/ru.json
  packages/pieces/community/aircall/src/i18n/vi.json
  packages/pieces/community/aircall/src/i18n/zh.json
  packages/pieces/community/help-scout/package.json
  packages/pieces/community/help-scout/src/i18n/de.json
  packages/pieces/community/help-scout/src/i18n/es.json
  packages/pieces/community/help-scout/src/i18n/fr.json
  packages/pieces/community/help-scout/src/i18n/ja.json
  packages/pieces/community/help-scout/src/i18n/nl.json
  packages/pieces/community/help-scout/src/i18n/pt.json
  packages/pieces/community/help-scout/src/i18n/ru.json
  packages/pieces/community/help-scout/src/i18n/vi.json
  packages/pieces/community/help-scout/src/i18n/zh.json
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/image-ai/src/i18n/de.json
  packages/pieces/community/image-ai/src/i18n/es.json
  packages/pieces/community/image-ai/src/i18n/fr.json
  packages/pieces/community/image-ai/src/i18n/ja.json
  packages/pieces/community/image-ai/src/i18n/nl.json
  packages/pieces/community/image-ai/src/i18n/pt.json
  packages/pieces/community/image-ai/src/i18n/ru.json
  packages/pieces/community/image-ai/src/i18n/vi.json
  packages/pieces/community/image-ai/src/i18n/zh.json
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/i18n/de.json
  packages/pieces/community/metabase/src/i18n/es.json
  packages/pieces/community/metabase/src/i18n/fr.json
  packages/pieces/community/metabase/src/i18n/ja.json
  packages/pieces/community/metabase/src/i18n/nl.json
  packages/pieces/community/metabase/src/i18n/pt.json
  packages/pieces/community/metabase/src/i18n/ru.json
  packages/pieces/community/metabase/src/i18n/vi.json
  packages/pieces/community/metabase/src/i18n/zh.json
  packages/pieces/community/respond-io/package.json
  packages/pieces/community/respond-io/src/i18n/de.json
  packages/pieces/community/respond-io/src/i18n/es.json
  packages/pieces/community/respond-io/src/i18n/fr.json
  packages/pieces/community/respond-io/src/i18n/ja.json
  packages/pieces/community/respond-io/src/i18n/nl.json
  packages/pieces/community/respond-io/src/i18n/pt.json
  packages/pieces/community/respond-io/src/i18n/ru.json
  packages/pieces/community/respond-io/src/i18n/vi.json
  packages/pieces/community/respond-io/src/i18n/zh.json
  packages/pieces/community/supabase/package.json
  packages/pieces/community/supabase/src/i18n/de.json
  packages/pieces/community/supabase/src/i18n/es.json
  packages/pieces/community/supabase/src/i18n/fr.json
  packages/pieces/community/supabase/src/i18n/ja.json
  packages/pieces/community/supabase/src/i18n/nl.json
  packages/pieces/community/supabase/src/i18n/pt.json
  packages/pieces/community/supabase/src/i18n/ru.json
  packages/pieces/community/supabase/src/i18n/vi.json
  packages/pieces/community/supabase/src/i18n/zh.json
Labels: skip-changelog, auto-merge, translations

#8658 feat: custom api call action in odoo piece
  packages/pieces/community/odoo/package.json
  packages/pieces/community/odoo/src/lib/actions/custom-api-call.ts
  packages/pieces/community/odoo/src/lib/actions/index.ts
Labels: 🔌 pieces

#8749 fix: bump pieces that had missing commit where they were bumped
  packages/pieces/community/aircall/package.json
  packages/pieces/community/help-scout/package.json
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/metabase/package.json
  packages/pieces/community/respond-io/package.json
  packages/pieces/community/supabase/package.json
Labels: skip-changelog

#8751 New translation files
  logs/.8929a066e1e20cab48ddbfa9c509b48984514299-audit.json
  logs/scrapeless-2025-08-11.log
  logs/scrapeless.log
  packages/pieces/community/bigin-by-zoho/src/i18n/translation.json
  packages/pieces/community/google-drive/src/i18n/translation.json
  packages/pieces/community/microsoft-onenote/src/i18n/translation.json
  packages/pieces/community/odoo/src/i18n/translation.json
Labels: skip-changelog, auto-merge, translations

#8750 fix: i18n metadata wasn't being synced to database
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/i18n.ts
  packages/pieces/community/webhook/package.json
  packages/react-ui/src/app/routes/agents/index.tsx
  packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx
  packages/react-ui/src/app/routes/project-release/create-release-dialog/operation-change.tsx
  packages/react-ui/src/features/flow-runs/lib/flow-runs-api.ts
  packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  tools/scripts/utils/piece-script-utils.ts
Labels: 🧹 clean up

#8757 fix: typo
  .github/workflows/crowdin-pr-merger.yml
Labels: skip-changelog

#8760 fix: batch inserting metadata so cloudflare doesn't think we are ddosing our cloud server
  tools/scripts/pieces/update-pieces-metadata.ts
Labels: skip-changelog

#8761 fix: remove unused crowdin action + revert bump translated pieces script
  .github/workflows/crowdin.yml
  tools/scripts/pieces/bump-translated-pieces.ts
Labels: skip-changelog

#8764 fix: only include available locales in docs for embed builder page
  docs/embedding/embed-builder.mdx
Labels: skip-changelog

#8767 New translation files
  logs/.8929a066e1e20cab48ddbfa9c509b48984514299-audit.json
  logs/scrapeless-2025-08-12.log
  logs/scrapeless.log
  packages/pieces/community/zendesk/src/i18n/translation.json
Labels: skip-changelog, auto-merge, translations

#8769 fix: reply to webhook only if trigger is matching
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/test/handler/test-helper.ts
  packages/pieces/community/framework/src/lib/context.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/workers/memory/memory-queue.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/src/lib/engine/engine-constants.ts
  packages/shared/src/lib/flow-run/execution/flow-execution.ts
Labels: 🐛 bug

#8766 feat(kallabot-ai): new 6 actions
  packages/pieces/community/kallabot-ai/package.json
  packages/pieces/community/kallabot-ai/src/index.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/add-contact-to-list.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/create-campaign.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/create-contact-list.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/delete-campaign.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/edit-contact-list.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/get-call-details.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/get-contacts-from-list.ts
  packages/pieces/community/kallabot-ai/src/lib/actions/make-call.ts
  packages/pieces/community/kallabot-ai/src/lib/triggers/call-events.ts
Labels: 🔌 pieces

#8765 fix: searching in piece selector when using a language that is not English
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
Labels: 🐛 bug

#8773 fix: added missing translations for unskip and skip
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/ru/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
  packages/react-ui/public/locales/zh/translation.json
  packages/react-ui/src/app/builder/flow-canvas/context-menu/canvas-context-menu-content.tsx
  packages/react-ui/src/app/builder/flow-canvas/edges/branch-label.tsx
Labels: skip-changelog

#8771 feat(krispcall): update to new V3 API URL
  packages/pieces/community/krisp-call/package.json
  packages/pieces/community/krisp-call/src/index.ts
  packages/pieces/community/krisp-call/src/lib/actions/add-contact.ts
  packages/pieces/community/krisp-call/src/lib/actions/delete-contacts.ts
  packages/pieces/community/krisp-call/src/lib/actions/send-mms.ts
  packages/pieces/community/krisp-call/src/lib/actions/send-sms.ts
  packages/pieces/community/krisp-call/src/lib/triggers/index.ts
Labels: 🔌 pieces

#8774 fix: align sidebar group with side bar items
  packages/react-ui/src/app/components/sidebar/index.tsx
Labels: 🐛 bug

#8778 fix: stop adding keys as values for new translations, instead just fallback to key in react config
  package.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/ru/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog

#8780 fix: translation for records count
  packages/react-ui/public/locales/ar/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
Labels: skip-changelog

#8786 New Crowdin updates
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/activepieces/src/i18n/fr.json
  packages/pieces/community/kallabot-ai/package.json
  packages/pieces/community/kallabot-ai/src/i18n/de.json
  packages/pieces/community/kallabot-ai/src/i18n/es.json
  packages/pieces/community/kallabot-ai/src/i18n/fr.json
  packages/pieces/community/kallabot-ai/src/i18n/ja.json
  packages/pieces/community/kallabot-ai/src/i18n/nl.json
  packages/pieces/community/kallabot-ai/src/i18n/pt.json
  packages/pieces/community/kallabot-ai/src/i18n/ru.json
  packages/pieces/community/kallabot-ai/src/i18n/zh.json
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/i18n/fr.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/ru/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#8785 feat: xero actions and triggers implmentation
  packages/pieces/community/xero/package.json
  packages/pieces/community/xero/src/index.ts
  packages/pieces/community/xero/src/lib/actions/add-items-to-sales-invoice.ts
  packages/pieces/community/xero/src/lib/actions/allocate-credit-note-to-invoice.ts
  packages/pieces/community/xero/src/lib/actions/create-bank-transfer.ts
  packages/pieces/community/xero/src/lib/actions/create-bill.ts
  packages/pieces/community/xero/src/lib/actions/create-credit-note.ts
  packages/pieces/community/xero/src/lib/actions/create-inventory-item.ts
  packages/pieces/community/xero/src/lib/actions/create-invoice.ts
  packages/pieces/community/xero/src/lib/actions/create-payment.ts
  packages/pieces/community/xero/src/lib/actions/create-project.ts
  packages/pieces/community/xero/src/lib/actions/create-purchase-order.ts
  packages/pieces/community/xero/src/lib/actions/create-quote-draft.ts
  packages/pieces/community/xero/src/lib/actions/create-repeating-sales-invoice.ts
  packages/pieces/community/xero/src/lib/actions/find-contact.ts
  packages/pieces/community/xero/src/lib/actions/find-invoice.ts
  packages/pieces/community/xero/src/lib/actions/find-item.ts
  packages/pieces/community/xero/src/lib/actions/find-purchase-order.ts
  packages/pieces/community/xero/src/lib/actions/send-invoice-email.ts
  packages/pieces/community/xero/src/lib/actions/update-purchase-order.ts
  packages/pieces/community/xero/src/lib/actions/update-sales-invoice.ts
  packages/pieces/community/xero/src/lib/actions/upload-attachment.ts
  packages/pieces/community/xero/src/lib/common/props.ts
  packages/pieces/community/xero/src/lib/triggers/new-bank-transaction.ts
  packages/pieces/community/xero/src/lib/triggers/new-bill.ts
  packages/pieces/community/xero/src/lib/triggers/new-contact.ts
  packages/pieces/community/xero/src/lib/triggers/new-credit-note.ts
  packages/pieces/community/xero/src/lib/triggers/new-or-updated-contact.ts
  packages/pieces/community/xero/src/lib/triggers/new-payment.ts
  packages/pieces/community/xero/src/lib/triggers/new-project.ts
  packages/pieces/community/xero/src/lib/triggers/new-purchase-order.ts
  packages/pieces/community/xero/src/lib/triggers/new-quote.ts
  packages/pieces/community/xero/src/lib/triggers/new-reconciled-payment.ts
  packages/pieces/community/xero/src/lib/triggers/new-sales-invoice.ts
  packages/pieces/community/xero/src/lib/triggers/updated-quote.ts
  packages/pieces/community/xero/src/lib/triggers/updated-sales-invoice.ts
Labels: 🔌 pieces, 🙋 Bounty claim

#8814 New Crowdin updates
  packages/pieces/community/activepieces/package.json
  packages/pieces/community/activepieces/src/i18n/fr.json
  packages/pieces/community/aianswer/package.json
  packages/pieces/community/aianswer/src/i18n/fr.json
  packages/pieces/community/approval/package.json
  packages/pieces/community/approval/src/i18n/fr.json
  packages/pieces/community/calendly/package.json
  packages/pieces/community/calendly/src/i18n/fr.json
  packages/pieces/community/claude/package.json
  packages/pieces/community/claude/src/i18n/fr.json
  packages/pieces/community/csv/package.json
  packages/pieces/community/csv/src/i18n/fr.json
  packages/pieces/community/date-helper/package.json
  packages/pieces/community/date-helper/src/i18n/fr.json
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/i18n/fr.json
  packages/pieces/community/vtiger/package.json
  packages/pieces/community/vtiger/src/i18n/de.json
  packages/pieces/community/vtiger/src/i18n/es.json
  packages/pieces/community/vtiger/src/i18n/fr.json
  packages/pieces/community/vtiger/src/i18n/ja.json
  packages/pieces/community/vtiger/src/i18n/nl.json
  packages/pieces/community/vtiger/src/i18n/pt.json
  packages/pieces/community/vtiger/src/i18n/ru.json
  packages/pieces/community/vtiger/src/i18n/zh.json
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/i18n/fr.json
  packages/pieces/community/xero/package.json
  packages/pieces/community/xero/src/i18n/de.json
  packages/pieces/community/xero/src/i18n/es.json
  packages/pieces/community/xero/src/i18n/fr.json
  packages/pieces/community/xero/src/i18n/ja.json
  packages/pieces/community/xero/src/i18n/nl.json
  packages/pieces/community/xero/src/i18n/pt.json
  packages/pieces/community/xero/src/i18n/ru.json
  packages/pieces/community/xero/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/ru/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#8828 feat: add basic serpstat actions
  packages/pieces/community/serpstat/.eslintrc.json
  packages/pieces/community/serpstat/README.md
  packages/pieces/community/serpstat/package.json
  packages/pieces/community/serpstat/project.json
  packages/pieces/community/serpstat/src/index.ts
  packages/pieces/community/serpstat/src/lib/actions/keyword-analysis/get-keywords.ts
  packages/pieces/community/serpstat/src/lib/actions/keyword-analysis/get-suggestions.ts
  packages/pieces/community/serpstat/src/lib/common/auth.ts
  packages/pieces/community/serpstat/src/lib/common/client.ts
  packages/pieces/community/serpstat/src/lib/common/search-engines.ts
  packages/pieces/community/serpstat/tsconfig.json
  packages/pieces/community/serpstat/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 💫 priority, 🧩 area/third-party-pieces

#8833 feat: [MCP] Microsoft 365 People
  packages/pieces/community/microsoft-365-people/.eslintrc.json
  packages/pieces/community/microsoft-365-people/README.md
  packages/pieces/community/microsoft-365-people/package.json
  packages/pieces/community/microsoft-365-people/project.json
  packages/pieces/community/microsoft-365-people/src/index.ts
  packages/pieces/community/microsoft-365-people/src/lib/actions/create-contact-folder.ts
  packages/pieces/community/microsoft-365-people/src/lib/actions/create-contact.ts
  packages/pieces/community/microsoft-365-people/src/lib/actions/delete-contact.ts
  packages/pieces/community/microsoft-365-people/src/lib/actions/get-contact-folder.ts
  packages/pieces/community/microsoft-365-people/src/lib/actions/search-contacts.ts
  packages/pieces/community/microsoft-365-people/src/lib/actions/update-contact.ts
  packages/pieces/community/microsoft-365-people/src/lib/common/auth.ts
  packages/pieces/community/microsoft-365-people/src/lib/common/common.ts
  packages/pieces/community/microsoft-365-people/src/lib/triggers/new-or-updated-contact.ts
  packages/pieces/community/microsoft-365-people/tsconfig.json
  packages/pieces/community/microsoft-365-people/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8838 fix: amazon-ses piece build & bump subflows piece
  package-lock.json
  packages/pieces/community/amazon-ses/project.json
  packages/pieces/community/subflows/package.json
Labels: 🐛 bug

#8846 chore: add zod peer dependency
  package-lock.json
  package.json
  packages/pieces/community/common/package.json
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/index.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
Labels: dependencies

#8826 feat: web search in Universal AI
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/index.ts
  packages/pieces/community/text-ai/src/lib/actions/ask-ai.ts
  packages/pieces/community/text-ai/src/lib/actions/summarize-text.ts
  packages/server/api/src/app/ai/providers/anthropic.ts
  packages/server/api/src/app/ai/providers/google.ts
  packages/server/api/src/app/ai/providers/openai.ts
  packages/server/api/src/app/ai/providers/utils.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/ai/proxy.test.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/ai/ai-sdk.ts
  packages/shared/src/lib/ai/supported-ai-providers.ts
Labels: 🌟 feature

#8860 chore: bump openai package version to 0.6.0
  packages/pieces/community/openai/package-lock.json
  packages/pieces/community/openai/package.json
Labels: dependencies

#8864 feat: release 0.67.4
  docker-compose.yml
  package.json
Labels: release

#8812 feat: new checkout experience
  packages/ee/shared/src/lib/billing/index.ts
  packages/react-ui/src/app/routes/platform/billing/index.tsx
  packages/react-ui/src/features/billing/components/active-flow-addon.tsx
  packages/react-ui/src/features/billing/components/extra-active-flows-dialog.tsx
  packages/react-ui/src/features/billing/components/extra-projects-dialog.tsx
  packages/react-ui/src/features/billing/components/extra-user-seats-dialog.tsx
  packages/react-ui/src/features/billing/components/plan-card.tsx
  packages/react-ui/src/features/billing/components/project-addon.tsx
  packages/react-ui/src/features/billing/components/upgrade-dialog/addons-step.tsx
  packages/react-ui/src/features/billing/components/upgrade-dialog/data.ts
  packages/react-ui/src/features/billing/components/upgrade-dialog/index.tsx
  packages/react-ui/src/features/billing/components/upgrade-dialog/plan-selection-step.tsx
  packages/react-ui/src/features/billing/components/upgrade-dialog/store.ts
  packages/react-ui/src/features/billing/components/upgrade-dialog/summary.tsx
  packages/react-ui/src/features/billing/components/upgrade-dialog/utils.tsx
  packages/react-ui/src/features/billing/components/user-seat-addon.tsx
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan-helper.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts
  packages/server/api/src/app/ee/platform/platform-plan/stripe-helper.ts
Labels: 🌟 feature

#8870 chore: shard the translation files generation process
  .github/workflows/generate-translations.yml
  .github/workflows/reusable-finalize-translations-pr.yml
  .github/workflows/reusable-generate-translations-shard.yml
  packages/cli/src/lib/commands/generate-translation-file-for-piece.ts
Labels: 🐛 bug, skip-changelog

#8872 feat: release 0.67.5
  docker-compose.yml
  package.json
Labels: release

#8796 feat: Hugging face
  packages/pieces/community/hugging-face/.eslintrc.json
  packages/pieces/community/hugging-face/README.md
  packages/pieces/community/hugging-face/package-lock.json
  packages/pieces/community/hugging-face/package.json
  packages/pieces/community/hugging-face/project.json
  packages/pieces/community/hugging-face/src/index.ts
  packages/pieces/community/hugging-face/src/lib/actions/chat-completion.ts
  packages/pieces/community/hugging-face/src/lib/actions/create-image.ts
  packages/pieces/community/hugging-face/src/lib/actions/document-question-answering.ts
  packages/pieces/community/hugging-face/src/lib/actions/image-classification.ts
  packages/pieces/community/hugging-face/src/lib/actions/language-translation.ts
  packages/pieces/community/hugging-face/src/lib/actions/object-detection.ts
  packages/pieces/community/hugging-face/src/lib/actions/text-classification.ts
  packages/pieces/community/hugging-face/src/lib/actions/text-summarization.ts
  packages/pieces/community/hugging-face/tsconfig.json
  packages/pieces/community/hugging-face/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8887 New Crowdin updates
  packages/pieces/community/crypto/package.json
  packages/pieces/community/crypto/src/i18n/de.json
  packages/pieces/community/crypto/src/i18n/es.json
  packages/pieces/community/crypto/src/i18n/fr.json
  packages/pieces/community/crypto/src/i18n/ja.json
  packages/pieces/community/crypto/src/i18n/nl.json
  packages/pieces/community/crypto/src/i18n/pt.json
  packages/pieces/community/crypto/src/i18n/zh.json
  packages/pieces/community/file-helper/package.json
  packages/pieces/community/file-helper/src/i18n/de.json
  packages/pieces/community/file-helper/src/i18n/es.json
  packages/pieces/community/file-helper/src/i18n/fr.json
  packages/pieces/community/file-helper/src/i18n/ja.json
  packages/pieces/community/file-helper/src/i18n/nl.json
  packages/pieces/community/file-helper/src/i18n/pt.json
  packages/pieces/community/file-helper/src/i18n/zh.json
  packages/pieces/community/hugging-face/package.json
  packages/pieces/community/hugging-face/src/i18n/de.json
  packages/pieces/community/hugging-face/src/i18n/es.json
  packages/pieces/community/hugging-face/src/i18n/fr.json
  packages/pieces/community/hugging-face/src/i18n/ja.json
  packages/pieces/community/hugging-face/src/i18n/nl.json
  packages/pieces/community/hugging-face/src/i18n/pt.json
  packages/pieces/community/hugging-face/src/i18n/zh.json
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/i18n/de.json
  packages/pieces/community/slack/src/i18n/es.json
  packages/pieces/community/slack/src/i18n/fr.json
  packages/pieces/community/slack/src/i18n/ja.json
  packages/pieces/community/slack/src/i18n/nl.json
  packages/pieces/community/slack/src/i18n/pt.json
  packages/pieces/community/slack/src/i18n/zh.json
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/text-ai/src/i18n/de.json
  packages/pieces/community/text-ai/src/i18n/es.json
  packages/pieces/community/text-ai/src/i18n/fr.json
  packages/pieces/community/text-ai/src/i18n/ja.json
  packages/pieces/community/text-ai/src/i18n/nl.json
  packages/pieces/community/text-ai/src/i18n/pt.json
  packages/pieces/community/text-ai/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#8892 fix: migration from http piece to webhook piece for return response
  packages/shared/src/lib/flows/operations/migrations/migrate-v5-http-to-webhook.ts
Labels: 🐛 bug

#8896 chore: add first version of ai-providers-shared
  .github/workflows/build-cloud-nx.yml
  .github/workflows/release-pieces.yml
  packages/ai-providers-shared/.eslintrc.json
  packages/ai-providers-shared/README.md
  packages/ai-providers-shared/jest.config.ts
  packages/ai-providers-shared/package.json
  packages/ai-providers-shared/project.json
  packages/ai-providers-shared/src/index.ts
  packages/ai-providers-shared/src/lib/ai-sdk.ts
  packages/ai-providers-shared/src/lib/index.ts
  packages/ai-providers-shared/src/lib/shared.ts
  packages/ai-providers-shared/src/lib/supported-ai-providers.ts
  packages/ai-providers-shared/tsconfig.json
  packages/ai-providers-shared/tsconfig.lib.json
  packages/ai-providers-shared/tsconfig.spec.json
  tsconfig.base.json
Labels: skip-changelog

#8897 New Crowdin updates
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#8902 fix: initializing cache + importing piece for engine in dev mode
  packages/engine/src/lib/helper/piece-loader.ts
  packages/server/worker/src/lib/piece-manager/local-piece-manager.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v5-http-to-webhook.ts
Labels: 🐛 bug, 🧹 clean up, skip-changelog

#8906 fix: custom pieces import
  package-lock.json
  packages/engine/src/lib/helper/piece-loader.ts
  packages/server/worker/src/lib/runner/process/factory/isolate-sandbox-process.ts
Labels: 🐛 bug, 🧹 clean up

#8909 feat: update wedof and medullar pieces
  packages/pieces/community/medullar/package.json
  packages/pieces/community/medullar/src/index.ts
  packages/pieces/community/medullar/src/lib/actions/ask-space.ts
  packages/pieces/community/medullar/src/lib/actions/delete-space.ts
  packages/pieces/community/medullar/src/lib/actions/rename-space.ts
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/i18n/de.json
  packages/pieces/community/wedof/src/i18n/es.json
  packages/pieces/community/wedof/src/i18n/fr.json
  packages/pieces/community/wedof/src/i18n/ja.json
  packages/pieces/community/wedof/src/i18n/nl.json
  packages/pieces/community/wedof/src/i18n/pt.json
  packages/pieces/community/wedof/src/i18n/ru.json
  packages/pieces/community/wedof/src/i18n/translation.json
  packages/pieces/community/wedof/src/i18n/vi.json
  packages/pieces/community/wedof/src/i18n/zh.json
  packages/pieces/community/wedof/src/index.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folders/create-certification-folder.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folders/search-certification-folder.ts
  packages/pieces/community/wedof/src/lib/actions/certification-folders/update-certification-folder.ts
  packages/pieces/community/wedof/src/lib/actions/registration-folders/create-registration-folder.ts
  packages/pieces/community/wedof/src/lib/common/wedof.ts
Labels: 🔌 pieces

#8914 feat: New translation files
  packages/pieces/community/gmail/src/i18n/translation.json
  packages/pieces/community/medullar/src/i18n/translation.json
  packages/pieces/community/open-phone/src/i18n/translation.json
  packages/pieces/community/wedof/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#8920 fix: use externalId instead of id and correct state comparison in all project states
  package-lock.json
  packages/engine/test/handler/flow-rerun.test.ts
  packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx
  packages/react-ui/src/app/routes/project-release/create-release-dialog/operation-change.tsx
  packages/server/api/src/app/agents/agent-controller.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-handler.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-helper.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-release.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/agent-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/diff/table-diff.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-state.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/tables/table/table.controller.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/project-release/project-state.ts
  packages/shared/src/lib/tables/table.ts
Labels: 🐛 bug

#8856 feat: retell ai piece
  packages/pieces/community/retell-ai/.eslintrc.json
  packages/pieces/community/retell-ai/README.md
  packages/pieces/community/retell-ai/package.json
  packages/pieces/community/retell-ai/project.json
  packages/pieces/community/retell-ai/src/index.ts
  packages/pieces/community/retell-ai/src/lib/actions/create-phone-number.ts
  packages/pieces/community/retell-ai/src/lib/actions/get-agent.ts
  packages/pieces/community/retell-ai/src/lib/actions/get-call.ts
  packages/pieces/community/retell-ai/src/lib/actions/get-phone-number.ts
  packages/pieces/community/retell-ai/src/lib/actions/get-voice.ts
  packages/pieces/community/retell-ai/src/lib/actions/make-phone-call.ts
  packages/pieces/community/retell-ai/src/lib/common/auth.ts
  packages/pieces/community/retell-ai/src/lib/common/client.ts
  packages/pieces/community/retell-ai/src/lib/common/props.ts
  packages/pieces/community/retell-ai/src/lib/triggers/new-call.ts
  packages/pieces/community/retell-ai/tsconfig.json
  packages/pieces/community/retell-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8933 chore: move commits from my account to automated bot account
  .github/workflows/crowdin-pr-merger.yml
  .github/workflows/reusable-finalize-translations-pr.yml
  .github/workflows/reusable-generate-translations-shard.yml
Labels: skip-changelog

#8924 feat(clickfunnels): implemented clickfunnels as a piece on activepieces
  packages/pieces/community/clickfunnels/.eslintrc.json
  packages/pieces/community/clickfunnels/README.md
  packages/pieces/community/clickfunnels/package.json
  packages/pieces/community/clickfunnels/project.json
  packages/pieces/community/clickfunnels/src/index.ts
  packages/pieces/community/clickfunnels/src/lib/actions/apply-tag-to-contact.ts
  packages/pieces/community/clickfunnels/src/lib/actions/create-opportunity.ts
  packages/pieces/community/clickfunnels/src/lib/actions/enroll-a-contact-into-a-course.ts
  packages/pieces/community/clickfunnels/src/lib/actions/remove-tag-from-contact.ts
  packages/pieces/community/clickfunnels/src/lib/actions/search-contacts.ts
  packages/pieces/community/clickfunnels/src/lib/actions/update-or-create-contact.ts
  packages/pieces/community/clickfunnels/src/lib/common/constants.ts
  packages/pieces/community/clickfunnels/src/lib/common/props.ts
  packages/pieces/community/clickfunnels/src/lib/common/requests.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/contact-completed-course.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/contact-identified.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/contact-submitted-form.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/contact-suspended-from-course.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/course-enrollment-created-for-contact.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/one-time-order-paid.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/scheduled-appointment-event-created.ts
  packages/pieces/community/clickfunnels/src/lib/triggers/subscription-invoice-paid.ts
  packages/pieces/community/clickfunnels/tsconfig.json
  packages/pieces/community/clickfunnels/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8941 feat: New translation files
  packages/pieces/community/clickfunnels/src/i18n/translation.json
  packages/pieces/community/mollie/src/i18n/translation.json
  packages/pieces/community/retell-ai/src/i18n/translation.json
  packages/pieces/community/straico/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#8944 fix(pipedrive): fix custom field filtering for deal trigger
  packages/pieces/community/pipedrive/package.json
  packages/pieces/community/pipedrive/src/lib/trigger/updated-deal.ts
Labels: 🔌 pieces

#8863 feat(pieces): add Pinecone piece
  packages/pieces/community/pinecone/.eslintrc.json
  packages/pieces/community/pinecone/README.md
  packages/pieces/community/pinecone/package-lock.json
  packages/pieces/community/pinecone/package.json
  packages/pieces/community/pinecone/project.json
  packages/pieces/community/pinecone/src/index.ts
  packages/pieces/community/pinecone/src/lib/actions/create-index.ts
  packages/pieces/community/pinecone/src/lib/actions/delete-vector.ts
  packages/pieces/community/pinecone/src/lib/actions/get-vector.ts
  packages/pieces/community/pinecone/src/lib/actions/search-index.ts
  packages/pieces/community/pinecone/src/lib/actions/search-vector.ts
  packages/pieces/community/pinecone/src/lib/actions/update-vector.ts
  packages/pieces/community/pinecone/src/lib/actions/upsert-vector.ts
  packages/pieces/community/pinecone/src/lib/common/pinecone-client.ts
  packages/pieces/community/pinecone/tsconfig.json
  packages/pieces/community/pinecone/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8947 fix: reset usage, stop testing from consuming tasks
  packages/ee/shared/src/lib/billing/index.ts
  packages/react-ui/src/features/billing/components/upgrade-dialog/index.tsx
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/src/app/workers/engine-controller.ts
Labels: 🐛 bug

#8803 feat: Add Private Key authentication for SFTP
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/property/authentication/custom-auth-prop.ts
  packages/pieces/community/framework/src/lib/property/authentication/index.ts
  packages/pieces/community/sftp/package.json
  packages/pieces/community/sftp/src/index.ts
Labels: 🔌 pieces, 💫 priority

#8957 fix: add description for microsoft auth
  packages/pieces/community/microsoft-365-people/package.json
  packages/pieces/community/microsoft-365-people/src/lib/common/auth.ts
  packages/pieces/community/microsoft-dynamics-365-business-central/package.json
  packages/pieces/community/microsoft-dynamics-365-business-central/src/index.ts
  packages/pieces/community/microsoft-dynamics-crm/package.json
  packages/pieces/community/microsoft-dynamics-crm/src/index.ts
  packages/pieces/community/microsoft-excel-365/package.json
  packages/pieces/community/microsoft-excel-365/src/index.ts
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/index.ts
  packages/pieces/community/microsoft-onenote/package.json
  packages/pieces/community/microsoft-onenote/src/index.ts
  packages/pieces/community/microsoft-outlook-calendar/package.json
  packages/pieces/community/microsoft-outlook-calendar/src/index.ts
  packages/pieces/community/microsoft-outlook/package.json
  packages/pieces/community/microsoft-outlook/src/lib/common/auth.ts
  packages/pieces/community/microsoft-power-bi/package.json
  packages/pieces/community/microsoft-power-bi/src/index.ts
  packages/pieces/community/microsoft-sharepoint/package.json
  packages/pieces/community/microsoft-sharepoint/src/index.ts
  packages/pieces/community/microsoft-teams/package.json
  packages/pieces/community/microsoft-teams/src/index.ts
  packages/pieces/community/microsoft-todo/package.json
  packages/pieces/community/microsoft-todo/src/index.ts
Labels: 🔌 pieces

#8960 fix: edge case of removeConnectionsFromInput function
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
Labels: 🐛 bug

#8961 fix: apply all flows in project release if no selected flows are provided
  packages/server/api/src/app/ee/projects/project-release/project-release.service.ts
Labels: 🐛 bug

#8998 feat: New translation files
  packages/pieces/community/mailchimp/src/i18n/translation.json
Labels: skip-changelog, auto-merge, translations

#8999 New Crowdin updates
  packages/pieces/community/mailchimp/package.json
  packages/pieces/community/mailchimp/src/i18n/de.json
  packages/pieces/community/mailchimp/src/i18n/es.json
  packages/pieces/community/mailchimp/src/i18n/fr.json
  packages/pieces/community/mailchimp/src/i18n/ja.json
  packages/pieces/community/mailchimp/src/i18n/nl.json
  packages/pieces/community/mailchimp/src/i18n/pt.json
  packages/pieces/community/mailchimp/src/i18n/zh.json
Labels: skip-changelog, auto-merge, translations
