Repository activepieces/activepieces, pull requests merged in 2025-02, with the labels that each got.

#6724 fix: speed up platform billing queries
  package-lock.json
  packages/server/api/src/app/ee/platform-billing/platform-billing.module.ts
Labels: 🐛 bug

#6729 fix: custom api request url description
  docs/handbook/customer-support/handle-requests.mdx
  docs/handbook/customer-support/overview.mdx
  packages/pieces/community/common/src/lib/helpers/index.ts
Labels: skip-changelog

#6733 fix: improve build-piece command using inquirer and enhance documentation styling
  docs/developers/misc/build-piece.mdx
  docs/mint.json
  package.json
  packages/cli/src/lib/commands/build-piece.ts
Labels: 🐛 bug

#6738 fix: show (Edit Flow) button when user is testing a flow that hasn't been published
  packages/react-ui/src/app/builder/builder-flow-status-section/view-draft-or-edit-flow-button.tsx
Labels: 🐛 bug

#6747 fix: add error message in console when sdk doesn't send the token
  packages/react-ui/src/app/components/loading-screen.tsx
  packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
Labels: skip-changelog

#6750 docs: add warning about screenshots with sensitive info
  docs/handbook/customer-support/handle-requests.mdx
Labels: 📚 documentation

#6760 fix: provision invitation based on sso
  packages/server/api/src/app/authentication/authentication.service.ts
Labels: 🐛 bug

#6761 feat: release 0.41.0 rc
  package.json
Labels: pre-release

#6718 feat(amazon-sns): Send Message Action
  package-lock.json
  package.json
  packages/pieces/community/amazon-sns/.eslintrc.json
  packages/pieces/community/amazon-sns/README.md
  packages/pieces/community/amazon-sns/package.json
  packages/pieces/community/amazon-sns/project.json
  packages/pieces/community/amazon-sns/src/index.ts
  packages/pieces/community/amazon-sns/src/lib/actions/send-message.ts
  packages/pieces/community/amazon-sns/src/lib/common.ts
  packages/pieces/community/amazon-sns/tsconfig.json
  packages/pieces/community/amazon-sns/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6752 feat: add ability to rename flow name by just clicking on it
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/builder-state-provider.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/features/flows/components/rename-flow-dialog.tsx
  packages/react-ui/src/lib/utils.ts
Labels: ✨ polishing

#6685 feat(deepseek): Ask Deepseek Action
  packages/pieces/community/deepseek/.eslintrc.json
  packages/pieces/community/deepseek/README.md
  packages/pieces/community/deepseek/package.json
  packages/pieces/community/deepseek/project.json
  packages/pieces/community/deepseek/src/index.ts
  packages/pieces/community/deepseek/src/lib/actions/ask-deepseek.ts
  packages/pieces/community/deepseek/src/lib/common/common.ts
  packages/pieces/community/deepseek/tsconfig.json
  packages/pieces/community/deepseek/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6769 fix: remove justyf-center
  packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
Labels: skip-changelog

#6766 fix: straight typo
  packages/react-ui/src/app/builder/flow-canvas/utils/flow-canvas-utils.ts
Labels: skip-changelog

#6765 fix: fix justify typo
  packages/react-ui/src/components/json-viewer.tsx
Labels: skip-changelog

#6768 fix: fix sidebarbarClosed typo
  packages/react-ui/src/app/builder/index.tsx
Labels: skip-changelog

#6767 fix: multiple typo fixes
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
Labels: ✨ polishing

#6778 feat: always allow client id/secret override in oauth2 connections
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/shared/src/lib/flag/flag.ts
Labels: ✨ polishing

#6578 chore: add worker version to workers table
  packages/react-ui/src/app/routes/platform/infra/workers/index.tsx
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/ee/usage-tracker/usage-tracker-module.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/telemetry.utils.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-sync-service.ts
  packages/server/api/src/app/worker.ts
  packages/server/shared/src/lib/system-props.ts
  packages/server/worker/src/lib/flow-worker.ts
  packages/server/worker/src/lib/utils/machine.ts
Labels: ✨ polishing

#6781 feat: release 0.41.0
  docker-compose.yml
  package.json
Labels: release

#6784 feat: introduce private url for sso
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/ee/custom-domains/domain-helper.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/shared/src/lib/system-props.ts
Labels: ✨ polishing

#6785 feat: release 0.42.0-rc.1
  package.json
Labels: pre-release

#6353 feat(utility-ai): add PDF and multiple files support
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/utility-ai/package.json
  packages/pieces/community/utility-ai/src/lib/actions/extract-structured-data.ts
Labels: 🔌 pieces

#6797 feat: Adding support for syncing specific pieces
  packages/cli/src/lib/commands/build-piece.ts
  packages/cli/src/lib/commands/create-action.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/commands/create-trigger.ts
  packages/cli/src/lib/commands/publish-piece.ts
  packages/cli/src/lib/commands/sync-pieces.ts
  packages/cli/src/lib/utils/piece-utils.ts
Labels: ✨ polishing

#6798 fix: update common and metabase pieces patch versions
  packages/pieces/community/common/package.json
  packages/pieces/community/metabase/package.json
Labels: 🔌 pieces

#6799 fix: speed up submitting payloads
  .husky/commit-msg
  .husky/pre-push
  packages/server/worker/package.json
  packages/server/worker/src/lib/api/server-api.service.ts
Labels: 🐛 bug

#6788 feat: add project role users table
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/project-members/platform-project-member-request.ts
  packages/ee/shared/src/lib/project-members/project-member-request.ts
  packages/ee/shared/src/lib/project-members/project-member.ts
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/index.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-members-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-users-table.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-roles-table.tsx
  packages/react-ui/src/components/ui/breadcrumb.tsx
  packages/react-ui/src/features/platform-admin-panel/lib/project-role-api.ts
  packages/react-ui/src/features/team/lib/platform-project-members-api.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/project-members/platform-project-members/platform-project-member.controller.ts
  packages/server/api/src/app/ee/project-members/platform-project-members/platform-project-member.module.ts
  packages/server/api/src/app/ee/project-members/project-member.controller.ts
  packages/server/api/src/app/ee/project-members/project-member.service.ts
  packages/server/api/src/app/ee/project-role/project-role.controller.ts
  packages/server/api/src/app/ee/project-role/project-role.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/project-role/project-role.request.ts
  packages/shared/src/lib/project/project.ts
Labels: 🌟 feature

#6811 feat: rc release
  docs/embedding/sdk-changelog.mdx
  package.json
Labels: pre-release

#6808 fix: update flow status when republishing again in project release
  packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
Labels: 🐛 bug

#6813 docs: introduce people book
  docs/_snippets/profile/abdulyki.mdx
  docs/_snippets/profile/abood.mdx
  docs/_snippets/profile/aboodzein.mdx
  docs/_snippets/profile/amr.mdx
  docs/_snippets/profile/amro.mdx
  docs/_snippets/profile/ash.mdx
  docs/_snippets/profile/ginika.mdx
  docs/_snippets/profile/hazem.mdx
  docs/_snippets/profile/issa.mdx
  docs/_snippets/profile/kareem.mdx
  docs/_snippets/profile/kishan.mdx
  docs/_snippets/profile/mo.mdx
  docs/_snippets/profile/sanad.mdx
  docs/handbook/teams/ai.mdx
  docs/handbook/teams/content.mdx
  docs/handbook/teams/developer-experience.mdx
  docs/handbook/teams/embed-sdk.mdx
  docs/handbook/teams/flow-builder.mdx
  docs/handbook/teams/flow-execution.mdx
  docs/handbook/teams/human-in-loop.mdx
  docs/handbook/teams/overview.mdx
  docs/handbook/teams/pieces.mdx
  docs/handbook/teams/platform-admin.mdx
  docs/handbook/teams/sales.mdx
  docs/handbook/teams/tables.mdx
  docs/mint.json
  docs/resources/profile/abdulyki.png
  docs/resources/profile/abood.webp
  docs/resources/profile/aboodzein.png
  docs/resources/profile/amr.png
  docs/resources/profile/amro.png
  docs/resources/profile/ash.png
  docs/resources/profile/ginika.png
  docs/resources/profile/hazem.jpg
  docs/resources/profile/issa.png
  docs/resources/profile/kareem.png
  docs/resources/profile/khaled.png
  docs/resources/profile/kishan.png
  docs/resources/profile/mo.png
  docs/resources/profile/sanad.png
Labels: 📚 documentation

#6816 feat: release 0.42.0
  docker-compose.yml
  package.json
Labels: release

#6824 fix: rename flow from the dashboard
  package-lock.json
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/components/ui/Input-with-icon.tsx
  packages/react-ui/src/features/flows/components/rename-flow-dialog.tsx
  packages/react-ui/src/features/flows/components/select-flow-template-dialog.tsx
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
Labels: 🐛 bug

#6820 feat(discord): send message with bot action
  README.md
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/index.ts
  packages/pieces/community/discord/src/lib/actions/send-message-with-bot.ts
Labels: 🔌 pieces

#6782 feat: enhance engineering handbook docs
  docs/handbook/engineering/incident-response.mdx
  docs/mint.json
Labels: 📚 documentation

#6830 docs: engineering playbooks
  docs/handbook/engineering/incident-response.mdx
  docs/handbook/engineering/on-call.mdx
  docs/handbook/engineering/onboarding/how-we-work.mdx
  docs/handbook/engineering/onboarding/on-call.mdx
  docs/handbook/engineering/overview.mdx
  docs/handbook/engineering/playbooks/bullboard.mdx
  docs/handbook/engineering/playbooks/database-migration.mdx
  docs/handbook/engineering/playbooks/infrastructure.mdx
  docs/handbook/engineering/playbooks/releases.mdx
  docs/handbook/engineering/playbooks/setup-incident-io.mdx
  docs/install/configuration/troubleshooting.mdx
  docs/mint.json
Labels: 📚 documentation

#6833 feat: add downtime incident guide
  docs/handbook/engineering/onboarding/downtime-incident.mdx
  docs/mint.json
Labels: 📚 documentation

#6832 feat(thankster): send cards action
  packages/pieces/community/thankster/.eslintrc.json
  packages/pieces/community/thankster/README.md
  packages/pieces/community/thankster/package.json
  packages/pieces/community/thankster/project.json
  packages/pieces/community/thankster/src/index.ts
  packages/pieces/community/thankster/src/lib/actions/send-cards.ts
  packages/pieces/community/thankster/tsconfig.json
  packages/pieces/community/thankster/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6846 chore(grist): fix typo
  packages/pieces/community/grist/package.json
  packages/pieces/community/grist/src/index.ts
Labels: 🔌 pieces

#6815 feat(respaid): add actions and triggers v0
  packages/pieces/community/respaid/.eslintrc.json
  packages/pieces/community/respaid/README.md
  packages/pieces/community/respaid/package.json
  packages/pieces/community/respaid/project.json
  packages/pieces/community/respaid/src/index.ts
  packages/pieces/community/respaid/src/lib/actions/create_new_campaign.ts
  packages/pieces/community/respaid/src/lib/actions/index.ts
  packages/pieces/community/respaid/src/lib/actions/stop_collection_client_paid_directly.ts
  packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_instalment_payment.ts
  packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_partial_payment.ts
  packages/pieces/community/respaid/src/lib/common/index.ts
  packages/pieces/community/respaid/src/lib/triggers/index.ts
  packages/pieces/community/respaid/src/lib/triggers/new_campaign_creation.ts
  packages/pieces/community/respaid/src/lib/triggers/new_cancelled_case.ts
  packages/pieces/community/respaid/src/lib/triggers/new_disputed_case.ts
  packages/pieces/community/respaid/src/lib/triggers/new_payout.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_paid_to_creditor.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_legal_officer.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_respaid.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_installment_payment_via_respaid.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_to_creditor.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_via_respaid.ts
  packages/pieces/community/respaid/tsconfig.json
  packages/pieces/community/respaid/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6851 fix(trigger): handle JSON parsing for webhook payload
  packages/pieces/community/respaid/package.json
  packages/pieces/community/respaid/src/lib/common/index.ts
  packages/pieces/community/respaid/src/lib/triggers/new_campaign_creation.ts
  packages/pieces/community/respaid/src/lib/triggers/new_cancelled_case.ts
  packages/pieces/community/respaid/src/lib/triggers/new_disputed_case.ts
  packages/pieces/community/respaid/src/lib/triggers/new_payout.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_paid_to_creditor.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_legal_officer.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_via_respaid.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_installment_payment_via_respaid.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_to_creditor.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_partial_payment_via_respaid.ts
Labels: 🔌 pieces

#6825 feat(intercom): new 9 actions and 2 triggers
  package-lock.json
  package.json
  packages/pieces/community/intercom/package.json
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/actions/add-note-to-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/add-note-to-user.ts
  packages/pieces/community/intercom/src/lib/actions/add-remove-tag-on-company.ts
  packages/pieces/community/intercom/src/lib/actions/add-remove-tag-on-contact.ts
  packages/pieces/community/intercom/src/lib/actions/add-remove-tag-on-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/create-article.ts
  packages/pieces/community/intercom/src/lib/actions/create-contact.action.ts
  packages/pieces/community/intercom/src/lib/actions/create-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/create-or-get-contact.action.ts
  packages/pieces/community/intercom/src/lib/actions/create-ticket.ts
  packages/pieces/community/intercom/src/lib/actions/create-update-lead.ts
  packages/pieces/community/intercom/src/lib/actions/create-update-user.ts
  packages/pieces/community/intercom/src/lib/actions/create-user.ts
  packages/pieces/community/intercom/src/lib/actions/find-company.ts
  packages/pieces/community/intercom/src/lib/actions/find-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/find-lead.ts
  packages/pieces/community/intercom/src/lib/actions/find-user.ts
  packages/pieces/community/intercom/src/lib/actions/get-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/list-all-tags.ts
  packages/pieces/community/intercom/src/lib/actions/reply-to-conversation.ts
  packages/pieces/community/intercom/src/lib/actions/send-message.action.ts
  packages/pieces/community/intercom/src/lib/actions/update-ticket.ts
  packages/pieces/community/intercom/src/lib/common/index.ts
  packages/pieces/community/intercom/src/lib/common/props.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-assigned.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-closed.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-part-tagged.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-rated.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-snoozed.ts
  packages/pieces/community/intercom/src/lib/triggers/conversation-unsnoozed.ts
  packages/pieces/community/intercom/src/lib/triggers/new-company.ts
  packages/pieces/community/intercom/src/lib/triggers/new-conversation-from-user.ts
  packages/pieces/community/intercom/src/lib/triggers/new-lead.ts
  packages/pieces/community/intercom/src/lib/triggers/note-added-to-conversation.ts
  packages/pieces/community/intercom/src/lib/triggers/reply-from-admin.ts
  packages/pieces/community/intercom/src/lib/triggers/reply-from-user.ts
Labels: 🔌 pieces

#6791 feat(google-docs): new document trigger and folder prop for find document action
  packages/pieces/community/google-docs/package.json
  packages/pieces/community/google-docs/src/index.ts
  packages/pieces/community/google-docs/src/lib/actions/find-documnet.ts
  packages/pieces/community/google-docs/src/lib/common/index.ts
  packages/pieces/community/google-docs/src/lib/common/props.ts
  packages/pieces/community/google-docs/src/lib/triggers/new-document.ts
Labels: 🔌 pieces

#6852 fix: restrict delete piece on file deletion
  packages/engine/src/lib/helper/execution-errors.ts
  packages/server/api/src/app/database/migration/postgres/1739546878775-RestrictPieces.ts
  packages/server/api/src/app/database/migration/sqlite/1739544872722-RestrictPiecesSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-metadata-entity.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
Labels: 🐛 bug

#6853 feat: enable multiple webhook secrets for APP_WEBHOOK
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/piece.ts
  packages/pieces/community/intercom/src/index.ts
  packages/pieces/community/intercom/src/lib/actions/update-ticket.ts
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/square/package.json
  packages/pieces/community/square/src/index.ts
  packages/server/shared/package.json
  packages/server/shared/src/lib/webhook-secrets-util.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/engine/engine-operation.ts
Labels: skip-changelog

#6821 feat(bulk-rerun): add bulk rerurn to run flow page
  packages/pieces/community/intercom/src/lib/triggers/conversation-part-tagged.ts
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/features/flow-runs/lib/flow-runs-api.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/shared/src/lib/flow-run/test-flow-run-request.ts
Labels: 🌟 feature

#6858 feat: allow SERVICE scope for sample-data endpoints
  docs/endpoints/sample-data/get.mdx
  docs/endpoints/sample-data/save.mdx
  docs/mint.json
  docs/openapi.json
  package-lock.json
  package.json
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/test-step/index.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/app/routes/flows/id/index.tsx
  packages/react-ui/src/app/routes/runs/id/index.tsx
  packages/react-ui/src/features/flows/lib/sample-data-hooks.ts
  packages/server/api/src/app/flows/step-run/sample-data.controller.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/common/base-model.ts
  packages/shared/src/lib/flows/sample-data/index.ts
  packages/shared/src/lib/platform/platform.model.ts
Labels: ✨ polishing

#6801 feat(google-sheets): new spreadsheet/worksheet trigger and find worksheet,copy worksheet , update multiple rows action
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/index.ts
  packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/copy-worksheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-column.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-spreadsheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-worksheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/delete-row.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-row-by-num.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-spreadsheets.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-worksheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-multiple-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/pieces/community/google-sheets/src/lib/common/props.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-spreadsheet.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-worksheet.ts
Labels: 🔌 pieces

#6871 feat: support multiple functions in v8 code SANDBOX_CODE_ONLY
  packages/engine/src/lib/core/code/v8-isolate-code-sandbox.ts
Labels: ✨ polishing

#6873 feat: allow the user to install piece on their platform
  packages/react-ui/src/app/components/request-trial.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/piece-actions.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx
  packages/react-ui/src/app/routes/settings/pieces/index.tsx
  packages/react-ui/src/components/ui/button.tsx
  packages/react-ui/src/components/ui/locked-alert.tsx
  packages/react-ui/src/features/pieces/components/install-piece-dialog.tsx
Labels: 🐛 bug

#6875 feat: upgrade to release v0.43.0
  docker-compose.yml
  package.json
Labels: release

#6882 fix: loading different piece versions for the same piece
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
Labels: 🐛 bug

#6883 feat: release v0.44.0
  docker-compose.yml
  package.json
Labels: release

#6888 fix(slack): fix new message trigger test data order
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/common/utils.ts
  packages/pieces/community/slack/src/lib/triggers/new-mention.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
Labels: 🔌 pieces

#6865 fix(perplexity-ai): Remove deprecated models
  packages/pieces/community/perplexity-ai/package.json
  packages/pieces/community/perplexity-ai/src/lib/actions/create-chat-completion.action.ts
Labels: 🔌 pieces

#6857 feat(confluence): create page from template action
  packages/pieces/community/confluence/package.json
  packages/pieces/community/confluence/src/index.ts
  packages/pieces/community/confluence/src/lib/actions/create-page-from-template.ts
  packages/pieces/community/confluence/src/lib/actions/get-page-content.ts
  packages/pieces/community/confluence/src/lib/common/index.ts
  packages/pieces/community/confluence/src/lib/common/props.ts
  packages/pieces/community/confluence/src/lib/triggers/new-page.ts
Labels: 🔌 pieces

#6884 fix(google-sheets): fix default sheet dropdown error
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/lib/actions/clear-sheet.ts
  packages/pieces/community/google-sheets/src/lib/actions/create-column.ts
  packages/pieces/community/google-sheets/src/lib/actions/delete-row.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-row-by-num.ts
  packages/pieces/community/google-sheets/src/lib/actions/find-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/get-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-multiple-rows.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/insert-row.action.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-multiple-rows.ts
  packages/pieces/community/google-sheets/src/lib/actions/update-row.ts
  packages/pieces/community/google-sheets/src/lib/common/common.ts
  packages/pieces/community/google-sheets/src/lib/common/props.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/pieces/community/google-sheets/src/lib/triggers/new-row-added-webhook.ts
Labels: 🔌 pieces

#6894 revert: linting before push
  .husky/pre-push
Labels: 🧹 clean up

#6897 fix(github): fix sdk import
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts
  packages/pieces/community/github/src/lib/actions/create-issue.ts
  packages/pieces/community/github/src/lib/actions/get-issue-information.ts
  packages/pieces/community/github/src/lib/actions/lock-issue.ts
  packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts
  packages/pieces/community/github/src/lib/actions/unlock-issue.ts
  packages/pieces/community/github/src/lib/common/index.ts
  packages/pieces/community/github/src/lib/trigger/register-trigger.ts
Labels: 🔌 pieces

#6893 fix: jira cloud fetching all pages of projects
  package-lock.json
  packages/pieces/community/google-sheets/src/lib/triggers/new-or-updated-row.trigger.ts
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/lib/common/index.ts
Labels: 🐛 bug

#6901 fix: new stop actions field invoice_number
  packages/pieces/community/respaid/package.json
  packages/pieces/community/respaid/src/lib/actions/stop_collection_client_paid_directly.ts
  packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_instalment_payment.ts
  packages/pieces/community/respaid/src/lib/actions/stop_collection_for_direct_partial_payment.ts
  packages/pieces/community/respaid/src/lib/common/index.ts
  packages/pieces/community/respaid/src/lib/triggers/new_successful_collection_paid_to_creditor.ts
Labels: 🔌 pieces

#6900 feat(cloutly): send review invite action
  packages/pieces/community/cloutly/.eslintrc.json
  packages/pieces/community/cloutly/README.md
  packages/pieces/community/cloutly/package.json
  packages/pieces/community/cloutly/project.json
  packages/pieces/community/cloutly/src/index.ts
  packages/pieces/community/cloutly/src/lib/actions/send-review-invite.ts
  packages/pieces/community/cloutly/tsconfig.json
  packages/pieces/community/cloutly/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6917 fix(respaid): added is_agency_collection property to create_new_campaign
  packages/pieces/community/respaid/package.json
  packages/pieces/community/respaid/src/lib/actions/create_new_campaign.ts
Labels: 🔌 pieces

#6919 feat: enable api key access for global connections endpoints
  docs/endpoints/global-connections/delete.mdx
  docs/endpoints/global-connections/list.mdx
  docs/endpoints/global-connections/schema.mdx
  docs/endpoints/global-connections/update.mdx
  docs/endpoints/global-connections/upsert.mdx
  docs/mint.json
  docs/openapi.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/global-connections/global-connection-module.ts
Labels: 🌟 feature

#6916 chore: enhance router output for test step
  packages/engine/.test.env
  packages/engine/jest.config.ts
  packages/engine/src/lib/handler/router-executor.ts
  packages/engine/test/handler/router-branching.test.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flow-run/execution/step-output.ts
Labels: ✨ polishing

#6938 fix(create-subdomain-for-cloud): fix create subdomain for cloud and f…
  packages/server/api/src/app/ee/license-keys/license-keys-trial.service.ts
  packages/server/api/src/app/helper/system-validator.ts
  packages/server/shared/src/lib/system-props.ts
  packages/shared/src/lib/license-keys/index.ts
Labels: 🐛 bug

#6942 fix(embed-sdk): whether the external Id passed to the connect method is used or not, third-party users will be able to connect their accounts
  docs/embedding/embed-connections.mdx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/routes/embed/embedded-connection-dialog.tsx
  packages/react-ui/src/features/connections/components/rename-connection-dialog.tsx
  packages/react-ui/src/features/connections/lib/utils.ts
Labels: 🐛 bug

#6931 docs: fix polling trigger syntax
  docs/developers/building-pieces/create-trigger.mdx
  docs/developers/piece-reference/triggers/polling-trigger.mdx
Labels: 📚 documentation

#6943 feat: release 0.45.1
  docker-compose.yml
  package.json
Labels: release

#6944 fix(github): fix github sdk build issue
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/lib/actions/create-comment-on-a-issue.ts
  packages/pieces/community/github/src/lib/actions/create-issue.ts
  packages/pieces/community/github/src/lib/actions/get-issue-information.ts
  packages/pieces/community/github/src/lib/actions/lock-issue.ts
  packages/pieces/community/github/src/lib/actions/raw-graphql-query.ts
  packages/pieces/community/github/src/lib/actions/unlock-issue.ts
  packages/pieces/community/github/src/lib/common/index.ts
  packages/pieces/community/github/src/lib/trigger/register-trigger.ts
Labels: 🔌 pieces

#6921 feat(JIRA): add custom fields for issue action and find user action
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/index.ts
  packages/pieces/community/jira-cloud/src/lib/actions/add-watcher-to-issue.ts
  packages/pieces/community/jira-cloud/src/lib/actions/create-issue.ts
  packages/pieces/community/jira-cloud/src/lib/actions/find-user.ts
  packages/pieces/community/jira-cloud/src/lib/actions/link-issues.ts
  packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts
  packages/pieces/community/jira-cloud/src/lib/common/index.ts
  packages/pieces/community/jira-cloud/src/lib/common/props.ts
  packages/pieces/community/jira-cloud/src/lib/common/types.ts
Labels: 🔌 pieces

#6947 fix: jira-cloud typos
  packages/pieces/community/jira-cloud/src/lib/actions/update-issue.ts
Labels: 🔌 pieces

#6945 feat(firecrawl): add extract with prompt and schema
  packages/pieces/community/firecrawl/.eslintrc.json
  packages/pieces/community/firecrawl/README.md
  packages/pieces/community/firecrawl/package.json
  packages/pieces/community/firecrawl/project.json
  packages/pieces/community/firecrawl/src/index.ts
  packages/pieces/community/firecrawl/src/lib/actions/extract-with-prompt.ts
  packages/pieces/community/firecrawl/src/lib/actions/extract-with-schema.ts
  packages/pieces/community/firecrawl/tsconfig.json
  packages/pieces/community/firecrawl/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6948 feat(devin): create session, get session and send message action
  packages/pieces/community/devin/.eslintrc.json
  packages/pieces/community/devin/README.md
  packages/pieces/community/devin/package.json
  packages/pieces/community/devin/project.json
  packages/pieces/community/devin/src/index.ts
  packages/pieces/community/devin/src/lib/actions/create-session.ts
  packages/pieces/community/devin/src/lib/actions/get-session-details.ts
  packages/pieces/community/devin/src/lib/actions/send-message.ts
  packages/pieces/community/devin/tsconfig.json
  packages/pieces/community/devin/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#6963 fix: jira cloud auth error message
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/auth.ts
Labels: 🔌 pieces

#6973 fix: added checker to check if new window closed to resolve connect method promise
  package-lock.json
  packages/ee/ui/embed-sdk/src/index.ts
Labels: 🐛 bug
