Repository activepieces/activepieces, pull requests merged in 2025-06, with the labels that each got.

#7913 fix: publish piece script
  package.json
  packages/cli/src/lib/utils/piece-utils.ts
  tools/scripts/pieces/publish-piece.ts
  tools/scripts/utils/files.ts
  tools/scripts/utils/piece-script-utils.ts
  tools/scripts/xlf/remove-ee-modules-from-xlf-files.ts
  tools/scripts/xlf/xlf-modifier.ts
Labels: 🔌 pieces

#7914 fix: sync dev pieces cache path with worker execution files
  packages/server/shared/package.json
  packages/server/shared/src/index.ts
  packages/server/shared/src/lib/cache/cache.ts
  packages/server/shared/src/lib/cache/index.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/cache/code-builder.ts
  packages/server/worker/src/lib/cache/execution-files.ts
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
  packages/server/worker/src/lib/piece-manager/local-piece-manager.ts
  packages/server/worker/src/lib/piece-manager/registry-piece-manager.ts
  packages/server/worker/src/lib/runner/process/factory/isolate-sandbox-process.ts
  packages/server/worker/src/lib/runner/process/factory/no-sandbox-process.ts
Labels: 🐛 bug

#7648 feat: kommo piece
  packages/pieces/community/kommo/.eslintrc.json
  packages/pieces/community/kommo/README.md
  packages/pieces/community/kommo/package.json
  packages/pieces/community/kommo/project.json
  packages/pieces/community/kommo/src/index.ts
  packages/pieces/community/kommo/src/lib/actions/create-new-contact.ts
  packages/pieces/community/kommo/src/lib/actions/create-new-lead.ts
  packages/pieces/community/kommo/src/lib/actions/find-company.ts
  packages/pieces/community/kommo/src/lib/actions/find-contact.ts
  packages/pieces/community/kommo/src/lib/actions/find-lead.ts
  packages/pieces/community/kommo/src/lib/actions/index.ts
  packages/pieces/community/kommo/src/lib/actions/update-contact.ts
  packages/pieces/community/kommo/src/lib/actions/update-lead.ts
  packages/pieces/community/kommo/src/lib/common/index.ts
  packages/pieces/community/kommo/src/lib/common/props.ts
  packages/pieces/community/kommo/src/lib/triggers/index.ts
  packages/pieces/community/kommo/src/lib/triggers/lead-status-changed.ts
  packages/pieces/community/kommo/src/lib/triggers/new-contact-added.ts
  packages/pieces/community/kommo/src/lib/triggers/new-lead-created.ts
  packages/pieces/community/kommo/src/lib/triggers/new-task-created.ts
  packages/pieces/community/kommo/tsconfig.json
  packages/pieces/community/kommo/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7937 fix: sync git connection deletion on release and support git push
  packages/ee/shared/package.json
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/react-ui/src/app/routes/connections/connection-actions-menu.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-side-effects.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/ee/connection-keys/connection-key.module.ts
  packages/server/api/src/app/ee/global-connections/global-connection-module.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync-helper.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.module.ts
  packages/server/api/src/app/ee/projects/project-release/git-sync/git-sync.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/tables/table/table.controller.ts
Labels: 🐛 bug

#7892 chore: revamp embedding docs
  docs/_snippets/replace-oauth2-apps.mdx
  docs/admin-console/appearance.mdx
  docs/admin-console/custom-domain.mdx
  docs/admin-console/customize-emails.mdx
  docs/admin-console/manage-oauth2.mdx
  docs/admin-console/manage-pieces.mdx
  docs/developers/piece-reference/properties.mdx
  docs/embedding/customize-pieces.mdx
  docs/embedding/embed-connections.mdx
  docs/embedding/overview.mdx
  docs/embedding/predefined-connections/development.mdx
  docs/embedding/predefined-connections/overview.mdx
  docs/embedding/predefined-connections/production.mdx
  docs/embedding/provision-users.mdx
  docs/embedding/sdk-changelog.mdx
  docs/mint.json
  docs/resources/screenshots/activation-license-key-settings.png
  docs/resources/screenshots/branding.png
  docs/resources/screenshots/connections-piece-usage.png
  docs/resources/screenshots/connections-piece.png
  docs/resources/screenshots/create-api-key.png
  docs/resources/screenshots/create-global-connection.png
  docs/resources/screenshots/create-signing-key.png
  docs/resources/screenshots/custom-domain.png
  docs/resources/screenshots/embedding-example.png
  docs/resources/screenshots/install-piece.png
  docs/resources/screenshots/manage-oauth2.png
  docs/resources/screenshots/manage-pieces-2.png
  docs/resources/screenshots/manage-pieces.png
  docs/resources/screenshots/manage-smtp.png
  docs/resources/screenshots/project-settings.png
  docs/resources/screenshots/signing-key-id.png
  docs/resources/screenshots/sso.png
  docs/resources/screenshots/tag-pieces.png
  docs/resources/screenshots/testing-predefined-connections-creation.png
  packages/engine/package.json
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/utils.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/platform/security/api-keys/new-api-key-dialog.tsx
  packages/react-ui/src/app/routes/platform/security/signing-keys/index.tsx
  packages/react-ui/src/app/routes/platform/security/sso/index.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/appearance-section.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx
  packages/react-ui/src/app/routes/settings/general/index.tsx
  packages/react-ui/src/app/routes/settings/pieces/manage-pieces-dialog.tsx
  packages/react-ui/src/components/custom/multi-select.tsx
  packages/react-ui/src/components/ui/copy-text-tooltip.tsx
  packages/react-ui/src/features/connections/components/assign-global-connection-to-projects.tsx
  packages/react-ui/src/features/platform-admin-panel/components/new-signing-key-dialog.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: 📚 documentation

#7941 feat: release v0.59.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7951 chore: release 0.60.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts
  packages/server/worker/.eslintrc.json
Labels: release

#7956 fix: ensure the vendor navigation listener is set before resolving he configure method promise
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
Labels: 🐛 bug

#7960 fix: ignore project memebers associated with soft deleted projects
  packages/server/api/src/app/ee/projects/project-members/project-member.service.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/project/project-service.ts
Labels: 🐛 bug

#7961 feat: release v0.60.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7815 feat: tarvent piece
  packages/pieces/community/tarvent/.eslintrc.json
  packages/pieces/community/tarvent/README.md
  packages/pieces/community/tarvent/package.json
  packages/pieces/community/tarvent/project.json
  packages/pieces/community/tarvent/src/index.ts
  packages/pieces/community/tarvent/src/lib/actions/create-audience-group.ts
  packages/pieces/community/tarvent/src/lib/actions/create-contact-note.ts
  packages/pieces/community/tarvent/src/lib/actions/create-contact.ts
  packages/pieces/community/tarvent/src/lib/actions/create-suppression-filter.ts
  packages/pieces/community/tarvent/src/lib/actions/create-transaction.ts
  packages/pieces/community/tarvent/src/lib/actions/generate-custom-event.ts
  packages/pieces/community/tarvent/src/lib/actions/get-audience-groups.ts
  packages/pieces/community/tarvent/src/lib/actions/get-audiences.ts
  packages/pieces/community/tarvent/src/lib/actions/get-campaigns.ts
  packages/pieces/community/tarvent/src/lib/actions/get-contact.ts
  packages/pieces/community/tarvent/src/lib/actions/get-custom-event.ts
  packages/pieces/community/tarvent/src/lib/actions/get-journey.ts
  packages/pieces/community/tarvent/src/lib/actions/index.ts
  packages/pieces/community/tarvent/src/lib/actions/send-campaign.ts
  packages/pieces/community/tarvent/src/lib/actions/update-contact-group.ts
  packages/pieces/community/tarvent/src/lib/actions/update-contact-journey.ts
  packages/pieces/community/tarvent/src/lib/actions/update-contact-status.ts
  packages/pieces/community/tarvent/src/lib/actions/update-contact-tag.ts
  packages/pieces/community/tarvent/src/lib/actions/update-journey-status.ts
  packages/pieces/community/tarvent/src/lib/common/client.ts
  packages/pieces/community/tarvent/src/lib/common/constants.ts
  packages/pieces/community/tarvent/src/lib/common/index.ts
  packages/pieces/community/tarvent/src/lib/common/types.ts
  packages/pieces/community/tarvent/src/lib/triggers/campaign-send-finished.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-added.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-bounced.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-clicked.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-group-updated.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-node-added.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-opened.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-replied.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-status-updated.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-tag-updated.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-unsubscribed.ts
  packages/pieces/community/tarvent/src/lib/triggers/contact-updated.ts
  packages/pieces/community/tarvent/src/lib/triggers/form-submitted.ts
  packages/pieces/community/tarvent/src/lib/triggers/index.ts
  packages/pieces/community/tarvent/src/lib/triggers/page-performed.ts
  packages/pieces/community/tarvent/src/lib/triggers/survey-submitted.ts
  packages/pieces/community/tarvent/src/lib/triggers/transaction-created.ts
  packages/pieces/community/tarvent/src/lib/triggers/transaction-sent.ts
  packages/pieces/community/tarvent/tsconfig.json
  packages/pieces/community/tarvent/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7958 fix: ensure the vendor navigation listener is set before resolving the configure method promise
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
Labels: skip-changelog

#7959 feat(jira-cloud): get attachment action
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/index.ts
  packages/pieces/community/jira-cloud/src/lib/actions/get-issue-attachment.ts
Labels: 🔌 pieces

#7969 feat: bump release 0.60.2
  docker-compose.yml
  package.json
Labels: release

#7976 feat(zoho-desk): list tickets, create tickets and find contact actions
  packages/pieces/community/zoho-desk/.eslintrc.json
  packages/pieces/community/zoho-desk/README.md
  packages/pieces/community/zoho-desk/package.json
  packages/pieces/community/zoho-desk/project.json
  packages/pieces/community/zoho-desk/src/index.ts
  packages/pieces/community/zoho-desk/src/lib/actions/create-ticket.ts
  packages/pieces/community/zoho-desk/src/lib/actions/find-contact.ts
  packages/pieces/community/zoho-desk/src/lib/actions/list-tickets.ts
  packages/pieces/community/zoho-desk/src/lib/common/auth.ts
  packages/pieces/community/zoho-desk/src/lib/common/index.ts
  packages/pieces/community/zoho-desk/src/lib/common/props.ts
  packages/pieces/community/zoho-desk/tsconfig.json
  packages/pieces/community/zoho-desk/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7977 fix(slack): expose actions and triggers
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
Labels: 🔌 pieces

#7982 fix: missing body in return response and wait for next webhook
  packages/engine/test/handler/flow-error-handling.test.ts
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/lib/actions/return-response-and-wait-for-next-webhook.ts
  packages/pieces/community/webhook/src/lib/actions/return-response.ts
Labels: 🐛 bug

#7984 feat: update mcp instructions for claude
  packages/react-ui/src/app/mcp/mcp-connect/index.tsx
  packages/react-ui/src/app/mcp/mcp-connect/mcp-server-url-box.tsx
Labels: 🐛 bug

#7991 fix: handle undefined values in versionSetTwo to prevent startsWith error
  packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
Labels: 🐛 bug

#7992 fix: add cascade delete to mcp tool flow
  packages/react-ui/src/components/ui/data-table/index.tsx
  packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
  packages/server/api/src/app/database/migration/postgres/1749128866314-AddMcpToolFlowCascadeDelete.ts
  packages/server/api/src/app/database/migration/sqlite/1749129178686-AddMcpToolFlowCascadeDeleteSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/mcp/tool/mcp-tool.entity.ts
Labels: 🐛 bug

#7980 feat: tarvent piece - update contributors
  packages/pieces/community/tarvent/package.json
  packages/pieces/community/tarvent/src/index.ts
Labels: 🔌 pieces

#7650 feat: zoho mail piece
  packages/pieces/community/zoho-mail/.eslintrc.json
  packages/pieces/community/zoho-mail/README.md
  packages/pieces/community/zoho-mail/package.json
  packages/pieces/community/zoho-mail/project.json
  packages/pieces/community/zoho-mail/src/index.ts
  packages/pieces/community/zoho-mail/src/lib/actions/get-email-details.ts
  packages/pieces/community/zoho-mail/src/lib/actions/mark-email-as-read.ts
  packages/pieces/community/zoho-mail/src/lib/actions/mark-email-as-unread.ts
  packages/pieces/community/zoho-mail/src/lib/actions/move-email.ts
  packages/pieces/community/zoho-mail/src/lib/actions/send-email.ts
  packages/pieces/community/zoho-mail/src/lib/common/auth.ts
  packages/pieces/community/zoho-mail/src/lib/common/index.ts
  packages/pieces/community/zoho-mail/src/lib/common/props.ts
  packages/pieces/community/zoho-mail/src/lib/triggers/new-email-received-trigger.ts
  packages/pieces/community/zoho-mail/tsconfig.json
  packages/pieces/community/zoho-mail/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7866 feat(piece-ticktick): implement ticktick piece with actions and triggers
  packages/pieces/community/ticktick/.eslintrc.json
  packages/pieces/community/ticktick/README.md
  packages/pieces/community/ticktick/package.json
  packages/pieces/community/ticktick/project.json
  packages/pieces/community/ticktick/src/index.ts
  packages/pieces/community/ticktick/src/lib/actions/complete-task.ts
  packages/pieces/community/ticktick/src/lib/actions/create-task.ts
  packages/pieces/community/ticktick/src/lib/actions/delete-task.ts
  packages/pieces/community/ticktick/src/lib/actions/find-task.ts
  packages/pieces/community/ticktick/src/lib/actions/get-project-by-id.ts
  packages/pieces/community/ticktick/src/lib/actions/get-task.ts
  packages/pieces/community/ticktick/src/lib/actions/update-task.ts
  packages/pieces/community/ticktick/src/lib/common/client.ts
  packages/pieces/community/ticktick/src/lib/common/constants.ts
  packages/pieces/community/ticktick/src/lib/common/props.ts
  packages/pieces/community/ticktick/src/lib/triggers/new-task-created.ts
  packages/pieces/community/ticktick/tsconfig.json
  packages/pieces/community/ticktick/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8009 feat: clockify piece
  packages/pieces/community/clockify/.eslintrc.json
  packages/pieces/community/clockify/README.md
  packages/pieces/community/clockify/package.json
  packages/pieces/community/clockify/project.json
  packages/pieces/community/clockify/src/index.ts
  packages/pieces/community/clockify/src/lib/actions/create-task.ts
  packages/pieces/community/clockify/src/lib/actions/create-time-entry.ts
  packages/pieces/community/clockify/src/lib/actions/find-running-timer.ts
  packages/pieces/community/clockify/src/lib/actions/find-task.ts
  packages/pieces/community/clockify/src/lib/actions/find-time-entry.ts
  packages/pieces/community/clockify/src/lib/actions/start-timer.ts
  packages/pieces/community/clockify/src/lib/actions/stop-timer.ts
  packages/pieces/community/clockify/src/lib/common/client.ts
  packages/pieces/community/clockify/src/lib/common/props.ts
  packages/pieces/community/clockify/src/lib/triggers/new-task.ts
  packages/pieces/community/clockify/src/lib/triggers/new-time-entry.ts
  packages/pieces/community/clockify/src/lib/triggers/new-timer-started.ts
  packages/pieces/community/clockify/tsconfig.json
  packages/pieces/community/clockify/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8013 fix: avatar pictures
  package-lock.json
  package.json
  packages/react-ui/src/app/builder/builder-header/builder-header.tsx
  packages/react-ui/src/app/builder/builder-header/user-avatar-menu.tsx
  packages/react-ui/src/app/builder/flow-versions/flow-versions-card.tsx
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/sidebar/sidebar-user.tsx
  packages/react-ui/src/components/ui/avatar-letter.tsx
  packages/react-ui/src/components/ui/user-avatar.tsx
  packages/react-ui/src/features/team/component/invitation-card.tsx
  packages/react-ui/src/features/team/component/project-member-card.tsx
Labels: 🐛 bug

#8003 fix: prevent dialog overflow on small screens in MCP Add Tool modal ( Issue #8002)
  packages/react-ui/src/app/mcp/mcp-piece-tool-dialog/index.tsx
Labels: ✨ polishing

#7930 feat: Mem Piece
  packages/pieces/community/mem/.eslintrc.json
  packages/pieces/community/mem/README.md
  packages/pieces/community/mem/package.json
  packages/pieces/community/mem/project.json
  packages/pieces/community/mem/src/index.ts
  packages/pieces/community/mem/src/lib/actions/create-mem.ts
  packages/pieces/community/mem/src/lib/actions/create-note.ts
  packages/pieces/community/mem/src/lib/actions/delete-note.ts
  packages/pieces/community/mem/src/lib/common/index.ts
  packages/pieces/community/mem/tsconfig.json
  packages/pieces/community/mem/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7924 feat: Chatbase piece
  packages/pieces/community/chatbase/.eslintrc.json
  packages/pieces/community/chatbase/README.md
  packages/pieces/community/chatbase/package.json
  packages/pieces/community/chatbase/project.json
  packages/pieces/community/chatbase/src/index.ts
  packages/pieces/community/chatbase/src/lib/actions/create-chatbot.ts
  packages/pieces/community/chatbase/src/lib/actions/list-all-chatbots.ts
  packages/pieces/community/chatbase/src/lib/actions/search-conversations-by-query.ts
  packages/pieces/community/chatbase/src/lib/actions/send-prompt-to-chatbot.ts
  packages/pieces/community/chatbase/src/lib/common/index.ts
  packages/pieces/community/chatbase/src/lib/common/props.ts
  packages/pieces/community/chatbase/tsconfig.json
  packages/pieces/community/chatbase/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7912 refactor: alerts + connections queries/mutations + add frontend best practices docs
  docs/handbook/engineering/onboarding/onboarding-check-list.mdx
  docs/handbook/engineering/playbooks/frontend-best-practices.mdx
  docs/mint.json
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
  packages/react-ui/src/app/connections/replace-connections-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-piece-tool-dialog/index.tsx
  packages/react-ui/src/app/routes/connections/connection-actions-menu.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/update-oauth2-dialog.tsx
  packages/react-ui/src/app/routes/settings/alerts/add-alert-email-dialog.tsx
  packages/react-ui/src/app/routes/settings/alerts/alerts-email-list-card.tsx
  packages/react-ui/src/features/alerts/lib/alert-hooks.ts
  packages/react-ui/src/features/alerts/lib/api.ts
  packages/react-ui/src/features/connections/components/edit-global-connection-dialog.tsx
  packages/react-ui/src/features/connections/components/rename-connection-dialog.tsx
  packages/react-ui/src/features/connections/lib/api/app-connections.ts
  packages/react-ui/src/features/connections/lib/api/global-connections.ts
  packages/react-ui/src/features/connections/lib/api/oauth-apps.ts
  packages/react-ui/src/features/connections/lib/app-connections-hooks.ts
  packages/react-ui/src/features/connections/lib/app-connections-utils.ts
  packages/react-ui/src/features/connections/lib/global-connections-hooks.ts
  packages/react-ui/src/features/connections/lib/oauth-apps-hooks.ts
  packages/react-ui/src/features/connections/lib/utils.ts
Labels: 📚 documentation, 🧹 clean up

#7908 refactor: revamp ai provider
  docs/about/breaking-changes.mdx
  package-lock.json
  package.json
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/index.ts
  packages/pieces/community/common/src/lib/ai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/anthropic/index.ts
  packages/pieces/community/common/src/lib/ai/providers/index.ts
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/common/src/lib/ai/providers/replicate/index.ts
  packages/pieces/community/common/src/lib/ai/providers/utils.ts
  packages/pieces/community/image-ai/src/index.ts
  packages/pieces/community/image-ai/src/lib/actions/generate-image.ts
  packages/pieces/community/text-ai/src/index.ts
  packages/pieces/community/text-ai/src/lib/actions/ask-ai.ts
  packages/pieces/community/text-ai/src/lib/actions/summarize-text.ts
  packages/react-ui/src/app/routes/platform/setup/ai/index.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/universal-pieces/ai-provider-card.tsx
  packages/react-ui/src/app/routes/platform/setup/ai/universal-pieces/upsert-provider-dialog.tsx
  packages/react-ui/src/features/platform-admin-panel/lib/ai-provider-api.ts
  packages/server/api/src/app/ai/ai-provider-controller.ts
  packages/server/api/src/app/ai/ai-provider-entity.ts
  packages/server/api/src/app/ai/ai-provider-proxy.ts
  packages/server/api/src/app/ai/ai-provider-service.ts
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/ai/ai-provider.service.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1748871900624-AIProviderRedactorPostgres.ts.ts
  packages/server/api/src/app/database/migration/sqlite/1748824241409-AIProviderRefactorSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/shared/src/lib/ai/ai-sdk.ts
  packages/shared/src/lib/ai/index.ts
  packages/shared/src/lib/ai/supported-ai-providers.ts
  packages/shared/src/lib/flag/flag.ts
Labels: 🧹 clean up

#8024 fix: avatars theming + tooltips weren't showing
  packages/react-ui/src/app/components/sidebar/sidebar-user.tsx
  packages/react-ui/src/components/ui/user-avatar.tsx
  packages/react-ui/src/features/team/component/invitation-card.tsx
  packages/react-ui/src/features/team/component/project-member-card.tsx
Labels: skip-changelog

#8023 refactor: handle undefined by using Map instead of Record in flow change check
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/ee/flags/enterprise-flags.hooks.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
Labels: ✨ polishing

#7970 feat(google-drive): duplicate file as a specific mime type (gdocs or gsheet)
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/index.ts
  packages/pieces/community/google-drive/src/lib/action/duplicate-file.action.ts
Labels: 🔌 pieces

#7918 fix: display error notification
  packages/server/api/src/app/flows/flow/flow-service-side-effects.ts
  packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/server/api/src/app/webhooks/webhook-simulation/webhook-simulation-side-effects.ts
Labels: 🐛 bug

#8040 fix: bump shared version
  packages/server/worker/package.json
  packages/shared/package.json
Labels: 🐛 bug

#8043 fix: apply validate-publishable-packages to all packages
  .github/workflows/validate-publishable-packages.yml
Labels: ✨ polishing

#8044 fix: bump versions for AI pieces
  packages/pieces/community/claude/package.json
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/openai/package-lock.json
  packages/pieces/community/openai/package.json
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/utility-ai/package.json
Labels: 🐛 bug

#8045 fix: bump version of @activepieces/pieces-common to 0.5.0
  packages/pieces/community/common/package.json
  packages/pieces/community/image-ai/package.json
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/utility-ai/package.json
  packages/server/worker/package.json
  packages/shared/package.json
Labels: 🐛 bug

#8047 fix: return entity not found instead of missing project id
  .cursor/mcp.json
  .gitignore
  .vscode/settings.json
  packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts
  packages/server/api/test/integration/cloud/core/security.test.ts
Labels: 🐛 bug

#8016 feat(returning-ai): add react message action
  packages/pieces/community/returning-ai/package.json
  packages/pieces/community/returning-ai/src/index.ts
  packages/pieces/community/returning-ai/src/lib/actions/react-message.ts
  packages/pieces/community/returning-ai/src/lib/actions/reply-message.ts
  packages/pieces/community/returning-ai/src/lib/actions/send-message.ts
Labels: 🔌 pieces

#8027 feat(amazon-s3): new action generate signed url
  packages/pieces/community/amazon-s3/package.json
  packages/pieces/community/amazon-s3/src/index.ts
  packages/pieces/community/amazon-s3/src/lib/actions/generate-signed-url.ts
Labels: 🔌 pieces, 💫 priority

#8032 fix(docusign): fix filename which was always archive.zip even for PDFs
  packages/pieces/community/docusign/package.json
  packages/pieces/community/docusign/src/lib/actions/get-document.ts
Labels: 🔌 pieces

#8065 chore: upgrade nx
  .github/workflows/build-cloud-nx.yml
  migrations.json
  package-lock.json
  package.json
  packages/server/api/project.json
  packages/server/worker/package.json
Labels: skip-changelog

#8050 feat: added ability to set locale in embedding + set light/dark mode + hide duplicate flow
  docs/ai/mcp.mdx
  docs/embedding/embed-builder.mdx
  docs/embedding/navigation.mdx
  docs/embedding/sdk-changelog.mdx
  docs/handbook/engineering/onboarding/on-call.mdx
  docs/handbook/teams/overview.mdx
  docs/mint.json
  packages/ee/ui/embed-sdk/src/index.ts
  packages/react-ui/src/app/app.tsx
  packages/react-ui/src/app/builder/builder-header/builder-header.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/app/routes/settings/appearance/language-switcher.tsx
  packages/react-ui/src/components/embed-provider.tsx
  packages/react-ui/src/components/ui/home-button.tsx
Labels: 🌟 feature

#8070 fix: make stepName optional in issues and update related queries
  packages/react-ui/src/app/routes/flows/issues-table/columns.tsx
  packages/server/api/src/app/database/migration/postgres/1750025401754-MakeStepNameOptional.ts
  packages/server/api/src/app/database/migration/sqlite/1750025280435-MakeStepNameOptionalSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/issues/issues-entity.ts
  packages/server/api/src/app/flows/issues/issues-service.ts
Labels: 🐛 bug

#8076 Fix/sdk rc docs
  docs/embedding/sdk-changelog.mdx
Labels: skip-changelog

#8077 fix: add url for rc sdk version
  docs/embedding/sdk-changelog.mdx
Labels: skip-changelog

#8084 fix: testing steps
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-agent-dialog.tsx
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-todo-dialog.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/react-ui/src/app/builder/test-step/test-trigger-section/first-time-testing-section.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section/index.tsx
Labels: skip-changelog

#8087 fix: remove unique constraint on issue
  packages/server/api/src/app/database/migration/postgres/1750093037011-RemoveUniqueOnFlow.ts
  packages/server/api/src/app/database/migration/sqlite/1750093133906-RemoveUniqueOnFlowSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/issues/issues-entity.ts
Labels: 🐛 bug

#8091 fix: filter pieces on embedding
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/pieces/filters/enterprise-piece-metadata-service-hooks.ts
  packages/server/api/src/app/ee/pieces/filters/piece-filtering-utils.ts
  packages/server/api/src/app/helper/system-jobs/redis-system-job.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/hooks/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/utils/index.ts
  packages/server/api/src/app/pieces/piece-metadata-service/utils/piece-searching.ts
  packages/server/api/src/app/pieces/piece-metadata-service/utils/piece-sorting.ts
Labels: 🐛 bug

#8092 feat: rename beta to new
  packages/react-ui/src/app/components/sidebar/index.tsx
  packages/react-ui/src/app/routes/agents/index.tsx
  packages/react-ui/src/app/routes/tables/index.tsx
  packages/react-ui/src/app/routes/todos/index.tsx
  packages/react-ui/src/components/custom/beta-badge.tsx
Labels: ✨ polishing

#8000 feat(github): add triggers on discussion creation and comments
  packages/pieces/community/github/.eslintrc.json
  packages/pieces/community/github/package.json
  packages/pieces/community/github/src/lib/trigger/index.ts
  packages/pieces/community/github/src/lib/trigger/register-trigger.ts
Labels: 🔌 pieces

#8097 fix: revert prefix removal in sdk
  docs/embedding/embed-builder.mdx
  docs/embedding/sdk-changelog.mdx
  package-lock.json
  packages/ee/ui/embed-sdk/src/index.ts
  packages/react-ui/src/app/components/sidebar/index.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-flow-tool-dialog/index.tsx
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: skip-changelog

#7994 feat(reddit): add Reddit piece for CRUD operations on posts and comments
  packages/pieces/community/reddit/.eslintrc.json
  packages/pieces/community/reddit/README.md
  packages/pieces/community/reddit/package.json
  packages/pieces/community/reddit/project.json
  packages/pieces/community/reddit/src/index.ts
  packages/pieces/community/reddit/src/lib/actions/create-reddit-comment.ts
  packages/pieces/community/reddit/src/lib/actions/create-reddit-post.ts
  packages/pieces/community/reddit/src/lib/actions/delete-reddit-comment.ts
  packages/pieces/community/reddit/src/lib/actions/delete-reddit-post.ts
  packages/pieces/community/reddit/src/lib/actions/edit-reddit-comment.ts
  packages/pieces/community/reddit/src/lib/actions/edit-reddit-post.ts
  packages/pieces/community/reddit/src/lib/actions/fetch-post-comments.ts
  packages/pieces/community/reddit/src/lib/actions/get-reddit-post-details.ts
  packages/pieces/community/reddit/src/lib/actions/retrieve-reddit-post.ts
  packages/pieces/community/reddit/tsconfig.json
  packages/pieces/community/reddit/tsconfig.lib.json
Labels: 🔌 pieces, 💫 priority

#8104 fix(mcp): mcp with connectionless pieces
  packages/react-ui/src/app/routes/mcp-servers/id/mcp-piece-tool-dialog/index.tsx
Labels: 🐛 bug

#8105 fix: remove depercated code of ai button & tooltips for bar
  packages/react-ui/src/app/builder/builder-header/builder-header.tsx
  packages/react-ui/src/app/builder/flow-canvas/edges/add-button.tsx
  packages/react-ui/src/app/builder/flow-canvas/edges/ask-ai-indicator.tsx
  packages/react-ui/src/app/builder/flow-canvas/nodes/big-add-button-node.tsx
  packages/react-ui/src/app/builder/step-settings/editable-step-name.tsx
Labels: 🧹 clean up

#8106 fix(fb-leads): Add Missing Page Scope and Enhance Lead Payload
  packages/pieces/community/facebook-leads/package.json
  packages/pieces/community/facebook-leads/src/index.ts
  packages/pieces/community/facebook-leads/src/lib/common/index.ts
  packages/pieces/community/facebook-leads/src/lib/common/types.ts
  packages/pieces/community/facebook-leads/src/lib/triggers/new-lead.ts
Labels: 🔌 pieces

#8112 feat: introduce google gemini AI provider
  package-lock.json
  package.json
  packages/server/api/src/app/ai/providers/anthropic.ts
  packages/server/api/src/app/ai/providers/google.ts
  packages/server/api/src/app/ai/providers/index.ts
  packages/server/api/src/app/ai/providers/openai.ts
  packages/server/api/src/app/ai/providers/utils.ts
  packages/shared/src/lib/ai/ai-sdk.ts
  packages/shared/src/lib/ai/supported-ai-providers.ts
Labels: 🌟 feature

#8054 fix: refresh oauth2 client credentials connections with correct scopes
  packages/react-ui/src/app/connections/basic-secret-connection-settings.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/oauth2-util.ts
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/server/worker/src/lib/runner/index.ts
  packages/shared/package.json
  packages/shared/src/lib/app-connection/app-connection.ts
  packages/shared/src/lib/flows/operations/index.ts
  packages/shared/src/lib/flows/sample-data/index.ts
Labels: 🐛 bug

#8128 feat: upgrade to fastify v5
  package-lock.json
  package.json
  packages/server/api/project.json
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/authentication/authorization.ts
  packages/server/api/src/app/core/security/authn/access-token-authn-handler.ts
  packages/server/api/src/app/core/security/authn/app-sumo-authn-handler.ts
  packages/server/api/src/app/core/security/authn/global-api-key-authn-handler.ts
  packages/server/api/src/app/core/security/authn/platform-api-key-authn-handler.ts
  packages/server/api/src/app/core/security/authz/principal-type-authz-handler.ts
  packages/server/api/src/app/core/security/authz/project-authz-handler.ts
  packages/server/api/src/app/ee/authentication/project-role/rbac-middleware.ts
  packages/server/api/src/app/pieces/piece-metadata-service/utils/index.ts
  packages/server/api/src/app/server.ts
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
  packages/server/api/test/integration/cloud/core/security.test.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/server/worker/package.json
Labels: 🧹 clean up

#8130 feat: polish agents & output in the builder
  packages/react-ui/src/app/builder/run-details/flow-step-io/flow-step-agent.tsx
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-todo-dialog.tsx
  packages/react-ui/src/app/routes/todos/todo-details/index.tsx
  packages/react-ui/src/app/routes/todos/todo-details/todo-timeline-comment-skeleton.tsx
  packages/react-ui/src/app/routes/todos/todo-details/todo-timeline.tsx
  packages/react-ui/src/features/todos/lib/todos-activity-hook.ts
  packages/server/api/src/app/todos/todo.controller.ts
  packages/server/api/src/app/todos/todo.service.ts
  packages/shared/src/lib/todos/todos-request.ts
Labels: ✨ polishing

#7926 feat: Crisp Piece
  packages/pieces/community/crisp/.eslintrc.json
  packages/pieces/community/crisp/README.md
  packages/pieces/community/crisp/package.json
  packages/pieces/community/crisp/project.json
  packages/pieces/community/crisp/src/index.ts
  packages/pieces/community/crisp/src/lib/actions/add-note-to-conversation.ts
  packages/pieces/community/crisp/src/lib/actions/create-conversation.ts
  packages/pieces/community/crisp/src/lib/actions/create-or-update-contact.ts
  packages/pieces/community/crisp/src/lib/actions/find-conversation.ts
  packages/pieces/community/crisp/src/lib/actions/find-user-profile.ts
  packages/pieces/community/crisp/src/lib/actions/update-conversation-state.ts
  packages/pieces/community/crisp/src/lib/common/auth.ts
  packages/pieces/community/crisp/src/lib/common/client.ts
  packages/pieces/community/crisp/src/lib/common/props.ts
  packages/pieces/community/crisp/src/lib/triggers/new-contact.ts
  packages/pieces/community/crisp/src/lib/triggers/new-conversation.ts
  packages/pieces/community/crisp/tsconfig.json
  packages/pieces/community/crisp/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7797 feat: acuity scheduling piece
  packages/pieces/community/acuity-scheduling/.eslintrc.json
  packages/pieces/community/acuity-scheduling/README.md
  packages/pieces/community/acuity-scheduling/package.json
  packages/pieces/community/acuity-scheduling/project.json
  packages/pieces/community/acuity-scheduling/src/index.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/add-blocked-time.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/create-appointment.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/create-client.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/find-appointments.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/find-client.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/index.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/reschedule-appointment.ts
  packages/pieces/community/acuity-scheduling/src/lib/actions/update-client.ts
  packages/pieces/community/acuity-scheduling/src/lib/common/index.ts
  packages/pieces/community/acuity-scheduling/src/lib/common/props.ts
  packages/pieces/community/acuity-scheduling/src/lib/triggers/appointment-canceled.ts
  packages/pieces/community/acuity-scheduling/src/lib/triggers/appointment-scheduled.ts
  packages/pieces/community/acuity-scheduling/src/lib/triggers/index.ts
  packages/pieces/community/acuity-scheduling/tsconfig.json
  packages/pieces/community/acuity-scheduling/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7873 feat: Circle.so piece
  packages/pieces/community/circle/.eslintrc.json
  packages/pieces/community/circle/README.md
  packages/pieces/community/circle/package.json
  packages/pieces/community/circle/project.json
  packages/pieces/community/circle/src/index.ts
  packages/pieces/community/circle/src/lib/actions/add-member-to-space.ts
  packages/pieces/community/circle/src/lib/actions/create-comment.ts
  packages/pieces/community/circle/src/lib/actions/create-post.ts
  packages/pieces/community/circle/src/lib/actions/find-member-by-email.ts
  packages/pieces/community/circle/src/lib/actions/get-member-details.ts
  packages/pieces/community/circle/src/lib/actions/get-post-details.ts
  packages/pieces/community/circle/src/lib/common/auth.ts
  packages/pieces/community/circle/src/lib/common/index.ts
  packages/pieces/community/circle/src/lib/common/types.ts
  packages/pieces/community/circle/src/lib/triggers/new-member-added.ts
  packages/pieces/community/circle/src/lib/triggers/new-post.ts
  packages/pieces/community/circle/tsconfig.json
  packages/pieces/community/circle/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8101 feat(talkable): Add action claimOffer and refactoring
  packages/pieces/community/talkable/package.json
  packages/pieces/community/talkable/src/index.ts
  packages/pieces/community/talkable/src/lib/actions/index.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-event.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-purchase.ts
  packages/pieces/community/talkable/src/lib/actions/people/update-person.ts
  packages/pieces/community/talkable/src/lib/actions/referrals/update-referral-status.ts
  packages/pieces/community/talkable/src/lib/actions/rewards/claim-offer.ts
Labels: 🔌 pieces

#8133 fix: agents and openai proxy streaming
  packages/react-ui/src/app/routes/todos/todo-details/index.tsx
  packages/server/api/src/app/agents/agent-executor.ts
  packages/server/api/src/app/ai/ai-provider-service.ts
  packages/server/api/src/app/ai/ai-provider.module.ts
  packages/server/api/src/app/ai/providers/anthropic.ts
  packages/server/api/src/app/ai/providers/google.ts
  packages/server/api/src/app/ai/providers/openai.ts
  packages/server/api/src/app/ai/providers/replicate.ts
  packages/server/api/src/app/ai/providers/types.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/api/src/app/todos/activity/todos-activity.service.ts
  packages/server/api/src/app/todos/todo-side-effects.ts
  packages/shared/package.json
  packages/shared/src/lib/agents/agent-output-utils.ts
  packages/shared/src/lib/ai/supported-ai-providers.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/websocket/index.ts
Labels: 🐛 bug

#8149 feat: remove project ids from connections
  packages/server/api/src/app/agents/agent-executor.ts
  packages/server/api/src/app/app-connection/app-connection.entity.ts
  packages/server/api/src/app/database/migration/common/1750712746125-RemoveProjectIdFromIndex.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
Labels: 🐛 bug

#8158 feat: release 0.64.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/react-ui/src/app/routes/todos/todo-details/index.tsx
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/src/lib/agents/index.ts
Labels: release

#8155 fix: enhance error messages for testing steps
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/react-ui/src/app/builder/test-step/test-step-utils.ts
  packages/server/worker/src/lib/cache/code-builder.ts
Labels: 🐛 bug

#8166 fix: upgrade bullmq compatibility with fastify 5
  package-lock.json
  package.json
  packages/server/api/src/app/workers/redis/redis-bullboard.ts
Labels: 🐛 bug

#8167 feat: release 0.64.2
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#8168 docs: add performance/benchmarks section
  docs/install/architecture/performance.mdx
  docs/mint.json
  docs/resources/screenshots/simple-webhook-flow.png
Labels: 📚 documentation

#7940 feat: smartsheet piece
  packages/pieces/community/smartsheet/.eslintrc.json
  packages/pieces/community/smartsheet/README.md
  packages/pieces/community/smartsheet/package.json
  packages/pieces/community/smartsheet/project.json
  packages/pieces/community/smartsheet/src/index.ts
  packages/pieces/community/smartsheet/src/lib/actions/add-row-to-sheet.ts
  packages/pieces/community/smartsheet/src/lib/actions/attach-file-to-row.ts
  packages/pieces/community/smartsheet/src/lib/actions/find-attachment-by-row-id.ts
  packages/pieces/community/smartsheet/src/lib/actions/find-rows-by-query.ts
  packages/pieces/community/smartsheet/src/lib/actions/find-sheet-by-name.ts
  packages/pieces/community/smartsheet/src/lib/actions/update-row.ts
  packages/pieces/community/smartsheet/src/lib/common/index.ts
  packages/pieces/community/smartsheet/src/lib/triggers/new-attachment-trigger.ts
  packages/pieces/community/smartsheet/src/lib/triggers/new-comment-trigger.ts
  packages/pieces/community/smartsheet/src/lib/triggers/new-row-trigger.ts
  packages/pieces/community/smartsheet/src/lib/triggers/updated-row-trigger.ts
  packages/pieces/community/smartsheet/tsconfig.json
  packages/pieces/community/smartsheet/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8117 feat(jira-cloud): Updated status trigger
  packages/pieces/community/jira-cloud/package.json
  packages/pieces/community/jira-cloud/src/index.ts
  packages/pieces/community/jira-cloud/src/lib/triggers/updated-issue-status.ts
Labels: 🔌 pieces, 💫 priority

#8156 feat(talkable): add custom field support to purchase and event actions
  packages/pieces/community/talkable/package.json
  packages/pieces/community/talkable/src/lib/actions/origins/create-event.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-events-batch.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-purchase.ts
  packages/pieces/community/talkable/src/lib/actions/origins/create-purchases-batch.ts
Labels: 🔌 pieces

#7896 feat: heygen piece
  packages/pieces/community/heygen/.eslintrc.json
  packages/pieces/community/heygen/README.md
  packages/pieces/community/heygen/package.json
  packages/pieces/community/heygen/project.json
  packages/pieces/community/heygen/src/index.ts
  packages/pieces/community/heygen/src/lib/actions/create-a-video-from-template.ts
  packages/pieces/community/heygen/src/lib/actions/retrieve-a-translated-video-status.ts
  packages/pieces/community/heygen/src/lib/actions/retrieve-a-video-status.ts
  packages/pieces/community/heygen/src/lib/actions/retrieve-shareable-link-for-a-video.ts
  packages/pieces/community/heygen/src/lib/actions/translate-a-video.ts
  packages/pieces/community/heygen/src/lib/actions/upload-an-asset.ts
  packages/pieces/community/heygen/src/lib/common/auth.ts
  packages/pieces/community/heygen/src/lib/common/client.ts
  packages/pieces/community/heygen/src/lib/common/props.ts
  packages/pieces/community/heygen/src/lib/triggers/video-generation-completed.ts
  packages/pieces/community/heygen/src/lib/triggers/video-generation-failed.ts
  packages/pieces/community/heygen/tsconfig.json
  packages/pieces/community/heygen/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#8186 update slack scopes
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
Labels: 🔌 pieces

#8192 fix: json input was overgrowing the dialog for generating webhook sample data
  packages/react-ui/src/components/custom/json-editor.tsx
  packages/react-ui/src/features/agents/agent-card.tsx
Labels: 🐛 bug

#8193 feat(docker): optimize build cache by reordering COPY and npm ci
  Dockerfile
Labels: ✨ polishing

#8184 feat: translations
  packages/pieces/community/google-sheets/src/i18n/de.json
  packages/pieces/community/google-sheets/src/i18n/es.json
  packages/pieces/community/google-sheets/src/i18n/fr.json
  packages/pieces/community/google-sheets/src/i18n/ja.json
  packages/pieces/community/google-sheets/src/i18n/nl.json
  packages/pieces/community/google-sheets/src/i18n/pt.json
  packages/pieces/community/google-sheets/src/i18n/ru.json
  packages/pieces/community/google-sheets/src/i18n/zh.json
  packages/pieces/community/store/src/i18n/de.json
  packages/pieces/community/store/src/i18n/es.json
  packages/pieces/community/store/src/i18n/fr.json
  packages/pieces/community/store/src/i18n/ja.json
  packages/pieces/community/store/src/i18n/nl.json
  packages/pieces/community/store/src/i18n/pt.json
  packages/pieces/community/store/src/i18n/ru.json
  packages/pieces/community/store/src/i18n/zh.json
  packages/pieces/community/webhook/src/i18n/nl.json
  packages/pieces/community/webhook/src/i18n/pt.json
  packages/pieces/community/webhook/src/i18n/ru.json
  packages/pieces/community/webhook/src/i18n/zh.json
Labels: 🧹 clean up

#8200 feat: list users endpoint by external id
  docs/endpoints/users/list.mdx
  docs/endpoints/users/schema.mdx
  docs/mint.json
  docs/openapi.json
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/ee/license-keys/license-keys-service.ts
  packages/server/api/src/app/user/platform/platform-user-controller.ts
  packages/server/api/src/app/user/user-service.ts
  packages/shared/src/lib/user/index.ts
Labels: ✨ polishing
