Repository activepieces/activepieces, pull requests merged in 2025-10, with the labels that each got.

#9507 New Crowdin updates
  packages/pieces/community/text-helper/package.json
  packages/pieces/community/text-helper/src/i18n/de.json
  packages/pieces/community/text-helper/src/i18n/es.json
  packages/pieces/community/text-helper/src/i18n/fr.json
  packages/pieces/community/text-helper/src/i18n/ja.json
  packages/pieces/community/text-helper/src/i18n/nl.json
  packages/pieces/community/text-helper/src/i18n/pt.json
  packages/pieces/community/text-helper/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9512 fix: add index for app events
  packages/server/api/src/app/database/migration/common/1759392852559-AddIndexForAppEvents.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/trigger/app-event-routing/app-event-routing.entity.ts
Labels: 🐛 bug

#9521 fix: agent output was showing an error when it actually finished "src property isn't a valid JSON"
  packages/react-ui/src/components/simple-json-viewer.tsx
Labels: 🐛 bug

#9520 fix: dynamic properties with static dropdowns with many options were freezing the browser
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
Labels: 🐛 bug

#9523 feat: New translation files
  packages/pieces/community/microsoft-sharepoint/src/i18n/translation.json
  packages/pieces/community/wrike/src/i18n/translation.json
  packages/pieces/community/zoho-bookings/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9361 feat: allow the user to view retried runs when the user retries runs in the runs table
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
  packages/react-ui/src/app/builder/builder-hooks.ts
  packages/react-ui/src/app/builder/index.tsx
  packages/react-ui/src/app/builder/run-list/flow-run-card.tsx
  packages/react-ui/src/app/builder/run-list/index.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/flows/flows-table/index.tsx
  packages/react-ui/src/app/routes/flows/id/index.tsx
  packages/react-ui/src/app/routes/flows/issues-table/index.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/runs/mcp-run-utils.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/runs/mcp-runs.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/platform/security/audit-logs/index.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/app/routes/runs/id/index.tsx
  packages/react-ui/src/app/routes/settings/pieces/index.tsx
  packages/react-ui/src/app/routes/tables/index.tsx
  packages/react-ui/src/components/ui/data-table/data-table-filter.tsx
  packages/react-ui/src/components/ui/data-table/index.tsx
  packages/react-ui/src/features/flow-runs/components/run-details-bar.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/index.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/retried-runs-snackbar.tsx
  packages/react-ui/tailwind.config.js
  packages/server/api/src/app/file/s3-helper.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/shared/src/lib/flow-run/dto/list-flow-runs-request.ts
Labels: 🌟 feature, preview

#9525 New Crowdin updates
  packages/pieces/community/microsoft-sharepoint/package.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/de.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/es.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/fr.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/ja.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/nl.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/pt.json
  packages/pieces/community/microsoft-sharepoint/src/i18n/zh.json
  packages/pieces/community/wrike/package.json
  packages/pieces/community/wrike/src/i18n/de.json
  packages/pieces/community/wrike/src/i18n/es.json
  packages/pieces/community/wrike/src/i18n/fr.json
  packages/pieces/community/wrike/src/i18n/ja.json
  packages/pieces/community/wrike/src/i18n/nl.json
  packages/pieces/community/wrike/src/i18n/pt.json
  packages/pieces/community/wrike/src/i18n/zh.json
  packages/pieces/community/zoho-bookings/package.json
  packages/pieces/community/zoho-bookings/src/i18n/de.json
  packages/pieces/community/zoho-bookings/src/i18n/es.json
  packages/pieces/community/zoho-bookings/src/i18n/fr.json
  packages/pieces/community/zoho-bookings/src/i18n/ja.json
  packages/pieces/community/zoho-bookings/src/i18n/nl.json
  packages/pieces/community/zoho-bookings/src/i18n/pt.json
  packages/pieces/community/zoho-bookings/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9527 fix(datadog): fix incorrect application key header for custom api call action
  packages/pieces/community/datadog/package.json
  packages/pieces/community/datadog/src/lib/common.ts
Labels: 🔌 pieces, 💫 priority

#9531 feat: New translation files
  packages/pieces/community/sender/src/i18n/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh-TW/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9539 fix: db_type env var in docs
  docs/handbook/engineering/playbooks/database-migration.mdx
Labels: 📚 documentation

#9548 feat(socialkit): add piece
  packages/pieces/community/socialkit/.eslintrc.json
  packages/pieces/community/socialkit/README.md
  packages/pieces/community/socialkit/package.json
  packages/pieces/community/socialkit/project.json
  packages/pieces/community/socialkit/src/index.ts
  packages/pieces/community/socialkit/src/lib/actions/get-youtube-comment.ts
  packages/pieces/community/socialkit/src/lib/actions/get-youtube-details.ts
  packages/pieces/community/socialkit/src/lib/actions/get-youtube-summary.ts
  packages/pieces/community/socialkit/src/lib/actions/get-youtube-transcript.ts
  packages/pieces/community/socialkit/tsconfig.json
  packages/pieces/community/socialkit/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces

#9552 fix(netsuite): signature query params
  packages/pieces/community/netsuite/package.json
  packages/pieces/community/netsuite/src/index.ts
  packages/pieces/community/netsuite/src/lib/actions/get-customer.ts
  packages/pieces/community/netsuite/src/lib/actions/get-vendor.ts
  packages/pieces/community/netsuite/src/lib/oauth.ts
Labels: 💫 priority

#9547 chore(OTEL): add custom traces for webhook flows
  package-lock.json
  packages/pieces/community/common-ai/package.json
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/api/src/app/workers/consumer/index.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/api/src/instrumentation.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/server/worker/src/lib/api/ap-axios.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
  packages/server/worker/src/lib/flow-worker.ts
  packages/shared/src/lib/workers/job-data.ts
Labels: 🛠️ area/infrastructure

#9555 feat: release 0.70.3
  docker-compose.yml
  package.json
Labels: release

#9522 feat: insightly actions and triggers implementation
  packages/pieces/community/insightly/.eslintrc.json
  packages/pieces/community/insightly/README.md
  packages/pieces/community/insightly/package.json
  packages/pieces/community/insightly/project.json
  packages/pieces/community/insightly/src/index.ts
  packages/pieces/community/insightly/src/lib/actions/create-record.ts
  packages/pieces/community/insightly/src/lib/actions/delete-record.ts
  packages/pieces/community/insightly/src/lib/actions/find-records.ts
  packages/pieces/community/insightly/src/lib/actions/get-record.ts
  packages/pieces/community/insightly/src/lib/actions/update-record.ts
  packages/pieces/community/insightly/src/lib/common/common.ts
  packages/pieces/community/insightly/src/lib/common/props.ts
  packages/pieces/community/insightly/src/lib/triggers/deleted-record.ts
  packages/pieces/community/insightly/src/lib/triggers/new-record.ts
  packages/pieces/community/insightly/src/lib/triggers/updated-record.ts
  packages/pieces/community/insightly/tsconfig.json
  packages/pieces/community/insightly/tsconfig.lib.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces

#9566 New Crowdin updates
  packages/pieces/community/deepseek/package.json
  packages/pieces/community/deepseek/src/i18n/zh.json
  packages/pieces/community/delay/package.json
  packages/pieces/community/delay/src/i18n/zh.json
  packages/pieces/community/devin/package.json
  packages/pieces/community/devin/src/i18n/zh.json
  packages/pieces/community/dimo/package.json
  packages/pieces/community/dimo/src/i18n/zh.json
  packages/pieces/community/discord/package.json
  packages/pieces/community/discord/src/i18n/zh.json
  packages/pieces/community/discourse/package.json
  packages/pieces/community/discourse/src/i18n/zh.json
  packages/pieces/community/docusign/package.json
  packages/pieces/community/docusign/src/i18n/zh.json
  packages/pieces/community/drip/package.json
  packages/pieces/community/drip/src/i18n/zh.json
  packages/pieces/community/dropbox/package.json
  packages/pieces/community/dropbox/src/i18n/zh.json
  packages/pieces/community/dumpling-ai/package.json
  packages/pieces/community/dumpling-ai/src/i18n/zh.json
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/i18n/zh.json
  packages/pieces/community/eden-ai/package.json
  packages/pieces/community/eden-ai/src/i18n/zh.json
  packages/pieces/community/elevenlabs/package.json
  packages/pieces/community/elevenlabs/src/i18n/zh.json
  packages/pieces/community/eth-name-service/package.json
  packages/pieces/community/eth-name-service/src/i18n/zh.json
  packages/pieces/community/google-sheets/package.json
  packages/pieces/community/google-sheets/src/i18n/de.json
  packages/pieces/community/google-sheets/src/i18n/es.json
  packages/pieces/community/google-sheets/src/i18n/fr.json
  packages/pieces/community/google-sheets/src/i18n/ja.json
  packages/pieces/community/google-sheets/src/i18n/nl.json
  packages/pieces/community/google-sheets/src/i18n/pt.json
  packages/pieces/community/google-sheets/src/i18n/zh.json
  packages/pieces/community/socialkit/package.json
  packages/pieces/community/socialkit/src/i18n/de.json
  packages/pieces/community/socialkit/src/i18n/es.json
  packages/pieces/community/socialkit/src/i18n/fr.json
  packages/pieces/community/socialkit/src/i18n/ja.json
  packages/pieces/community/socialkit/src/i18n/nl.json
  packages/pieces/community/socialkit/src/i18n/pt.json
  packages/pieces/community/socialkit/src/i18n/zh.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog, auto-merge, translations

#9563 feat: release 0.70.4
  docker-compose.yml
  package.json
Labels: release

#9545 feat: extracta-ai actions and triggers
  packages/pieces/community/extracta-ai/.eslintrc.json
  packages/pieces/community/extracta-ai/README.md
  packages/pieces/community/extracta-ai/package.json
  packages/pieces/community/extracta-ai/project.json
  packages/pieces/community/extracta-ai/src/index.ts
  packages/pieces/community/extracta-ai/src/lib/actions/extract-file-data.ts
  packages/pieces/community/extracta-ai/src/lib/actions/get-extraction-results.ts
  packages/pieces/community/extracta-ai/src/lib/actions/upload-file.ts
  packages/pieces/community/extracta-ai/src/lib/common/auth.ts
  packages/pieces/community/extracta-ai/src/lib/common/index.ts
  packages/pieces/community/extracta-ai/src/lib/triggers/extraction-failed.ts
  packages/pieces/community/extracta-ai/src/lib/triggers/new-document-processed.ts
  packages/pieces/community/extracta-ai/tsconfig.json
  packages/pieces/community/extracta-ai/tsconfig.lib.json
Labels: 🔌 pieces, 🙋 Bounty claim, 🧩 area/third-party-pieces
