Repository activepieces/activepieces, pull requests merged in 2025-04, with the labels that each got.

#7272 feat(wedof): add 2 triggers events on certificationFolders
  packages/pieces/community/wedof/package.json
  packages/pieces/community/wedof/src/lib/common/wedof.ts
Labels: 🔌 pieces

#7278 fix: increase connection limit in ConnectionSelect component
  packages/react-ui/src/app/builder/step-settings/piece-settings/connection-select.tsx
Labels: 🐛 bug

#7279 fix: listing workers
  packages/server/api/src/app/workers/machine/machine-controller.ts
  packages/server/api/src/app/workers/machine/machine-service.ts
  packages/shared/src/lib/workers/index.ts
Labels: 🐛 bug

#7286 fix: build piece cli on windows
  packages/cli/src/lib/utils/piece-utils.ts
Labels: 🐛 bug

#7292 docs: update trigger timeout
  docs/install/configuration/environment-variables.mdx
Labels: 📚 documentation

#7298 fix(slack): fix request action response for published flow
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/common/request-action.ts
Labels: 🔌 pieces

#5935 fix(actualbudget): Update actual-app/api to latest
  package-lock.json
  package.json
  packages/pieces/community/actualbudget/package.json
  packages/pieces/community/actualbudget/src/lib/actions/import-transaction.ts
Labels: 🔌 pieces

#7316 fix: remove button wasn't showing for array inputs
  packages/react-ui/src/components/ui/array-input.tsx
Labels: 🐛 bug

#7313 feat(firecrawl): improve firecrawl and consolidate into scrape action
  packages/pieces/community/firecrawl/package.json
  packages/pieces/community/firecrawl/src/index.ts
  packages/pieces/community/firecrawl/src/lib/actions/crawl-results.ts
  packages/pieces/community/firecrawl/src/lib/actions/extract-with-prompt.ts
  packages/pieces/community/firecrawl/src/lib/actions/extract-with-schema.ts
  packages/pieces/community/firecrawl/src/lib/actions/scrape.ts
  packages/pieces/community/firecrawl/src/lib/actions/start-crawl.ts
Labels: 🔌 pieces

#7320 feat: be able to decide if the status option should continue flow or not
  packages/pieces/community/todos/package.json
  packages/pieces/community/todos/src/lib/actions/create-todo-and-wait.ts
  packages/pieces/community/todos/src/lib/utils/utils.ts
  packages/react-ui/src/app/routes/todos/id/index.tsx
  packages/react-ui/src/app/routes/todos/todo-details.tsx
  packages/server/api/src/app/todos/todo.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/todos/index.ts
Labels: 🌟 feature

#7227 fix(facebook-leads): fix payload response
  packages/pieces/community/facebook-leads/package.json
  packages/pieces/community/facebook-leads/src/lib/common/index.ts
  packages/pieces/community/facebook-leads/src/lib/triggers/new-lead.ts
Labels: 🔌 pieces

#7325 fix: loop item reference breaks if it has pause state inside
  .github/pull_request_template.md
  packages/engine/src/lib/handler/loop-executor.ts
  packages/engine/src/lib/handler/router-executor.ts
  packages/engine/test/handler/flow-with-pause.test.ts
Labels: 🐛 bug

#7326 feat: release 0.50.1
  docker-compose.yml
  package.json
Labels: release

#7324 feat(gslide): create from template, get presentation and refresh sheets charts actions
  packages/pieces/community/google-slides/package.json
  packages/pieces/community/google-slides/src/index.ts
  packages/pieces/community/google-slides/src/lib/actions/generate-from-template.ts
  packages/pieces/community/google-slides/src/lib/actions/get-presentation.ts
  packages/pieces/community/google-slides/src/lib/actions/refresh-charts.ts
  packages/pieces/community/google-slides/src/lib/commons/common.ts
Labels: 🔌 pieces

#7327 feat: import csv files as tables
  package-lock.json
  package.json
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/lib/common/index.ts
  packages/pieces/community/tables/src/lib/triggers/deleted-record.ts
  packages/pieces/community/tables/src/lib/triggers/new-record.ts
  packages/pieces/community/tables/src/lib/triggers/updated-record.ts
  packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/initial-data-guard.tsx
  packages/react-ui/src/app/components/loading-screen.tsx
  packages/react-ui/src/app/components/sidebar-invite-user.tsx
  packages/react-ui/src/app/components/sidebar-platform-admin.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/ap-tables/id/index.tsx
  packages/react-ui/src/app/routes/ap-tables/index.tsx
  packages/react-ui/src/app/routes/chat/index.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/app/routes/todos/id/index.tsx
  packages/react-ui/src/components/custom/beta-badge.tsx
  packages/react-ui/src/components/custom/markdown.tsx
  packages/react-ui/src/components/ui/copy-button.tsx
  packages/react-ui/src/components/ui/data-table/index.tsx
  packages/react-ui/src/components/ui/loading-screen.tsx
  packages/react-ui/src/features/tables/components/ap-table-footer.tsx
  packages/react-ui/src/features/tables/components/ap-table-header.tsx
  packages/react-ui/src/features/tables/components/ap-table-state-provider.tsx
  packages/react-ui/src/features/tables/components/export-csv-button.tsx
  packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
  packages/react-ui/src/features/tables/lib/records-api.ts
  packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx
  packages/react-ui/src/features/tables/lib/store/ap-tables-server-state.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1744187975994-AddRecordIndexForTableIdAndProjectIdAndRecordId.ts
  packages/server/api/src/app/database/migration/sqlite/1744104496262-AddRecordIndexForTableIdAndProjectIdAndRecordId.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flags/flag.service.ts
  packages/server/api/src/app/helper/system/system.ts
  packages/server/api/src/app/server.ts
  packages/server/api/src/app/tables/field/field.service.ts
  packages/server/api/src/app/tables/record/record.controller.ts
  packages/server/api/src/app/tables/record/record.entity.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/tables/table/table.controller.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/common/utils/utils.ts
  packages/shared/src/lib/flag/flag.ts
  packages/shared/src/lib/tables/dto/records.dto.ts
  packages/shared/src/lib/tables/dto/tables.dto.ts
Labels: 🌟 feature

#7330 feat(rounded-studio): add piece with custom api call action
  packages/pieces/community/rounded-studio/.eslintrc.json
  packages/pieces/community/rounded-studio/README.md
  packages/pieces/community/rounded-studio/package.json
  packages/pieces/community/rounded-studio/project.json
  packages/pieces/community/rounded-studio/src/index.ts
  packages/pieces/community/rounded-studio/tsconfig.json
  packages/pieces/community/rounded-studio/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7340 fix: should apply connections changes before flows to avoid auth validation error
  package-lock.json
  packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
Labels: 🐛 bug

#7341 fix: show project usage for enterprise edition in the sidebar
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/components/usage-limits-button.tsx
Labels: 🐛 bug

#7342 feat: release 0.50.2
  docker-compose.yml
  package-lock.json
  package.json
  packages/react-ui/src/features/tables/components/fields-mapping.tsx
  packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
  packages/react-ui/src/features/tables/lib/records-api.ts
  packages/react-ui/src/features/tables/lib/store/ap-tables-client-state.tsx
  packages/react-ui/src/features/tables/lib/utils.tsx
  packages/server/api/src/app/tables/record/record.controller.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/tables/dto/records.dto.ts
Labels: release

#7344 fix(docs): table limits env variables defaults
  docs/install/configuration/environment-variables.mdx
Labels: skip-changelog

#7338 chore(google-drive): fix typo
  packages/pieces/community/google-drive/package.json
  packages/pieces/community/google-drive/src/lib/common/get-file-content.ts
Labels: 🔌 pieces

#7343 feat(lusha): add pagination for the search #104
  packages/pieces/community/lusha/package.json
  packages/pieces/community/lusha/src/lib/actions/companies/search.ts
Labels: 🔌 pieces

#7333 feat: support mcp flows
  package-lock.json
  package.json
  packages/ee/shared/src/index.ts
  packages/ee/shared/src/lib/mcp/index.ts
  packages/pieces/community/mcp/.eslintrc.json
  packages/pieces/community/mcp/README.md
  packages/pieces/community/mcp/package.json
  packages/pieces/community/mcp/project.json
  packages/pieces/community/mcp/src/index.ts
  packages/pieces/community/mcp/src/lib/actions/reply-to-mcp-client.ts
  packages/pieces/community/mcp/src/lib/triggers/mcp-tool.ts
  packages/pieces/community/mcp/tsconfig.json
  packages/pieces/community/mcp/tsconfig.lib.json
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/mcp/index.tsx
  packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx
  packages/react-ui/src/app/routes/mcp/mcp-connection.tsx
  packages/react-ui/src/app/routes/mcp/mcp-flow-card.tsx
  packages/react-ui/src/app/routes/mcp/mcp-tools-section.tsx
  packages/react-ui/src/app/routes/mcp/mcp-url.tsx
  packages/react-ui/src/app/routes/settings/mcp/index.tsx
  packages/react-ui/src/app/routes/settings/mcp/mcp-connection.tsx
  packages/react-ui/src/app/routes/settings/mcp/mcp-instruction.tsx
  packages/react-ui/src/app/routes/settings/mcp/mcp-url.tsx
  packages/react-ui/src/components/ui/accordion.tsx
  packages/react-ui/src/features/mcp/mcp-api.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/mcp/mcp-controller.ts
  packages/server/api/src/app/mcp/mcp-entity.ts
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/lib/flows/dto/list-flows-request.ts
  packages/shared/src/lib/mcp/index.ts
  tsconfig.base.json
Labels: 🌟 feature

#7359 fix: hide request piece in piece selector when in embedding mode
  packages/react-ui/src/app/builder/pieces-selector/pieces-card-list.tsx
Labels: 🐛 bug

#7360 fix: hide platform admins when listing connection owners in embedding
  packages/react-ui/src/features/connections/lib/app-connections-hooks.ts
Labels: 🐛 bug

#7362 fix: add actions button inside table to make it easier to know how to delete records
  packages/react-ui/src/app/components/sidebar-platform-admin.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/routes/ap-tables/id/index.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/components/ui/copy-text-tooltip.tsx
  packages/react-ui/src/features/tables/components/ap-table-header.tsx
  packages/react-ui/src/features/tables/components/export-csv-button.tsx
  packages/react-ui/src/features/tables/lib/utils.tsx
Labels: ✨ polishing

#7323 fix: type in the code
  packages/react-ui/src/app/builder/data-selector/data-selector-node.tsx
  packages/react-ui/src/app/builder/data-selector/data-selector-size-togglers.tsx
  packages/react-ui/src/app/builder/pieces-selector/ask-ai.tsx
Labels: 🧹 clean up

#7358 fix: enhance nx pipeline by adding cache
  nx.json
Labels: 🧹 clean up

#7377 fix: delete env variable for show changelog
  docs/install/configuration/environment-variables.mdx
  packages/server/api/src/app/flags/flag.service.ts
Labels: 🧹 clean up

#7380 feat: add gpt 4.1 models
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/utility-ai/package.json
Labels: 🔌 pieces

#7392 fix: exporting tables in utf-8 format
  packages/react-ui/src/features/tables/components/ap-table-header.tsx
  packages/react-ui/src/lib/utils.ts
Labels: 🐛 bug

#7393 fix(cli): resolve path to piece build folder correctly
  packages/cli/src/lib/commands/publish-piece.ts
  packages/cli/src/lib/utils/piece-utils.ts
Labels: 🐛 bug

#7383 fix(onedrive): fix parent folder dropdown
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/lib/common/common.ts
Labels: 🔌 pieces

#7308 feat: flows, connections and projects all now can have metadata in them
  packages/ee/shared/package.json
  packages/ee/shared/src/lib/flow-templates/index.ts
  packages/ee/shared/src/lib/project/project-requests.ts
  packages/react-ui/src/app/routes/platform/setup/templates/upsert-template-dialog.tsx
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection.controller.ts
  packages/server/api/src/app/app-connection/app-connection.entity.ts
  packages/server/api/src/app/database/migration/postgres/1743780156664-AddMetadataFields.ts
  packages/server/api/src/app/database/migration/sqlite/1743780156664-AddMetadataFields.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/flow-template/flow-template.entity.ts
  packages/server/api/src/app/ee/flow-template/flow-template.service.ts
  packages/server/api/src/app/ee/flow-template/platform-flow-template.module.ts
  packages/server/api/src/app/ee/projects/platform-project-controller.ts
  packages/server/api/src/app/flows/flow/flow.entity.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/project/project-entity.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/ce/flows/flow.test.ts
  packages/server/api/test/integration/cloud/app-connection/app-connection.test.ts
  packages/server/api/test/integration/cloud/flow-templates/flow-templates.test.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/app-connection/app-connection.ts
  packages/shared/src/lib/app-connection/dto/upsert-app-connection-request.ts
  packages/shared/src/lib/common/index.ts
  packages/shared/src/lib/common/metadata.ts
  packages/shared/src/lib/flows/dto/create-flow-request.ts
  packages/shared/src/lib/flows/dto/flow-template-request.ts
  packages/shared/src/lib/flows/flow.ts
  packages/shared/src/lib/project/project.ts
Labels: 🌟 feature

#7397 chore: npm audit fix
  package-lock.json
Labels: 🧹 clean up

#7396 chore: 0.50.4 release
  Dockerfile
  docker-compose.yml
  nx.json
  package-lock.json
  package.json
Labels: release

#7404 feat: added action to get run id during the run
  package-lock.json
  packages/pieces/community/flow-helper/.eslintrc.json
  packages/pieces/community/flow-helper/README.md
  packages/pieces/community/flow-helper/package.json
  packages/pieces/community/flow-helper/project.json
  packages/pieces/community/flow-helper/src/index.ts
  packages/pieces/community/flow-helper/src/lib/actions/get-run-id.ts
  packages/pieces/community/flow-helper/tsconfig.json
  packages/pieces/community/flow-helper/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7406 fix: better names for flow-helper piece
  packages/pieces/community/flow-helper/src/index.ts
  packages/pieces/community/flow-helper/src/lib/actions/get-run-id.ts
Labels: skip-changelog

#7407 chore: bump piece version for flow-helper
  packages/pieces/community/flow-helper/package.json
Labels: skip-changelog

#7418 fix: updating/adding flow templates was broken
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/database/migrations/postgres/1744780800000-AddMetadataFieldToFlowTemplates.ts
Labels: 🐛 bug

#7411 feat: add mcp pieces
  docs/embedding/embed-builder.mdx
  docs/embedding/mcps.mdx
  docs/embedding/sdk-server-requests.mdx
  docs/endpoints/mcp-pieces/add.mdx
  docs/endpoints/mcp-pieces/delete.mdx
  docs/endpoints/mcp-pieces/list.mdx
  docs/endpoints/mcp-pieces/schema.mdx
  docs/endpoints/mcp-pieces/update.mdx
  docs/endpoints/mcp-servers/list.mdx
  docs/endpoints/mcp-servers/rotate.mdx
  docs/endpoints/mcp-servers/schema.mdx
  docs/endpoints/mcp-servers/update.mdx
  docs/endpoints/mcp/delete.mdx
  docs/endpoints/mcp/get.mdx
  docs/endpoints/mcp/rotate.mdx
  docs/endpoints/mcp/schema.mdx
  docs/endpoints/mcp/update.mdx
  docs/mint.json
  docs/openapi.json
  packages/ee/ui/embed-sdk/src/index.ts
  packages/pieces/community/mcp/package.json
  packages/pieces/community/mcp/src/lib/triggers/mcp-tool.ts
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-flow-card.tsx
  packages/react-ui/src/app/mcp/mcp-piece-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-piece.tsx
  packages/react-ui/src/app/mcp/mcp-tools-section.tsx
  packages/react-ui/src/app/mcp/mcp-url.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/mcp/index.tsx
  packages/react-ui/src/app/routes/mcp/mcp-connection.tsx
  packages/react-ui/src/components/custom/searchable-select.tsx
  packages/react-ui/src/features/mcp/lib/mcp-api.ts
  packages/react-ui/src/features/mcp/lib/mcp-hooks.ts
  packages/react-ui/src/features/mcp/mcp-api.ts
  packages/server/api/src/app/app-connection/app-connection.entity.ts
  packages/server/api/src/app/app.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1744822233873-AddMcpPiece.ts
  packages/server/api/src/app/database/migration/sqlite/1744822233873-AddMcpPieceSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/helper/error-handler.ts
  packages/server/api/src/app/mcp/mcp-entity.ts
  packages/server/api/src/app/mcp/mcp-module.ts
  packages/server/api/src/app/mcp/mcp-piece-controller.ts
  packages/server/api/src/app/mcp/mcp-piece-entity.ts
  packages/server/api/src/app/mcp/mcp-piece-service.ts
  packages/server/api/src/app/mcp/mcp-server-controller.ts
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/mcp/dto/mcp.dto.ts
  packages/shared/src/lib/mcp/index.ts
  packages/shared/src/lib/mcp/mcp.ts
Labels: 🌟 feature

#7421 feat: bump release version 0.50.5
  docker-compose.yml
  package.json
Labels: release

#7425 fix: clickup auth url
  package-lock.json
  packages/pieces/community/clickup/package.json
  packages/pieces/community/clickup/src/index.ts
Labels: 🐛 bug

#7428 feat: include 2.5-flash model in models dropdown
  packages/pieces/community/google-gemini/package.json
  packages/pieces/community/google-gemini/src/lib/common/common.ts
Labels: 🔌 pieces

#7429 fix: mcp timeout
  packages/server/api/src/app/mcp/mcp-sse-controller.ts
Labels: 🐛 bug

#7431 fix: disable caching for MCP endpoints only
  nginx.react.conf
Labels: ✨ polishing

#7433 fix: disable buffering and caching for MCP SSE controller only
  nginx.react.conf
Labels: ✨ polishing

#7420 feat(metabase): new action get graph
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/index.ts
  packages/pieces/community/metabase/src/lib/actions/get-graph-question.ts
Labels: 🔌 pieces

#7438 fix: update mcp tool name to match regex
  packages/server/api/src/app/mcp/mcp-server.ts
Labels: 🐛 bug

#7440 fix: make a database migration to fix type of positive variant name
  packages/pieces/community/todos/package.json
  packages/server/api/src/app/database/migration/postgres/1745272231418-RenameTodoPostiveVariantName.ts
  packages/server/api/src/app/database/migration/sqlite/1745269828603-RenameTodoVariantName.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
Labels: 🐛 bug

#7424 feat(mongodb): CRUD document actions
  package-lock.json
  package.json
  packages/pieces/community/mongodb/.eslintrc.json
  packages/pieces/community/mongodb/README.md
  packages/pieces/community/mongodb/package-lock.json
  packages/pieces/community/mongodb/package.json
  packages/pieces/community/mongodb/project.json
  packages/pieces/community/mongodb/src/index.ts
  packages/pieces/community/mongodb/src/lib/actions.ts
  packages/pieces/community/mongodb/src/lib/actions/aggregate-documents.ts
  packages/pieces/community/mongodb/src/lib/actions/delete-documents.ts
  packages/pieces/community/mongodb/src/lib/actions/find-and-replace-documents.ts
  packages/pieces/community/mongodb/src/lib/actions/find-and-update-documents.ts
  packages/pieces/community/mongodb/src/lib/actions/find-documents.ts
  packages/pieces/community/mongodb/src/lib/actions/insert-documents.ts
  packages/pieces/community/mongodb/src/lib/actions/update-documents.ts
  packages/pieces/community/mongodb/src/lib/common/index.ts
  packages/pieces/community/mongodb/tsconfig.json
  packages/pieces/community/mongodb/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7444 fix(onedrive): add limit for parent folder dropdown
  packages/pieces/community/microsoft-onedrive/package.json
  packages/pieces/community/microsoft-onedrive/src/lib/actions/list-files.ts
  packages/pieces/community/microsoft-onedrive/src/lib/actions/list-folders.ts
  packages/pieces/community/microsoft-onedrive/src/lib/actions/upload-file.ts
  packages/pieces/community/microsoft-onedrive/src/lib/common/common.ts
  packages/pieces/community/microsoft-onedrive/src/lib/triggers/new-file.ts
Labels: 🔌 pieces

#7441 fix: polishing mcp info
  docs/embedding/mcps.mdx
  packages/pieces/community/mcp/package.json
  packages/pieces/community/mcp/src/lib/triggers/mcp-tool.ts
  packages/react-ui/src/app/mcp/mcp-flow-card.tsx
  packages/react-ui/src/app/mcp/mcp-piece-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-piece.tsx
  packages/react-ui/src/app/mcp/mcp-tools-section.tsx
  packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx
  packages/react-ui/src/components/simple-json-viewer.tsx
Labels: ✨ polishing

#7450 feat: release v0.50.6
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7451 fix: mcp connection required condition
  packages/react-ui/src/app/mcp/mcp-piece.tsx
Labels: 🐛 bug

#7453 fix: update changelog fetching to 5 minutes instead of 1 day
  packages/server/api/src/app/changelog/changelog.service.ts
Labels: ✨ polishing

#7473 chore: bump release version
  docker-compose.yml
  package.json
Labels: release

#7477 fix: stop logging axios errors fully in invalid oauth2 calim failure
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
Labels: 🐛 bug

#7445 chore: introduce connections manager to triggers hooks
  packages/engine/package.json
  packages/engine/src/lib/handler/piece-executor.ts
  packages/engine/src/lib/helper/trigger-helper.ts
  packages/engine/src/lib/utils.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/server/worker/package.json
Labels: 🛠️ piece-framework

#7479 feat: release 0.50.8
  docker-compose.yml
  package.json
Labels: release

#7480 fix: only clean up after exit
  packages/server/worker/src/lib/engine/threads/worker.ts
Labels: 🐛 bug

#7481 feat: release 0.50.9
  docker-compose.yml
  package.json
Labels: release

#7493 fix: missing images in README.md
  README.md
Labels: 🐛 bug

#7499 fix: add missing resolve when internal error happens in the flow
  packages/server/worker/src/lib/engine/threads/worker.ts
Labels: 🐛 bug

#7500 feat: release 0.50.10
  docker-compose.yml
  package.json
Labels: release

#7469 feat: support mcp permissions
  packages/ee/shared/src/lib/authn/access-control-list.ts
  packages/react-ui/src/app/mcp/mcp-piece.tsx
  packages/react-ui/src/app/mcp/mcp-tools-section.tsx
  packages/react-ui/src/app/routes/mcp/index.tsx
  packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx
  packages/react-ui/src/app/routes/platform/security/project-role/project-role-dialog.tsx
  packages/server/api/src/app/mcp/mcp-piece-controller.ts
  packages/server/api/src/app/mcp/mcp-server-controller.ts
Labels: 🌟 feature

#7449 fix: remove You from all contributors and add s31w4n as contributor f…
  .all-contributorsrc
  README.md
Labels: 📚 documentation

#7461 feat(returning-ai): add reply message action
  packages/pieces/community/returning-ai/package.json
  packages/pieces/community/returning-ai/src/index.ts
  packages/pieces/community/returning-ai/src/lib/actions/reply-message.ts
  packages/pieces/community/returning-ai/src/lib/actions/send-message.ts
  packages/pieces/community/returning-ai/src/lib/common/index.ts
Labels: 🔌 pieces

#7430 feat: enhance async and refactor webhook handler
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
Labels: ✨ polishing

#7419 feat: add caching for populated flow and enhance async webhook request
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
Labels: ✨ polishing

#7508 feat: release 0.50.11
  docker-compose.yml
  package.json
Labels: release

#7509 feat: enhance flow execution with new payload handling and format option
  packages/engine/src/lib/operations.ts
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/shared/src/lib/engine/engine-operation.ts
Labels: 🐛 bug

#7510 feat: release 0.50.12
  docker-compose.yml
  package.json
Labels: release

#7494 feat(straico): add file upload, update image generation, update prompt completion
  packages/pieces/community/straico/package.json
  packages/pieces/community/straico/src/index.ts
  packages/pieces/community/straico/src/lib/actions/file-upload.ts
  packages/pieces/community/straico/src/lib/actions/image-generation.ts
  packages/pieces/community/straico/src/lib/actions/prompt-completion.ts
  packages/pieces/community/straico/src/lib/common/common.ts
Labels: 🔌 pieces

#7511 feat(backblaze): upload file, read file actions and new file trigger
  packages/pieces/community/backblaze/.eslintrc.json
  packages/pieces/community/backblaze/README.md
  packages/pieces/community/backblaze/package.json
  packages/pieces/community/backblaze/project.json
  packages/pieces/community/backblaze/src/index.ts
  packages/pieces/community/backblaze/src/lib/actions/read-file.ts
  packages/pieces/community/backblaze/src/lib/actions/upload-file.ts
  packages/pieces/community/backblaze/src/lib/common.ts
  packages/pieces/community/backblaze/src/lib/triggers/new-file.ts
  packages/pieces/community/backblaze/tsconfig.json
  packages/pieces/community/backblaze/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7487 fix(slack): fix trigger for private channel
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/lib/triggers/new-command.ts
  packages/pieces/community/slack/src/lib/triggers/new-mention.ts
  packages/pieces/community/slack/src/lib/triggers/new-message-in-channel.ts
  packages/pieces/community/slack/src/lib/triggers/new-message.ts
Labels: 🔌 pieces

#7516 fix: login using Google without popup
  package-lock.json
  packages/engine/src/lib/operations.ts
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/components/allow-logged-in-user-only-guard.tsx
  packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/components/sidebar-invite-user.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/ap-tables/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/platform/billing/index.tsx
  packages/react-ui/src/app/routes/redirect.tsx
  packages/react-ui/src/app/routes/runs/issues/issues-table.tsx
  packages/react-ui/src/app/routes/settings/appearance/language-switcher.tsx
  packages/react-ui/src/features/authentication/components/auth-form-template.tsx
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
  packages/react-ui/src/features/authentication/components/sign-up-form.tsx
  packages/react-ui/src/features/authentication/components/third-party-logins.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table.tsx
  packages/react-ui/src/features/flows/components/share-template-dialog.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/react-ui/src/lib/navigation-utils.tsx
  packages/react-ui/src/lib/oauth2-utils.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/worker/src/lib/engine/threads/worker.ts
Labels: 🐛 bug

#7519 fix: show resend verification email if user signs in with unverified email
  packages/react-ui/src/features/authentication/components/auth-form-template.tsx
  packages/react-ui/src/features/authentication/components/check-email-note.tsx
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
  packages/react-ui/src/features/authentication/components/verify-email.tsx
Labels: 🐛 bug

#7518 feat(dust): upload file piece
  package-lock.json
  package.json
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/actions/upload-file.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#7523 feat(straico): add RAG actions and API integration for Straico
  package-lock.json
  packages/pieces/community/dust/package.json
  packages/pieces/community/straico/package.json
  packages/pieces/community/straico/src/index.ts
  packages/pieces/community/straico/src/lib/actions/rag-create.ts
  packages/pieces/community/straico/src/lib/actions/rag-delete.ts
  packages/pieces/community/straico/src/lib/actions/rag-get-by-id.ts
  packages/pieces/community/straico/src/lib/actions/rag-list.ts
  packages/pieces/community/straico/src/lib/actions/rag-prompt-completion.ts
  packages/pieces/community/straico/src/lib/actions/rag-update.ts
Labels: 🔌 pieces

#7514 feat(Gslide): generate from template new props placeholder
  packages/pieces/community/google-slides/package.json
  packages/pieces/community/google-slides/src/lib/actions/generate-from-template.ts
  packages/pieces/community/google-slides/src/lib/commons/common.ts
Labels: 🔌 pieces

#7482 feat: add a new flow operation to update metadata
  packages/ee/shared/src/lib/audit-events/index.ts
  packages/server/api/src/app/ee/authentication/project-role/rbac-middleware.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/test/integration/ce/flows/flow.test.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/flows/operations/index.ts
Labels: 🌟 feature
