Repository activepieces/activepieces, pull requests merged in 2025-05, with the labels that each got.

#7529 feat(straico): add new agent actions
  packages/pieces/community/straico/package.json
  packages/pieces/community/straico/src/index.ts
  packages/pieces/community/straico/src/lib/actions/agent-add-rag.ts
  packages/pieces/community/straico/src/lib/actions/agent-create.ts
  packages/pieces/community/straico/src/lib/actions/agent-delete.ts
  packages/pieces/community/straico/src/lib/actions/agent-get.ts
  packages/pieces/community/straico/src/lib/actions/agent-list.ts
  packages/pieces/community/straico/src/lib/actions/agent-prompt-completion.ts
  packages/pieces/community/straico/src/lib/actions/agent-update.ts
  packages/pieces/community/straico/src/lib/common/props.ts
Labels: 🔌 pieces

#7521 fix: mcp testing trigger
  packages/pieces/community/mcp/package.json
  packages/pieces/community/mcp/src/index.ts
  packages/pieces/community/mcp/src/lib/actions/reply-to-mcp-client.ts
  packages/pieces/community/mcp/src/lib/triggers/mcp-tool.ts
  packages/react-ui/src/app/builder/piece-properties/auto-form-field-wrapper.tsx
  packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx
  packages/react-ui/src/app/builder/step-settings/code-settings/add-npm-dialog.tsx
  packages/react-ui/src/app/builder/test-step/custom-test-step/mcp-tool-testing-dialog.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/app/connections/new-connection-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-piece-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-piece.tsx
  packages/react-ui/src/app/routes/platform/setup/license-key/activate-license-dialog.tsx
  packages/react-ui/src/features/team/component/invite-user-dialog.tsx
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/mcp/mcp.ts
Labels: 🐛 bug

#7544 feat: wait for next webhook and improve testing webhooks experience
  packages/engine/package.json
  packages/engine/src/lib/handler/piece-executor.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/context.ts
  packages/pieces/community/mcp/package.json
  packages/pieces/community/mcp/src/index.ts
  packages/pieces/community/webhook/package.json
  packages/pieces/community/webhook/src/index.ts
  packages/pieces/community/webhook/src/lib/actions/return-response-and-wait-for-next-webhook.ts
  packages/pieces/community/webhook/src/lib/actions/return-response.ts
  packages/react-ui/src/app/builder/piece-properties/dictionary-property.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-tag-group.tsx
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/react-ui/src/app/builder/test-step/custom-test-step/mcp-tool-testing-dialog.tsx
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-todo-dialog.tsx
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-webhook-dialog.tsx
  packages/react-ui/src/app/builder/test-step/test-action-section.tsx
  packages/react-ui/src/app/builder/test-step/test-sample-data-viewer.tsx
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/components/custom/copy-to-clipboard.tsx
  packages/react-ui/src/features/pieces/lib/pieces-api.ts
  packages/react-ui/src/features/pieces/lib/types.ts
  packages/react-ui/src/lib/api.ts
  packages/server/api/src/app/flows/flow-run/flow-run-controller.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: 🌟 feature

#7550 feat(text-ai): add reasoning models
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/ai/providers/openai/index.ts
  packages/pieces/community/text-ai/package.json
  packages/pieces/community/utility-ai/package.json
Labels: 🔌 pieces

#7526 fix(apitable): fix API baseurl
  packages/pieces/community/apitable/package.json
  packages/pieces/community/apitable/src/index.ts
Labels: 🔌 pieces

#7437 feat(store): bulk add items in list
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/lib/actions/store-add-to-list.ts
Labels: 🔌 pieces

#7541 fix(connection): add flows count column, improve delete confirmation dialog
  packages/react-ui/src/app/connections/flows-connection-dialog.tsx
  packages/react-ui/src/app/connections/replace-connections-dialog.tsx
  packages/react-ui/src/app/routes/connections/index.tsx
  packages/react-ui/src/app/routes/platform/setup/connections/index.tsx
  packages/react-ui/src/features/connections/components/edit-global-connection-dialog.tsx
  packages/react-ui/src/features/connections/components/rename-connection-dialog.tsx
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/app-connection/app-connection.ts
Labels: ✨ polishing

#7504 feat: introduce tables releases
  packages/ee/shared/src/lib/git-repo/index.ts
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/ap-tables/index.tsx
  packages/react-ui/src/app/routes/project-release/apply-plan.tsx
  packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx
  packages/react-ui/src/app/routes/project-release/selection-release-dialog/project-dialog.tsx
  packages/react-ui/src/features/flows/lib/use-flows-bulk-actions.tsx
  packages/react-ui/src/features/git-sync/components/push-to-git-dialog.tsx
  packages/react-ui/src/features/tables/components/ap-table-actions-menu.tsx
  packages/server/api/src/app/database/migration/postgres/1746356907629-AddExternalIdForTablesAndFields.ts
  packages/server/api/src/app/database/migration/sqlite/1746367601605-AddExternalIdForTablesAndFieldsSQLITE.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/project-release/git-sync/git-helper.ts
  packages/server/api/src/app/ee/project-release/git-sync/git-sync-helper.ts
  packages/server/api/src/app/ee/project-release/git-sync/git-sync.service.ts
  packages/server/api/src/app/ee/project-release/project-release.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/tables/field/field.entity.ts
  packages/server/api/src/app/tables/field/field.service.ts
  packages/server/api/src/app/tables/table/table.controller.ts
  packages/server/api/src/app/tables/table/table.entity.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/project-release/project-state.ts
  packages/shared/src/lib/tables/dto/fields.dto.ts
  packages/shared/src/lib/tables/dto/tables.dto.ts
  packages/shared/src/lib/tables/field.ts
  packages/shared/src/lib/tables/table.ts
Labels: 🌟 feature

#7557 feat: release 0.52.0
  docker-compose.yml
  package.json
Labels: release

#7560 feat: release 0.52.1
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7564 fix: show localhost for mcp server url if no public instance url is set
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/mcp/index.tsx
  packages/react-ui/src/app/routes/mcp/mcp-client-tabs.tsx
Labels: 🐛 bug

#7562 fix: improve worker management and error handling
  packages/server/worker/src/lib/engine/threads/worker.ts
Labels: 🐛 bug

#7578 fix: naming of indices for mcp piece entity
  packages/server/api/src/app/database/migration/postgres/1746543299109-ChangeMcpPieceForeignKey.ts
  packages/server/api/src/app/database/migration/sqlite/1746543346220-ChangeMcpPieceForeignKey.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/mcp/mcp-piece-entity.ts
  packages/server/api/src/app/tables/field/field.entity.ts
Labels: 🐛 bug

#7501 feat(jina-ai): add jina-ai piece
  packages/pieces/community/jina-ai/.eslintrc.json
  packages/pieces/community/jina-ai/README.md
  packages/pieces/community/jina-ai/package.json
  packages/pieces/community/jina-ai/project.json
  packages/pieces/community/jina-ai/src/index.ts
  packages/pieces/community/jina-ai/src/lib/actions/classify-content.ts
  packages/pieces/community/jina-ai/src/lib/actions/deepsearch-query.ts
  packages/pieces/community/jina-ai/src/lib/actions/extract-webpage-content.ts
  packages/pieces/community/jina-ai/src/lib/actions/index.ts
  packages/pieces/community/jina-ai/src/lib/actions/train-custom-classifier.ts
  packages/pieces/community/jina-ai/src/lib/actions/web-search-summarization.ts
  packages/pieces/community/jina-ai/src/lib/common/index.ts
  packages/pieces/community/jina-ai/tsconfig.json
  packages/pieces/community/jina-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#7551 feat(dust): add support for EU region
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/index.ts
  packages/pieces/community/dust/src/lib/actions/add-fragment-to-conversation.ts
  packages/pieces/community/dust/src/lib/actions/create-conversation.ts
  packages/pieces/community/dust/src/lib/actions/get-conversation.ts
  packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
  packages/pieces/community/dust/src/lib/actions/upsert-document.ts
  packages/pieces/community/dust/src/lib/common.ts
Labels: 🔌 pieces

#7555 feat(twin-labs): new API url and new polling process
  packages/pieces/community/twin-labs/package.json
  packages/pieces/community/twin-labs/src/lib/actions/start-browsing-task.ts
Labels: 🔌 pieces

#7559 feat(google-docs): add placeholder format choice for edit action
  packages/pieces/community/google-docs/package.json
  packages/pieces/community/google-docs/src/index.ts
  packages/pieces/community/google-docs/src/lib/actions/create-document-based-on-template.action.ts
Labels: 🔌 pieces

#7583 fix: update flows on connection merge without republish
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/lib/actions/reply-to-conversation.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection.handler.ts
  packages/server/api/src/app/flows/flow-version/flow-version.service.ts
Labels: 🐛 bug

#7525 feat(netsuite): get vendor and get customer actions
  packages/pieces/community/netsuite/.eslintrc.json
  packages/pieces/community/netsuite/README.md
  packages/pieces/community/netsuite/package.json
  packages/pieces/community/netsuite/project.json
  packages/pieces/community/netsuite/src/index.ts
  packages/pieces/community/netsuite/src/lib/actions/get-customer.ts
  packages/pieces/community/netsuite/src/lib/actions/get-vendor.ts
  packages/pieces/community/netsuite/src/lib/oauth.ts
  packages/pieces/community/netsuite/tsconfig.json
  packages/pieces/community/netsuite/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7594 refactor: simplify app connection replacement
  packages/server/api/src/app/app-connection/app-connection-service/app-connection.handler.ts
Labels: 🧹 clean up

#7596 feat: release v0.52.3
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7585 feat: revamp flows + folders
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
  packages/react-ui/src/components/ui/data-table/index.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/columns.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/index.tsx
  packages/react-ui/src/features/flows/components/flows-table/columns.tsx
  packages/react-ui/src/features/flows/components/flows-table/index.tsx
  packages/react-ui/src/features/folders/component/create-folder-dialog.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/react-ui/src/features/folders/component/rename-folder-dialog.tsx
  packages/react-ui/src/features/issues/components/issues-table/columns.tsx
  packages/react-ui/src/features/issues/components/issues-table/index.tsx
Labels: 🌟 feature

#7614 fix: search by name and connection ids
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#7615 refactor: clean up imports and improve formatting
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/flows-table/columns.tsx
  packages/react-ui/src/app/routes/flows/flows-table/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/flows/issues-table/columns.tsx
  packages/react-ui/src/app/routes/flows/issues-table/index.tsx
  packages/react-ui/src/components/ui/data-table/index.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/columns.tsx
  packages/react-ui/src/features/flow-runs/components/runs-table/index.tsx
  packages/react-ui/src/features/folders/component/create-folder-dialog.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/react-ui/src/features/folders/component/rename-folder-dialog.tsx
Labels: 🧹 clean up

#7617 feat: add externalId column to temporary_table migration for SQLite
  packages/server/api/src/app/database/migration/sqlite/1746367601605-AddExternalIdForTablesAndFieldsSQLITE.ts
Labels: 🐛 bug

#7619 fix: project releases icon in sidebar
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/server/api/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#7618 feat: release v0.52.4
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7620 fix: array contains in postgres
  packages/server/api/src/app/database/database-connection.ts
Labels: 🐛 bug

#7623 feat: release v0.52.5
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7580 feat: add dappier piece
  packages/pieces/community/dappier/.eslintrc.json
  packages/pieces/community/dappier/README.md
  packages/pieces/community/dappier/package.json
  packages/pieces/community/dappier/project.json
  packages/pieces/community/dappier/src/index.ts
  packages/pieces/community/dappier/src/lib/actions/lifestyle-news.ts
  packages/pieces/community/dappier/src/lib/actions/real-time-data.ts
  packages/pieces/community/dappier/src/lib/actions/sports-news.ts
  packages/pieces/community/dappier/src/lib/actions/stock-market-data.ts
  packages/pieces/community/dappier/src/lib/common/index.ts
  packages/pieces/community/dappier/tsconfig.json
  packages/pieces/community/dappier/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7627 Revert "revert: "feat: flow table actions issue""
  packages/react-ui/src/app/routes/flows/flows-table/columns.tsx
  packages/react-ui/src/app/routes/flows/flows-table/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
Labels: skip-changelog

#7628 fix: added rerouting to the new runs page when browser navigates to /runs
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
Labels: 🐛 bug

#7567 feat(microsoft-todo): 6 actions and 2 triggers
  packages/pieces/community/microsoft-todo/.eslintrc.json
  packages/pieces/community/microsoft-todo/README.md
  packages/pieces/community/microsoft-todo/package.json
  packages/pieces/community/microsoft-todo/project.json
  packages/pieces/community/microsoft-todo/src/index.ts
  packages/pieces/community/microsoft-todo/src/lib/actions/create-task-list.ts
  packages/pieces/community/microsoft-todo/src/lib/actions/create-task.ts
  packages/pieces/community/microsoft-todo/src/lib/actions/find-task-by-title.ts
  packages/pieces/community/microsoft-todo/src/lib/actions/find-task-list-by-name.ts
  packages/pieces/community/microsoft-todo/src/lib/actions/update-task.ts
  packages/pieces/community/microsoft-todo/src/lib/common/index.ts
  packages/pieces/community/microsoft-todo/src/lib/triggers/new-task-created.ts
  packages/pieces/community/microsoft-todo/src/lib/triggers/task-completed.ts
  packages/pieces/community/microsoft-todo/src/lib/triggers/task-updated.ts
  packages/pieces/community/microsoft-todo/tsconfig.json
  packages/pieces/community/microsoft-todo/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#7632 refactor: remove FlowsRunsPageReroute and update FlowsPage routing logic
  packages/react-ui/src/app/components/dashboard-container.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/app/routes/runs/index.tsx
Labels: 🐛 bug

#7577 feat: DumplingAI Piece
  packages/pieces/community/dumpling-ai/.eslintrc.json
  packages/pieces/community/dumpling-ai/README.md
  packages/pieces/community/dumpling-ai/package.json
  packages/pieces/community/dumpling-ai/project.json
  packages/pieces/community/dumpling-ai/src/index.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/crawl-website.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/extract-document.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/generate-image.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/index.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/scrape-website.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/search-news.ts
  packages/pieces/community/dumpling-ai/src/lib/actions/web-search.ts
  packages/pieces/community/dumpling-ai/tsconfig.json
  packages/pieces/community/dumpling-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#7651 feat: skip cache for flow version when polling
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
Labels: 🐛 bug

#7656 refactor: fix webhook handshake & optmize webhooks
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/trigger/trigger.ts
  packages/server/api/src/app/app-event-routing/app-event-routing.module.ts
  packages/server/api/src/app/database/migration/postgres/1746848208563-AddHandshakeConfigurationToFlow.ts
  packages/server/api/src/app/database/migration/sqlite/1746845932780-AddHandshakeConfigurationToFlowSqlite.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/pieces/admin-piece-requests.ee.ts
  packages/server/api/src/app/flows/flow/flow-service-side-effects.ts
  packages/server/api/src/app/flows/flow/flow.entity.ts
  packages/server/api/src/app/flows/flow/flow.service.ts
  packages/server/api/src/app/flows/trigger/hooks/enable-trigger-hook.ts
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/webhooks/handshake-handler.ts
  packages/server/api/src/app/webhooks/webhook-controller.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/server/worker/src/lib/executors/repeating-job-executor.ts
  packages/server/worker/src/lib/executors/user-interaction-job-executor.ts
  packages/server/worker/src/lib/executors/webhook-job-executor.ts
  packages/server/worker/src/lib/trigger/hooks/handshake-trigger.hook.ts
  packages/server/worker/src/lib/trigger/hooks/trigger-consumer.ts
  packages/server/worker/src/lib/utils/webhook-utils.ts
  packages/shared/src/lib/engine/engine-operation.ts
  packages/shared/src/lib/engine/requests.ts
  packages/shared/src/lib/flows/flow.ts
Labels: 🐛 bug

#7657 fix: handshake and flow is disabled / onfleet imports
  packages/pieces/community/framework/src/index.ts
  packages/pieces/community/onfleet/src/lib/triggers/auto-dispatch-completed.ts
  packages/pieces/community/onfleet/src/lib/triggers/sms-recipient-opt-out.ts
  packages/pieces/community/onfleet/src/lib/triggers/sms-recipient-response-missed.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-arrival.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-assigned.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-cloned.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-completed.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-created.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-delayed.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-deleted.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-eta.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-failed.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-started.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-unassigned.ts
  packages/pieces/community/onfleet/src/lib/triggers/task-updated.ts
  packages/pieces/community/onfleet/src/lib/triggers/worker-created.ts
  packages/pieces/community/onfleet/src/lib/triggers/worker-deleted.ts
  packages/pieces/community/onfleet/src/lib/triggers/worker-duty-change.ts
  packages/pieces/community/quickzu/src/lib/triggers/order-created.ts
  packages/pieces/community/woocommerce/src/lib/triggers/register-trigger.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
Labels: 🐛 bug

#7676 fix: make testing ci run in parallel
  .github/workflows/build-cloud-nx.yml
  packages/server/api/test/integration/ce/flows/flow.test.ts
Labels: 🐛 bug

#7678 fix: upgrade nx to extra large
  .github/workflows/build-cloud-nx.yml
Labels: ✨ polishing

#7677 fix: switching between pieces was triggering unnecessary saving
  package-lock.json
  packages/pieces/community/monday/package.json
  packages/pieces/community/monday/src/lib/triggers/new-item-in-board.ts
  packages/pieces/community/monday/src/lib/triggers/specific-column-updated.ts
  packages/react-ui/src/app/builder/piece-properties/form-utils.tsx
  packages/react-ui/src/app/builder/pieces-selector/piece-selector-utils.ts
  packages/react-ui/src/app/builder/step-settings/index.tsx
  packages/server/api/src/app/flows/flow-version/flow-version-validator-util.ts
Labels: 🐛 bug

#7680 feat: release 0.53.1
  docker-compose.yml
  package.json
Labels: release

#7681 fix: enhance ci workflow for nx
  .github/workflows/build-cloud-nx.yml
Labels: ✨ polishing

#7682 fix: increase timeout for flow-piece.test.ts
  packages/engine/test/handler/flow-piece.test.ts
Labels: 🐛 bug

#7645 refactor: move jimp & mailchain to local deps
  package-lock.json
  package.json
  packages/pieces/community/image-helper/package-lock.json
  packages/pieces/community/image-helper/package.json
  packages/pieces/community/image-helper/project.json
  packages/pieces/community/mailchain/package-lock.json
  packages/pieces/community/mailchain/package.json
  packages/pieces/community/mailchain/project.json
  packages/pieces/community/mailchain/src/index.ts
  packages/pieces/community/pdf/package-lock.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/project.json
  packages/server/shared/src/lib/pieces/file-pieces-utils.ts
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
Labels: 🧹 clean up

#7572 feat: introduce mcp telemetry
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/shared/src/lib/common/telemetry.ts
  packages/shared/src/lib/mcp/mcp.ts
Labels: 🧹 clean up

#7687 refactor: move clarifai sdk to piece package.json
  package-lock.json
  package.json
  packages/pieces/community/clarifai/package-lock.json
  packages/pieces/community/clarifai/package.json
  packages/pieces/community/clarifai/project.json
Labels: 🧹 clean up

#7688 refactor: move pdf deps to piece package.json
  package-lock.json
  package.json
  packages/pieces/community/pdf/package-lock.json
  packages/pieces/community/pdf/package.json
  packages/pieces/community/pdf/project.json
Labels: 🧹 clean up

#7696 refactor: delete more unused deps
  package-lock.json
  package.json
Labels: 🧹 clean up

#7691 fix(dust): uploadFile piece compatibility with node v18
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/src/lib/actions/upload-file.ts
Labels: 🔌 pieces

#7695 refactor: move @aws-sdk/client-sns to piece package.json
  package-lock.json
  package.json
  packages/pieces/community/amazon-sns/package-lock.json
  packages/pieces/community/amazon-sns/package.json
  packages/pieces/community/amazon-sns/project.json
Labels: 🧹 clean up

#7702 feat: make quota exceeded retryable by storing trigger payload
  packages/server/worker/src/lib/executors/flow-job-executor.ts
Labels: 🌟 feature

#7703 fix: hide the flow menu when flow name is hidden
  packages/react-ui/src/app/builder/builder-header.tsx
Labels: 🐛 bug

#7704 fix(subflow): only use callback url when the parent is waiting for re…
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
  packages/pieces/community/subflows/src/lib/actions/respond.ts
Labels: 🐛 bug, 🔌 pieces

#7699 feat: revamp folders
  package-lock.json
  package.json
  packages/react-ui/src/app/routes/flows/flows-table/index.tsx
  packages/react-ui/src/components/delete-dialog.tsx
  packages/react-ui/src/components/ui/emoji-picker.tsx
  packages/react-ui/src/features/folders/component/create-folder-dialog.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list/folder-action.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list/folder-actions-menu.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list/folders-container.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list/index.tsx
  packages/react-ui/src/features/folders/component/folder-filter-list/sortable-folder.tsx
  packages/react-ui/src/features/folders/component/rename-folder-dialog.tsx
  packages/react-ui/src/features/folders/lib/folders-api.ts
  packages/react-ui/src/features/folders/lib/folders-hooks.ts
  packages/server/api/src/app/database/migration/sqlite/1747062679388-AddFolderDisplayOrder.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/flows/folder/folder.entity.ts
  packages/server/api/src/app/flows/folder/folder.module.ts
  packages/server/api/src/app/flows/folder/folder.service.ts
  packages/shared/src/lib/flows/folders/folder-requests.ts
  packages/shared/src/lib/flows/folders/folder.ts
Labels: ✨ polishing

#7701 feat(metabase): add timeout so graph can load
  packages/pieces/community/metabase/package.json
  packages/pieces/community/metabase/src/lib/actions/get-graph-question.ts
Labels: 🔌 pieces

#7705 fix(handshake): handle undefined payload by fetching data when necessary
  packages/server/api/src/app/flows/flow/flow-service-side-effects.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
Labels: 🐛 bug

#7711 fix(project-releases): fallback to id in case external Id is not null
  packages/server/api/src/app/ee/project-release/git-sync/git-sync-helper.ts
Labels: 🐛 bug

#7712 fix(project-state): skip overriding auth for empty trigger
  packages/server/api/src/app/ee/project-release/project-state/project-diff.service.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state-helper.ts
Labels: 🐛 bug

#7714 fix(flow): improve case-insensitive search for flow display names
  packages/server/api/src/app/flows/flow/flow.service.ts
Labels: 🐛 bug

#7715 fix: generate webhook sample data via dialog by hitting /test
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-webhook-dialog.tsx
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
Labels: 🐛 bug

#7716 feat(migration): add externalId column to tables and fields in SQLite…
  packages/server/api/src/app/database/migration/sqlite/1746367601605-AddExternalIdForTablesAndFieldsSQLITE.ts
Labels: 🐛 bug

#7717 feat: release 0.54.0
  docker-compose.yml
  package.json
Labels: release

#7719 chore: improve webhooks testing
  packages/react-ui/src/app/builder/test-step/custom-test-step/test-webhook-dialog.tsx
  packages/react-ui/src/app/builder/test-step/test-step-hooks.ts
  packages/react-ui/src/app/builder/test-step/test-trigger-section.tsx
  packages/react-ui/src/features/flows/lib/trigger-events-api.ts
  packages/react-ui/src/lib/utils.ts
Labels: skip-changelog

#7718 feat: agent piece
  package-lock.json
  package.json
  packages/pieces/community/agent/.eslintrc.json
  packages/pieces/community/agent/README.md
  packages/pieces/community/agent/package.json
  packages/pieces/community/agent/project.json
  packages/pieces/community/agent/src/index.ts
  packages/pieces/community/agent/src/lib/actions/run-agent.ts
  packages/pieces/community/agent/tsconfig.json
  packages/pieces/community/agent/tsconfig.lib.json
  packages/react-ui/src/app/builder/pieces-selector/index.tsx
  tsconfig.base.json
Labels: 🌟 feature

#7635 feat: translate pieces
  crowdin.yml
  docs/developers/building-pieces/overview.mdx
  docs/developers/piece-reference/i18n.mdx
  docs/developers/unified-ai/overview.mdx
  docs/mint.json
  docs/resources/french-webhooks.png
  docs/resources/i18n-pieces.png
  package-lock.json
  package.json
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/commands/generate-translation-file-for-piece.ts
  packages/cli/src/lib/utils/files.ts
  packages/cli/src/lib/utils/piece-utils.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/helper/piece-loader.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/i18n.ts
  packages/pieces/community/framework/src/lib/index.ts
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/piece.ts
  packages/pieces/community/framework/translation-keys.json
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/appearance-section.tsx
  packages/react-ui/src/app/routes/settings/appearance/language-switcher.tsx
  packages/react-ui/src/features/pieces/lib/pieces-api.ts
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
  packages/server/api/src/app/database/migration/postgres/1746714836833-AddI18nColumnToPieceMetadata.ts
  packages/server/api/src/app/database/migration/sqlite/1746714949131-AddI18nColumnToPieceMetadata.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-metadata-entity.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/server/shared/package.json
  packages/server/shared/src/lib/pieces/file-pieces-utils.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
  packages/shared/package.json
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  tools/scripts/utils/piece-script-utils.ts
Labels: 🌟 feature

#7721 fix: add username to redis sentinel setup
  packages/server/api/src/app/database/redis-connection.ts
Labels: 🧹 clean up

#7728 chore: add more logs to framework
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/i18n.ts
Labels: skip-changelog

#7729 refactor: update webhook handler to improve payload saving logic
  packages/server/api/src/app/webhooks/webhook-handler.ts
Labels: 🐛 bug

#7730 Revert "chore: add more logs to framework"
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/i18n.ts
Labels: skip-changelog

#7725 fix: prevent stale code by separating test and production run caches
  packages/engine/src/lib/handler/code-executor.ts
  packages/engine/src/lib/handler/context/engine-constants.ts
  packages/engine/test/handler/test-helper.ts
  packages/engine/test/resources/codes/flowVersionId/echo_step/TESTING/index.js
  packages/engine/test/resources/codes/flowVersionId/echo_step_1/TESTING/index.js
  packages/engine/test/resources/codes/flowVersionId/runtime/TESTING/index.js
  packages/server/api/src/app/flows/step-run/sample-data.controller.ts
  packages/server/api/src/app/flows/step-run/sample-data.service.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/server/worker/src/lib/engine/execution-files.ts
  packages/server/worker/src/lib/engine/isolate/isolate-engine-runner.ts
  packages/server/worker/src/lib/engine/isolate/sandbox/provisioner/sandbox-provisioner.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
  packages/server/worker/src/lib/executors/user-interaction-job-executor.ts
  packages/server/worker/src/lib/utils/code-builder.ts
  packages/shared/src/lib/engine/engine-operation.ts
Labels: 🐛 bug

#7733 feat(dust): bump dust SDK version to re-allow creating conversation with empty messages
  package-lock.json
  package.json
  packages/pieces/community/dust/package.json
Labels: 🔌 pieces

#7736 chore: update replace connections dialog message
  packages/react-ui/src/app/connections/replace-connections-dialog.tsx
Labels: 🐛 bug

#7607 feat: adding fireflies.ai piece
  packages/pieces/community/fireflies-ai/.eslintrc.json
  packages/pieces/community/fireflies-ai/README.md
  packages/pieces/community/fireflies-ai/package.json
  packages/pieces/community/fireflies-ai/project.json
  packages/pieces/community/fireflies-ai/src/index.ts
  packages/pieces/community/fireflies-ai/src/lib/actions/find-meeting-by-id.ts
  packages/pieces/community/fireflies-ai/src/lib/actions/find-meeting-by-query.ts
  packages/pieces/community/fireflies-ai/src/lib/actions/find-recent-meeting.ts
  packages/pieces/community/fireflies-ai/src/lib/actions/get-user-details.ts
  packages/pieces/community/fireflies-ai/src/lib/actions/upload-audio.ts
  packages/pieces/community/fireflies-ai/src/lib/common/index.ts
  packages/pieces/community/fireflies-ai/src/lib/common/queries.ts
  packages/pieces/community/fireflies-ai/src/lib/triggers/new-transcription-complete.ts
  packages/pieces/community/fireflies-ai/tsconfig.json
  packages/pieces/community/fireflies-ai/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7738 feat: piece translation
  crowdin.yml
  docs/developers/building-pieces/overview.mdx
  docs/developers/piece-reference/i18n.mdx
  docs/developers/unified-ai/overview.mdx
  docs/mint.json
  docs/resources/french-webhooks.png
  docs/resources/i18n-pieces.png
  package-lock.json
  package.json
  packages/cli/src/index.ts
  packages/cli/src/lib/commands/create-piece.ts
  packages/cli/src/lib/commands/generate-translation-file-for-piece.ts
  packages/cli/src/lib/utils/files.ts
  packages/cli/src/lib/utils/piece-utils.ts
  packages/engine/src/lib/helper/piece-helper.ts
  packages/engine/src/lib/helper/piece-loader.ts
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/i18n.ts
  packages/pieces/community/framework/src/lib/index.ts
  packages/pieces/community/framework/src/lib/piece-metadata.ts
  packages/pieces/community/framework/src/lib/piece.ts
  packages/pieces/community/framework/translation-keys.json
  packages/react-ui/src/app/components/sidebar.tsx
  packages/react-ui/src/app/router/index.tsx
  packages/react-ui/src/app/router/project-route-wrapper.tsx
  packages/react-ui/src/app/routes/platform/setup/branding/appearance-section.tsx
  packages/react-ui/src/app/routes/settings/appearance/language-switcher.tsx
  packages/react-ui/src/features/pieces/lib/pieces-api.ts
  packages/react-ui/src/features/pieces/lib/pieces-hook.ts
  packages/server/api/src/app/database/migration/postgres/1746714836833-AddI18nColumnToPieceMetadata.ts
  packages/server/api/src/app/database/migration/sqlite/1746714949131-AddI18nColumnToPieceMetadata.ts
  packages/server/api/src/app/pieces/base-piece-module.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/server/shared/package.json
  packages/server/shared/src/lib/pieces/file-pieces-utils.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
  packages/shared/src/lib/pieces/dto/piece-requests.ts
  tools/scripts/pieces/update-pieces-metadata.ts
  tools/scripts/utils/piece-script-utils.ts
Labels: 🌟 feature

#7739 docs: Add on-boarding check list
  docs/handbook/engineering/onboarding/onboarding-check-list.mdx
  docs/mint.json
Labels: 📚 documentation

#7740 feat(dropbox): download file action
  packages/pieces/community/dropbox/package.json
  packages/pieces/community/dropbox/src/index.ts
  packages/pieces/community/dropbox/src/lib/actions/download-file.ts
Labels: 🔌 pieces

#7752 fix: retry run on latest version should not copy logs
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
Labels: 🐛 bug

#7746 feat(microsoft-sharepoint): upload file action
  packages/pieces/community/microsoft-sharepoint/package.json
  packages/pieces/community/microsoft-sharepoint/src/index.ts
  packages/pieces/community/microsoft-sharepoint/src/lib/actions/upload-file.ts
Labels: 🔌 pieces

#7747 feat: make table actions and triggers work with external ids
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/i18n.ts
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/index.ts
  packages/pieces/community/tables/src/lib/actions/create-records.ts
  packages/pieces/community/tables/src/lib/actions/find-records.ts
  packages/pieces/community/tables/src/lib/actions/update-record.ts
  packages/pieces/community/tables/src/lib/common/index.ts
  packages/pieces/community/tables/src/lib/triggers/deleted-record.ts
  packages/pieces/community/tables/src/lib/triggers/new-record.ts
  packages/pieces/community/tables/src/lib/triggers/updated-record.ts
  packages/react-ui/src/app/routes/project-release/create-release-dialog/index.tsx
  packages/react-ui/src/features/tables/lib/records-api.ts
  packages/server/api/src/app/database/migration/common/1747312147549-ChangeExternalIdsForTables.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/project-release/project-state/project-state.service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/tables/record/record.controller.ts
  packages/server/api/src/app/tables/record/record.service.ts
  packages/server/api/src/app/tables/table/table.controller.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/worker/package.json
  packages/server/worker/src/lib/piece-manager/development/pieces-builder.ts
  packages/shared/package.json
  packages/shared/src/lib/tables/dto/tables.dto.ts
Labels: 🔌 pieces

#7754 feat: release 0.55.0
  docker-compose.yml
  package.json
  packages/server/api/src/app/database/migration/common/1747346473000-ChangeExternalIdsForTables.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
Labels: release

#7755 fix: replace connections to be exact match
  packages/server/api/src/app/app-connection/app-connection-service/app-connection.handler.ts
Labels: 🐛 bug

#7756 feat: change mcp to new auth spec
  packages/server/api/src/app/mcp/mcp-module.ts
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-session-manager.ts
  packages/server/api/src/app/mcp/mcp-sse-controller.ts
Labels: 🌟 feature

#7605 feat(piece-coda): implement full coda piece with triggers and actions
  packages/pieces/community/coda/.eslintrc.json
  packages/pieces/community/coda/README.md
  packages/pieces/community/coda/package.json
  packages/pieces/community/coda/project.json
  packages/pieces/community/coda/src/index.ts
  packages/pieces/community/coda/src/lib/actions/create-row.ts
  packages/pieces/community/coda/src/lib/actions/find-row.ts
  packages/pieces/community/coda/src/lib/actions/get-row.ts
  packages/pieces/community/coda/src/lib/actions/get-table.ts
  packages/pieces/community/coda/src/lib/actions/list-tables.ts
  packages/pieces/community/coda/src/lib/actions/update-row.ts
  packages/pieces/community/coda/src/lib/actions/upsert-row.ts
  packages/pieces/community/coda/src/lib/common/props.ts
  packages/pieces/community/coda/src/lib/common/types.ts
  packages/pieces/community/coda/src/lib/triggers/new-row-created.ts
  packages/pieces/community/coda/tsconfig.json
  packages/pieces/community/coda/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7759 fix: fetch all table records when listing
  package-lock.json
  packages/react-ui/src/features/tables/components/ap-table-state-provider.tsx
  packages/react-ui/src/features/tables/components/import-csv-dialog.tsx
Labels: 🐛 bug

#7603 feat(piece-pdf-co): implement pdf.co community piece
  packages/pieces/community/pdf-co/.eslintrc.json
  packages/pieces/community/pdf-co/README.md
  packages/pieces/community/pdf-co/package.json
  packages/pieces/community/pdf-co/project.json
  packages/pieces/community/pdf-co/src/index.ts
  packages/pieces/community/pdf-co/src/lib/actions/add-barcode-to-pdf.ts
  packages/pieces/community/pdf-co/src/lib/actions/add-image-to-pdf.ts
  packages/pieces/community/pdf-co/src/lib/actions/add-text-to-pdf.ts
  packages/pieces/community/pdf-co/src/lib/actions/convert-html-to-pdf.ts
  packages/pieces/community/pdf-co/src/lib/actions/convert-pdf-to-structured-format.ts
  packages/pieces/community/pdf-co/src/lib/actions/extract-tables-from-pdf.ts
  packages/pieces/community/pdf-co/src/lib/actions/extract-text-from-pdf.ts
  packages/pieces/community/pdf-co/src/lib/actions/index.ts
  packages/pieces/community/pdf-co/src/lib/actions/search-and-replace-text.ts
  packages/pieces/community/pdf-co/src/lib/common/props.ts
  packages/pieces/community/pdf-co/src/lib/common/types.ts
  packages/pieces/community/pdf-co/tsconfig.json
  packages/pieces/community/pdf-co/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7582 feat: Manychat Piece
  packages/pieces/community/manychat/.eslintrc.json
  packages/pieces/community/manychat/README.md
  packages/pieces/community/manychat/package.json
  packages/pieces/community/manychat/project.json
  packages/pieces/community/manychat/src/index.ts
  packages/pieces/community/manychat/src/lib/actions/add-tag-to-user.ts
  packages/pieces/community/manychat/src/lib/actions/create-subscriber.ts
  packages/pieces/community/manychat/src/lib/actions/find-user-by-custom-field.ts
  packages/pieces/community/manychat/src/lib/actions/find-user-by-name.ts
  packages/pieces/community/manychat/src/lib/actions/remove-tag-from-user.ts
  packages/pieces/community/manychat/src/lib/actions/send-content-to-user.ts
  packages/pieces/community/manychat/src/lib/actions/set-custom-fields.ts
  packages/pieces/community/manychat/src/lib/common/props.ts
  packages/pieces/community/manychat/tsconfig.json
  packages/pieces/community/manychat/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7775 fix: project switcher width
  packages/react-ui/src/app/components/ap-dashboard-sidebar-header.tsx
  packages/react-ui/src/features/projects/components/project-switcher.tsx
Labels: ✨ polishing

#7783 chore: sync translations from crowdin to react-ui
  crowdin.yml
  packages/react-ui/public/locales/ar/translation.json
  packages/react-ui/public/locales/bg/translation.json
  packages/react-ui/public/locales/ca/translation.json
  packages/react-ui/public/locales/de/translation.json
  packages/react-ui/public/locales/en/translation.json
  packages/react-ui/public/locales/es/translation.json
  packages/react-ui/public/locales/fr/translation.json
  packages/react-ui/public/locales/hi/translation.json
  packages/react-ui/public/locales/hu/translation.json
  packages/react-ui/public/locales/hy/translation.json
  packages/react-ui/public/locales/id/translation.json
  packages/react-ui/public/locales/it/translation.json
  packages/react-ui/public/locales/ja/translation.json
  packages/react-ui/public/locales/ko/translation.json
  packages/react-ui/public/locales/nl/translation.json
  packages/react-ui/public/locales/pl/translation.json
  packages/react-ui/public/locales/pt/translation.json
  packages/react-ui/public/locales/ru/translation.json
  packages/react-ui/public/locales/sv/translation.json
  packages/react-ui/public/locales/uk/translation.json
  packages/react-ui/public/locales/vi/translation.json
  packages/react-ui/public/locales/zh/translation.json
Labels: skip-changelog

#7780 feat: exa
  packages/pieces/community/exa/.eslintrc.json
  packages/pieces/community/exa/README.md
  packages/pieces/community/exa/package.json
  packages/pieces/community/exa/project.json
  packages/pieces/community/exa/src/index.ts
  packages/pieces/community/exa/src/lib/actions/find-similar-links.ts
  packages/pieces/community/exa/src/lib/actions/generate-answer.ts
  packages/pieces/community/exa/src/lib/actions/get-contents.ts
  packages/pieces/community/exa/src/lib/actions/perform-search.ts
  packages/pieces/community/exa/src/lib/common/index.ts
  packages/pieces/community/exa/tsconfig.json
  packages/pieces/community/exa/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#7788 chore: switching embedding to use session storage instead of local storage
  packages/react-ui/src/app/routes/authenticate/index.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/app/routes/redirect.tsx
  packages/react-ui/src/features/authentication/components/sign-in-form.tsx
  packages/react-ui/src/features/authentication/components/sign-up-form.tsx
  packages/react-ui/src/hooks/project-hooks.ts
  packages/react-ui/src/lib/ap-browser-storage.ts
  packages/react-ui/src/lib/authentication-session.ts
Labels: 🐛 bug

#7665 feat: Adding Campaign Monitor Piece
  packages/pieces/community/campaign-monitor/.eslintrc.json
  packages/pieces/community/campaign-monitor/README.md
  packages/pieces/community/campaign-monitor/package.json
  packages/pieces/community/campaign-monitor/project.json
  packages/pieces/community/campaign-monitor/src/index.ts
  packages/pieces/community/campaign-monitor/src/lib/actions/add-subscriber-to-list.ts
  packages/pieces/community/campaign-monitor/src/lib/actions/find-subscriber.ts
  packages/pieces/community/campaign-monitor/src/lib/actions/unsubscribe-subscriber.ts
  packages/pieces/community/campaign-monitor/src/lib/actions/update-subscriber-details.ts
  packages/pieces/community/campaign-monitor/src/lib/common/client.ts
  packages/pieces/community/campaign-monitor/src/lib/common/props.ts
  packages/pieces/community/campaign-monitor/src/lib/triggers/new-client.ts
  packages/pieces/community/campaign-monitor/src/lib/triggers/new-subscriber-added.ts
  packages/pieces/community/campaign-monitor/src/lib/triggers/subscriber-unsubscribed.ts
  packages/pieces/community/campaign-monitor/tsconfig.json
  packages/pieces/community/campaign-monitor/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7792 fix: update textProcessor to handle empty values of required strings
  packages/engine/src/lib/variables/processors/text.ts
  packages/pieces/community/store/package.json
  packages/pieces/community/store/src/lib/actions/store-append-action.ts
Labels: 🐛 bug

#7787 fix(gmail): fix new labeled trigger
  packages/pieces/community/gmail/package.json
  packages/pieces/community/gmail/src/lib/triggers/new-labeled-email.ts
Labels: 🔌 pieces

#7766 refactor: move langchain packages to agent piece package.json
  package-lock.json
  package.json
  packages/pieces/community/agent/package-lock.json
  packages/pieces/community/agent/package.json
  packages/pieces/community/agent/project.json
Labels: 🧹 clean up

#7765 refactor: move dust client to piece package.json
  package-lock.json
  package.json
  packages/pieces/community/dust/package-lock.json
  packages/pieces/community/dust/package.json
  packages/pieces/community/dust/project.json
Labels: 🧹 clean up

#7764 refactor: move actualbudget sdk to piece package.json
  package-lock.json
  package.json
  packages/pieces/community/actualbudget/package-lock.json
  packages/pieces/community/actualbudget/package.json
  packages/pieces/community/actualbudget/project.json
Labels: 🧹 clean up

#7760 refactor: move "contentful-management" sdk to piece package.json
  package-lock.json
  package.json
  packages/pieces/community/contentful/package-lock.json
  packages/pieces/community/contentful/package.json
  packages/pieces/community/contentful/project.json
Labels: 🧹 clean up

#7761 refactor: delete more unused deps
  package-lock.json
  package.json
  packages/react-ui/src/components/ui/data-table/index.tsx
Labels: 🧹 clean up

#7800 chore: update sdk changelog
  docs/embedding/sdk-changelog.mdx
Labels: 📚 documentation, skip-changelog

#7640 feat(saleor): new piece implementation
  packages/pieces/community/saleor/.eslintrc.json
  packages/pieces/community/saleor/README.md
  packages/pieces/community/saleor/package.json
  packages/pieces/community/saleor/project.json
  packages/pieces/community/saleor/src/index.ts
  packages/pieces/community/saleor/src/lib/actions/add-note-to-order.ts
  packages/pieces/community/saleor/src/lib/actions/get-order.ts
  packages/pieces/community/saleor/src/lib/actions/raw-graphql-query.ts
  packages/pieces/community/saleor/tsconfig.json
  packages/pieces/community/saleor/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces

#7793 fix(convertkit): add desc sort and move params from body into queryParams
  packages/pieces/community/convertkit/package.json
  packages/pieces/community/convertkit/src/lib/common/service.ts
Labels: 🔌 pieces

#7708 fix(pipedrive): replace dropdown props with text fields to reduce API token usage
  packages/pieces/community/pipedrive/package.json
  packages/pieces/community/pipedrive/src/lib/actions/add-follower.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-notes.ts
  packages/pieces/community/pipedrive/src/lib/actions/find-products.ts
  packages/pieces/community/pipedrive/src/lib/common/index.ts
  packages/pieces/community/pipedrive/src/lib/common/props.ts
Labels: 🔌 pieces

#7799 feat(returning-ai): add forum channel send message action
  packages/pieces/community/returning-ai/package.json
  packages/pieces/community/returning-ai/src/lib/actions/send-message.ts
Labels: 🔌 pieces

#7802 fix: add tiktoken package to azure-openai piece package.json
  packages/pieces/community/azure-openai/package-lock.json
  packages/pieces/community/azure-openai/package.json
  packages/pieces/community/azure-openai/project.json
Labels: 🐛 bug, 🔌 pieces

#7804 fix: ignore patch version when comparing piece versions in project release diff
  packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
Labels: 🐛 bug

#7806 refactor: improve the flow changed function
  packages/server/api/src/app/ee/projects/project-release/project-release.service.ts
  packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
  packages/server/api/src/app/flows/flow/human-input/human-input.service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/db-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/file-piece-metadata-service.ts
  packages/server/api/src/app/pieces/piece-metadata-service/piece-metadata-service.ts
  packages/server/worker/src/lib/engine/flow-engine-util.ts
  packages/server/worker/src/lib/engine/isolate/isolate-engine-runner.ts
  packages/server/worker/src/lib/engine/threads/thread-engine-runner.ts
Labels: 🧹 clean up

#7414 feat(slack): 4 new actions and 3 triggers
  packages/pieces/community/slack/package.json
  packages/pieces/community/slack/src/index.ts
  packages/pieces/community/slack/src/lib/actions/find-user-by-id.ts
  packages/pieces/community/slack/src/lib/actions/get-message.ts
  packages/pieces/community/slack/src/lib/actions/invite-user-to-channel.ts
  packages/pieces/community/slack/src/lib/actions/set-channel-topic.ts
  packages/pieces/community/slack/src/lib/common/props.ts
  packages/pieces/community/slack/src/lib/triggers/new-saved-message.ts
  packages/pieces/community/slack/src/lib/triggers/new-team-custom-emoji.ts
  packages/pieces/community/slack/src/lib/triggers/new-user.ts
Labels: 🔌 pieces

#7807 refactor: enhance version comparison logic in project diff service
  packages/server/api/src/app/ee/projects/project-release/project-state/project-diff.service.ts
Labels: 🧹 clean up

#7808 fix: failed unit tests
  packages/server/api/test/helpers/flow-generator.ts
  packages/server/api/test/integration/ce/flows/consumer/flow-consume.test.ts
  packages/server/api/test/unit/app/ee/git-repos/operations/project-diff.test.ts
Labels: 🐛 bug

#7794 feat: added option to hide exporting and importing flows in embed
  docs/embedding/embed-builder.mdx
  docs/embedding/sdk-changelog.mdx
  packages/ee/ui/embed-sdk/package.json
  packages/ee/ui/embed-sdk/src/index.ts
  packages/react-ui/src/app/builder/builder-header.tsx
  packages/react-ui/src/app/components/flow-actions-menu.tsx
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/app/routes/flows/index.tsx
  packages/react-ui/src/components/embed-provider.tsx
Labels: 🌟 feature

#7803 feat: added a method to override home button being clicked in embedding
  docs/embedding/embed-builder.mdx
  docs/embedding/sdk-changelog.mdx
  packages/ee/ui/embed-sdk/src/index.ts
  packages/react-ui/src/app/routes/embed/index.tsx
  packages/react-ui/src/components/embed-provider.tsx
  packages/react-ui/src/components/ui/home-button.tsx
  packages/react-ui/src/lib/utils.ts
Labels: 🌟 feature

#7768 feat: allow both oauth2 grant types
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts
  packages/pieces/community/framework/src/lib/property/index.ts
  packages/react-ui/src/app/builder/piece-properties/dynamic-piece-property.tsx
  packages/react-ui/src/app/connections/create-edit-connection-dialog.tsx
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/react-ui/src/components/custom/markdown.tsx
  packages/react-ui/src/components/ui/skeleton.tsx
  packages/react-ui/src/features/connections/lib/oauth2-apps-hooks.ts
  packages/server/api/src/app/app-connection/app-connection-service/app-connection-service.ts
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/oauth2-service.ts
  packages/server/api/src/app/app-connection/app-connection-service/oauth2/services/credentials-oauth2-service.ts
  packages/server/shared/package.json
  packages/server/worker/package.json
  packages/shared/package.json
  packages/shared/src/lib/common/activepieces-error.ts
Labels: 🌟 feature

#7812 feat: release 0.56.0
  docker-compose.yml
  package-lock.json
  package.json
  packages/server/shared/package.json
Labels: release

#7816 chore(Subflows): add retry on failure option to call flow action
  package-lock.json
  packages/pieces/community/subflows/package.json
  packages/pieces/community/subflows/src/lib/actions/call-flow.ts
Labels: 🔌 pieces

#7817 chore: allow both grant types for http oauth2 piece
  docs/embedding/embed-builder.mdx
  packages/pieces/community/http-oauth2/package.json
  packages/pieces/community/http-oauth2/src/index.ts
Labels: 🔌 pieces

#7818 fix: docs embed builder
  docs/embedding/embed-builder.mdx
Labels: skip-changelog

#7823 fix(tables): find-records action & use qs query parser
  packages/pieces/community/tables/package.json
  packages/pieces/community/tables/src/lib/common/index.ts
  packages/server/api/src/app/server.ts
  packages/server/api/src/app/tables/record/record.service.ts
Labels: 🐛 bug

#7828 fix: integration tests with new platform plan schema
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.service.ts
  packages/server/api/src/app/platform/platform.service.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/api/test/integration/cloud/audit-event/audit-event.test.ts
  packages/server/api/test/integration/cloud/authn/cloud-authn.test.ts
  packages/server/api/test/integration/cloud/flow-templates/flow-templates.test.ts
  packages/server/api/test/integration/cloud/git-repos/git-repos.test.ts
  packages/server/api/test/integration/cloud/global-connection/global-connection.test.ts
  packages/server/api/test/integration/cloud/managed-authn/external-token.test.ts
  packages/server/api/test/integration/cloud/platform/platform.test.ts
  packages/server/api/test/integration/cloud/project-members/project-members.test.ts
  packages/server/api/test/integration/cloud/project/project.test.ts
  packages/server/api/test/integration/cloud/signing-key/signing-key.test.ts
  packages/server/api/test/integration/cloud/user-invitations/user-invitations.test.ts
  packages/server/api/test/integration/ee/authn/ee-authn.test.ts
Labels: 🧹 clean up

#7829 feat: migrate flow schema verison
  packages/shared/src/lib/flows/flow-version.ts
  packages/shared/src/lib/flows/operations/migrations/index.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v0-branch-to-router.ts
  packages/shared/src/lib/flows/operations/migrations/migrate-v1-connection-ids.ts
Labels: 🧹 clean up

#7830 feat(mcp): add streamable http transport
  packages/server/api/src/app/mcp/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-sse-controller.ts
Labels: 🌟 feature

#7597 feat: support basic and bearer auth for send-http-request-action
  packages/pieces/community/http/package.json
  packages/pieces/community/http/src/lib/actions/send-http-request-action.ts
Labels: 🔌 pieces, 💫 priority

#7805 fix: custom api call file response
  packages/pieces/community/common/package.json
  packages/pieces/community/common/src/lib/helpers/index.ts
Labels: 🔌 pieces, 💫 priority

#7833 fix: show oauth2 configure button condition
  packages/pieces/community/framework/src/lib/property/authentication/oauth2-prop.ts
  packages/react-ui/src/app/routes/platform/setup/pieces/index.tsx
  packages/shared/src/lib/app-connection/dto/upsert-app-connection-request.ts
Labels: 🐛 bug

#7834 refactor: remove unused export
  packages/pieces/community/framework/src/lib/property/index.ts
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
Labels: skip-changelog

#7837 fix: test webhook google drive
  packages/engine/src/lib/operations.ts
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/webhooks/webhook-handler.ts
  packages/server/api/src/app/workers/worker-controller.ts
  packages/server/shared/src/lib/job/job-data.ts
  packages/server/worker/src/lib/executors/flow-job-executor.ts
  packages/shared/src/lib/engine/engine-operation.ts
Labels: 🐛 bug

#7839 feat: release 0.57.0
  docker-compose.yml
  package-lock.json
  package.json
Labels: release

#7842 fix: wasn't using platform OAuth2 by default when creating a connection
  package-lock.json
  packages/react-ui/src/app/connections/oauth2-connection-settings.tsx
Labels: 🐛 bug

#7843 feat: release 0.57.1
  docker-compose.yml
  package.json
Labels: release

#7844 fix: text for invalid steps note and importing flows toast had typos
  packages/react-ui/public/locales/en/translation.json
Labels: 🐛 bug

#7847 feat(coda): custom api call action
  packages/pieces/community/coda/package.json
  packages/pieces/community/coda/src/index.ts
Labels: 🔌 pieces

#7604 feat(instantly.ai): Add Instantly Piece
  packages/pieces/community/instantly-ai/.eslintrc.json
  packages/pieces/community/instantly-ai/README.md
  packages/pieces/community/instantly-ai/package.json
  packages/pieces/community/instantly-ai/project.json
  packages/pieces/community/instantly-ai/src/index.ts
  packages/pieces/community/instantly-ai/src/lib/actions/add-lead-to-campaign.ts
  packages/pieces/community/instantly-ai/src/lib/actions/create-campaign.ts
  packages/pieces/community/instantly-ai/src/lib/actions/create-lead-list.ts
  packages/pieces/community/instantly-ai/src/lib/actions/search-campaigns.ts
  packages/pieces/community/instantly-ai/src/lib/actions/search-leads.ts
  packages/pieces/community/instantly-ai/src/lib/common/client.ts
  packages/pieces/community/instantly-ai/src/lib/common/props.ts
  packages/pieces/community/instantly-ai/src/lib/triggers/campaign-status-changed.ts
  packages/pieces/community/instantly-ai/src/lib/triggers/new-lead-added.ts
  packages/pieces/community/instantly-ai/tsconfig.json
  packages/pieces/community/instantly-ai/tsconfig.lib.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7840 Feat: new billing page
  packages/ee/shared/src/lib/billing/index.ts
  packages/ee/shared/src/lib/project/project-requests.ts
  packages/react-ui/src/app/components/sidebar/usage-limits-button.tsx
  packages/react-ui/src/app/routes/platform/billing/api/billing-api.ts
  packages/react-ui/src/app/routes/platform/billing/index.tsx
  packages/react-ui/src/app/routes/platform/projects/index.tsx
  packages/react-ui/src/app/routes/settings/general/index.tsx
  packages/server/api/src/app/ai/ai-provider-proxy.ts
  packages/server/api/src/app/database/migration/postgres/1747921788059-AddLimitsOnPlatformPlan.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/ee/flow-run/cloud-flow-run-hooks.ts
  packages/server/api/src/app/ee/managed-authn/lib/external-token-extractor.ts
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan-helper.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.entity.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.module.ts
  packages/server/api/src/app/ee/platform/platform-plan/stripe-helper.ts
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/src/app/ee/projects/platform-project-controller.ts
  packages/server/api/src/app/ee/projects/platform-project-service.ts
  packages/server/api/src/app/ee/projects/project-plan/project-plan.entity.ts
  packages/server/api/src/app/ee/projects/project-plan/project-plan.service.ts
  packages/server/api/src/app/flows/flow/flow.controller.ts
  packages/server/api/src/app/helper/error-handler.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/server/api/src/app/project/project-service.ts
  packages/server/api/src/app/tables/table/table.service.ts
  packages/server/api/src/app/user/user-service.ts
  packages/server/api/src/app/webhooks/webhook.service.ts
  packages/server/api/src/app/workers/engine-controller.ts
  packages/server/api/test/helpers/mocks/index.ts
  packages/server/worker/src/lib/api/server-api.service.ts
  packages/shared/src/lib/common/activepieces-error.ts
  packages/shared/src/lib/platform/platform.model.ts
  packages/shared/src/lib/project/project.ts
Labels: 🌟 feature

#7832 chore: enhance custom property and its documentation
  docs/developers/piece-reference/properties.mdx
  packages/pieces/community/framework/package.json
  packages/pieces/community/framework/src/lib/property/index.ts
  packages/pieces/community/framework/src/lib/property/input/custom-property.ts
  packages/pieces/community/framework/src/lib/property/input/index.ts
  packages/react-ui/src/app/builder/piece-properties/auto-properties-form.tsx
  packages/react-ui/src/app/builder/piece-properties/custom-property.tsx
  packages/server/shared/package.json
  packages/server/worker/package.json
Labels: 🛠️ piece-framework

#7663 feat: add SmartSuite integration
  packages/pieces/community/smartsuite/.eslintrc.json
  packages/pieces/community/smartsuite/README.md
  packages/pieces/community/smartsuite/package.json
  packages/pieces/community/smartsuite/project.json
  packages/pieces/community/smartsuite/src/index.ts
  packages/pieces/community/smartsuite/src/lib/actions/create-record.ts
  packages/pieces/community/smartsuite/src/lib/actions/delete-record.ts
  packages/pieces/community/smartsuite/src/lib/actions/find-records.ts
  packages/pieces/community/smartsuite/src/lib/actions/get-record.ts
  packages/pieces/community/smartsuite/src/lib/actions/update-record.ts
  packages/pieces/community/smartsuite/src/lib/actions/upload-file.ts
  packages/pieces/community/smartsuite/src/lib/auth.ts
  packages/pieces/community/smartsuite/src/lib/common/constants.ts
  packages/pieces/community/smartsuite/src/lib/common/index.ts
  packages/pieces/community/smartsuite/src/lib/common/props.ts
  packages/pieces/community/smartsuite/src/lib/triggers/new-record.ts
  packages/pieces/community/smartsuite/src/lib/triggers/updated-record.ts
  packages/pieces/community/smartsuite/tsconfig.json
  packages/pieces/community/smartsuite/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim

#7858 feat(flow-run): sync webhook didn't extract payloads
  packages/server/api/src/app/flows/flow-run/flow-run-service.ts
  packages/server/api/src/app/flows/flow-run/flow-run-side-effects.ts
Labels: 🐛 bug

#7853 fix: change patch to post in billing and folders
  packages/react-ui/src/app/routes/platform/billing/api/billing-api.ts
  packages/react-ui/src/features/folders/lib/folders-api.ts
  packages/server/api/src/app/ee/platform/platform-plan/platform-plan.controller.ts
  packages/server/api/src/app/flows/folder/folder.entity.ts
  packages/server/api/src/app/flows/folder/folder.module.ts
  packages/server/api/src/app/flows/folder/folder.service.ts
  packages/shared/src/lib/flows/folders/folder-requests.ts
Labels: 🐛 bug, 🧹 clean up

#7875 feat: refactor multiple mcp
  packages/react-ui/src/app/builder/test-step/custom-test-step/mcp-tool-testing-dialog.tsx
  packages/react-ui/src/app/mcp/mcp-config.tsx
  packages/react-ui/src/app/mcp/mcp-connect.tsx
  packages/react-ui/src/app/mcp/mcp-tool-dialog.tsx
  packages/react-ui/src/app/mcp/runs/mcp-run-utils.tsx
  packages/react-ui/src/app/mcp/runs/mcp-runs.tsx
  packages/react-ui/src/app/routes/mcp-servers/id/index.tsx
  packages/react-ui/src/app/routes/mcp-servers/index.tsx
  packages/react-ui/src/components/ui/sheet.tsx
  packages/react-ui/src/features/mcp/lib/mcp-api.ts
  packages/react-ui/src/features/mcp/lib/mcp-hooks.ts
  packages/react-ui/src/features/mcp/lib/mcp-run-api.ts
  packages/react-ui/src/features/mcp/lib/mcp-tool-api.ts
  packages/react-ui/src/features/mcp/lib/mcp-tool-history-api.ts
  packages/server/api/src/app/database/database-connection.ts
  packages/server/api/src/app/database/migration/postgres/1748282988335-AddMcpToolHistory.ts
  packages/server/api/src/app/database/migration/postgres/1748352614033-AddMcpToolEntity.ts
  packages/server/api/src/app/database/migration/postgres/1748358415599-AddMcpRunEntity.ts
  packages/server/api/src/app/database/migration/sqlite/1748199919401-AddMcpToolEntitySQLITE.ts
  packages/server/api/src/app/database/migration/sqlite/1748365593414-AddMcpToolEntitySQLITE.ts
  packages/server/api/src/app/database/migration/sqlite/1748365786218-AddMcpRunEntitySQLITE.ts
  packages/server/api/src/app/database/postgres-connection.ts
  packages/server/api/src/app/database/sqlite-connection.ts
  packages/server/api/src/app/ee/platform/platform-usage-service.ts
  packages/server/api/src/app/mcp/mcp-entity.ts
  packages/server/api/src/app/mcp/mcp-module.ts
  packages/server/api/src/app/mcp/mcp-run/mcp-run.controller.ts
  packages/server/api/src/app/mcp/mcp-run/mcp-run.entity.ts
  packages/server/api/src/app/mcp/mcp-run/mcp-run.service.ts
  packages/server/api/src/app/mcp/mcp-server-controller.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-server.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-service.ts
  packages/server/api/src/app/mcp/mcp-server/mcp-sse-controller.ts
  packages/server/api/src/app/mcp/mcp-service.ts
  packages/server/api/src/app/mcp/mcp-tools/mcp-tool-handler.ts
  packages/server/api/src/app/mcp/mcp-tools/mcp-tool-history/mcp-tool-history.controller.ts
  packages/server/api/src/app/mcp/mcp-tools/mcp-tool.controller.ts
  packages/server/api/src/app/mcp/mcp-tools/mcp-tool.service.ts
  packages/server/api/src/app/mcp/mcp-utils.ts
  packages/server/api/src/app/mcp/tool/mcp-tool.entity.ts
  packages/shared/src/lib/mcp/index.ts
  packages/shared/src/lib/mcp/mcp.request.ts
  packages/shared/src/lib/mcp/mcp.ts
  packages/shared/src/lib/mcp/tools/history/mcp-tool-history.request.ts
  packages/shared/src/lib/mcp/tools/history/mcp-tool-history.ts
  packages/shared/src/lib/mcp/tools/mcp-tool.request.ts
  packages/shared/src/lib/mcp/tools/mcp-tool.ts
  packages/shared/src/lib/mcp/tools/run/mcp-run.request.ts
  packages/shared/src/lib/mcp/tools/run/mcp-run.ts
  path=packages/react-ui/src/app/routes/mcp/index.tsx
Labels: 🧹 clean up

#7886 fix: only set project tasks limit when its new, while provisioning embedding users
  packages/server/api/src/app/ee/managed-authn/managed-authn-service.ts
Labels: 🐛 bug

#7867 feat: implement motion piece with actions and triggers
  packages/pieces/community/motion/.eslintrc.json
  packages/pieces/community/motion/README.md
  packages/pieces/community/motion/package.json
  packages/pieces/community/motion/project.json
  packages/pieces/community/motion/src/index.ts
  packages/pieces/community/motion/src/lib/actions/create-project.ts
  packages/pieces/community/motion/src/lib/actions/create-task.ts
  packages/pieces/community/motion/src/lib/actions/find-task.ts
  packages/pieces/community/motion/src/lib/actions/get-task.ts
  packages/pieces/community/motion/src/lib/actions/move-task.ts
  packages/pieces/community/motion/src/lib/actions/update-task.ts
  packages/pieces/community/motion/src/lib/common/props.ts
  packages/pieces/community/motion/src/lib/triggers/task-created.ts
  packages/pieces/community/motion/tsconfig.json
  packages/pieces/community/motion/tsconfig.lib.json
  tsconfig.base.json
Labels: 🙋 Bounty claim

#7904 refactor: karma, jasmine, & angular cleanup
  .devcontainer/Dockerfile
  docs/handbook/engineering/onboarding/onboarding-check-list.mdx
  karma.conf.js
  nx.json
  package-lock.json
  package.json
  packages/ee/ui/.eslintrc.json
Labels: 🧹 clean up

#7633 feat: beehiiv piece
  packages/pieces/community/beehiiv/.eslintrc.json
  packages/pieces/community/beehiiv/README.md
  packages/pieces/community/beehiiv/package.json
  packages/pieces/community/beehiiv/project.json
  packages/pieces/community/beehiiv/src/index.ts
  packages/pieces/community/beehiiv/src/lib/actions/add-subscription-to-automation.action.ts
  packages/pieces/community/beehiiv/src/lib/actions/create-subscription.action.ts
  packages/pieces/community/beehiiv/src/lib/actions/list-automations.action.ts
  packages/pieces/community/beehiiv/src/lib/actions/list-posts.action.ts
  packages/pieces/community/beehiiv/src/lib/actions/update-subscription.action.ts
  packages/pieces/community/beehiiv/src/lib/common/auth.ts
  packages/pieces/community/beehiiv/src/lib/common/client.ts
  packages/pieces/community/beehiiv/src/lib/common/props.ts
  packages/pieces/community/beehiiv/src/lib/triggers/new-post-sent.trigger.ts
  packages/pieces/community/beehiiv/src/lib/triggers/new-subscription-confirmed.trigger.ts
  packages/pieces/community/beehiiv/src/lib/triggers/user-unsubscribes.trigger.ts
  packages/pieces/community/beehiiv/tsconfig.json
  packages/pieces/community/beehiiv/tsconfig.lib.json
  tsconfig.base.json
Labels: 🔌 pieces, 🙋 Bounty claim
